import type { ImageModel, ImageTask } from './publicTypes';
export const modelFixture = (): ImageModel => ({
  id: 'imdl_AAAAAAAAAAAAAAAAAAAAAA',
  display_name: '<script>display only</script>',
  description: '<img src=x onerror=alert(1)>',
  revision: '2',
  price: { paper: '2', brush: '1' },
  parameters: [
    {
      key: 'prompt',
      supported: true,
      required: true,
      type: 'string',
      max_length: 65536,
      length_unit: 'utf8_bytes',
    },
    {
      key: 'negative_prompt',
      length_unit: 'utf8_bytes',
      supported: true,
      required: false,
      type: 'string',
    },
    {
      key: 'n',
      supported: true,
      required: false,
      type: 'integer',
      minimum: 1,
      maximum: 4,
      default: 1,
    },
    {
      key: 'quality',
      length_unit: 'utf8_bytes',
      supported: true,
      required: false,
      type: 'string',
      enum: ['standard', 'high'],
      default: 'standard',
    },
  ],
  combinations: [],
});
export const taskFixture = (overrides: Partial<ImageTask> = {}): ImageTask => ({
  id: 'img_AAAAAAAAAAAAAAAAAAAAAA',
  model_id: 'imdl_AAAAAAAAAAAAAAAAAAAAAA',
  status: 'queued',
  billing_state: 'reserved',
  n: 4,
  actual_images: 0,
  created_at: 1700000000,
  dispatched_at: null,
  completed_at: null,
  charge: { paper: '8', brush: '4' },
  refund: { paper: '0', brush: '0' },
  queue_position: 1,
  result_expires_at: null,
  result_available: false,
  error_code: null,
  images: [],
  ...overrides,
});
