import { useRegisteredCopy } from '@shared/i18n/useRegisteredCopy';

const keys = {
  title: 'admin.lakeNotes.title',
  description: 'admin.lakeNotes.description',
  openEditor: 'admin.lakeNotes.openEditor',
  back: 'admin.lakeNotes.back',
  availability: 'admin.lakeNotes.availability',
  availabilityHelp: 'admin.lakeNotes.availabilityHelp',
  visible: 'admin.lakeNotes.visible',
  paused: 'admin.lakeNotes.paused',
  start: 'admin.lakeNotes.start',
  end: 'admin.lakeNotes.end',
  umbrellaHelp: 'admin.lakeNotes.umbrellaHelp',
  saveAvailability: 'admin.lakeNotes.saveAvailability',
  periods: 'admin.lakeNotes.periods',
  periodHistoryDescription: 'admin.lakeNotes.periodHistoryDescription',
  newPeriod: 'admin.lakeNotes.newPeriod',
  edit: 'admin.lakeNotes.edit',
  name: 'admin.lakeNotes.name',
  draft: 'admin.lakeNotes.draft',
  published: 'admin.lakeNotes.published',
  cancelled: 'admin.lakeNotes.cancelled',
  status: 'admin.lakeNotes.status',
  fee: 'admin.lakeNotes.fee',
  feeHelp: 'admin.lakeNotes.feeHelp',
  periodHelp: 'admin.lakeNotes.periodHelp',
  exchangeHeading: 'admin.lakeNotes.exchangeHeading',
  enabled: 'admin.lakeNotes.enabled',
  source: 'admin.lakeNotes.source',
  target: 'admin.lakeNotes.target',
  exchangeHelp: 'admin.lakeNotes.exchangeHelp',
  saveDraft: 'admin.lakeNotes.saveDraft',
  publish: 'admin.lakeNotes.publish',
  publishHelp: 'admin.lakeNotes.publishHelp',
  withdrawalHelp: 'admin.lakeNotes.withdrawalHelp',
  savePeriod: 'admin.lakeNotes.savePeriod',
  cancelPeriod: 'admin.lakeNotes.cancelPeriod',
  cancelEdit: 'admin.lakeNotes.cancelEdit',
  saved: 'admin.lakeNotes.saved',
  unknown: 'admin.lakeNotes.unknown',
  retry: 'admin.lakeNotes.retry',
  invalid: 'admin.lakeNotes.invalid',
  empty: 'admin.lakeNotes.empty',
  previous: 'admin.lakeNotes.previous',
  next: 'admin.lakeNotes.next',
  cancelHelp: 'admin.lakeNotes.cancelHelp',
  coverAlt: 'common.lakeNotes.coverAlt',
  coins: 'common.lakeNotes.coins',
  general: 'common.lakeNotes.general',
  game: 'common.lakeNotes.game',
  coins_to_general: 'common.lakeNotes.coins_to_general',
  general_to_coins: 'common.lakeNotes.general_to_coins',
  coins_to_game: 'common.lakeNotes.coins_to_game',
  game_to_coins: 'common.lakeNotes.game_to_coins',
} as const;
export const useLakeAdminCopy = () => useRegisteredCopy(keys);
export type LakeText = ReturnType<typeof useLakeAdminCopy>['t'];
