import { useRegisteredCopy } from '@shared/i18n/useRegisteredCopy';

const keys = {
  ledgerEntry: 'user.lakeNotes.ledgerEntry',
  ledgerExchange: 'user.lakeNotes.ledgerExchange',
  back: 'user.lakeNotes.back',
  intro: 'user.lakeNotes.intro',
  entryHeading: 'user.lakeNotes.entryHeading',
  entryFee: 'user.lakeNotes.entryFee',
  entryScope: 'user.lakeNotes.entryScope',
  paid: 'user.lakeNotes.paid',
  enter: 'user.lakeNotes.enter',
  closed: 'user.lakeNotes.closed',
  entryUnknown: 'user.lakeNotes.entryUnknown',
  retry: 'user.lakeNotes.retry',
  saved: 'user.lakeNotes.saved',
  saving: 'user.lakeNotes.saving',
  reconnecting: 'user.lakeNotes.reconnecting',
  checkSaved: 'user.lakeNotes.checkSaved',
  controllerLost: 'user.lakeNotes.controllerLost',
  start: 'user.lakeNotes.start',
  again: 'user.lakeNotes.again',
  pause: 'user.lakeNotes.pause',
  resume: 'user.lakeNotes.resume',
  takeOver: 'user.lakeNotes.takeOver',
  hold: 'user.lakeNotes.hold',
  track: 'user.lakeNotes.track',
  progress: 'user.lakeNotes.progress',
  idle: 'user.lakeNotes.idle',
  waiting: 'user.lakeNotes.waiting',
  playing: 'user.lakeNotes.playing',
  success: 'user.lakeNotes.success',
  failed: 'user.lakeNotes.failed',
  paused: 'user.lakeNotes.paused',
  confirming: 'user.lakeNotes.confirming',
  unknownFish: 'user.lakeNotes.unknownFish',
  caught: 'user.lakeNotes.caught',
  streak: 'user.lakeNotes.streak',
  clock: 'user.lakeNotes.clock',
  level: 'user.lakeNotes.level',
  xp: 'user.lakeNotes.xp',
  maxLevel: 'user.lakeNotes.maxLevel',
  loadout: 'user.lakeNotes.loadout',
  none: 'user.lakeNotes.none',
  empty: 'user.lakeNotes.empty',
  skills: 'user.lakeNotes.skills',
  shop: 'user.lakeNotes.shop',
  basket: 'user.lakeNotes.basket',
  catalog: 'user.lakeNotes.catalogTitle',
  locations: 'user.lakeNotes.locations',
  contracts: 'user.lakeNotes.contracts',
  rest: 'user.lakeNotes.rest',
  close: 'user.lakeNotes.close',
  pausedMenus: 'user.lakeNotes.pausedMenus',
  skillIntro: 'user.lakeNotes.skillIntro',
  skillTier: 'user.lakeNotes.skillTier',
  selected: 'user.lakeNotes.selected',
  locked: 'user.lakeNotes.locked',
  skillPrerequisite: 'user.lakeNotes.skillPrerequisite',
  respec: 'user.lakeNotes.respec',
  respecHelp: 'user.lakeNotes.respecHelp',
  rods: 'user.lakeNotes.rods',
  tackle: 'user.lakeNotes.tackle',
  baits: 'user.lakeNotes.baits',
  presets: 'user.lakeNotes.presets',
  owned: 'user.lakeNotes.owned',
  equipped: 'user.lakeNotes.equipped',
  buy: 'user.lakeNotes.buy',
  claim: 'user.lakeNotes.claim',
  equip: 'user.lakeNotes.equip',
  tackleSlot: 'user.lakeNotes.tackleSlot',
  unequip: 'user.lakeNotes.unequip',
  equipSlot: 'user.lakeNotes.equipSlot',
  savePreset: 'user.lakeNotes.savePreset',
  applyPreset: 'user.lakeNotes.applyPreset',
  preset: 'user.lakeNotes.preset',
  stock: 'user.lakeNotes.stock',
  useBait: 'user.lakeNotes.useBait',
  disableBait: 'user.lakeNotes.disableBait',
  previewStats: 'user.lakeNotes.previewStats',
  shopHelp: 'user.lakeNotes.shopHelp',
  basketHelp: 'user.lakeNotes.basketHelp',
  basketEmpty: 'user.lakeNotes.basketEmpty',
  sell: 'user.lakeNotes.sell',
  sellAll: 'user.lakeNotes.sellAll',
  lockFish: 'user.lakeNotes.lockFish',
  unlockFish: 'user.lakeNotes.unlockFish',
  catchDetail: 'user.lakeNotes.catchDetail',
  perfect: 'user.lakeNotes.perfect',
  debris: 'user.lakeNotes.debris',
  recycle: 'user.lakeNotes.recycle',
  recycleAll: 'user.lakeNotes.recycleAll',
  debrisSummary: 'user.lakeNotes.debrisSummary',
  catalogSummary: 'user.lakeNotes.catalogSummary',
  undiscovered: 'user.lakeNotes.undiscovered',
  conditions: 'user.lakeNotes.conditions',
  allPeriods: 'user.lakeNotes.allPeriods',
  allWeather: 'user.lakeNotes.allWeather',
  record: 'user.lakeNotes.record',
  locationFound: 'user.lakeNotes.locationFound',
  currentLocation: 'user.lakeNotes.currentLocation',
  contractsHelp: 'user.lakeNotes.contractsHelp',
  contractSummary: 'user.lakeNotes.contractSummary',
  available: 'user.lakeNotes.available',
  active: 'user.lakeNotes.active',
  completed: 'user.lakeNotes.completed',
  deliveryContract: 'user.lakeNotes.deliveryContract',
  catchContract: 'user.lakeNotes.catchContract',
  perfectContract: 'user.lakeNotes.perfectContract',
  cleanupContract: 'user.lakeNotes.cleanupContract',
  contractReward: 'user.lakeNotes.contractReward',
  acceptContract: 'user.lakeNotes.acceptContract',
  cancelContract: 'user.lakeNotes.cancelContract',
  claimContract: 'user.lakeNotes.claimContract',
  treasureCollect: 'user.lakeNotes.treasureCollect',
  treasureSecured: 'user.lakeNotes.treasureSecured',
  rewardSummary: 'user.lakeNotes.rewardSummary',
  overflow: 'user.lakeNotes.overflow',
  treasureReward: 'user.lakeNotes.treasureReward',
  debrisReward: 'user.lakeNotes.debrisReward',
  exchangeHeading: 'user.lakeNotes.exchangeHeading',
  exchangeHelp: 'user.lakeNotes.exchangeHelp',
  direction: 'user.lakeNotes.direction',
  batches: 'user.lakeNotes.batches',
  quote: 'user.lakeNotes.quote',
  quoteAmounts: 'user.lakeNotes.quoteAmounts',
  exchangeConfirm: 'user.lakeNotes.exchangeConfirm',
  exchangeUnknown: 'user.lakeNotes.exchangeUnknown',
  exchangeSaved: 'user.lakeNotes.exchangeSaved',
  exchangeConflict: 'user.lakeNotes.exchangeConflict',
  batchInvalid: 'user.lakeNotes.batchInvalid',
  saveUnknown: 'user.lakeNotes.saveUnknown',
  actionSaved: 'user.lakeNotes.actionSaved',
  catalog_fish_gold_name: 'user.lakeNotes.catalog.fish.gold.name',
  catalog_fish_lake_carp_name: 'user.lakeNotes.catalog.fish.lake_carp.name',
  catalog_fish_lake_yellowcat_name: 'user.lakeNotes.catalog.fish.lake_yellowcat.name',
  catalog_fish_sky_name: 'user.lakeNotes.catalog.fish.sky.name',
  catalog_fish_lake_grasscarp_name: 'user.lakeNotes.catalog.fish.lake_grasscarp.name',
  catalog_fish_mud_name: 'user.lakeNotes.catalog.fish.mud.name',
  catalog_fish_silver_name: 'user.lakeNotes.catalog.fish.silver.name',
  catalog_fish_violet_name: 'user.lakeNotes.catalog.fish.violet.name',
  catalog_fish_lake_snakehead_name: 'user.lakeNotes.catalog.fish.lake_snakehead.name',
  catalog_fish_lake_silvercarp_name: 'user.lakeNotes.catalog.fish.lake_silvercarp.name',
  catalog_fish_lake_bighead_name: 'user.lakeNotes.catalog.fish.lake_bighead.name',
  catalog_fish_star_name: 'user.lakeNotes.catalog.fish.star.name',
  catalog_fish_lake_bitterling_name: 'user.lakeNotes.catalog.fish.lake_bitterling.name',
  catalog_fish_lake_icefish_name: 'user.lakeNotes.catalog.fish.lake_icefish.name',
  catalog_fish_lake_tench_name: 'user.lakeNotes.catalog.fish.lake_tench.name',
  catalog_fish_lake_topmouth_name: 'user.lakeNotes.catalog.fish.lake_topmouth.name',
  catalog_fish_lake_swamp_eel_name: 'user.lakeNotes.catalog.fish.lake_swamp_eel.name',
  catalog_fish_lake_sturgeon_name: 'user.lakeNotes.catalog.fish.lake_sturgeon.name',
  catalog_fish_teal_name: 'user.lakeNotes.catalog.fish.teal.name',
  catalog_fish_river_zacco_name: 'user.lakeNotes.catalog.fish.river_zacco.name',
  catalog_fish_river_loach_name: 'user.lakeNotes.catalog.fish.river_loach.name',
  catalog_fish_river_gudgeon_name: 'user.lakeNotes.catalog.fish.river_gudgeon.name',
  catalog_fish_river_ayu_name: 'user.lakeNotes.catalog.fish.river_ayu.name',
  catalog_fish_river_perch_name: 'user.lakeNotes.catalog.fish.river_perch.name',
  catalog_fish_red_name: 'user.lakeNotes.catalog.fish.red.name',
  catalog_fish_river_browntrout_name: 'user.lakeNotes.catalog.fish.river_browntrout.name',
  catalog_fish_river_pike_name: 'user.lakeNotes.catalog.fish.river_pike.name',
  catalog_fish_frost_name: 'user.lakeNotes.catalog.fish.frost.name',
  catalog_fish_river_salmon_name: 'user.lakeNotes.catalog.fish.river_salmon.name',
  catalog_fish_abyss_name: 'user.lakeNotes.catalog.fish.abyss.name',
  catalog_fish_river_spined_loach_name: 'user.lakeNotes.catalog.fish.river_spined_loach.name',
  catalog_fish_river_grayling_name: 'user.lakeNotes.catalog.fish.river_grayling.name',
  catalog_fish_river_red_eye_name: 'user.lakeNotes.catalog.fish.river_red_eye.name',
  catalog_fish_river_yamame_name: 'user.lakeNotes.catalog.fish.river_yamame.name',
  catalog_fish_river_burbot_name: 'user.lakeNotes.catalog.fish.river_burbot.name',
  catalog_fish_river_hilsa_name: 'user.lakeNotes.catalog.fish.river_hilsa.name',
  catalog_fish_coast_sardine_name: 'user.lakeNotes.catalog.fish.coast_sardine.name',
  catalog_fish_coast_anchovy_name: 'user.lakeNotes.catalog.fish.coast_anchovy.name',
  catalog_fish_coast_herring_name: 'user.lakeNotes.catalog.fish.coast_herring.name',
  catalog_fish_coast_horsemackerel_name: 'user.lakeNotes.catalog.fish.coast_horsemackerel.name',
  catalog_fish_coast_mackerel_name: 'user.lakeNotes.catalog.fish.coast_mackerel.name',
  catalog_fish_coast_seabass_name: 'user.lakeNotes.catalog.fish.coast_seabass.name',
  catalog_fish_coast_flounder_name: 'user.lakeNotes.catalog.fish.coast_flounder.name',
  catalog_fish_coast_seabream_name: 'user.lakeNotes.catalog.fish.coast_seabream.name',
  catalog_fish_coast_grouper_name: 'user.lakeNotes.catalog.fish.coast_grouper.name',
  catalog_fish_coast_yellowtail_name: 'user.lakeNotes.catalog.fish.coast_yellowtail.name',
  catalog_fish_coast_tuna_name: 'user.lakeNotes.catalog.fish.coast_tuna.name',
  catalog_fish_coast_swordfish_name: 'user.lakeNotes.catalog.fish.coast_swordfish.name',
  catalog_fish_coast_pomfret_name: 'user.lakeNotes.catalog.fish.coast_pomfret.name',
  catalog_fish_coast_flyingfish_name: 'user.lakeNotes.catalog.fish.coast_flyingfish.name',
  catalog_fish_coast_cutlassfish_name: 'user.lakeNotes.catalog.fish.coast_cutlassfish.name',
  catalog_fish_coast_conger_name: 'user.lakeNotes.catalog.fish.coast_conger.name',
  catalog_fish_coast_skipjack_name: 'user.lakeNotes.catalog.fish.coast_skipjack.name',
  catalog_fish_coast_anglerfish_name: 'user.lakeNotes.catalog.fish.coast_anglerfish.name',
  catalog_fish_gold_description: 'user.lakeNotes.catalog.fish.gold.description',
  catalog_fish_lake_carp_description: 'user.lakeNotes.catalog.fish.lake_carp.description',
  catalog_fish_lake_yellowcat_description: 'user.lakeNotes.catalog.fish.lake_yellowcat.description',
  catalog_fish_sky_description: 'user.lakeNotes.catalog.fish.sky.description',
  catalog_fish_lake_grasscarp_description: 'user.lakeNotes.catalog.fish.lake_grasscarp.description',
  catalog_fish_mud_description: 'user.lakeNotes.catalog.fish.mud.description',
  catalog_fish_silver_description: 'user.lakeNotes.catalog.fish.silver.description',
  catalog_fish_violet_description: 'user.lakeNotes.catalog.fish.violet.description',
  catalog_fish_lake_snakehead_description: 'user.lakeNotes.catalog.fish.lake_snakehead.description',
  catalog_fish_lake_silvercarp_description:
    'user.lakeNotes.catalog.fish.lake_silvercarp.description',
  catalog_fish_lake_bighead_description: 'user.lakeNotes.catalog.fish.lake_bighead.description',
  catalog_fish_star_description: 'user.lakeNotes.catalog.fish.star.description',
  catalog_fish_teal_description: 'user.lakeNotes.catalog.fish.teal.description',
  catalog_fish_river_zacco_description: 'user.lakeNotes.catalog.fish.river_zacco.description',
  catalog_fish_river_loach_description: 'user.lakeNotes.catalog.fish.river_loach.description',
  catalog_fish_river_gudgeon_description: 'user.lakeNotes.catalog.fish.river_gudgeon.description',
  catalog_fish_river_ayu_description: 'user.lakeNotes.catalog.fish.river_ayu.description',
  catalog_fish_river_perch_description: 'user.lakeNotes.catalog.fish.river_perch.description',
  catalog_fish_red_description: 'user.lakeNotes.catalog.fish.red.description',
  catalog_fish_river_browntrout_description:
    'user.lakeNotes.catalog.fish.river_browntrout.description',
  catalog_fish_river_pike_description: 'user.lakeNotes.catalog.fish.river_pike.description',
  catalog_fish_frost_description: 'user.lakeNotes.catalog.fish.frost.description',
  catalog_fish_river_salmon_description: 'user.lakeNotes.catalog.fish.river_salmon.description',
  catalog_fish_abyss_description: 'user.lakeNotes.catalog.fish.abyss.description',
  catalog_fish_coast_sardine_description: 'user.lakeNotes.catalog.fish.coast_sardine.description',
  catalog_fish_coast_anchovy_description: 'user.lakeNotes.catalog.fish.coast_anchovy.description',
  catalog_fish_coast_herring_description: 'user.lakeNotes.catalog.fish.coast_herring.description',
  catalog_fish_coast_horsemackerel_description:
    'user.lakeNotes.catalog.fish.coast_horsemackerel.description',
  catalog_fish_coast_mackerel_description: 'user.lakeNotes.catalog.fish.coast_mackerel.description',
  catalog_fish_coast_seabass_description: 'user.lakeNotes.catalog.fish.coast_seabass.description',
  catalog_fish_coast_flounder_description: 'user.lakeNotes.catalog.fish.coast_flounder.description',
  catalog_fish_coast_seabream_description: 'user.lakeNotes.catalog.fish.coast_seabream.description',
  catalog_fish_coast_grouper_description: 'user.lakeNotes.catalog.fish.coast_grouper.description',
  catalog_fish_coast_yellowtail_description:
    'user.lakeNotes.catalog.fish.coast_yellowtail.description',
  catalog_fish_coast_tuna_description: 'user.lakeNotes.catalog.fish.coast_tuna.description',
  catalog_fish_coast_swordfish_description:
    'user.lakeNotes.catalog.fish.coast_swordfish.description',
  catalog_fish_lake_bitterling_description:
    'user.lakeNotes.catalog.fish.lake_bitterling.description',
  catalog_fish_lake_icefish_description: 'user.lakeNotes.catalog.fish.lake_icefish.description',
  catalog_fish_lake_tench_description: 'user.lakeNotes.catalog.fish.lake_tench.description',
  catalog_fish_lake_topmouth_description: 'user.lakeNotes.catalog.fish.lake_topmouth.description',
  catalog_fish_lake_swamp_eel_description: 'user.lakeNotes.catalog.fish.lake_swamp_eel.description',
  catalog_fish_lake_sturgeon_description: 'user.lakeNotes.catalog.fish.lake_sturgeon.description',
  catalog_fish_river_spined_loach_description:
    'user.lakeNotes.catalog.fish.river_spined_loach.description',
  catalog_fish_river_grayling_description: 'user.lakeNotes.catalog.fish.river_grayling.description',
  catalog_fish_river_red_eye_description: 'user.lakeNotes.catalog.fish.river_red_eye.description',
  catalog_fish_river_yamame_description: 'user.lakeNotes.catalog.fish.river_yamame.description',
  catalog_fish_river_burbot_description: 'user.lakeNotes.catalog.fish.river_burbot.description',
  catalog_fish_river_hilsa_description: 'user.lakeNotes.catalog.fish.river_hilsa.description',
  catalog_fish_coast_pomfret_description: 'user.lakeNotes.catalog.fish.coast_pomfret.description',
  catalog_fish_coast_flyingfish_description:
    'user.lakeNotes.catalog.fish.coast_flyingfish.description',
  catalog_fish_coast_cutlassfish_description:
    'user.lakeNotes.catalog.fish.coast_cutlassfish.description',
  catalog_fish_coast_conger_description: 'user.lakeNotes.catalog.fish.coast_conger.description',
  catalog_fish_coast_skipjack_description: 'user.lakeNotes.catalog.fish.coast_skipjack.description',
  catalog_fish_coast_anglerfish_description:
    'user.lakeNotes.catalog.fish.coast_anglerfish.description',
  catalog_locations_lake_name: 'user.lakeNotes.catalog.locations.lake.name',
  catalog_locations_lake_scene: 'user.lakeNotes.catalog.locations.lake.scene',
  catalog_locations_lake_description: 'user.lakeNotes.catalog.locations.lake.description',
  catalog_locations_river_name: 'user.lakeNotes.catalog.locations.river.name',
  catalog_locations_river_scene: 'user.lakeNotes.catalog.locations.river.scene',
  catalog_locations_river_description: 'user.lakeNotes.catalog.locations.river.description',
  catalog_locations_coast_name: 'user.lakeNotes.catalog.locations.coast.name',
  catalog_locations_coast_scene: 'user.lakeNotes.catalog.locations.coast.scene',
  catalog_locations_coast_description: 'user.lakeNotes.catalog.locations.coast.description',
  catalog_gear_trainingRod_name: 'user.lakeNotes.catalog.gear.trainingRod.name',
  catalog_gear_trainingRod_description: 'user.lakeNotes.catalog.gear.trainingRod.description',
  catalog_gear_bambooPole_name: 'user.lakeNotes.catalog.gear.bambooPole.name',
  catalog_gear_bambooPole_description: 'user.lakeNotes.catalog.gear.bambooPole.description',
  catalog_gear_fiberglassRod_name: 'user.lakeNotes.catalog.gear.fiberglassRod.name',
  catalog_gear_fiberglassRod_description: 'user.lakeNotes.catalog.gear.fiberglassRod.description',
  catalog_gear_iridiumRod_name: 'user.lakeNotes.catalog.gear.iridiumRod.name',
  catalog_gear_iridiumRod_description: 'user.lakeNotes.catalog.gear.iridiumRod.description',
  catalog_gear_advancedRod_name: 'user.lakeNotes.catalog.gear.advancedRod.name',
  catalog_gear_advancedRod_description: 'user.lakeNotes.catalog.gear.advancedRod.description',
  catalog_gear_corkBobber_name: 'user.lakeNotes.catalog.gear.corkBobber.name',
  catalog_gear_corkBobber_description: 'user.lakeNotes.catalog.gear.corkBobber.description',
  catalog_gear_leadBobber_name: 'user.lakeNotes.catalog.gear.leadBobber.name',
  catalog_gear_leadBobber_description: 'user.lakeNotes.catalog.gear.leadBobber.description',
  catalog_gear_trapBobber_name: 'user.lakeNotes.catalog.gear.trapBobber.name',
  catalog_gear_trapBobber_description: 'user.lakeNotes.catalog.gear.trapBobber.description',
  catalog_gear_barbedHook_name: 'user.lakeNotes.catalog.gear.barbedHook.name',
  catalog_gear_barbedHook_description: 'user.lakeNotes.catalog.gear.barbedHook.description',
  catalog_gear_qualityBobber_name: 'user.lakeNotes.catalog.gear.qualityBobber.name',
  catalog_gear_qualityBobber_description: 'user.lakeNotes.catalog.gear.qualityBobber.description',
  catalog_gear_curiosityLure_name: 'user.lakeNotes.catalog.gear.curiosityLure.name',
  catalog_gear_curiosityLure_description: 'user.lakeNotes.catalog.gear.curiosityLure.description',
  catalog_gear_spinner_name: 'user.lakeNotes.catalog.gear.spinner.name',
  catalog_gear_spinner_description: 'user.lakeNotes.catalog.gear.spinner.description',
  catalog_gear_dressedSpinner_name: 'user.lakeNotes.catalog.gear.dressedSpinner.name',
  catalog_gear_dressedSpinner_description: 'user.lakeNotes.catalog.gear.dressedSpinner.description',
  catalog_gear_sonarBobber_name: 'user.lakeNotes.catalog.gear.sonarBobber.name',
  catalog_gear_sonarBobber_description: 'user.lakeNotes.catalog.gear.sonarBobber.description',
  catalog_skills_steady_name: 'user.lakeNotes.catalog.skills.steady.name',
  catalog_skills_steady_description: 'user.lakeNotes.catalog.skills.steady.description',
  catalog_skills_tracker_name: 'user.lakeNotes.catalog.skills.tracker.name',
  catalog_skills_tracker_description: 'user.lakeNotes.catalog.skills.tracker.description',
  catalog_skills_calm_name: 'user.lakeNotes.catalog.skills.calm.name',
  catalog_skills_calm_description: 'user.lakeNotes.catalog.skills.calm.description',
  catalog_skills_control_name: 'user.lakeNotes.catalog.skills.control.name',
  catalog_skills_control_description: 'user.lakeNotes.catalog.skills.control.description',
  catalog_skills_legendHunter_name: 'user.lakeNotes.catalog.skills.legendHunter.name',
  catalog_skills_legendHunter_description: 'user.lakeNotes.catalog.skills.legendHunter.description',
  catalog_skills_brawler_name: 'user.lakeNotes.catalog.skills.brawler.name',
  catalog_skills_brawler_description: 'user.lakeNotes.catalog.skills.brawler.description',
  catalog_skills_patience_name: 'user.lakeNotes.catalog.skills.patience.name',
  catalog_skills_patience_description: 'user.lakeNotes.catalog.skills.patience.description',
  catalog_skills_reader_name: 'user.lakeNotes.catalog.skills.reader.name',
  catalog_skills_reader_description: 'user.lakeNotes.catalog.skills.reader.description',
  catalog_skills_master_name: 'user.lakeNotes.catalog.skills.master.name',
  catalog_skills_master_description: 'user.lakeNotes.catalog.skills.master.description',
  catalog_skills_deepSeeker_name: 'user.lakeNotes.catalog.skills.deepSeeker.name',
  catalog_skills_deepSeeker_description: 'user.lakeNotes.catalog.skills.deepSeeker.description',
  catalog_baits_basic_name: 'user.lakeNotes.catalog.baits.basic.name',
  catalog_baits_basic_description: 'user.lakeNotes.catalog.baits.basic.description',
  catalog_baits_glimmer_name: 'user.lakeNotes.catalog.baits.glimmer.name',
  catalog_baits_glimmer_description: 'user.lakeNotes.catalog.baits.glimmer.description',
  catalog_baits_abyss_name: 'user.lakeNotes.catalog.baits.abyss.name',
  catalog_baits_abyss_description: 'user.lakeNotes.catalog.baits.abyss.description',
  catalog_baits_deluxe_name: 'user.lakeNotes.catalog.baits.deluxe.name',
  catalog_baits_deluxe_description: 'user.lakeNotes.catalog.baits.deluxe.description',
  catalog_debris_driftwood_name: 'user.lakeNotes.catalog.debris.driftwood.name',
  catalog_debris_bottle_name: 'user.lakeNotes.catalog.debris.bottle.name',
  catalog_debris_boot_name: 'user.lakeNotes.catalog.debris.boot.name',
  catalog_debris_line_name: 'user.lakeNotes.catalog.debris.line.name',
  catalog_periods_dawn: 'user.lakeNotes.catalog.periods.dawn',
  catalog_periods_day: 'user.lakeNotes.catalog.periods.day',
  catalog_periods_dusk: 'user.lakeNotes.catalog.periods.dusk',
  catalog_periods_night: 'user.lakeNotes.catalog.periods.night',
  catalog_weathers_sunny: 'user.lakeNotes.catalog.weathers.sunny',
  catalog_weathers_cloudy: 'user.lakeNotes.catalog.weathers.cloudy',
  catalog_weathers_rain: 'user.lakeNotes.catalog.weathers.rain',
  catalog_rarities_common: 'user.lakeNotes.catalog.rarities.common',
  catalog_rarities_uncommon: 'user.lakeNotes.catalog.rarities.uncommon',
  catalog_rarities_rare: 'user.lakeNotes.catalog.rarities.rare',
  catalog_rarities_epic: 'user.lakeNotes.catalog.rarities.epic',
  catalog_rarities_legendary: 'user.lakeNotes.catalog.rarities.legendary',
  catalog_quality_q0: 'user.lakeNotes.catalog.quality.q0',
  catalog_quality_q1: 'user.lakeNotes.catalog.quality.q1',
  catalog_quality_q2: 'user.lakeNotes.catalog.quality.q2',
  catalog_quality_q3: 'user.lakeNotes.catalog.quality.q3',
  title: 'common.lakeNotes.title',
  coverAlt: 'common.lakeNotes.coverAlt',
  description: 'common.lakeNotes.description',
  coins: 'common.lakeNotes.coins',
  general: 'common.lakeNotes.general',
  game: 'common.lakeNotes.game',
  coins_to_general: 'common.lakeNotes.coins_to_general',
  general_to_coins: 'common.lakeNotes.general_to_coins',
  coins_to_game: 'common.lakeNotes.coins_to_game',
  game_to_coins: 'common.lakeNotes.game_to_coins',
  catalog_fish_lake_bluegill_name: 'user.lakeNotes.catalog.fish.lake_bluegill.name',
  catalog_fish_lake_bluegill_description: 'user.lakeNotes.catalog.fish.lake_bluegill.description',
  catalog_fish_lake_pumpkinseed_name: 'user.lakeNotes.catalog.fish.lake_pumpkinseed.name',
  catalog_fish_lake_pumpkinseed_description:
    'user.lakeNotes.catalog.fish.lake_pumpkinseed.description',
  catalog_fish_lake_rudd_name: 'user.lakeNotes.catalog.fish.lake_rudd.name',
  catalog_fish_lake_rudd_description: 'user.lakeNotes.catalog.fish.lake_rudd.description',
  catalog_fish_lake_roach_name: 'user.lakeNotes.catalog.fish.lake_roach.name',
  catalog_fish_lake_roach_description: 'user.lakeNotes.catalog.fish.lake_roach.description',
  catalog_fish_lake_yellowperch_name: 'user.lakeNotes.catalog.fish.lake_yellowperch.name',
  catalog_fish_lake_yellowperch_description:
    'user.lakeNotes.catalog.fish.lake_yellowperch.description',
  catalog_fish_lake_paddlefish_name: 'user.lakeNotes.catalog.fish.lake_paddlefish.name',
  catalog_fish_lake_paddlefish_description:
    'user.lakeNotes.catalog.fish.lake_paddlefish.description',
  catalog_fish_river_minnow_name: 'user.lakeNotes.catalog.fish.river_minnow.name',
  catalog_fish_river_minnow_description: 'user.lakeNotes.catalog.fish.river_minnow.description',
  catalog_fish_river_bleak_name: 'user.lakeNotes.catalog.fish.river_bleak.name',
  catalog_fish_river_bleak_description: 'user.lakeNotes.catalog.fish.river_bleak.description',
  catalog_fish_river_stoneloach_name: 'user.lakeNotes.catalog.fish.river_stoneloach.name',
  catalog_fish_river_stoneloach_description:
    'user.lakeNotes.catalog.fish.river_stoneloach.description',
  catalog_fish_river_smallmouth_name: 'user.lakeNotes.catalog.fish.river_smallmouth.name',
  catalog_fish_river_smallmouth_description:
    'user.lakeNotes.catalog.fish.river_smallmouth.description',
  catalog_fish_river_chub_name: 'user.lakeNotes.catalog.fish.river_chub.name',
  catalog_fish_river_chub_description: 'user.lakeNotes.catalog.fish.river_chub.description',
  catalog_fish_river_europeansturgeon_name:
    'user.lakeNotes.catalog.fish.river_europeansturgeon.name',
  catalog_fish_river_europeansturgeon_description:
    'user.lakeNotes.catalog.fish.river_europeansturgeon.description',
  catalog_fish_coast_mullet_name: 'user.lakeNotes.catalog.fish.coast_mullet.name',
  catalog_fish_coast_mullet_description: 'user.lakeNotes.catalog.fish.coast_mullet.description',
  catalog_fish_coast_whiting_name: 'user.lakeNotes.catalog.fish.coast_whiting.name',
  catalog_fish_coast_whiting_description: 'user.lakeNotes.catalog.fish.coast_whiting.description',
  catalog_fish_coast_garfish_name: 'user.lakeNotes.catalog.fish.coast_garfish.name',
  catalog_fish_coast_garfish_description: 'user.lakeNotes.catalog.fish.coast_garfish.description',
  catalog_fish_coast_blackseabream_name: 'user.lakeNotes.catalog.fish.coast_blackseabream.name',
  catalog_fish_coast_blackseabream_description:
    'user.lakeNotes.catalog.fish.coast_blackseabream.description',
  catalog_fish_coast_mahimahi_name: 'user.lakeNotes.catalog.fish.coast_mahimahi.name',
  catalog_fish_coast_mahimahi_description: 'user.lakeNotes.catalog.fish.coast_mahimahi.description',
  catalog_fish_coast_humpheadwrasse_name: 'user.lakeNotes.catalog.fish.coast_humpheadwrasse.name',
  catalog_fish_coast_humpheadwrasse_description:
    'user.lakeNotes.catalog.fish.coast_humpheadwrasse.description',
  catalog_fish_jungle_climbingperch_name: 'user.lakeNotes.catalog.fish.jungle_climbingperch.name',
  catalog_fish_jungle_climbingperch_description:
    'user.lakeNotes.catalog.fish.jungle_climbingperch.description',
  catalog_fish_jungle_threespotgourami_name:
    'user.lakeNotes.catalog.fish.jungle_threespotgourami.name',
  catalog_fish_jungle_threespotgourami_description:
    'user.lakeNotes.catalog.fish.jungle_threespotgourami.description',
  catalog_fish_jungle_snakeskingourami_name:
    'user.lakeNotes.catalog.fish.jungle_snakeskingourami.name',
  catalog_fish_jungle_snakeskingourami_description:
    'user.lakeNotes.catalog.fish.jungle_snakeskingourami.description',
  catalog_fish_jungle_croakinggourami_name:
    'user.lakeNotes.catalog.fish.jungle_croakinggourami.name',
  catalog_fish_jungle_croakinggourami_description:
    'user.lakeNotes.catalog.fish.jungle_croakinggourami.description',
  catalog_fish_jungle_moonlightgourami_name:
    'user.lakeNotes.catalog.fish.jungle_moonlightgourami.name',
  catalog_fish_jungle_moonlightgourami_description:
    'user.lakeNotes.catalog.fish.jungle_moonlightgourami.description',
  catalog_fish_jungle_redtailrasbora_name: 'user.lakeNotes.catalog.fish.jungle_redtailrasbora.name',
  catalog_fish_jungle_redtailrasbora_description:
    'user.lakeNotes.catalog.fish.jungle_redtailrasbora.description',
  catalog_fish_jungle_silverflyingbarb_name:
    'user.lakeNotes.catalog.fish.jungle_silverflyingbarb.name',
  catalog_fish_jungle_silverflyingbarb_description:
    'user.lakeNotes.catalog.fish.jungle_silverflyingbarb.description',
  catalog_fish_jungle_silverbarb_name: 'user.lakeNotes.catalog.fish.jungle_silverbarb.name',
  catalog_fish_jungle_silverbarb_description:
    'user.lakeNotes.catalog.fish.jungle_silverbarb.description',
  catalog_fish_jungle_bronzefeatherback_name:
    'user.lakeNotes.catalog.fish.jungle_bronzefeatherback.name',
  catalog_fish_jungle_bronzefeatherback_description:
    'user.lakeNotes.catalog.fish.jungle_bronzefeatherback.description',
  catalog_fish_jungle_yellowcatfish_name: 'user.lakeNotes.catalog.fish.jungle_yellowcatfish.name',
  catalog_fish_jungle_yellowcatfish_description:
    'user.lakeNotes.catalog.fish.jungle_yellowcatfish.description',
  catalog_fish_jungle_bigheadcatfish_name: 'user.lakeNotes.catalog.fish.jungle_bigheadcatfish.name',
  catalog_fish_jungle_bigheadcatfish_description:
    'user.lakeNotes.catalog.fish.jungle_bigheadcatfish.description',
  catalog_fish_jungle_stripedsnakehead_name:
    'user.lakeNotes.catalog.fish.jungle_stripedsnakehead.name',
  catalog_fish_jungle_stripedsnakehead_description:
    'user.lakeNotes.catalog.fish.jungle_stripedsnakehead.description',
  catalog_fish_jungle_peacockeel_name: 'user.lakeNotes.catalog.fish.jungle_peacockeel.name',
  catalog_fish_jungle_peacockeel_description:
    'user.lakeNotes.catalog.fish.jungle_peacockeel.description',
  catalog_fish_jungle_beardlessbarb_name: 'user.lakeNotes.catalog.fish.jungle_beardlessbarb.name',
  catalog_fish_jungle_beardlessbarb_description:
    'user.lakeNotes.catalog.fish.jungle_beardlessbarb.description',
  catalog_fish_jungle_clownfeatherback_name:
    'user.lakeNotes.catalog.fish.jungle_clownfeatherback.name',
  catalog_fish_jungle_clownfeatherback_description:
    'user.lakeNotes.catalog.fish.jungle_clownfeatherback.description',
  catalog_fish_jungle_smallscalearcherfish_name:
    'user.lakeNotes.catalog.fish.jungle_smallscalearcherfish.name',
  catalog_fish_jungle_smallscalearcherfish_description:
    'user.lakeNotes.catalog.fish.jungle_smallscalearcherfish.description',
  catalog_fish_jungle_giantgourami_name: 'user.lakeNotes.catalog.fish.jungle_giantgourami.name',
  catalog_fish_jungle_giantgourami_description:
    'user.lakeNotes.catalog.fish.jungle_giantgourami.description',
  catalog_fish_jungle_tinfoilbarb_name: 'user.lakeNotes.catalog.fish.jungle_tinfoilbarb.name',
  catalog_fish_jungle_tinfoilbarb_description:
    'user.lakeNotes.catalog.fish.jungle_tinfoilbarb.description',
  catalog_fish_jungle_hampalabarb_name: 'user.lakeNotes.catalog.fish.jungle_hampalabarb.name',
  catalog_fish_jungle_hampalabarb_description:
    'user.lakeNotes.catalog.fish.jungle_hampalabarb.description',
  catalog_fish_jungle_asianarowana_name: 'user.lakeNotes.catalog.fish.jungle_asianarowana.name',
  catalog_fish_jungle_asianarowana_description:
    'user.lakeNotes.catalog.fish.jungle_asianarowana.description',
  catalog_fish_jungle_giantsnakehead_name: 'user.lakeNotes.catalog.fish.jungle_giantsnakehead.name',
  catalog_fish_jungle_giantsnakehead_description:
    'user.lakeNotes.catalog.fish.jungle_giantsnakehead.description',
  catalog_fish_jungle_stripedpangasius_name:
    'user.lakeNotes.catalog.fish.jungle_stripedpangasius.name',
  catalog_fish_jungle_stripedpangasius_description:
    'user.lakeNotes.catalog.fish.jungle_stripedpangasius.description',
  catalog_fish_jungle_mekonggiantcatfish_name:
    'user.lakeNotes.catalog.fish.jungle_mekonggiantcatfish.name',
  catalog_fish_jungle_mekonggiantcatfish_description:
    'user.lakeNotes.catalog.fish.jungle_mekonggiantcatfish.description',
  catalog_fish_jungle_siamesegiantcarp_name:
    'user.lakeNotes.catalog.fish.jungle_siamesegiantcarp.name',
  catalog_fish_jungle_siamesegiantcarp_description:
    'user.lakeNotes.catalog.fish.jungle_siamesegiantcarp.description',
  catalog_locations_jungle_name: 'user.lakeNotes.catalog.locations.jungle.name',
  catalog_locations_jungle_scene: 'user.lakeNotes.catalog.locations.jungle.scene',
  catalog_locations_jungle_description: 'user.lakeNotes.catalog.locations.jungle.description',
  catalog_gear_legendRod_name: 'user.lakeNotes.catalog.gear.legendRod.name',
  catalog_gear_legendRod_description: 'user.lakeNotes.catalog.gear.legendRod.description',
  buyBatch: 'user.lakeNotes.buyBatch',
  bitePreparation: 'user.lakeNotes.bitePreparation',
} as const;
export const useLakeCopy = () => useRegisteredCopy(keys);
export type LakeText = ReturnType<typeof useLakeCopy>['t'];

export function catalogText(t: LakeText, group: string, id: string, field = 'name') {
  const key = ('catalog_' + group + '_' + id + (field ? '_' + field : '')) as keyof typeof keys;
  return key in keys ? t(key) : '';
}
