const english = {
  title: 'Abuse audit',
  description:
    'Review request patterns and supporting evidence. Audit findings do not automatically penalize accounts.',
  caveat:
    'Client names and headers are self-reported and may be changed or relayed. A rule match is a lead, not proof of identity or misuse.',
  comparisonHelp:
    'Compare samples from the same time range and model. A cluster near 125 seconds may reflect a CDN timeout. Generic SDK names, shared limits, mixed clients, and a 200 SPA response do not establish misuse.',
  users: 'Users',
  ips: 'Shared IPs',
  clients: 'Client matches',
  rules: 'Client rules',
  config: 'Thresholds',
  access: 'Access events',
  from: 'From',
  to: 'To',
  apply: 'Apply filters',
  kind: 'Call type',
  total: 'All calls',
  self: 'Self-use',
  charity: 'Charity',
  unclassified: 'Unclassified',
  signal: 'Risk filter',
  all: 'All',
  rpm: 'Sustained RPM',
  concurrency: 'Sustained concurrency',
  user: 'User ID',
  inspect: 'Inspect',
  back: 'Back',
  next: 'Next page',
  refresh: 'Refresh',
  empty: 'No entries on this page',
  loading: 'Loading',
  coverage: 'Coverage',
  sampled: 'Sampled records',
  partial: 'Partial coverage',
  completed: 'Complete minutes',
  incomplete: 'Incomplete minutes',
  noMatch: 'No sustained match in the observed complete minutes',
  rpmUsed: 'Consumed RPM events',
  rpmDenied: 'RPM refusals',
  concurrentDenied: 'Concurrency refusals',
  peak: 'Peak concurrency',
  average: 'Average occupancy',
  minutes: 'Minute observations',
  minute: 'Minute',
  cap: 'Effective limits',
  status: 'Status',
  request: 'Request',
  model: 'Model',
  result: 'Outcome',
  reason: 'Refusal / error',
  dispatched: 'Dispatched',
  rejected: 'Rejected before dispatch',
  duration: 'Duration (ms)',
  response: 'Response started',
  unknown: 'Unknown',
  yes: 'Yes',
  no: 'No',
  source: 'Source information',
  quality: 'Source quality',
  ip: 'Observed IP',
  count: 'Count',
  first: 'First seen',
  last: 'Last seen',
  related: 'Related users and calls',
  ipHelp:
    'Only authenticated logical calls with direct or trusted forwarded IPs are associated. Proxy fallback IPs and anonymous scans are excluded; shared networks may contain unrelated people.',
  matches: 'Matched rules',
  matchLimit:
    'Evidence details are limited on this page. Review the paged rule list for further rule definitions.',
  revision: 'Revision',
  suspected: 'Suspected client',
  confirmed: 'Client risk confirmed',
  evidence: 'Evidence note',
  link: 'Evidence URL',
  enabled: 'Enabled',
  name: 'Rule name',
  edit: 'Edit',
  remove: 'Delete',
  create: 'New rule',
  save: 'Save',
  cancel: 'Cancel',
  add: 'Add AND condition',
  field: 'Field',
  operator: 'Operator',
  value: 'Match value',
  sensitive: 'Case sensitive',
  equals: 'Equals',
  contains: 'Contains',
  prefix: 'Starts with',
  ruleHelp:
    'All conditions in a rule must match. Rules are alternatives. Missing or truncated values cannot match. Up to 8 conditions per rule and 1,000 rules.',
  threshold: 'Threshold (%)',
  consecutive: 'Consecutive complete minutes',
  hours: 'Shared IP window (hours)',
  accounts: 'Shared IP account threshold',
  adminOnly: 'Only administrators can change thresholds.',
  configHelp:
    'Risk is assessed using total user occupancy and the limits recorded at that time. Restarts, gaps, pending settlements, and changed or unknown limits break the chain.',
  comparison: 'Same-model comparison',
  thisUser: 'This user',
  others: 'Other users',
  cancellations: 'Cancellation duration (seconds)',
  distribution: 'Client distribution on this source page',
  scan: 'Scan next source page',
  stop: 'Stop scan',
  resume: 'Resume scan',
  scanHelp:
    'Each step scans up to 100 logical requests. An empty match page does not mean the entire selected period has no matches.',
  key: 'CallerKey generation',
  path: 'Path category',
  http: 'HTTP status class',
  authenticated: 'Authenticated events',
  anonymous: 'Anonymous events',
  models: 'Model-list events',
  generations: 'Logical generation calls',
  ratio: 'Model-list / generation ratio',
  accessHelp:
    'Anonymous events are site totals and never attributed to an account. A zero generation denominator gives an unknown ratio. Access events do not count toward generation RPM or shared-IP risk.',
  capture: 'Capture started',
  dropped: 'Dropped events',
  gap: 'Last capture gap',
  partialAssociations: 'Only the first 100 user/type associations are shown.',
  policyRevision: 'Policy revision',
  range: 'Time range',
  defaultRange: 'Default window',
  lastHour: 'Last hour',
  lastDay: 'Last 24 hours',
  lastWeek: 'Last 7 days',
  custom: 'Custom range',
  rangeHelp:
    'Quick ranges use server time. The default is 24 hours, or the configured shared-IP window.',
  invalidRange:
    'Choose a valid past range of up to 30 days. Quick ranges avoid differences between your clock and the server.',
  observations: 'Recorded minutes only; missing time is not treated as zero usage',
  latestObservations:
    'Latest 100 minute records; the summary uses all available records in this range',
  sourcePage: 'This page of recorded requests',
  candidatePage: 'This page of candidate accounts',
  authenticatedCalls: 'Authenticated logical requests',
  noGap: 'No capture gaps recorded',
  ruleSteps:
    'Create and enable a rule, then open Client matches to review matching requests. Saved rules are evaluated automatically when you view the selected period.',
  ruleTemplate: 'Start with a matching pattern',
  uaTemplate: 'Client name in User-Agent',
  siteTemplate: 'Source website and application title',
  templateHelp:
    'Enter the observed values and save. Website and title must both match. These patterns cannot identify clients that hide or replace their headers.',
  advanced: 'Risk classification and supporting evidence',
  and: 'All of these',
  or: 'OR',
};
const chinese: typeof english = {
  title: '防滥用审计',
  description: '查看请求行为与命中依据，供人工初筛；审计命中不会自动处罚账号。',
  caveat:
    '客户端名称与请求头是自报信息，可能被修改或中继覆盖。命中规则只提供线索，不证明身份或盗用行为。',
  comparisonHelp:
    '对照同一时间段、同一模型的样本。125 秒附近的取消可能来自 CDN 超时；通用 SDK 标识、共享额度、混用客户端和 200 首页响应都不能独立认定盗用。',
  users: '用户',
  ips: '共享 IP',
  clients: '客户端命中',
  rules: '客户端规则',
  config: '审计阈值',
  access: '探测访问',
  from: '开始时间',
  to: '结束时间',
  apply: '应用筛选',
  kind: '调用类型',
  total: '全部调用',
  self: '自用',
  charity: '公益',
  unclassified: '未分类',
  signal: '风险筛选',
  all: '全部',
  rpm: 'RPM 持续偏高',
  concurrency: '并发持续偏高',
  user: '用户 ID',
  inspect: '查看详情',
  back: '返回',
  next: '下一页',
  refresh: '刷新',
  empty: '本页没有记录',
  loading: '加载中',
  coverage: '覆盖范围',
  sampled: '已查看样本',
  partial: '覆盖不完整',
  completed: '完整分钟',
  incomplete: '不完整分钟',
  noMatch: '已观察到的完整分钟未达到持续命中条件',
  rpmUsed: '已消耗 RPM 次数',
  rpmDenied: 'RPM 拒绝次数',
  concurrentDenied: '并发拒绝次数',
  peak: '并发峰值',
  average: '平均占用',
  minutes: '分钟记录',
  minute: '分钟',
  cap: '当时生效额度',
  status: '状态',
  request: '请求',
  model: '模型',
  result: '终态',
  reason: '拒绝／错误原因',
  dispatched: '已派发',
  rejected: '派发前拒绝',
  duration: '时长（毫秒）',
  response: '响应是否开始',
  unknown: '未知',
  yes: '是',
  no: '否',
  source: '来源信息',
  quality: '来源质量',
  ip: '观察到的 IP',
  count: '次数',
  first: '首次出现',
  last: '末次出现',
  related: '关联账号与调用',
  ipHelp:
    '仅关联已认证逻辑调用的直连或可信转发 IP；代理回退 IP 与匿名扫描不计入。共享网络可能包含互不相关的用户。',
  matches: '命中规则',
  matchLimit: '本页限制显示的依据详情数量；更多规则定义可在客户端规则分页列表查看。',
  revision: '版本',
  suspected: '客户端存在风险嫌疑',
  confirmed: '客户端风险已证实',
  evidence: '依据备注',
  link: '依据链接',
  enabled: '启用',
  name: '规则名称',
  edit: '编辑',
  remove: '删除',
  create: '新增规则',
  save: '保存',
  cancel: '取消',
  add: '增加 AND 条件',
  field: '字段',
  operator: '匹配方式',
  value: '匹配值',
  sensitive: '区分大小写',
  equals: '完全相等',
  contains: '包含',
  prefix: '前缀',
  ruleHelp:
    '同一规则的全部条件共同匹配，规则之间为 OR。缺失或截断字段不匹配；每条最多 8 个条件，全站最多 1,000 条规则。',
  threshold: '额度占比阈值（%）',
  consecutive: '连续完整分钟数',
  hours: '共享 IP 窗口（小时）',
  accounts: '共享 IP 账号数阈值',
  adminOnly: '仅管理员可修改阈值。',
  configHelp:
    '依据用户总占用及当时的额度判断风险。重启、缺口、未结算请求及变化或未知的额度都会中断连续命中链。',
  comparison: '同模型对照',
  thisUser: '当前用户',
  others: '其他用户',
  cancellations: '取消时长（秒）',
  distribution: '本页来源样本的客户端分布',
  scan: '扫描下一页来源',
  stop: '停止扫描',
  resume: '继续扫描',
  scanHelp: '每步最多扫描 100 次逻辑请求。本页无命中不表示整个时间范围没有命中。',
  key: 'CallerKey 代次',
  path: '路径类别',
  http: 'HTTP 状态类别',
  authenticated: '已认证访问',
  anonymous: '匿名访问',
  models: '模型列表访问',
  generations: '逻辑生成调用',
  ratio: '模型列表／生成调用比例',
  accessHelp:
    '匿名访问仅计全站数量，不关联账号。生成分母为零时比例未知。探测访问不计入生成 RPM 或共享 IP 主指标。',
  capture: '采集起点',
  dropped: '丢弃事件数',
  gap: '最近采集缺口',
  partialAssociations: '仅显示前 100 条账号／类型关联。',
  policyRevision: '政策版本',
  range: '时间范围',
  defaultRange: '默认时间窗口',
  lastHour: '最近 1 小时',
  lastDay: '最近 24 小时',
  lastWeek: '最近 7 天',
  custom: '自定义时间',
  rangeHelp: '快捷范围以服务器时间为准。默认查询 24 小时，共享 IP 使用审计阈值中设置的窗口。',
  invalidRange: '请选择不超过 30 天的有效过去时间段。使用快捷范围可避免电脑与服务器的时钟偏差。',
  observations: '仅统计已记录的分钟，缺失时段不按零占用计算',
  latestObservations: '展示最近 100 条分钟记录；汇总仍使用此范围内全部可用记录',
  sourcePage: '本页已记录的请求',
  candidatePage: '本页候选账号',
  authenticatedCalls: '已认证的逻辑请求',
  noGap: '未记录到采集缺口',
  ruleSteps:
    '先新增并启用规则，再到“客户端命中”查看请求。查看所选时间段时，系统会自动匹配已保存的规则。',
  ruleTemplate: '选择匹配方式',
  uaTemplate: 'User-Agent 中的客户端名称',
  siteTemplate: '来源网站与应用标题',
  templateHelp:
    '填写实际观察到的值并保存。“网站与标题”需要两项同时匹配；隐藏或改写请求头的客户端无法据此识别。',
  advanced: '风险分类与依据',
  and: '同时满足',
  or: 'OR',
};
export function riskCopy(language: string) {
  return language.startsWith('zh') ? chinese : english;
}
export type RiskCopy = typeof english;

export function fieldLabel(field: string, c: RiskCopy): string {
  const labels: Record<string, string> = {
    effective_ip: c.ip,
    user_agent: 'User-Agent',
    origin: 'Origin',
    referer: 'Referer',
    http_referer: 'HTTP-Referer',
    openrouter_title: 'X-OpenRouter-Title',
    legacy_title: 'X-Title',
    sdk_lang: 'X-Stainless-Lang',
    sdk_version: 'X-Stainless-Package-Version',
    sdk_runtime: 'X-Stainless-Runtime',
    sdk_runtime_version: 'X-Stainless-Runtime-Version',
  };
  return labels[field] ?? field;
}
export function pathLabel(path: string): string {
  return (
    (
      {
        models: 'GET /v1/models',
        billing_subscription: 'GET /dashboard/billing/subscription',
        billing_usage: 'GET /dashboard/billing/usage',
        v1_billing_subscription: 'GET /v1/dashboard/billing/subscription',
        v1_billing_usage: 'GET /v1/dashboard/billing/usage',
        sub2api_billing: 'GET /v1/sub2api/billing',
        chat_head: 'HEAD /v1/chat/completions',
      } as Record<string, string>
    )[path] ?? path
  );
}
