import type { TFunction } from 'i18next';
export function riskCopy(t: TFunction) {
  return {
    title: t('common.riskAudit.title'),
    description: t('common.riskAudit.description'),
    caveat: t('common.riskAudit.caveat'),
    comparisonHelp: t('common.riskAudit.comparisonHelp'),
    users: t('common.riskAudit.users'),
    ips: t('common.riskAudit.ips'),
    clients: t('common.riskAudit.clients'),
    rules: t('common.riskAudit.rules'),
    config: t('common.riskAudit.config'),
    access: t('common.riskAudit.access'),
    from: t('common.riskAudit.from'),
    to: t('common.riskAudit.to'),
    apply: t('common.riskAudit.apply'),
    kind: t('common.riskAudit.kind'),
    total: t('common.riskAudit.total'),
    self: t('common.riskAudit.self'),
    charity: t('common.riskAudit.charity'),
    unclassified: t('common.riskAudit.unclassified'),
    signal: t('common.riskAudit.signal'),
    all: t('common.riskAudit.all'),
    rpm: t('common.riskAudit.rpm'),
    concurrency: t('common.riskAudit.concurrency'),
    user: t('common.riskAudit.user'),
    inspect: t('common.riskAudit.inspect'),
    back: t('common.riskAudit.back'),
    next: t('common.riskAudit.next'),
    refresh: t('common.riskAudit.refresh'),
    empty: t('common.riskAudit.empty'),
    loading: t('common.riskAudit.loading'),
    coverage: t('common.riskAudit.coverage'),
    sampled: t('common.riskAudit.sampled'),
    partial: t('common.riskAudit.partial'),
    completed: t('common.riskAudit.completed'),
    incomplete: t('common.riskAudit.incomplete'),
    noMatch: t('common.riskAudit.noMatch'),
    rpmUsed: t('common.riskAudit.rpmUsed'),
    rpmDenied: t('common.riskAudit.rpmDenied'),
    concurrentDenied: t('common.riskAudit.concurrentDenied'),
    peak: t('common.riskAudit.peak'),
    average: t('common.riskAudit.average'),
    minutes: t('common.riskAudit.minutes'),
    minute: t('common.riskAudit.minute'),
    cap: t('common.riskAudit.cap'),
    status: t('common.riskAudit.status'),
    request: t('common.riskAudit.request'),
    model: t('common.riskAudit.model'),
    result: t('common.riskAudit.result'),
    reason: t('common.riskAudit.reason'),
    dispatched: t('common.riskAudit.dispatched'),
    rejected: t('common.riskAudit.rejected'),
    duration: t('common.riskAudit.duration'),
    response: t('common.riskAudit.response'),
    unknown: t('common.riskAudit.unknown'),
    yes: t('common.riskAudit.yes'),
    no: t('common.riskAudit.no'),
    source: t('common.riskAudit.source'),
    quality: t('common.riskAudit.quality'),
    ip: t('common.riskAudit.ip'),
    count: t('common.riskAudit.count'),
    first: t('common.riskAudit.first'),
    last: t('common.riskAudit.last'),
    related: t('common.riskAudit.related'),
    ipHelp: t('common.riskAudit.ipHelp'),
    matches: t('common.riskAudit.matches'),
    matchLimit: t('common.riskAudit.matchLimit'),
    revision: t('common.riskAudit.revision'),
    suspected: t('common.riskAudit.suspected'),
    confirmed: t('common.riskAudit.confirmed'),
    evidence: t('common.riskAudit.evidence'),
    link: t('common.riskAudit.link'),
    enabled: t('common.riskAudit.enabled'),
    name: t('common.riskAudit.name'),
    edit: t('common.riskAudit.edit'),
    remove: t('common.riskAudit.remove'),
    create: t('common.riskAudit.create'),
    save: t('common.riskAudit.save'),
    cancel: t('common.riskAudit.cancel'),
    add: t('common.riskAudit.add'),
    field: t('common.riskAudit.field'),
    operator: t('common.riskAudit.operator'),
    value: t('common.riskAudit.value'),
    sensitive: t('common.riskAudit.sensitive'),
    equals: t('common.riskAudit.equals'),
    contains: t('common.riskAudit.contains'),
    prefix: t('common.riskAudit.prefix'),
    ruleHelp: t('common.riskAudit.ruleHelp'),
    autoBan: t('common.riskAudit.autoBan'),
    noAutoBan: t('common.riskAudit.noAutoBan'),
    autoBanDisabled: t('common.riskAudit.autoBanDisabled'),
    autoBanEnabled: t('common.riskAudit.autoBanEnabled'),
    autoBanHours: t('common.riskAudit.autoBanHours'),
    autoBanDays: t('common.riskAudit.autoBanDays'),
    autoBanSeconds: t('common.riskAudit.autoBanSeconds'),
    autoBanPermanent: t('common.riskAudit.autoBanPermanent'),
    autoBanDuration: t('common.riskAudit.autoBanDuration'),
    autoBanInvalid: t('common.riskAudit.autoBanInvalid'),
    autoBanProtected: t('common.riskAudit.autoBanProtected'),
    autoBanHelp: t('common.riskAudit.autoBanHelp'),
    threshold: t('common.riskAudit.threshold'),
    consecutive: t('common.riskAudit.consecutive'),
    hours: t('common.riskAudit.hours'),
    accounts: t('common.riskAudit.accounts'),
    adminOnly: t('common.riskAudit.adminOnly'),
    configHelp: t('common.riskAudit.configHelp'),
    comparison: t('common.riskAudit.comparison'),
    thisUser: t('common.riskAudit.thisUser'),
    others: t('common.riskAudit.others'),
    cancellations: t('common.riskAudit.cancellations'),
    distribution: t('common.riskAudit.distribution'),
    scan: t('common.riskAudit.scan'),
    stop: t('common.riskAudit.stop'),
    resume: t('common.riskAudit.resume'),
    scanHelp: t('common.riskAudit.scanHelp'),
    key: t('common.riskAudit.key'),
    path: t('common.riskAudit.path'),
    http: t('common.riskAudit.http'),
    authenticated: t('common.riskAudit.authenticated'),
    anonymous: t('common.riskAudit.anonymous'),
    models: t('common.riskAudit.models'),
    generations: t('common.riskAudit.generations'),
    ratio: t('common.riskAudit.ratio'),
    accessHelp: t('common.riskAudit.accessHelp'),
    capture: t('common.riskAudit.capture'),
    dropped: t('common.riskAudit.dropped'),
    gap: t('common.riskAudit.gap'),
    partialAssociations: t('common.riskAudit.partialAssociations'),
    policyRevision: t('common.riskAudit.policyRevision'),
    range: t('common.riskAudit.range'),
    defaultRange: t('common.riskAudit.defaultRange'),
    lastHour: t('common.riskAudit.lastHour'),
    lastDay: t('common.riskAudit.lastDay'),
    lastWeek: t('common.riskAudit.lastWeek'),
    custom: t('common.riskAudit.custom'),
    rangeHelp: t('common.riskAudit.rangeHelp'),
    invalidRange: t('common.riskAudit.invalidRange'),
    observations: t('common.riskAudit.observations'),
    latestObservations: t('common.riskAudit.latestObservations'),
    sourcePage: t('common.riskAudit.sourcePage'),
    candidatePage: t('common.riskAudit.candidatePage'),
    authenticatedCalls: t('common.riskAudit.authenticatedCalls'),
    noGap: t('common.riskAudit.noGap'),
    ruleSteps: t('common.riskAudit.ruleSteps'),
    ruleTemplate: t('common.riskAudit.ruleTemplate'),
    uaTemplate: t('common.riskAudit.uaTemplate'),
    siteTemplate: t('common.riskAudit.siteTemplate'),
    templateHelp: t('common.riskAudit.templateHelp'),
    advanced: t('common.riskAudit.advanced'),
    and: t('common.riskAudit.and'),
    or: t('common.riskAudit.or'),
  };
}
export type RiskCopy = ReturnType<typeof riskCopy>;
export function fieldLabel(field: string, c: RiskCopy): string {
  const labels: Record<string, string> = {
    effective_ip: c.ip,
    user_agent: 'User-Agent',
    origin: 'Origin',
    referer: 'Referer',
    http_referer: 'HTTP-Referer',
    openrouter_title: 'X-OpenRouter-Title',
    legacy_title: 'X-Title',
    sdk_lang: 'X-Stainless-Lang',
    sdk_version: 'X-Stainless-Package-Version',
    sdk_runtime: 'X-Stainless-Runtime',
    sdk_runtime_version: 'X-Stainless-Runtime-Version',
  };
  return labels[field] ?? field;
}
export function pathLabel(path: string): string {
  return (
    (
      {
        models: 'GET /v1/models',
        billing_subscription: 'GET /dashboard/billing/subscription',
        billing_usage: 'GET /dashboard/billing/usage',
        v1_billing_subscription: 'GET /v1/dashboard/billing/subscription',
        v1_billing_usage: 'GET /v1/dashboard/billing/usage',
        sub2api_billing: 'GET /v1/sub2api/billing',
        chat_head: 'HEAD /v1/chat/completions',
      } as Record<string, string>
    )[path] ?? path
  );
}
