// Generates THIRD_PARTY_NOTICES.md from package.json + package-lock.json and
// the installed package metadata. Classifies every resolved package as either
// a runtime dependency (bundled into the served application) or development /
// build tooling, using the dependency closure from the lockfile.
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const webDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const lock = JSON.parse(await readFile(join(webDir, 'package-lock.json'), 'utf8'));
const packages = lock.packages ?? {};

function entryFor(name) {
  const keys = Object.keys(packages).filter(
    (key) => key === `node_modules/${name}` || key.endsWith(`/node_modules/${name}`),
  );
  if (keys.length === 0) return null;
  // Prefer the top-level entry so nested duplicate versions are read from the
  // correct location.
  const key = keys.find((k) => k === `node_modules/${name}`) ?? keys[0];
  return { key, entry: packages[key] };
}

async function metadataFor(name) {
  const found = entryFor(name);
  if (!found) return null;
  try {
    const meta = JSON.parse(
      await readFile(
        join(webDir, 'node_modules', found.key.slice('node_modules/'.length), 'package.json'),
        'utf8',
      ),
    );
    return {
      version: found.entry.version ?? '?',
      license: licenseOf(meta),
      homepage: homepageOf(meta),
    };
  } catch {
    return { version: found.entry.version ?? '?', license: 'Unknown', homepage: '' };
  }
}

function licenseOf(meta) {
  const value = meta.license ?? meta.licenses?.[0];
  if (!value) return 'Unknown';
  if (typeof value === 'string') return value;
  if (typeof value === 'object' && typeof value.type === 'string') return value.type;
  return 'Unknown';
}

function homepageOf(meta) {
  if (typeof meta.homepage === 'string') return meta.homepage;
  if (typeof meta.repository === 'string') return meta.repository;
  if (meta.repository && typeof meta.repository === 'object') {
    const url = meta.repository.url;
    if (typeof url === 'string') {
      return url.replace(/^git\+/, '').replace(/\.git$/, '');
    }
  }
  return '';
}

function licenseCell(license) {
  if (/^[A-Za-z0-9.+-]+$/.test(license) && !license.startsWith('SEE LICENSE')) {
    return `[${license}](https://spdx.org/licenses/${license}.html)`;
  }
  return license;
}

function closureOf(directDeps) {
  const seen = new Set();
  const queue = [...Object.keys(directDeps)];
  while (queue.length > 0) {
    const name = queue.shift();
    if (seen.has(name)) continue;
    seen.add(name);
    const found = entryFor(name);
    if (!found) continue;
    const entry = found.entry;
    for (const dep of Object.keys(entry.dependencies ?? {})) queue.push(dep);
    for (const key of Object.keys(packages)) {
      if (key.startsWith(`${found.key}/node_modules/`)) {
        queue.push(key.slice('node_modules/'.length));
      }
    }
  }
  return seen;
}

async function markdownTable(names) {
  const rows = [];
  for (const name of [...names].sort()) {
    const meta = (await metadataFor(name)) ?? { version: '?', license: 'Unknown', homepage: '' };
    rows.push(`| ${name} | ${meta.version} | ${licenseCell(meta.license)} | ${meta.homepage} |`);
  }
  return ['| Package | Version | License | Homepage |', '| --- | --- | --- | --- |', ...rows].join(
    '\n',
  );
}

const root = packages[''] ?? {};
const runtimeClosure = closureOf(root.dependencies ?? {});
const devClosure = closureOf(root.devDependencies ?? {});
const buildOnly = new Set([...devClosure].filter((name) => !runtimeClosure.has(name)));

const runtimeTable = await markdownTable(runtimeClosure);
const buildTable = await markdownTable(buildOnly);

const output = `# Third-Party Notices

This project is licensed under the GNU Affero General Public License v3.0 (see the
LICENSE file at the repository root). The web frontend additionally bundles or
links the third-party packages listed below. Their license texts are available
from the SPDX License List or from each package's repository.

This file is generated by \`scripts/gen-notices.mjs\`; do not edit by hand.
It is regenerated by \`npm run build\` / \`npm run notices\`.

## Runtime dependencies (bundled into the served application)

${runtimeTable}

## Development & build tooling (not shipped in the application)

${buildTable}

The classification above is derived from the dependency closure of
\`package-lock.json\`; the lockfile remains the authoritative full dependency
tree.
`;

await writeFile(join(webDir, 'THIRD_PARTY_NOTICES.md'), output);
console.log(
  `THIRD_PARTY_NOTICES.md written (${runtimeClosure.size} runtime, ${buildOnly.size} build-only packages)`,
);
