package lakenotes

import (
	"database/sql"
	"encoding/json"
	"math"
	"strings"
	"testing"
	"time"

	"github.com/waiting-here/NonbiriAPI/internal/lakenotes/rules"
)

func TestTreasurePrivateSamplingTerminalAtomicReplay(t *testing.T) {
	f := newFixture(t)
	f.random.value = 0.125
	f.enable(t)
	view := f.profile(t)
	// Seed a prior authoritative catch so the original treasure branch is eligible.
	f.tx(t, func(tx *sql.Tx) {
		row, e := profileTx(f.ctx(f.user), tx, f.user, false, testNow)
		if e != nil {
			t.Fatal(e)
		}
		fish, ok := rules.Fish("lake_carp")
		if !ok {
			t.Fatal("compiled carp missing")
		}
		if e = row.profile.StoreCatch(fish, fish.Length[0], 0, false); e != nil {
			t.Fatal(e)
		}
		if e = saveProfileTx(f.ctx(f.user), tx, f.user, &row, testNow); e != nil {
			t.Fatal(e)
		}
		view.Revision = rev(row.revision)
	})
	start, e := f.service.Start(f.ctx(f.user), f.user, testKey(500), StartInput{view.Revision})
	if e != nil {
		t.Fatal(e)
	}
	cast := start.Value.Cast
	if cast.State.Plan.TreasureY == nil || cast.State.Reward != nil {
		t.Fatal(cast)
	}
	for batch := 0; cast.Phase == "waiting"; batch++ {
		f.now.Add(2 * int64(time.Second))
		out, e := f.service.Checkpoint(f.ctx(f.user), f.user, cast.ID, testKey(501+batch), checkpoint(cast, 120))
		if e != nil {
			t.Fatal(e)
		}
		cast = out.Value.Cast
	}
	if cast.State.Treasure == nil {
		t.Fatal("missing compiled treasure")
	}
	// This is a server checkpoint fixture, never an HTTP-importable state.
	f.tx(t, func(tx *sql.Tx) {
		row, e := castTx(f.ctx(f.user), tx, f.user, cast.ID)
		if e != nil {
			t.Fatal(e)
		}
		half := row.state.Snapshot.BarHeight / 2
		row.state.BarY = math.Max(half, math.Min(1-half, row.state.Fish.Y))
		row.state.BarVelocity = 0
		row.state.Progress = 0.9999
		row.state.Treasure.Progress = 1
		row.state.Treasure.Secured = true
		row.state.WasHit = true
		if e = saveCastTx(f.ctx(f.user), tx, &row, time.Unix(0, f.now.Load()), map[string]any{}); e != nil {
			t.Fatal(e)
		}
		cast = row.view(1)
	})
	before := f.random.draws.Load()
	f.now.Add(int64(time.Second))
	in := checkpoint(cast, 120)
	result, e := f.service.Checkpoint(f.ctx(f.user), f.user, cast.ID, testKey(510), in)
	if e != nil || result.Value.Cast.Phase != "success" || result.Value.Cast.State.Reward == nil || result.Value.Profile.Profile.TreasureOpened != "1" {
		t.Fatal(result, e)
	}
	if result.Value.Cast.AckTick >= in.ToTick {
		t.Fatal("terminal did not stop within segment")
	}
	drawn := f.random.draws.Load()
	if drawn <= before {
		t.Fatal("reward was not sampled at terminal")
	}
	replay, e := f.service.Checkpoint(f.ctx(f.user), f.user, cast.ID, testKey(510), in)
	if e != nil || !replay.Replayed || f.random.draws.Load() != drawn || replay.Value.Profile.Profile.Coins != result.Value.Profile.Profile.Coins {
		t.Fatal(replay, e)
	}
	f.tx(t, func(tx *sql.Tx) {
		var private []byte
		if e := tx.QueryRow("SELECT reward_plan FROM lake_notes_casts WHERE id=?", cast.ID).Scan(&private); e != nil || string(private) == "{}" {
			t.Fatal(string(private), e)
		}
		var reward rules.TreasureReward
		if e := json.Unmarshal(private, &reward); e != nil || reward != *result.Value.Cast.State.Reward {
			t.Fatal(reward, e)
		}
		export, e := f.service.ExportUserTx(f.ctx(f.user), tx, f.user, 100)
		if e != nil {
			t.Fatal(e)
		}
		raw, _ := json.Marshal(export)
		if strings.Contains(string(raw), "reward_plan") || strings.Contains(string(raw), "input_digest") {
			t.Fatal("private storage leaked")
		}
	})
}
func TestTerminalRetentionKeepsNewReplayIdentity(t *testing.T) {
	f := newFixture(t)
	f.enable(t)
	v := f.profile(t)
	start, e := f.service.Start(f.ctx(f.user), f.user, testKey(520), StartInput{v.Revision})
	if e != nil {
		t.Fatal(e)
	}
	f.tx(t, func(tx *sql.Tx) {
		c, e := castTx(f.ctx(f.user), tx, f.user, start.Value.Cast.ID)
		if e != nil {
			t.Fatal(e)
		}
		row, e := profileTx(f.ctx(f.user), tx, f.user, false, testNow)
		if e != nil {
			t.Fatal(e)
		}
		// A valid terminal fixture is generated by the complete compiled engine.
		for i := 0; i < 1000 && !c.state.Terminal(); i++ {
			held := false
			if c.state.Fish != nil {
				held = c.state.Fish.Y < c.state.BarY
			}
			row.profile, c.state, e = rules.Advance(row.profile, c.state, []bool{held})
			if e != nil {
				t.Fatal(e)
			}
		}
		if !c.state.Terminal() {
			t.Fatal("terminal fixture not reached")
		}
		if e = c.stop(testNow * int64(time.Second)); e != nil {
			t.Fatal(e)
		}
		if e = saveProfileTx(f.ctx(f.user), tx, f.user, &row, testNow); e != nil {
			t.Fatal(e)
		}
		if e = saveCastTx(f.ctx(f.user), tx, &c, time.Unix(testNow, 0), map[string]any{}); e != nil {
			t.Fatal(e)
		}
		if _, e = tx.Exec("UPDATE sessions SET expires_at=?,absolute_expires_at=? WHERE user_id=?", testNow+40*86400, testNow+40*86400, f.user); e != nil {
			t.Fatal(e)
		}
	})
	f.now.Store((testNow + 30*86400) * int64(time.Second))
	state, e := f.service.Cast(f.ctx(f.user), f.user, start.Value.Cast.ID)
	if e != nil {
		t.Fatal(e)
	}
	if _, e = f.service.Pause(f.ctx(f.user), f.user, state.Cast.ID, testKey(521), control(state.Cast)); e != nil {
		t.Fatal(e)
	}
	work, e := f.service.Retain(f.ctx(f.admin), testNow+30*86400, 100, time.Second)
	if e != nil || work.Processed != 0 {
		t.Fatal(work, e)
	}
	work, e = f.service.Retain(f.ctx(f.admin), testNow+31*86400, 100, time.Second)
	if e != nil || work.Processed != 1 {
		t.Fatal(work, e)
	}
}
