import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';

type CoreCopyEntry = readonly [en: string, zh: string];

const copy = {
  'account.musicQuality': ['Game music quality', '游戏音乐音质'],
  'account.musicLight': ['Lightweight', '轻量版'],
  'account.musicLossless': ['Lossless', '无损版'],
  'account.musicQualityBody': [
    'Saved only in this browser. Lossless uses more data. Applies the next time you enable music or enter a game; sound effects are unchanged.',
    '仅保存在当前浏览器。无损版使用更多流量，下次开启音乐或进入游戏时生效，不影响短音效。',
  ],
  'common.loading': ['Loading…', '正在加载…'],
  'common.retry': ['Retry', '重试'],
  'common.errorTitle': ['Could not load this section', '无法加载此区域'],
  'common.errorBody': [
    'The confirmed data for this section is unavailable.',
    '此区域的最新数据当前不可用。',
  ],
  'common.unavailableTitle': ['Not available yet', '暂未可用'],
  'common.unavailableBody': ['This section is not available in this version.', '此功能暂不可用。'],
  'common.emptyTitle': ['Nothing here yet', '这里还没有内容'],
  'common.working': ['Working…', '正在处理…'],
  'common.cancel': ['Cancel', '取消'],
  'common.close': ['Close', '关闭'],
  'common.save': ['Save', '保存'],
  'common.delete': ['Delete', '删除'],
  'common.edit': ['Edit', '编辑'],
  'common.copy': ['Copy', '复制'],
  'common.copied': ['Copied', '已复制'],
  'common.copyFailed': [
    'Copy failed. Select and copy the value manually.',
    '复制失败，请手动选择并复制。',
  ],
  'common.previous': ['Previous', '上一页'],
  'common.next': ['Next', '下一页'],
  'common.enabled': ['Enabled', '已启用'],
  'common.disabled': ['Disabled', '已停用'],
  'common.yes': ['Yes', '是'],
  'common.no': ['No', '否'],
  'common.unknown': ['Unknown', '未知'],
  'common.notSet': ['Not set', '未设置'],
  'common.available': ['Available', '可用'],
  'common.blocked': ['Blocked', '已阻止'],
  'common.reconcile': ['Check latest status', '检查最新状态'],
  'common.retrySame': ['Retry the same operation', '重试同一操作'],
  'common.created': ['Created', '创建时间'],
  'common.updated': ['Updated', '更新时间'],
  'common.refresh': ['Refresh', '刷新'],
  'common.back': ['Back', '返回'],
  'common.remove': ['Remove', '移除'],
  'common.search': ['Search', '搜索'],
  'common.conflict': [
    'The data changed. Review the latest values and try again.',
    '数据已更新，请核对后重试。',
  ],
  'common.outcomeUnknown': [
    'The response was lost. The page is checking the latest status and will not resend the action.',
    '响应已丢失。页面正在检查最新状态，不会自动重发操作。',
  ],
  'common.fixedFailure': [
    'The one-time value was not received. Click again only if you want a new operation.',
    '没有取得一次性明文。只有再次点击才会开始新操作。',
  ],
  'common.maintenance': ['This operation is temporarily unavailable.', '此操作暂时不可用。'],
  'common.permissionLost': [
    'Your current session no longer permits this operation.',
    '当前会话已无权执行此操作。',
  ],
  'connector.openai': ['OpenAI-compatible', 'OpenAI 兼容'],
  'connector.anthropic': ['Anthropic-compatible', 'Anthropic 兼容'],
  'connector.gateway': ['AI SDK Gateway v3', 'AI SDK Gateway v3'],
  'home.title': ['Welcome back, {{name}}', '欢迎回来，{{name}}'],
  'home.signedOutTitle': ['Your AI routing workspace', '你的 AI 路由工作台'],
  'home.signedOutBody': [
    'Sign in to manage endpoints, models, and your account.',
    '登录后即可管理端点、模型和账户。',
  ],
  'home.signIn': ['Sign in with Discord', '使用 Discord 登录'],
  'home.description': [
    'Manage API resources and check your usage and balance.',
    '管理 API 资源，查看用量与余额。',
  ],
  'home.profileTitle': ['Account', '账户'],
  'home.username': ['Username', '用户名'],
  'home.accountStatus': ['Account status', '账户状态'],
  'home.active': ['Active', '正常'],
  'home.banned': ['Restricted', '受限'],
  'home.economyTitle': ['Balance and level', '余额与等级'],
  'home.balance': ['General credits', '通用积分'],
  'home.gameBalance': ['Game credits', '游戏积分'],
  'home.creditHistory': ['Credit history', '积分流水'],
  'home.donationCredit': ['Total donation rewards', '累计捐赠回馈'],
  'home.level': ['Level', '等级'],
  'home.levelValue': ['Lv{{level}} · {{name}}', '等级 {{level}} · {{name}}'],
  'home.usageTitle': ['Lifetime usage', '累计用量'],
  'home.requests': ['Requests', '请求数'],
  'home.promptTokens': ['Prompt tokens', '提示 Token'],
  'home.outputTokens': ['Output tokens', '输出 Token'],
  'home.unknownUsage': ['Requests with unknown usage', '用量未知请求'],
  'home.checkinTitle': ['General-credit check-in', '通用积分签到'],
  'home.gameCheckinTitle': ['Game-credit check-in', '游戏积分签到'],
  'home.checkin.unavailable': ['Check-in is not available', '签到未启用'],
  'home.checkin.today': ['Today', '今日状态'],
  'home.checkin.checkedIn': ['Checked in', '已签到'],
  'home.checkin.notCheckedIn': ['Not checked in yet', '未签到'],
  'home.checkin.awardRange': ['Award range (credits)', '奖励范围（积分）'],
  'home.checkin.threshold': ['Check-in threshold (credits)', '签到门槛（积分）'],
  'home.checkin.thresholdNone': ['No limit', '无上限'],
  'home.checkin.thresholdHint': [
    'This limit applies to every level and only decides whether you can check in. Once reached, no new check-in is allowed; rewards already granted do not change.',
    '此上限适用于所有等级，只决定还能否签到；达到后不能再签到，已发放的奖励不会减少。',
  ],
  'home.checkin.submit': ['Check in', '立即签到'],
  'home.checkin.done': [
    'Checked in: awarded {{award}} credits; this wallet now holds {{credits}}.',
    '签到成功：获得 {{award}} 积分，该钱包当前积分 {{credits}}。',
  ],
  'home.checkinRefreshFailed': [
    'Check-in succeeded, but the latest status could not be refreshed. Refresh to retry the read; the check-in will not be submitted again.',
    '签到已经成功，但最新状态刷新失败。你可以重新刷新读取；页面不会再次提交签到。',
  ],
  'home.gamesTitle': ['Continue or view results', '继续进行或查看结果'],
  'home.announcementsTitle': ['Announcements', '公告'],
  'home.announcement.viewAll': ['View all announcements', '查看全部公告'],
  'home.announcement.viewFull': ['View full announcement', '查看公告全文'],
  'home.announcement.hide': ['Hide from home', '在首页隐藏'],
  'home.announcement.loadingBody': ['Loading the full announcement…', '正在加载公告全文…'],
  'home.announcement.detailError': [
    'The full announcement could not be loaded.',
    '公告全文加载失败。',
  ],
  'home.announcement.pinned': ['Pinned', '置顶'],
  'home.announcement.languageFallback': [
    'Language fallback: {{language}}',
    '语言回退：{{language}}',
  ],
  'home.announcement.severity.info': ['Info', '信息'],
  'home.announcement.severity.warning': ['Warning', '警告'],
  'home.announcement.severity.important': ['Important', '重要'],
  'home.announcement.language.zh': ['Chinese', '中文'],
  'home.announcement.language.en': ['English', '英文'],
  'home.quickTitle': ['Quick access', '快捷入口'],
  'home.endpoints': ['Manage resources', '管理资源'],
  'home.models': ['Manage models', '管理模型'],
  'home.callerKey': ['API access', 'API 接入'],
  'home.activities': ['Open activities', '打开活动'],
  'home.games': ['Open games', '打开游戏'],
  'home.continue': ['Continue', '继续'],
  'home.view': ['View result', '查看结果'],
  'home.gameFishing': ['Fishing', '钓鱼'],
  'home.gameLinklink': ['Link Link', '连连看'],
  'home.gameRps': ['Three-player rock paper scissors', '三人猜拳'],
  'home.gameBidding': ['Bidding Duel', '竞标对决'],
  'home.gameBlackjack': ['Blackjack', '二十一点'],
  'home.gameLikes': ['Like Battle', '点赞大战'],
  'home.capabilityUnavailable': ['This summary is not available yet.', '此摘要暂不可用。'],
  'endpoints.title': ['Resources', '资源'],
  'endpoints.description': [
    'Manage service addresses, keys, model checks, and available model connections.',
    '管理服务地址、密钥、模型检查结果和可用的模型连接。',
  ],
  'endpoints.create': ['Create endpoint', '创建端点'],
  'endpoints.emptyTitle': ['No endpoints yet', '还没有端点'],
  'endpoints.emptyBody': [
    'Create an endpoint to connect a service you own or are allowed to use.',
    '创建端点，连接你拥有或获准使用的服务。',
  ],
  'endpoints.connector': ['Service type', '服务类型'],
  'endpoints.origin': ['Origin', '来源'],
  'endpoints.originCustom': ['Custom endpoint', '自定义端点'],
  'endpoints.originMainstream': ['Mainstream channel: {{name}}', '主流渠道：{{name}}'],
  'endpoints.mainstream': ['Mainstream channel', '主流渠道'],
  'endpoints.custom': ['Custom endpoint', '自定义端点'],
  'endpoints.channel': ['Channel', '渠道'],
  'endpoints.baseUrl': ['Service address', '服务地址'],
  'endpoints.note': ['Note', '备注'],
  'endpoints.keyCount': ['Key count', '密钥数量'],
  'endpoints.configuration': ['Endpoint configuration', '端点配置'],
  'endpoints.manage': ['Manage endpoint', '管理端点'],
  'endpoints.detailsTitle': ['Endpoint details', '端点详情'],
  'endpoints.detailsDescription': [
    'The service type and address cannot be changed after creation. Create a new endpoint to replace either one.',
    '服务类型与地址创建后不可更改；如需更换，请新建端点。',
  ],
  'endpoints.addKey': ['Add key', '添加密钥'],
  'endpoints.noKeysTitle': ['No keys', '还没有密钥'],
  'endpoints.noKeysBody': [
    'Add a key you own to check models and create model connections.',
    '添加你拥有的密钥后，即可检查模型并创建模型连接。',
  ],
  'endpoints.key': ['Key', '密钥'],
  'endpoints.keyIdentifier': ['Key identifier (partial key)', '密钥标识（非完整密钥）'],
  'endpoints.keyState': ['Key status', '密钥状态'],
  'endpoints.storePolicy': [
    'Do not save chat requests (store=false)',
    '不保存聊天请求（store=false）',
  ],
  'endpoints.securityProcessing': [
    'Security processing — currently unavailable',
    '安全处理中，当前不可操作',
  ],
  'endpoints.discovery': ['Model check result', '模型检查结果'],
  'endpoints.discoveryUnknown': ['No model check yet', '尚未检查模型'],
  'endpoints.discoveryChecking': ['Checking models', '正在检查模型'],
  'endpoints.discoveryEmpty': [
    'The check completed, but no models were found',
    '检查完成，但没有找到模型',
  ],
  'endpoints.discoveryNonempty': [
    'The check found {{count}} model(s)',
    '检查完成，共找到 {{count}} 个模型',
  ],
  'endpoints.discoveryFailed': ['The model check failed: {{reason}}', '模型检查失败：{{reason}}'],
  'endpoints.discoveryReasonAuth': ['authentication was rejected', '所连接的服务拒绝了身份验证'],
  'endpoints.discoveryReasonRateLimit': [
    'the connected service rate limit was reached',
    '所连接的服务已达到访问频率限制',
  ],
  'endpoints.discoveryReasonTimeout': ['the connected service timed out', '所连接的服务响应超时'],
  'endpoints.discoveryReasonProtocol': [
    'the connected service returned an unsupported response',
    '所连接的服务返回了不支持的内容',
  ],
  'endpoints.discoveryReasonTransport': [
    'the connected service could not be reached',
    '无法连接所选服务',
  ],
  'endpoints.discoveryReasonInterrupted': ['the check was interrupted', '检查已中断'],
  'endpoints.observedAt': ['Checked at', '检查时间'],
  'endpoints.refreshDiscovery': ['Check models', '检查模型'],
  'endpoints.routing': ['Model connection status', '模型连接状态'],
  'endpoints.routingNone': [
    'No platform model currently uses this key.',
    '当前没有平台模型使用此密钥。',
  ],
  'endpoints.routingUnknown': [
    'Model connection status could not be checked.',
    '暂时无法检查模型连接状态。',
  ],
  'endpoints.toggleOn': ['Enable endpoint', '启用端点'],
  'endpoints.toggleOff': ['Disable endpoint', '停用端点'],
  'endpoints.keyToggleOn': ['Enable key', '启用密钥'],
  'endpoints.keyToggleOff': ['Disable key', '停用密钥'],
  'endpoints.storePolicyOn': ['Require store=false', '要求 store=false'],
  'endpoints.storePolicyOff': ['Stop requiring store=false', '取消要求 store=false'],
  'endpoints.dangerTitle': ['Danger zone', '危险区'],
  'endpoints.deleteEndpoint': ['Delete endpoint', '删除端点'],
  'endpoints.deleteEndpointTitle': ['Delete this endpoint?', '删除此端点？'],
  'endpoints.deleteEndpointBody': [
    'Its keys, model check results, model connections, and shared resources will be affected. This cannot be undone.',
    '其密钥、模型检查结果、模型连接和共享资源都会受到影响，且无法撤销。',
  ],
  'endpoints.deleteKey': ['Delete key', '删除密钥'],
  'endpoints.deleteKeyTitle': ['Delete this key?', '删除此密钥？'],
  'endpoints.deleteKeyBody': [
    'Model connections, shared resources, and model check results that use this key will be affected.',
    '使用此密钥的模型连接、共享资源和模型检查结果都会受到影响。',
  ],
  'endpoints.wizardTitle': ['Create endpoint and key', '创建端点与密钥'],
  'endpoints.finishLater': ['Finish later', '稍后继续'],
  'endpoints.savedForLater': [
    'Endpoint saved. You can add keys later from Manage endpoint.',
    '端点已保存，稍后可从「管理端点」继续添加密钥。',
  ],
  'endpoints.wizardConnector': ['1 · Service type', '1 · 服务类型'],
  'endpoints.wizardUrl': ['2 · URL preview', '2 · 地址预览'],
  'endpoints.wizardKey': ['3 · Key', '3 · 密钥'],
  'endpoints.wizardDiscovery': ['4 · Model check', '4 · 模型检查'],
  'endpoints.wizardBinding': ['5 · Optional model connection', '5 · 可选模型连接'],
  'endpoints.preview': ['Address preview', '地址预览'],
  'endpoints.previewAuthority': [
    'The saved address is shown after creation.',
    '创建后会显示最终保存的地址。',
  ],
  'endpoints.createEndpointStep': ['Create endpoint', '创建端点'],
  'endpoints.secret': ['Service key', '服务密钥'],
  'endpoints.keyNote': ['Key note', '密钥备注'],
  'endpoints.ownership': [
    'I own this credential or have explicit permission to use it here.',
    '我拥有此凭据，或已取得在此使用它的明确授权。',
  ],
  'endpoints.costWarning': [
    'Model checks contact the connected service and may be rate-limited or billed under its terms.',
    '模型检查会访问所连接的服务，并可能受到访问频率限制或按其条款产生费用。',
  ],
  'endpoints.addKeyStep': ['Add key', '添加密钥'],
  'endpoints.multipleKeysHint': [
    'An endpoint can hold multiple keys. Add them here, or return to key management later.',
    '一个端点可以添加多把密钥。你可以在这里连续添加，也可以稍后进入密钥管理。',
  ],
  'endpoints.addAnotherKey': ['Add another key', '再添加一把密钥'],
  'endpoints.secretRequired': [
    'Enter the service key and confirm permission to use it. Other fields were kept.',
    '请输入服务密钥并确认有权使用；其他字段已保留。',
  ],
  'endpoints.finish': ['Finish', '完成'],
  'endpoints.openBindings': ['Open model connections', '打开模型连接'],
  'endpoints.manualTitle': ['Manual catalog', '手工目录'],
  'endpoints.manualAlways': [
    'Manual entries remain available even when automatic discovery fails.',
    '即使自动发现失败，手工入口仍然可用。',
  ],
  'endpoints.manualModel': ['Exact service model ID', '精确服务模型 ID'],
  'endpoints.manualProvider': ['Note (optional)', '备注（可选）'],
  'endpoints.manualAdd': ['Add manual entry', '添加手工条目'],
  'endpoints.manualEmpty': ['No manual entries for this key.', '此密钥没有手工条目。'],
  'endpoints.manualImpact': [
    'Used by {{count}} model connection(s). Before changing or deleting it, choose an exact replacement for each connection.',
    '有 {{count}} 个模型连接使用此条目。修改或删除前，请为每个连接选择精确替代项。',
  ],
  'endpoints.manualImpactUnknown': [
    'The affected model connections could not be checked. Refresh their status before changing or deleting this entry.',
    '暂时无法检查受影响的模型连接。请先刷新连接状态，再修改或删除此条目。',
  ],
  'endpoints.manualImpactTooMany': [
    'This entry has {{count}} connections. To rename or delete it, first reduce them to 256 or fewer in model connection management. You can still update its note.',
    '此条目关联 {{count}} 个连接。改名或删除前，请先在模型连接管理中将关联数量减少至 256 个以内；备注仍可修改。',
  ],
  'browse.modelCount': ['{{count}} associated model(s)', '关联模型 {{count}} 个'],
  'browse.keyCount': ['{{count}} key(s)', '密钥 {{count}} 把'],
  'browse.availableConnections': [
    '{{available}} of {{total}} connections available',
    '{{available}} / {{total}} 个连接可用',
  ],
  'browse.allConnections': ['Browse all {{count}} connections', '查看全部 {{count}} 个连接'],
  'browse.noConnections': ['No connections configured', '尚未配置连接'],
  'browse.personalLimits': [
    'Site expiry: none. Charity quotas do not apply to personal calls.',
    '站内有效期：未设期限。自用调用不计入公益限量。',
  ],
  'browse.state.available': ['Available', '可用'],
  'browse.state.endpoint_disabled': ['Endpoint disabled', '端点已停用'],
  'browse.state.key_disabled': ['Key disabled', '密钥已停用'],
  'browse.state.key_suspended': ['Key under security review', '密钥安全审核中'],
  'browse.state.unsupported': ['Model no longer supported by this key', '此密钥当前不再支持该模型'],
  'browse.endpoint.available': ['Enabled with a usable key', '已启用，有可用密钥'],
  'browse.endpoint.endpoint_disabled': ['Endpoint disabled', '端点已停用'],
  'browse.endpoint.no_keys': ['No keys added', '尚未添加密钥'],
  'browse.endpoint.no_usable_key': ['No usable keys', '暂无可用密钥'],
  'endpoints.replacement': [
    'Replacement service model ID for {{model}} (connection {{id}})',
    '{{model}}（连接 {{id}}）的替代服务模型 ID',
  ],
  'endpoints.updateManual': ['Update entry', '更新条目'],
  'endpoints.deleteManual': ['Delete entry', '删除条目'],
  'keys.title': ['Global API access', '全局 API 接入'],
  'keys.description': [
    'Your account API key works across the whole account. Its full value is shown only once.',
    '账户 API 密钥可用于整个账号；完整内容只会显示一次。',
  ],
  'keys.metadataTitle': ['API key details', 'API 密钥详情'],
  'keys.noKeyTitle': ['No account API key', '尚未创建账户 API 密钥'],
  'keys.noKeyBody': ['Create your first API key.', '创建你的第一把 API 密钥。'],
  'keys.generate': ['Create API key', '创建 API 密钥'],
  'keys.rotate': ['Replace API key', '更换 API 密钥'],
  'keys.rotateTitle': ['Replace the account API key?', '更换账户 API 密钥？'],
  'keys.rotateBody': [
    'The previous key stops working immediately. Update every client that uses it.',
    '旧密钥会立即失效，请更新所有使用它的程序。',
  ],
  'keys.display': ['Key identifier (cannot be used for calls)', '密钥标识（不能用于调用）'],
  'keys.oneTimeTitle': ['Copy this API key now', '请立即复制此 API 密钥'],
  'keys.oneTimeBody': [
    'It will never be shown again after you close it or leave this page.',
    '关闭或离开此页面后将永不再次显示。',
  ],
  'keys.closeReveal': ['I have saved it — close', '我已保存，关闭明文'],
  'keys.refreshError': [
    'Key details could not be refreshed. The full key remains visible until you close it.',
    '密钥详情刷新失败；完整密钥会保留到你主动关闭。',
  ],
  'models.title': ['Platform models', '平台模型'],
  'models.description': [
    'Create stable model names and connect service models. Your client selects chat completions or embeddings through the API path; the connected model must support that operation.',
    '创建稳定的模型名称并连接上游模型。调用方通过 API 路径选择聊天补全或向量嵌入，所连接的模型须支持对应操作。',
  ],
  'models.create': ['Create platform model', '创建平台模型'],
  'models.emptyTitle': ['No platform models', '还没有平台模型'],
  'models.emptyBody': [
    'Create a provider/model name, then add one or more service connections.',
    '先创建服务商/模型名称，再添加一个或多个服务连接。',
  ],
  'models.provider': ['Service provider', '服务商'],
  'models.model': ['Model name', '模型名称'],
  'models.fullName': ['Platform model name', '平台模型名称'],
  'models.namingHelp': [
    'Choose your own provider and model names to form the name used in API calls. Select the actual upstream models under service connections after creation.',
    '服务商和模型名称可自行命名，用来组成站内 API 调用名。创建后，在服务连接中选择实际调用的上游模型。',
  ],
  'models.namePreview': ['API model name preview', 'API 调用模型名预览'],
  'models.strategy': ['Connection strategy', '连接策略'],
  'models.ordered': ['Ordered', '顺序'],
  'models.random': ['Random', '随机'],
  'models.silentRetry': ['Silent retry', '静默重试'],
  'models.flattenTools': ['Flatten tool calls (chat only)', '扁平化工具调用（仅聊天）'],
  'models.bindingCount': ['Connections', '连接数'],
  'models.manage': ['Manage connections', '管理连接'],
  'models.configurationTitle': ['Platform model settings', '平台模型设置'],
  'models.editModel': ['Edit platform model', '编辑平台模型'],
  'models.invalidName': [
    'Provider and model must each contain 1–64 characters with no surrounding whitespace or control characters.',
    'provider 与 model 均须为 1–64 个字符，且不能含首尾空白或控制字符。',
  ],
  'models.detailTitle': ['Model connections', '模型连接'],
  'models.detailDescription': [
    'Choose the models to connect and arrange the order in which they are tried.',
    '选择要连接的模型，并按需要调整尝试顺序。',
  ],
  'models.selectorTitle': ['Add connections', '新增连接'],
  'models.levelEndpoint': ['1 · Endpoint', '1 · 端点'],
  'models.levelKey': ['2 · Key', '2 · 密钥'],
  'models.levelCandidate': ['3 · Automatic or manual model', '3 · 自动或手工模型'],
  'models.searchCandidates': ['Search upstream models', '搜索上游模型'],
  'models.chooseEndpoint': ['Choose an endpoint', '请选择端点'],
  'models.chooseKey': ['Choose a key', '请选择密钥'],
  'models.endpointEmpty': ['No endpoint is available on this page.', '当前页没有可用端点。'],
  'models.keyEmpty': ['No usable key is available on this page.', '当前页没有可用的密钥。'],
  'models.securityLocked': ['Security processing', '安全处理中'],
  'models.automatic': ['Automatically found models', '自动找到的模型'],
  'models.manual': ['Manually added models', '手动添加的模型'],
  'models.sourceBoth': ['Automatic + manual', '自动 + 手工'],
  'models.candidateEmpty': ['No models in this source.', '此来源没有模型。'],
  'models.candidateSelected': ['Selected', '已选择'],
  'models.alreadyBound': ['Already connected', '已连接'],
  'models.selectedCount': [
    '{{count}} unique model(s) selected across filters and pages.',
    '已跨筛选和分页选择 {{count}} 个不同模型。',
  ],
  'models.addSelected': ['Add {{count}} selected connection(s)', '添加已选的 {{count}} 个连接'],
  'models.selectionInvalid': [
    'A model became unavailable; only that selection was removed.',
    '某个模型已不可用，仅移除了该选择。',
  ],
  'models.bindingsTitle': ['Current connections and order', '现有连接及其顺序'],
  'models.noBindings': [
    'This platform model has no service connections.',
    '此平台模型还没有服务连接。',
  ],
  'models.moveUp': ['Move up', '上移'],
  'models.moveDown': ['Move down', '下移'],
  'models.saveOrder': ['Save complete order', '保存完整顺序'],
  'models.removeBinding': ['Remove connection', '移除连接'],
  'models.removeBindingTitle': ['Remove this connection?', '移除此连接？'],
  'models.removeBindingBody': [
    'The platform model may lose an available service connection.',
    '此平台模型可能失去一个可用的服务连接。',
  ],
  'models.deleteModel': ['Delete platform model', '删除平台模型'],
  'models.deleteModelTitle': ['Delete this platform model?', '删除此平台模型？'],
  'models.deleteModelBody': [
    'All service connections for this platform model will be removed.',
    '此平台模型的全部服务连接都会被移除。',
  ],
  'models.nextCandidates': ['Next models', '下一页模型'],
  'models.previousCandidates': ['Previous models', '上一页模型'],
  'account.title': ['Account', '账户'],
  'account.description': [
    'Review your profile, save account language, and manage local display preferences.',
    '查看资料、保存账户语言，并管理仅保存在此浏览器的显示偏好。',
  ],
  'account.profileTitle': ['Profile', '账户资料'],
  'account.id': ['Account ID', '账户 ID'],
  'account.username': ['Username', '用户名'],
  'account.nickname': ['Server nickname', '服务器昵称'],
  'account.created': ['Account created', '账户创建时间'],
  'account.languageTitle': ['Account language', '账户语言'],
  'account.languageBody': [
    'The interface changes only after the server confirms the update.',
    '选择界面语言，保存后生效。',
  ],
  'account.language': ['Language', '语言'],
  'account.zh': ['中文', '中文'],
  'account.en': ['English', 'English'],
  'account.languageSaved': ['Language saved.', '语言已保存。'],
  'account.localTitle': ['This browser', '此浏览器'],
  'account.localBody': [
    'Theme, density, and font size stay only in this browser.',
    '主题、密度和字号只保存在当前浏览器。',
  ],
  'account.theme': ['Theme', '主题'],
  'account.themeLight': ['Light', '浅色'],
  'account.themeDark': ['Dark', '深色'],
  'account.themeSystem': ['Follow system', '跟随系统'],
  'account.density': ['Density', '密度'],
  'account.densityComfortable': ['Comfortable', '舒适'],
  'account.densityCompact': ['Compact', '紧凑'],
  'account.fontSize': ['Font size', '字号'],
  'account.fontDefault': ['Default', '默认'],
  'account.fontLarge': ['Large', '较大'],
  'account.exportTitle': ['Account export', '账户导出'],
  'account.exportBody': [
    'Download a copy of the account information available for export.',
    '下载当前可导出的账户信息副本。',
  ],
  'account.export': ['Request export', '申请导出'],
  'account.exportConfirm': ['Create export', '创建导出'],
  'account.deleteTitle': ['Delete account', '删除账户'],
  'account.deleteBody': [
    'Deletion is irreversible and removes access to account-owned resources. Shared records keep only the necessary information without your identity.',
    '删除不可逆，并会移除账户所拥有资源的访问权；共享记录只保留不含个人身份的必要信息。',
  ],
  'account.delete': ['Delete account', '删除账户'],
  'account.deleteConfirm': ['Permanently delete account', '永久删除账户'],
  'account.deleteWord': ['Type DELETE to continue', '输入 DELETE 以继续'],
  'account.deleteWordError': ['Type DELETE exactly.', '请精确输入 DELETE。'],
  'account.dangerTitle': ['Danger zone', '危险区'],
  'account.reauthorize': [
    'Verify your Discord identity again to continue.',
    '请重新验证 Discord 身份后继续。',
  ],
  'account.lifecycleUnavailable': [
    'This account action is not available in this version.',
    '此账号操作暂不可用。',
  ],
  'account.elevationFailed': [
    'Discord verification could not be started.',
    '无法开始 Discord 身份验证。',
  ],
  'account.exportUnknown': [
    'The export result could not be confirmed. Verify your Discord identity again to create a new export; the previous request will not run again.',
    '暂时无法确认导出结果。请重新验证 Discord 身份后创建新导出；先前请求不会再次执行。',
  ],
  'account.deleteUnknown': [
    'The deletion response was unknown. Do not submit it again; check whether the account still exists.',
    '删除响应状态未知。请勿再次提交；先检查账号是否仍然存在。',
  ],
  'account.checkAuthority': ['Check account status', '检查账号状态'],
  'account.deleteStillActive': [
    'The account is still active. Verify your Discord identity again before another deletion attempt.',
    '账号仍处于活动状态；再次尝试删除前，请重新验证 Discord 身份。',
  ],
  'account.authorityCheckFailed': [
    'Account status could not be checked. The deletion request was not repeated.',
    '暂时无法检查账号状态；删除请求未被重复提交。',
  ],
} as const satisfies Record<string, CoreCopyEntry>;

export type CoreCopyKey = keyof typeof copy;

export const CORE_COPY_KEYS = Object.freeze(Object.keys(copy) as CoreCopyKey[]);
export const CORE_COPY_DESCRIPTORS = Object.freeze(
  CORE_COPY_KEYS.map((key) => {
    const [en, zh] = copy[key];
    return Object.freeze({ key, en, zh });
  }),
);

function interpolate(template: string, values?: Readonly<Record<string, string | number>>): string {
  if (!values) return template;
  return template.replace(/\{\{([A-Za-z0-9_]+)\}\}/g, (_match, key: string) =>
    Object.hasOwn(values, key) ? String(values[key]) : '',
  );
}

export function coreText(
  key: CoreCopyKey,
  language: 'zh' | 'en',
  values?: Readonly<Record<string, string | number>>,
): string {
  return interpolate(copy[key][language === 'zh' ? 1 : 0], values);
}

export function useCoreCopy() {
  const { i18n } = useTranslation();
  const language = i18n.resolvedLanguage?.toLowerCase().startsWith('zh') ? 'zh' : 'en';
  return useMemo(
    () => ({
      language,
      t: (key: CoreCopyKey, values?: Readonly<Record<string, string | number>>) =>
        coreText(key, language, values),
    }),
    [language],
  );
}
