import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';

const en = {
  'common.loading': 'Loading…',
  'common.retry': 'Retry',
  'common.errorTitle': 'Could not load this section',
  'common.errorBody': 'The confirmed data for this section is unavailable.',
  'common.unavailableTitle': 'Not available yet',
  'common.unavailableBody': 'This section is not available in this version.',
  'common.emptyTitle': 'Nothing here yet',
  'common.working': 'Working…',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.copy': 'Copy',
  'common.copied': 'Copied',
  'common.copyFailed': 'Copy failed. Select and copy the value manually.',
  'common.previous': 'Previous',
  'common.next': 'Next',
  'common.enabled': 'Enabled',
  'common.disabled': 'Disabled',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.unknown': 'Unknown',
  'common.notSet': 'Not set',
  'common.available': 'Available',
  'common.blocked': 'Blocked',
  'common.reconcile': 'Check authoritative state',
  'common.retrySame': 'Retry the same operation',
  'common.created': 'Created',
  'common.updated': 'Updated',
  'common.refresh': 'Refresh',
  'common.back': 'Back',
  'common.conflict':
    'This resource changed. The authoritative version was refreshed; review it before trying again.',
  'common.outcomeUnknown':
    'The response was lost. The page is reconciling against authoritative state and will not resend the operation.',
  'common.fixedFailure':
    'The one-time value was not received. Click again only if you want a new operation.',
  'common.maintenance': 'This operation is temporarily unavailable.',
  'common.permissionLost': 'Your current session no longer permits this operation.',
  'connector.openai': 'OpenAI-compatible',
  'connector.anthropic': 'Anthropic-compatible',
  'home.title': 'Welcome back, {{name}}',
  'home.signedOutTitle': 'Your AI routing workspace',
  'home.signedOutBody': 'Sign in to manage endpoints, models, and your account.',
  'home.signIn': 'Sign in with Discord',
  'home.description':
    'See confirmed account status and continue the things that need your attention.',
  'home.profileTitle': 'Account',
  'home.username': 'Username',
  'home.accountStatus': 'Account status',
  'home.active': 'Active',
  'home.banned': 'Restricted',
  'home.economyTitle': 'Balance and level',
  'home.balance': 'Balance',
  'home.donationCredit': 'Donation credit',
  'home.level': 'Effective level',
  'home.levelValue': 'Lv{{level}} · {{name}}',
  'home.usageTitle': 'Lifetime usage',
  'home.requests': 'Requests',
  'home.promptTokens': 'Prompt tokens',
  'home.outputTokens': 'Output tokens',
  'home.unknownUsage': 'Requests with unknown usage',
  'home.checkinTitle': 'Daily check-in',
  'home.checkin.unavailable': 'Check-in is not available',
  'home.checkin.today': 'Today',
  'home.checkin.checkedIn': 'Checked in',
  'home.checkin.notCheckedIn': 'Not checked in yet',
  'home.checkin.awardRange': 'Award range (credits)',
  'home.checkin.threshold': 'Check-in threshold (credits)',
  'home.checkin.thresholdNone': 'No limit',
  'home.checkin.thresholdHint':
    'The threshold only gates admission: once reached the server refuses new check-ins; an admitted award is never truncated.',
  'home.checkin.submit': 'Check in',
  'home.checkin.done':
    'Checked in: awarded {{award}} credits; the Nonbiri credits balance is now {{credits}}.',
  'home.checkinRefreshFailed':
    'Check-in succeeded, but the latest status could not be refreshed. Refresh to retry the read; the check-in will not be submitted again.',
  'home.gamesTitle': 'Continue or view results',
  'home.announcementsTitle': 'Announcements',
  'home.quickTitle': 'Quick access',
  'home.endpoints': 'Manage resources',
  'home.models': 'Manage models',
  'home.callerKey': 'API access',
  'home.activities': 'Open activities',
  'home.games': 'Open games',
  'home.continue': 'Continue',
  'home.view': 'View result',
  'home.gameFishing': 'Fishing',
  'home.gameLinklink': 'Link Link',
  'home.gameRps': 'Three-player rock paper scissors',
  'home.capabilityUnavailable': 'This summary is not available yet.',
  'endpoints.title': 'Resources',
  'endpoints.description':
    'Manage endpoint configuration, physical keys, discovery evidence, and binding reachability separately.',
  'endpoints.create': 'Create endpoint',
  'endpoints.emptyTitle': 'No endpoints yet',
  'endpoints.emptyBody': 'Create an endpoint to connect an upstream service you control.',
  'endpoints.connector': 'Connector',
  'endpoints.origin': 'Origin',
  'endpoints.originCustom': 'Custom endpoint',
  'endpoints.originMainstream': 'Mainstream channel: {{name}}',
  'endpoints.mainstream': 'Mainstream channel',
  'endpoints.custom': 'Custom endpoint',
  'endpoints.channel': 'Channel',
  'endpoints.baseUrl': 'Canonical base URL',
  'endpoints.note': 'Note',
  'endpoints.keyCount': 'EndpointKey count',
  'endpoints.configuration': 'Endpoint configuration',
  'endpoints.manage': 'Manage endpoint',
  'endpoints.detailsTitle': 'Endpoint details',
  'endpoints.detailsDescription':
    'Connector and canonical URL are immutable. Replace the endpoint to change either value.',
  'endpoints.addKey': 'Add EndpointKey',
  'endpoints.noKeysTitle': 'No EndpointKeys',
  'endpoints.noKeysBody': 'Add a key you own to discover models and create bindings.',
  'endpoints.key': 'EndpointKey',
  'endpoints.keyState': 'Physical key state',
  'endpoints.storePolicy': 'Force store=false',
  'endpoints.securityProcessing': 'Security processing — currently unavailable',
  'endpoints.discovery': 'Model discovery evidence',
  'endpoints.discoveryUnknown': 'No discovery evidence',
  'endpoints.discoveryChecking': 'Checking models',
  'endpoints.discoveryEmpty': 'Discovery succeeded with no models',
  'endpoints.discoveryNonempty': 'Discovery succeeded with {{count}} model(s)',
  'endpoints.discoveryFailed': 'Discovery failed: {{reason}}',
  'endpoints.discoveryReasonAuth': 'authentication was rejected',
  'endpoints.discoveryReasonRateLimit': 'the upstream rate limit was reached',
  'endpoints.discoveryReasonTimeout': 'the upstream timed out',
  'endpoints.discoveryReasonProtocol': 'the upstream response was incompatible',
  'endpoints.discoveryReasonTransport': 'the upstream connection failed',
  'endpoints.discoveryReasonInterrupted': 'the check was interrupted',
  'endpoints.observedAt': 'Evidence time',
  'endpoints.refreshDiscovery': 'Check models',
  'endpoints.routing': 'Complete binding reachability',
  'endpoints.routingNone': 'No logical model currently binds through this key.',
  'endpoints.routingAvailable': 'Routable through {{count}} logical model(s)',
  'endpoints.routingBlocked':
    'Bindings exist, but endpoint/key configuration currently blocks routing.',
  'endpoints.routingUnknown': 'Binding reachability could not be confirmed.',
  'endpoints.toggleOn': 'Enable endpoint',
  'endpoints.toggleOff': 'Disable endpoint',
  'endpoints.keyToggleOn': 'Enable key',
  'endpoints.keyToggleOff': 'Disable key',
  'endpoints.storePolicyOn': 'Require store=false',
  'endpoints.storePolicyOff': 'Stop requiring store=false',
  'endpoints.dangerTitle': 'Danger zone',
  'endpoints.deleteEndpoint': 'Delete endpoint',
  'endpoints.deleteEndpointTitle': 'Delete this endpoint?',
  'endpoints.deleteEndpointBody':
    'Its EndpointKeys, discovery evidence, bindings, and donation projections will be affected. This cannot be undone.',
  'endpoints.deleteKey': 'Delete key',
  'endpoints.deleteKeyTitle': 'Delete this EndpointKey?',
  'endpoints.deleteKeyBody':
    'Bindings, donation projections, and discovery evidence that depend on this key will be affected.',
  'endpoints.wizardTitle': 'Create endpoint and key',
  'endpoints.wizardConnector': '1 · Connector',
  'endpoints.wizardUrl': '2 · URL preview',
  'endpoints.wizardKey': '3 · EndpointKey',
  'endpoints.wizardDiscovery': '4 · Model check',
  'endpoints.wizardBinding': '5 · Optional binding',
  'endpoints.preview': 'Normalization preview',
  'endpoints.previewAuthority': 'The server response remains authoritative.',
  'endpoints.createEndpointStep': 'Create endpoint',
  'endpoints.secret': 'Upstream secret',
  'endpoints.keyNote': 'Key note',
  'endpoints.ownership': 'I own this credential or have explicit permission to use it here.',
  'endpoints.costWarning':
    'Model checks may contact the upstream and can be rate-limited or billed under its terms.',
  'endpoints.addKeyStep': 'Add key',
  'endpoints.secretRequired':
    'Enter the upstream secret and confirm ownership. Other fields were kept.',
  'endpoints.finish': 'Finish',
  'endpoints.openBindings': 'Open model bindings',
  'endpoints.manualTitle': 'Manual catalog',
  'endpoints.manualAlways': 'Manual entries remain available even when automatic discovery fails.',
  'endpoints.manualModel': 'Exact upstream model ID',
  'endpoints.manualProvider': 'Provider (optional)',
  'endpoints.manualAdd': 'Add manual entry',
  'endpoints.manualEmpty': 'No manual entries for this key.',
  'endpoints.manualImpact':
    'Used by {{count}} binding(s). Changing the upstream model ID or deleting this entry requires one exact replacement per binding.',
  'endpoints.manualImpactUnknown':
    'Binding impact could not be confirmed. Refresh routing authority before changing the upstream model ID or deleting this entry.',
  'endpoints.replacement': 'Replacement upstream model ID for {{model}} (binding {{id}})',
  'endpoints.updateManual': 'Update entry atomically',
  'endpoints.deleteManual': 'Delete entry atomically',
  'keys.title': 'Global API access',
  'keys.description':
    'CallerKey belongs to your account, never to an endpoint. Plaintext is shown once in this page instance.',
  'keys.metadataTitle': 'CallerKey metadata',
  'keys.noKeyTitle': 'No CallerKey exists',
  'keys.noKeyBody': 'Generate the first key without a rotation confirmation.',
  'keys.generate': 'Generate CallerKey',
  'keys.rotate': 'Rotate CallerKey',
  'keys.rotateTitle': 'Rotate the account CallerKey?',
  'keys.rotateBody':
    'The previous key stops working immediately. Update every client that uses it.',
  'keys.display': 'Safe display',
  'keys.generation': 'Generation',
  'keys.oneTimeTitle': 'Copy this CallerKey now',
  'keys.oneTimeBody': 'It will never be shown again after you close it or leave this page.',
  'keys.closeReveal': 'I have saved it — close',
  'keys.refreshError':
    'Metadata refresh failed. The one-time plaintext remains visible until you close it.',
  'models.title': 'Logical models',
  'models.description':
    'Create stable model names, select exact upstream candidates, and order the complete binding set.',
  'models.create': 'Create logical model',
  'models.emptyTitle': 'No logical models',
  'models.emptyBody': 'Create a logical provider/model name, then add one or more bindings.',
  'models.provider': 'Provider',
  'models.model': 'Model',
  'models.fullName': 'Logical name',
  'models.strategy': 'Route strategy',
  'models.ordered': 'Ordered',
  'models.random': 'Random',
  'models.silentRetry': 'Silent retry',
  'models.flattenTools': 'Flatten tool calls',
  'models.bindingCount': 'Bindings',
  'models.manage': 'Manage bindings',
  'models.configurationTitle': 'Logical model configuration',
  'models.editModel': 'Edit logical model',
  'models.invalidName':
    'Provider and model must each contain 1–64 characters with no surrounding whitespace or control characters.',
  'models.detailTitle': 'Binding manager',
  'models.detailDescription': 'Candidate selection and route order are separate operations.',
  'models.selectorTitle': 'Add bindings',
  'models.levelEndpoint': '1 · Endpoint',
  'models.levelKey': '2 · EndpointKey',
  'models.levelCandidate': '3 · Automatic or manual model',
  'models.chooseEndpoint': 'Choose an endpoint',
  'models.chooseKey': 'Choose an EndpointKey',
  'models.endpointEmpty': 'No endpoint is available on this page.',
  'models.keyEmpty': 'No usable EndpointKey is available on this page.',
  'models.securityLocked': 'Security processing',
  'models.automatic': 'Automatic candidates',
  'models.manual': 'Manual candidates',
  'models.sourceBoth': 'Automatic + manual',
  'models.candidateEmpty': 'No candidates in this source.',
  'models.candidateSelected': 'Selected',
  'models.alreadyBound': 'Already bound',
  'models.selectedCount': '{{count}} unique candidate(s) selected across filters and pages.',
  'models.addSelected': 'Add {{count}} selected binding(s)',
  'models.selectionInvalid': 'A candidate became unavailable; only that selection was removed.',
  'models.bindingsTitle': 'Current bindings and route order',
  'models.noBindings': 'This logical model has no bindings.',
  'models.moveUp': 'Move up',
  'models.moveDown': 'Move down',
  'models.saveOrder': 'Save complete order',
  'models.removeBinding': 'Remove binding',
  'models.removeBindingTitle': 'Remove this binding?',
  'models.removeBindingBody': 'The logical model may lose a routable upstream path.',
  'models.deleteModel': 'Delete logical model',
  'models.deleteModelTitle': 'Delete this logical model?',
  'models.deleteModelBody': 'All bindings for this logical model will be removed.',
  'models.nextCandidates': 'Next candidates',
  'models.previousCandidates': 'Previous candidates',
  'account.title': 'Account',
  'account.description':
    'Review your profile, save account language, and manage local display preferences.',
  'account.profileTitle': 'Profile',
  'account.id': 'Account ID',
  'account.username': 'Username',
  'account.nickname': 'Server nickname',
  'account.created': 'Account created',
  'account.languageTitle': 'Account language',
  'account.languageBody': 'The interface changes only after the server confirms the update.',
  'account.language': 'Language',
  'account.zh': '中文',
  'account.en': 'English',
  'account.languageSaved': 'Language saved.',
  'account.localTitle': 'This browser',
  'account.localBody': 'Theme, density, and font size stay only in this browser.',
  'account.theme': 'Theme',
  'account.themeLight': 'Light',
  'account.themeDark': 'Dark',
  'account.themeSystem': 'Follow system',
  'account.density': 'Density',
  'account.densityComfortable': 'Comfortable',
  'account.densityCompact': 'Compact',
  'account.fontSize': 'Font size',
  'account.fontDefault': 'Default',
  'account.fontLarge': 'Large',
  'account.exportTitle': 'Account export',
  'account.exportBody': 'Export v4 will appear here after the lifecycle service is connected.',
  'account.export': 'Request export',
  'account.exportConfirm': 'Create export',
  'account.deleteTitle': 'Delete account',
  'account.deleteBody':
    'Deletion is irreversible and removes access to account-owned resources. Shared records retain only the frozen de-identified projection.',
  'account.delete': 'Delete account',
  'account.deleteConfirm': 'Permanently delete account',
  'account.deleteWord': 'Type DELETE to continue',
  'account.deleteWordError': 'Type DELETE exactly.',
  'account.dangerTitle': 'Danger zone',
  'account.reauthorize': 'Fresh Discord authorization is required for this action.',
  'account.lifecycleUnavailable': 'This account action is not available in this version.',
  'account.elevationFailed': 'Fresh authorization could not be started.',
  'account.exportUnknown':
    'The export response was unknown. Request fresh authorization to generate a new export; the previous request will not be replayed.',
  'account.deleteUnknown':
    'The deletion response was unknown. Do not submit it again; check whether the account still exists.',
  'account.checkAuthority': 'Check account status',
  'account.deleteStillActive':
    'The account is still active. Any later deletion attempt requires fresh authorization.',
  'account.authorityCheckFailed':
    'Account status could not be checked. The deletion request was not repeated.',
} as const;

export type CoreCopyKey = keyof typeof en;

const zh: Record<CoreCopyKey, string> = {
  'common.loading': '正在加载…',
  'common.retry': '重试',
  'common.errorTitle': '无法加载此区域',
  'common.errorBody': '此区域的权威数据当前不可用。',
  'common.unavailableTitle': '暂未可用',
  'common.unavailableBody': '此区域在当前版本中暂不可用。',
  'common.emptyTitle': '这里还没有内容',
  'common.working': '正在处理…',
  'common.cancel': '取消',
  'common.close': '关闭',
  'common.save': '保存',
  'common.delete': '删除',
  'common.edit': '编辑',
  'common.copy': '复制',
  'common.copied': '已复制',
  'common.copyFailed': '复制失败，请手动选择并复制。',
  'common.previous': '上一页',
  'common.next': '下一页',
  'common.enabled': '已启用',
  'common.disabled': '已停用',
  'common.yes': '是',
  'common.no': '否',
  'common.unknown': '未知',
  'common.notSet': '未设置',
  'common.available': '可用',
  'common.blocked': '已阻止',
  'common.reconcile': '检查权威状态',
  'common.retrySame': '重试同一操作',
  'common.created': '创建时间',
  'common.updated': '更新时间',
  'common.refresh': '刷新',
  'common.back': '返回',
  'common.conflict': '此资源已经变化。页面已刷新权威版本，请重新核对后再操作。',
  'common.outcomeUnknown': '响应已丢失。页面正在按权威状态对账，不会自动重发操作。',
  'common.fixedFailure': '没有取得一次性明文。只有再次点击才会开始新操作。',
  'common.maintenance': '此操作暂时不可用。',
  'common.permissionLost': '当前会话已无权执行此操作。',
  'connector.openai': 'OpenAI 兼容',
  'connector.anthropic': 'Anthropic 兼容',
  'home.title': '欢迎回来，{{name}}',
  'home.signedOutTitle': '你的 AI 路由工作台',
  'home.signedOutBody': '登录后即可管理端点、模型和账户。',
  'home.signIn': '使用 Discord 登录',
  'home.description': '查看已确认的账户状态，并继续需要你处理的事项。',
  'home.profileTitle': '账户',
  'home.username': '用户名',
  'home.accountStatus': '账户状态',
  'home.active': '正常',
  'home.banned': '受限',
  'home.economyTitle': '余额与等级',
  'home.balance': '余额',
  'home.donationCredit': '捐赠积分',
  'home.level': '最终有效等级',
  'home.levelValue': '等级 {{level}} · {{name}}',
  'home.usageTitle': '账号存续期用量',
  'home.requests': '请求数',
  'home.promptTokens': '提示 Token',
  'home.outputTokens': '输出 Token',
  'home.unknownUsage': '用量未知请求',
  'home.checkinTitle': '每日签到',
  'home.checkin.unavailable': '签到未启用',
  'home.checkin.today': '今日状态',
  'home.checkin.checkedIn': '已签到',
  'home.checkin.notCheckedIn': '未签到',
  'home.checkin.awardRange': '奖励范围（积分）',
  'home.checkin.threshold': '签到门槛（积分）',
  'home.checkin.thresholdNone': '无上限',
  'home.checkin.thresholdHint':
    '门槛只影响能否签到：达到后服务端会拒绝新签到，不会截断已发放的奖励。',
  'home.checkin.submit': '立即签到',
  'home.checkin.done': '签到成功：获得 {{award}} 积分，当前悠哉积分 {{credits}}。',
  'home.checkinRefreshFailed':
    '签到已经成功，但最新状态刷新失败。你可以重新刷新读取；页面不会再次提交签到。',
  'home.gamesTitle': '继续进行或查看结果',
  'home.announcementsTitle': '公告',
  'home.quickTitle': '快捷入口',
  'home.endpoints': '管理资源',
  'home.models': '管理模型',
  'home.callerKey': 'API 接入',
  'home.activities': '打开活动',
  'home.games': '打开游戏',
  'home.continue': '继续',
  'home.view': '查看结果',
  'home.gameFishing': '钓鱼',
  'home.gameLinklink': '连连看',
  'home.gameRps': '三人猜拳',
  'home.capabilityUnavailable': '此摘要暂不可用。',
  'endpoints.title': '资源',
  'endpoints.description': '分别管理端点配置、物理密钥、发现证据与 binding 可路由性。',
  'endpoints.create': '创建端点',
  'endpoints.emptyTitle': '还没有端点',
  'endpoints.emptyBody': '创建端点，连接你拥有或获准使用的上游服务。',
  'endpoints.connector': '连接器',
  'endpoints.origin': '来源',
  'endpoints.originCustom': '自定义端点',
  'endpoints.originMainstream': '主流渠道：{{name}}',
  'endpoints.mainstream': '主流渠道',
  'endpoints.custom': '自定义端点',
  'endpoints.channel': '渠道',
  'endpoints.baseUrl': '规范基础地址',
  'endpoints.note': '备注',
  'endpoints.keyCount': 'EndpointKey 数量',
  'endpoints.configuration': '端点配置',
  'endpoints.manage': '管理端点',
  'endpoints.detailsTitle': '端点详情',
  'endpoints.detailsDescription': '连接器与规范地址创建后只读；如需更换，请新建端点。',
  'endpoints.addKey': '添加 EndpointKey',
  'endpoints.noKeysTitle': '没有 EndpointKey',
  'endpoints.noKeysBody': '添加你拥有的密钥后，才可发现模型并创建 binding。',
  'endpoints.key': 'EndpointKey',
  'endpoints.keyState': '物理密钥状态',
  'endpoints.storePolicy': '强制 store=false',
  'endpoints.securityProcessing': '安全处理中，当前不可操作',
  'endpoints.discovery': '模型发现证据',
  'endpoints.discoveryUnknown': '尚无发现证据',
  'endpoints.discoveryChecking': '正在检查模型',
  'endpoints.discoveryEmpty': '发现成功，但没有模型',
  'endpoints.discoveryNonempty': '发现成功，共 {{count}} 个模型',
  'endpoints.discoveryFailed': '发现失败：{{reason}}',
  'endpoints.discoveryReasonAuth': '上游拒绝了身份验证',
  'endpoints.discoveryReasonRateLimit': '已触发上游速率限制',
  'endpoints.discoveryReasonTimeout': '上游响应超时',
  'endpoints.discoveryReasonProtocol': '上游响应不兼容',
  'endpoints.discoveryReasonTransport': '上游连接失败',
  'endpoints.discoveryReasonInterrupted': '检查已中断',
  'endpoints.observedAt': '证据时间',
  'endpoints.refreshDiscovery': '检查模型',
  'endpoints.routing': '完整 binding 可路由性',
  'endpoints.routingNone': '当前没有逻辑模型通过此密钥绑定。',
  'endpoints.routingAvailable': '可通过 {{count}} 个逻辑模型路由',
  'endpoints.routingBlocked': '存在 binding，但端点或密钥配置当前阻止路由。',
  'endpoints.routingUnknown': '无法确认 binding 可路由性。',
  'endpoints.toggleOn': '启用端点',
  'endpoints.toggleOff': '停用端点',
  'endpoints.keyToggleOn': '启用密钥',
  'endpoints.keyToggleOff': '停用密钥',
  'endpoints.storePolicyOn': '要求 store=false',
  'endpoints.storePolicyOff': '取消要求 store=false',
  'endpoints.dangerTitle': '危险区',
  'endpoints.deleteEndpoint': '删除端点',
  'endpoints.deleteEndpointTitle': '删除此端点？',
  'endpoints.deleteEndpointBody':
    '其 EndpointKey、发现证据、binding 与公益投影都会受到影响，且无法撤销。',
  'endpoints.deleteKey': '删除密钥',
  'endpoints.deleteKeyTitle': '删除此 EndpointKey？',
  'endpoints.deleteKeyBody': '依赖此密钥的 binding、公益投影和发现证据都会受到影响。',
  'endpoints.wizardTitle': '创建端点与密钥',
  'endpoints.wizardConnector': '1 · 连接器',
  'endpoints.wizardUrl': '2 · 地址预览',
  'endpoints.wizardKey': '3 · EndpointKey',
  'endpoints.wizardDiscovery': '4 · 模型检查',
  'endpoints.wizardBinding': '5 · 可选 binding',
  'endpoints.preview': '规范化预览',
  'endpoints.previewAuthority': '最终以服务端响应为权威。',
  'endpoints.createEndpointStep': '创建端点',
  'endpoints.secret': '上游密钥',
  'endpoints.keyNote': '密钥备注',
  'endpoints.ownership': '我拥有此凭据，或已取得在此使用它的明确授权。',
  'endpoints.costWarning': '模型检查可能访问上游，并可能受到限流或按上游条款产生费用。',
  'endpoints.addKeyStep': '添加密钥',
  'endpoints.secretRequired': '请输入上游密钥并确认所有权；其他字段已保留。',
  'endpoints.finish': '完成',
  'endpoints.openBindings': '打开模型 binding',
  'endpoints.manualTitle': '手工目录',
  'endpoints.manualAlways': '即使自动发现失败，手工入口仍然可用。',
  'endpoints.manualModel': '精确上游模型 ID',
  'endpoints.manualProvider': 'Provider（可选）',
  'endpoints.manualAdd': '添加手工条目',
  'endpoints.manualEmpty': '此密钥没有手工条目。',
  'endpoints.manualImpact':
    '有 {{count}} 个 binding 依赖此条目。修改上游模型 ID 或删除此条目前，须为每个 binding 提供精确替代项。',
  'endpoints.manualImpactUnknown':
    '无法确认 binding 影响范围。请先刷新权威路由状态，再修改上游模型 ID或删除此条目。',
  'endpoints.replacement': '{{model}}（binding {{id}}）的替代上游模型 ID',
  'endpoints.updateManual': '原子更新条目',
  'endpoints.deleteManual': '原子删除条目',
  'keys.title': '全局 API 接入',
  'keys.description': 'CallerKey 归属整个账户，不属于任何端点；明文只在当前页面实例显示一次。',
  'keys.metadataTitle': 'CallerKey 元数据',
  'keys.noKeyTitle': '尚未创建 CallerKey',
  'keys.noKeyBody': '首次生成无需轮换确认。',
  'keys.generate': '生成 CallerKey',
  'keys.rotate': '轮换 CallerKey',
  'keys.rotateTitle': '轮换账户 CallerKey？',
  'keys.rotateBody': '旧密钥会立即失效，请更新所有使用它的客户端。',
  'keys.display': '安全显示',
  'keys.generation': 'Generation',
  'keys.oneTimeTitle': '请立即复制 CallerKey',
  'keys.oneTimeBody': '关闭或离开此页面后将永不再次显示。',
  'keys.closeReveal': '我已保存，关闭明文',
  'keys.refreshError': '元数据刷新失败；一次性明文会保留到你主动关闭。',
  'models.title': '逻辑模型',
  'models.description': '创建稳定模型名、选择精确上游候选，并独立维护完整 binding 顺序。',
  'models.create': '创建逻辑模型',
  'models.emptyTitle': '还没有逻辑模型',
  'models.emptyBody': '先创建逻辑 provider/model 名称，再添加一个或多个 binding。',
  'models.provider': 'Provider',
  'models.model': 'Model',
  'models.fullName': '逻辑名称',
  'models.strategy': '路由策略',
  'models.ordered': '顺序',
  'models.random': '随机',
  'models.silentRetry': '静默重试',
  'models.flattenTools': '扁平化工具调用',
  'models.bindingCount': 'Binding 数',
  'models.manage': '管理 binding',
  'models.configurationTitle': '逻辑模型配置',
  'models.editModel': '编辑逻辑模型',
  'models.invalidName': 'provider 与 model 均须为 1–64 个字符，且不能含首尾空白或控制字符。',
  'models.detailTitle': 'Binding 管理',
  'models.detailDescription': '候选选择与路由排序是两个独立操作。',
  'models.selectorTitle': '新增 binding',
  'models.levelEndpoint': '1 · 端点',
  'models.levelKey': '2 · EndpointKey',
  'models.levelCandidate': '3 · 自动或手工模型',
  'models.chooseEndpoint': '请选择端点',
  'models.chooseKey': '请选择 EndpointKey',
  'models.endpointEmpty': '当前页没有可用端点。',
  'models.keyEmpty': '当前页没有可用的 EndpointKey。',
  'models.securityLocked': '安全处理中',
  'models.automatic': '自动候选',
  'models.manual': '手工候选',
  'models.sourceBoth': '自动 + 手工',
  'models.candidateEmpty': '此来源没有候选项。',
  'models.candidateSelected': '已选择',
  'models.alreadyBound': '已绑定',
  'models.selectedCount': '已跨筛选和分页选择 {{count}} 个唯一候选。',
  'models.addSelected': '添加已选的 {{count}} 个 binding',
  'models.selectionInvalid': '某个候选已失效，仅移除了该选择。',
  'models.bindingsTitle': '现有 binding 与路由顺序',
  'models.noBindings': '此逻辑模型还没有 binding。',
  'models.moveUp': '上移',
  'models.moveDown': '下移',
  'models.saveOrder': '保存完整顺序',
  'models.removeBinding': '移除 binding',
  'models.removeBindingTitle': '移除此 binding？',
  'models.removeBindingBody': '逻辑模型可能失去一条可路由的上游路径。',
  'models.deleteModel': '删除逻辑模型',
  'models.deleteModelTitle': '删除此逻辑模型？',
  'models.deleteModelBody': '此逻辑模型的全部 binding 都会被移除。',
  'models.nextCandidates': '下一页候选',
  'models.previousCandidates': '上一页候选',
  'account.title': '账户',
  'account.description': '查看资料、保存账户语言，并管理仅保存在此浏览器的显示偏好。',
  'account.profileTitle': '账户资料',
  'account.id': '账户 ID',
  'account.username': '用户名',
  'account.nickname': '服务器昵称',
  'account.created': '账户创建时间',
  'account.languageTitle': '账户语言',
  'account.languageBody': '只有服务端确认保存后，界面才会切换语言。',
  'account.language': '语言',
  'account.zh': '中文',
  'account.en': 'English',
  'account.languageSaved': '语言已保存。',
  'account.localTitle': '此浏览器',
  'account.localBody': '主题、密度和字号只保存在当前浏览器。',
  'account.theme': '主题',
  'account.themeLight': '浅色',
  'account.themeDark': '深色',
  'account.themeSystem': '跟随系统',
  'account.density': '密度',
  'account.densityComfortable': '舒适',
  'account.densityCompact': '紧凑',
  'account.fontSize': '字号',
  'account.fontDefault': '默认',
  'account.fontLarge': '较大',
  'account.exportTitle': '账户导出',
  'account.exportBody': '生命周期服务接线后，Export v4 会在此提供。',
  'account.export': '申请导出',
  'account.exportConfirm': '创建导出',
  'account.deleteTitle': '删除账户',
  'account.deleteBody':
    '删除不可逆，并会移除账户所拥有资源的访问权；共享记录只保留冻结的去身份投影。',
  'account.delete': '删除账户',
  'account.deleteConfirm': '永久删除账户',
  'account.deleteWord': '输入 DELETE 以继续',
  'account.deleteWordError': '请精确输入 DELETE。',
  'account.dangerTitle': '危险区',
  'account.reauthorize': '此操作需要新的 Discord 身份提升。',
  'account.lifecycleUnavailable': '此账号操作在当前版本中暂不可用。',
  'account.elevationFailed': '无法开始新的身份提升。',
  'account.exportUnknown': '导出响应状态未知。请重新完成身份提升后生成新导出；先前请求不会重放。',
  'account.deleteUnknown': '删除响应状态未知。请勿再次提交；先检查账号是否仍然存在。',
  'account.checkAuthority': '检查账号状态',
  'account.deleteStillActive': '账号仍处于活动状态；后续删除尝试必须重新完成身份提升。',
  'account.authorityCheckFailed': '暂时无法检查账号状态；删除请求未被重复提交。',
};

export const CORE_COPY_KEYS = Object.freeze(Object.keys(en) as CoreCopyKey[]);
export const CORE_COPY_DESCRIPTORS = Object.freeze(
  CORE_COPY_KEYS.map((key) =>
    Object.freeze({
      key,
      en: en[key],
      zh: zh[key],
    }),
  ),
);

function interpolate(template: string, values?: Readonly<Record<string, string | number>>): string {
  if (!values) return template;
  return template.replace(/\{\{([A-Za-z0-9_]+)\}\}/g, (_match, key: string) =>
    Object.hasOwn(values, key) ? String(values[key]) : '',
  );
}

export function coreText(
  key: CoreCopyKey,
  language: 'zh' | 'en',
  values?: Readonly<Record<string, string | number>>,
): string {
  return interpolate((language === 'zh' ? zh : en)[key], values);
}

export function useCoreCopy() {
  const { i18n } = useTranslation();
  const language = i18n.resolvedLanguage?.toLowerCase().startsWith('zh') ? 'zh' : 'en';
  return useMemo(
    () => ({
      language,
      t: (key: CoreCopyKey, values?: Readonly<Record<string, string | number>>) =>
        coreText(key, language, values),
    }),
    [language],
  );
}
