import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';

const en = {
  'common.loading': 'Loading…',
  'common.retry': 'Retry',
  'common.errorTitle': 'Could not load this section',
  'common.errorBody': 'The confirmed data for this section is unavailable.',
  'common.unavailableTitle': 'Not available yet',
  'common.unavailableBody': 'This section is not available in this version.',
  'common.emptyTitle': 'Nothing here yet',
  'common.working': 'Working…',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.copy': 'Copy',
  'common.copied': 'Copied',
  'common.copyFailed': 'Copy failed. Select and copy the value manually.',
  'common.previous': 'Previous',
  'common.next': 'Next',
  'common.enabled': 'Enabled',
  'common.disabled': 'Disabled',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.unknown': 'Unknown',
  'common.notSet': 'Not set',
  'common.available': 'Available',
  'common.blocked': 'Blocked',
  'common.reconcile': 'Check latest status',
  'common.retrySame': 'Retry the same operation',
  'common.created': 'Created',
  'common.updated': 'Updated',
  'common.refresh': 'Refresh',
  'common.back': 'Back',
  'common.remove': 'Remove',
  'common.search': 'Search',
  'common.conflict': 'The data changed. Review the latest values and try again.',
  'common.outcomeUnknown':
    'The response was lost. The page is checking the latest status and will not resend the action.',
  'common.fixedFailure':
    'The one-time value was not received. Click again only if you want a new operation.',
  'common.maintenance': 'This operation is temporarily unavailable.',
  'common.permissionLost': 'Your current session no longer permits this operation.',
  'connector.openai': 'OpenAI-compatible',
  'connector.anthropic': 'Anthropic-compatible',
  'home.title': 'Welcome back, {{name}}',
  'home.signedOutTitle': 'Your AI routing workspace',
  'home.signedOutBody': 'Sign in to manage endpoints, models, and your account.',
  'home.signIn': 'Sign in with Discord',
  'home.description': 'Manage API resources and check your usage and balance.',
  'home.profileTitle': 'Account',
  'home.username': 'Username',
  'home.accountStatus': 'Account status',
  'home.active': 'Active',
  'home.banned': 'Restricted',
  'home.economyTitle': 'Balance and level',
  'home.balance': 'Balance',
  'home.creditHistory': 'Credit history',
  'home.donationCredit': 'Total donation rewards',
  'home.level': 'Level',
  'home.levelValue': 'Lv{{level}} · {{name}}',
  'home.usageTitle': 'Lifetime usage',
  'home.requests': 'Requests',
  'home.promptTokens': 'Prompt tokens',
  'home.outputTokens': 'Output tokens',
  'home.unknownUsage': 'Requests with unknown usage',
  'home.checkinTitle': 'Daily check-in',
  'home.checkin.unavailable': 'Check-in is not available',
  'home.checkin.today': 'Today',
  'home.checkin.checkedIn': 'Checked in',
  'home.checkin.notCheckedIn': 'Not checked in yet',
  'home.checkin.awardRange': 'Award range (credits)',
  'home.checkin.threshold': 'Check-in threshold (credits)',
  'home.checkin.thresholdNone': 'No limit',
  'home.checkin.thresholdHint':
    'This limit only decides whether you can check in. Once reached, no new check-in is allowed; rewards already granted do not change.',
  'home.checkin.submit': 'Check in',
  'home.checkin.done':
    'Checked in: awarded {{award}} credits; the Nonbiri credits balance is now {{credits}}.',
  'home.checkinRefreshFailed':
    'Check-in succeeded, but the latest status could not be refreshed. Refresh to retry the read; the check-in will not be submitted again.',
  'home.gamesTitle': 'Continue or view results',
  'home.announcementsTitle': 'Announcements',
  'home.quickTitle': 'Quick access',
  'home.endpoints': 'Manage resources',
  'home.models': 'Manage models',
  'home.callerKey': 'API access',
  'home.activities': 'Open activities',
  'home.games': 'Open games',
  'home.continue': 'Continue',
  'home.view': 'View result',
  'home.gameFishing': 'Fishing',
  'home.gameLinklink': 'Link Link',
  'home.gameRps': 'Three-player rock paper scissors',
  'home.capabilityUnavailable': 'This summary is not available yet.',
  'endpoints.title': 'Resources',
  'endpoints.description':
    'Manage service addresses, keys, model checks, and available model connections.',
  'endpoints.create': 'Create endpoint',
  'endpoints.emptyTitle': 'No endpoints yet',
  'endpoints.emptyBody': 'Create an endpoint to connect a service you own or are allowed to use.',
  'endpoints.connector': 'Service type',
  'endpoints.origin': 'Origin',
  'endpoints.originCustom': 'Custom endpoint',
  'endpoints.originMainstream': 'Mainstream channel: {{name}}',
  'endpoints.mainstream': 'Mainstream channel',
  'endpoints.custom': 'Custom endpoint',
  'endpoints.channel': 'Channel',
  'endpoints.baseUrl': 'Service address',
  'endpoints.note': 'Note',
  'endpoints.keyCount': 'Key count',
  'endpoints.configuration': 'Endpoint configuration',
  'endpoints.manage': 'Manage endpoint',
  'endpoints.detailsTitle': 'Endpoint details',
  'endpoints.detailsDescription':
    'The service type and address cannot be changed after creation. Create a new endpoint to replace either one.',
  'endpoints.addKey': 'Add key',
  'endpoints.noKeysTitle': 'No keys',
  'endpoints.noKeysBody': 'Add a key you own to check models and create model connections.',
  'endpoints.key': 'Key',
  'endpoints.keyState': 'Key status',
  'endpoints.storePolicy': 'Do not save requests (store=false)',
  'endpoints.securityProcessing': 'Security processing — currently unavailable',
  'endpoints.discovery': 'Model check result',
  'endpoints.discoveryUnknown': 'No model check yet',
  'endpoints.discoveryChecking': 'Checking models',
  'endpoints.discoveryEmpty': 'The check completed, but no models were found',
  'endpoints.discoveryNonempty': 'The check found {{count}} model(s)',
  'endpoints.discoveryFailed': 'The model check failed: {{reason}}',
  'endpoints.discoveryReasonAuth': 'authentication was rejected',
  'endpoints.discoveryReasonRateLimit': 'the connected service rate limit was reached',
  'endpoints.discoveryReasonTimeout': 'the connected service timed out',
  'endpoints.discoveryReasonProtocol': 'the connected service returned an unsupported response',
  'endpoints.discoveryReasonTransport': 'the connected service could not be reached',
  'endpoints.discoveryReasonInterrupted': 'the check was interrupted',
  'endpoints.observedAt': 'Checked at',
  'endpoints.refreshDiscovery': 'Check models',
  'endpoints.routing': 'Model connection status',
  'endpoints.routingNone': 'No platform model currently uses this key.',
  'endpoints.routingAvailable': 'Used by {{count}} available platform model(s)',
  'endpoints.routingBlocked':
    'Model connections exist, but this endpoint or key is currently unavailable.',
  'endpoints.routingUnknown': 'Model connection status could not be checked.',
  'endpoints.toggleOn': 'Enable endpoint',
  'endpoints.toggleOff': 'Disable endpoint',
  'endpoints.keyToggleOn': 'Enable key',
  'endpoints.keyToggleOff': 'Disable key',
  'endpoints.storePolicyOn': 'Require store=false',
  'endpoints.storePolicyOff': 'Stop requiring store=false',
  'endpoints.dangerTitle': 'Danger zone',
  'endpoints.deleteEndpoint': 'Delete endpoint',
  'endpoints.deleteEndpointTitle': 'Delete this endpoint?',
  'endpoints.deleteEndpointBody':
    'Its keys, model check results, model connections, and shared resources will be affected. This cannot be undone.',
  'endpoints.deleteKey': 'Delete key',
  'endpoints.deleteKeyTitle': 'Delete this key?',
  'endpoints.deleteKeyBody':
    'Model connections, shared resources, and model check results that use this key will be affected.',
  'endpoints.wizardTitle': 'Create endpoint and key',
  'endpoints.wizardConnector': '1 · Service type',
  'endpoints.wizardUrl': '2 · URL preview',
  'endpoints.wizardKey': '3 · Key',
  'endpoints.wizardDiscovery': '4 · Model check',
  'endpoints.wizardBinding': '5 · Optional model connection',
  'endpoints.preview': 'Address preview',
  'endpoints.previewAuthority': 'The saved address is shown after creation.',
  'endpoints.createEndpointStep': 'Create endpoint',
  'endpoints.secret': 'Service key',
  'endpoints.keyNote': 'Key note',
  'endpoints.ownership': 'I own this credential or have explicit permission to use it here.',
  'endpoints.costWarning':
    'Model checks contact the connected service and may be rate-limited or billed under its terms.',
  'endpoints.addKeyStep': 'Add key',
  'endpoints.multipleKeysHint':
    'An endpoint can hold multiple keys. Add them here, or return to key management later.',
  'endpoints.addAnotherKey': 'Add another key',
  'endpoints.secretRequired':
    'Enter the service key and confirm permission to use it. Other fields were kept.',
  'endpoints.finish': 'Finish',
  'endpoints.openBindings': 'Open model connections',
  'endpoints.manualTitle': 'Manual catalog',
  'endpoints.manualAlways': 'Manual entries remain available even when automatic discovery fails.',
  'endpoints.manualModel': 'Exact service model ID',
  'endpoints.manualProvider': 'Service provider (optional)',
  'endpoints.manualAdd': 'Add manual entry',
  'endpoints.manualEmpty': 'No manual entries for this key.',
  'endpoints.manualImpact':
    'Used by {{count}} model connection(s). Before changing or deleting it, choose an exact replacement for each connection.',
  'endpoints.manualImpactUnknown':
    'The affected model connections could not be checked. Refresh their status before changing or deleting this entry.',
  'endpoints.replacement': 'Replacement service model ID for {{model}} (connection {{id}})',
  'endpoints.updateManual': 'Update entry',
  'endpoints.deleteManual': 'Delete entry',
  'keys.title': 'Global API access',
  'keys.description':
    'Your account API key works across the whole account. Its full value is shown only once.',
  'keys.metadataTitle': 'API key details',
  'keys.noKeyTitle': 'No account API key',
  'keys.noKeyBody': 'Create your first API key.',
  'keys.generate': 'Create API key',
  'keys.rotate': 'Replace API key',
  'keys.rotateTitle': 'Replace the account API key?',
  'keys.rotateBody':
    'The previous key stops working immediately. Update every client that uses it.',
  'keys.display': 'Key preview',
  'keys.oneTimeTitle': 'Copy this API key now',
  'keys.oneTimeBody': 'It will never be shown again after you close it or leave this page.',
  'keys.closeReveal': 'I have saved it — close',
  'keys.refreshError':
    'Key details could not be refreshed. The full key remains visible until you close it.',
  'models.title': 'Platform models',
  'models.description':
    'Create stable model names, connect exact service models, and choose the order in which connections are tried.',
  'models.create': 'Create platform model',
  'models.emptyTitle': 'No platform models',
  'models.emptyBody': 'Create a provider/model name, then add one or more service connections.',
  'models.provider': 'Service provider',
  'models.model': 'Model name',
  'models.fullName': 'Platform model name',
  'models.namingHelp':
    'Choose your own provider and model names to form the name used in API calls. Select the actual upstream models under service connections after creation.',
  'models.namePreview': 'API model name preview',
  'models.strategy': 'Connection strategy',
  'models.ordered': 'Ordered',
  'models.random': 'Random',
  'models.silentRetry': 'Silent retry',
  'models.flattenTools': 'Flatten tool calls',
  'models.bindingCount': 'Connections',
  'models.manage': 'Manage connections',
  'models.configurationTitle': 'Platform model settings',
  'models.editModel': 'Edit platform model',
  'models.invalidName':
    'Provider and model must each contain 1–64 characters with no surrounding whitespace or control characters.',
  'models.detailTitle': 'Model connections',
  'models.detailDescription':
    'Choose the models to connect and arrange the order in which they are tried.',
  'models.selectorTitle': 'Add connections',
  'models.levelEndpoint': '1 · Endpoint',
  'models.levelKey': '2 · Key',
  'models.levelCandidate': '3 · Automatic or manual model',
  'models.searchCandidates': 'Search upstream models',
  'models.chooseEndpoint': 'Choose an endpoint',
  'models.chooseKey': 'Choose a key',
  'models.endpointEmpty': 'No endpoint is available on this page.',
  'models.keyEmpty': 'No usable key is available on this page.',
  'models.securityLocked': 'Security processing',
  'models.automatic': 'Automatically found models',
  'models.manual': 'Manually added models',
  'models.sourceBoth': 'Automatic + manual',
  'models.candidateEmpty': 'No models in this source.',
  'models.candidateSelected': 'Selected',
  'models.alreadyBound': 'Already connected',
  'models.selectedCount': '{{count}} unique model(s) selected across filters and pages.',
  'models.addSelected': 'Add {{count}} selected connection(s)',
  'models.selectionInvalid': 'A model became unavailable; only that selection was removed.',
  'models.bindingsTitle': 'Current connections and order',
  'models.noBindings': 'This platform model has no service connections.',
  'models.moveUp': 'Move up',
  'models.moveDown': 'Move down',
  'models.saveOrder': 'Save complete order',
  'models.removeBinding': 'Remove connection',
  'models.removeBindingTitle': 'Remove this connection?',
  'models.removeBindingBody': 'The platform model may lose an available service connection.',
  'models.deleteModel': 'Delete platform model',
  'models.deleteModelTitle': 'Delete this platform model?',
  'models.deleteModelBody': 'All service connections for this platform model will be removed.',
  'models.nextCandidates': 'Next models',
  'models.previousCandidates': 'Previous models',
  'account.title': 'Account',
  'account.description':
    'Review your profile, save account language, and manage local display preferences.',
  'account.profileTitle': 'Profile',
  'account.id': 'Account ID',
  'account.username': 'Username',
  'account.nickname': 'Server nickname',
  'account.created': 'Account created',
  'account.languageTitle': 'Account language',
  'account.languageBody': 'The interface changes only after the server confirms the update.',
  'account.language': 'Language',
  'account.zh': '中文',
  'account.en': 'English',
  'account.languageSaved': 'Language saved.',
  'account.localTitle': 'This browser',
  'account.localBody': 'Theme, density, and font size stay only in this browser.',
  'account.theme': 'Theme',
  'account.themeLight': 'Light',
  'account.themeDark': 'Dark',
  'account.themeSystem': 'Follow system',
  'account.density': 'Density',
  'account.densityComfortable': 'Comfortable',
  'account.densityCompact': 'Compact',
  'account.fontSize': 'Font size',
  'account.fontDefault': 'Default',
  'account.fontLarge': 'Large',
  'account.exportTitle': 'Account export',
  'account.exportBody': 'Download a copy of the account information available for export.',
  'account.export': 'Request export',
  'account.exportConfirm': 'Create export',
  'account.deleteTitle': 'Delete account',
  'account.deleteBody':
    'Deletion is irreversible and removes access to account-owned resources. Shared records keep only the necessary information without your identity.',
  'account.delete': 'Delete account',
  'account.deleteConfirm': 'Permanently delete account',
  'account.deleteWord': 'Type DELETE to continue',
  'account.deleteWordError': 'Type DELETE exactly.',
  'account.dangerTitle': 'Danger zone',
  'account.reauthorize': 'Verify your Discord identity again to continue.',
  'account.lifecycleUnavailable': 'This account action is not available in this version.',
  'account.elevationFailed': 'Discord verification could not be started.',
  'account.exportUnknown':
    'The export result could not be confirmed. Verify your Discord identity again to create a new export; the previous request will not run again.',
  'account.deleteUnknown':
    'The deletion response was unknown. Do not submit it again; check whether the account still exists.',
  'account.checkAuthority': 'Check account status',
  'account.deleteStillActive':
    'The account is still active. Verify your Discord identity again before another deletion attempt.',
  'account.authorityCheckFailed':
    'Account status could not be checked. The deletion request was not repeated.',
} as const;

export type CoreCopyKey = keyof typeof en;

const zh: Record<CoreCopyKey, string> = {
  'common.loading': '正在加载…',
  'common.retry': '重试',
  'common.errorTitle': '无法加载此区域',
  'common.errorBody': '此区域的最新数据当前不可用。',
  'common.unavailableTitle': '暂未可用',
  'common.unavailableBody': '此功能暂不可用。',
  'common.emptyTitle': '这里还没有内容',
  'common.working': '正在处理…',
  'common.cancel': '取消',
  'common.close': '关闭',
  'common.save': '保存',
  'common.delete': '删除',
  'common.edit': '编辑',
  'common.copy': '复制',
  'common.copied': '已复制',
  'common.copyFailed': '复制失败，请手动选择并复制。',
  'common.previous': '上一页',
  'common.next': '下一页',
  'common.enabled': '已启用',
  'common.disabled': '已停用',
  'common.yes': '是',
  'common.no': '否',
  'common.unknown': '未知',
  'common.notSet': '未设置',
  'common.available': '可用',
  'common.blocked': '已阻止',
  'common.reconcile': '检查最新状态',
  'common.retrySame': '重试同一操作',
  'common.created': '创建时间',
  'common.updated': '更新时间',
  'common.refresh': '刷新',
  'common.back': '返回',
  'common.remove': '移除',
  'common.search': '搜索',
  'common.conflict': '数据已更新，请核对后重试。',
  'common.outcomeUnknown': '响应已丢失。页面正在检查最新状态，不会自动重发操作。',
  'common.fixedFailure': '没有取得一次性明文。只有再次点击才会开始新操作。',
  'common.maintenance': '此操作暂时不可用。',
  'common.permissionLost': '当前会话已无权执行此操作。',
  'connector.openai': 'OpenAI 兼容',
  'connector.anthropic': 'Anthropic 兼容',
  'home.title': '欢迎回来，{{name}}',
  'home.signedOutTitle': '你的 AI 路由工作台',
  'home.signedOutBody': '登录后即可管理端点、模型和账户。',
  'home.signIn': '使用 Discord 登录',
  'home.description': '管理 API 资源，查看用量与余额。',
  'home.profileTitle': '账户',
  'home.username': '用户名',
  'home.accountStatus': '账户状态',
  'home.active': '正常',
  'home.banned': '受限',
  'home.economyTitle': '余额与等级',
  'home.balance': '余额',
  'home.creditHistory': '积分流水',
  'home.donationCredit': '累计捐赠回馈',
  'home.level': '等级',
  'home.levelValue': '等级 {{level}} · {{name}}',
  'home.usageTitle': '累计用量',
  'home.requests': '请求数',
  'home.promptTokens': '提示 Token',
  'home.outputTokens': '输出 Token',
  'home.unknownUsage': '用量未知请求',
  'home.checkinTitle': '每日签到',
  'home.checkin.unavailable': '签到未启用',
  'home.checkin.today': '今日状态',
  'home.checkin.checkedIn': '已签到',
  'home.checkin.notCheckedIn': '未签到',
  'home.checkin.awardRange': '奖励范围（积分）',
  'home.checkin.threshold': '签到门槛（积分）',
  'home.checkin.thresholdNone': '无上限',
  'home.checkin.thresholdHint': '此上限只决定还能否签到；达到后不能再签到，已发放的奖励不会减少。',
  'home.checkin.submit': '立即签到',
  'home.checkin.done': '签到成功：获得 {{award}} 积分，当前悠哉积分 {{credits}}。',
  'home.checkinRefreshFailed':
    '签到已经成功，但最新状态刷新失败。你可以重新刷新读取；页面不会再次提交签到。',
  'home.gamesTitle': '继续进行或查看结果',
  'home.announcementsTitle': '公告',
  'home.quickTitle': '快捷入口',
  'home.endpoints': '管理资源',
  'home.models': '管理模型',
  'home.callerKey': 'API 接入',
  'home.activities': '打开活动',
  'home.games': '打开游戏',
  'home.continue': '继续',
  'home.view': '查看结果',
  'home.gameFishing': '钓鱼',
  'home.gameLinklink': '连连看',
  'home.gameRps': '三人猜拳',
  'home.capabilityUnavailable': '此摘要暂不可用。',
  'endpoints.title': '资源',
  'endpoints.description': '管理服务地址、密钥、模型检查结果和可用的模型连接。',
  'endpoints.create': '创建端点',
  'endpoints.emptyTitle': '还没有端点',
  'endpoints.emptyBody': '创建端点，连接你拥有或获准使用的服务。',
  'endpoints.connector': '服务类型',
  'endpoints.origin': '来源',
  'endpoints.originCustom': '自定义端点',
  'endpoints.originMainstream': '主流渠道：{{name}}',
  'endpoints.mainstream': '主流渠道',
  'endpoints.custom': '自定义端点',
  'endpoints.channel': '渠道',
  'endpoints.baseUrl': '服务地址',
  'endpoints.note': '备注',
  'endpoints.keyCount': '密钥数量',
  'endpoints.configuration': '端点配置',
  'endpoints.manage': '管理端点',
  'endpoints.detailsTitle': '端点详情',
  'endpoints.detailsDescription': '服务类型与地址创建后不可更改；如需更换，请新建端点。',
  'endpoints.addKey': '添加密钥',
  'endpoints.noKeysTitle': '还没有密钥',
  'endpoints.noKeysBody': '添加你拥有的密钥后，即可检查模型并创建模型连接。',
  'endpoints.key': '密钥',
  'endpoints.keyState': '密钥状态',
  'endpoints.storePolicy': '不保存请求（store=false）',
  'endpoints.securityProcessing': '安全处理中，当前不可操作',
  'endpoints.discovery': '模型检查结果',
  'endpoints.discoveryUnknown': '尚未检查模型',
  'endpoints.discoveryChecking': '正在检查模型',
  'endpoints.discoveryEmpty': '检查完成，但没有找到模型',
  'endpoints.discoveryNonempty': '检查完成，共找到 {{count}} 个模型',
  'endpoints.discoveryFailed': '模型检查失败：{{reason}}',
  'endpoints.discoveryReasonAuth': '所连接的服务拒绝了身份验证',
  'endpoints.discoveryReasonRateLimit': '所连接的服务已达到访问频率限制',
  'endpoints.discoveryReasonTimeout': '所连接的服务响应超时',
  'endpoints.discoveryReasonProtocol': '所连接的服务返回了不支持的内容',
  'endpoints.discoveryReasonTransport': '无法连接所选服务',
  'endpoints.discoveryReasonInterrupted': '检查已中断',
  'endpoints.observedAt': '检查时间',
  'endpoints.refreshDiscovery': '检查模型',
  'endpoints.routing': '模型连接状态',
  'endpoints.routingNone': '当前没有平台模型使用此密钥。',
  'endpoints.routingAvailable': '已有 {{count}} 个平台模型可通过此密钥使用',
  'endpoints.routingBlocked': '已有模型连接，但此端点或密钥当前不可用。',
  'endpoints.routingUnknown': '暂时无法检查模型连接状态。',
  'endpoints.toggleOn': '启用端点',
  'endpoints.toggleOff': '停用端点',
  'endpoints.keyToggleOn': '启用密钥',
  'endpoints.keyToggleOff': '停用密钥',
  'endpoints.storePolicyOn': '要求 store=false',
  'endpoints.storePolicyOff': '取消要求 store=false',
  'endpoints.dangerTitle': '危险区',
  'endpoints.deleteEndpoint': '删除端点',
  'endpoints.deleteEndpointTitle': '删除此端点？',
  'endpoints.deleteEndpointBody':
    '其密钥、模型检查结果、模型连接和共享资源都会受到影响，且无法撤销。',
  'endpoints.deleteKey': '删除密钥',
  'endpoints.deleteKeyTitle': '删除此密钥？',
  'endpoints.deleteKeyBody': '使用此密钥的模型连接、共享资源和模型检查结果都会受到影响。',
  'endpoints.wizardTitle': '创建端点与密钥',
  'endpoints.wizardConnector': '1 · 服务类型',
  'endpoints.wizardUrl': '2 · 地址预览',
  'endpoints.wizardKey': '3 · 密钥',
  'endpoints.wizardDiscovery': '4 · 模型检查',
  'endpoints.wizardBinding': '5 · 可选模型连接',
  'endpoints.preview': '地址预览',
  'endpoints.previewAuthority': '创建后会显示最终保存的地址。',
  'endpoints.createEndpointStep': '创建端点',
  'endpoints.secret': '服务密钥',
  'endpoints.keyNote': '密钥备注',
  'endpoints.ownership': '我拥有此凭据，或已取得在此使用它的明确授权。',
  'endpoints.costWarning': '模型检查会访问所连接的服务，并可能受到访问频率限制或按其条款产生费用。',
  'endpoints.addKeyStep': '添加密钥',
  'endpoints.multipleKeysHint':
    '一个端点可以添加多把密钥。你可以在这里连续添加，也可以稍后进入密钥管理。',
  'endpoints.addAnotherKey': '再添加一把密钥',
  'endpoints.secretRequired': '请输入服务密钥并确认有权使用；其他字段已保留。',
  'endpoints.finish': '完成',
  'endpoints.openBindings': '打开模型连接',
  'endpoints.manualTitle': '手工目录',
  'endpoints.manualAlways': '即使自动发现失败，手工入口仍然可用。',
  'endpoints.manualModel': '精确服务模型 ID',
  'endpoints.manualProvider': '服务商（可选）',
  'endpoints.manualAdd': '添加手工条目',
  'endpoints.manualEmpty': '此密钥没有手工条目。',
  'endpoints.manualImpact':
    '有 {{count}} 个模型连接使用此条目。修改或删除前，请为每个连接选择精确替代项。',
  'endpoints.manualImpactUnknown':
    '暂时无法检查受影响的模型连接。请先刷新连接状态，再修改或删除此条目。',
  'endpoints.replacement': '{{model}}（连接 {{id}}）的替代服务模型 ID',
  'endpoints.updateManual': '更新条目',
  'endpoints.deleteManual': '删除条目',
  'keys.title': '全局 API 接入',
  'keys.description': '账户 API 密钥可用于整个账号；完整内容只会显示一次。',
  'keys.metadataTitle': 'API 密钥详情',
  'keys.noKeyTitle': '尚未创建账户 API 密钥',
  'keys.noKeyBody': '创建你的第一把 API 密钥。',
  'keys.generate': '创建 API 密钥',
  'keys.rotate': '更换 API 密钥',
  'keys.rotateTitle': '更换账户 API 密钥？',
  'keys.rotateBody': '旧密钥会立即失效，请更新所有使用它的程序。',
  'keys.display': '密钥预览',
  'keys.oneTimeTitle': '请立即复制此 API 密钥',
  'keys.oneTimeBody': '关闭或离开此页面后将永不再次显示。',
  'keys.closeReveal': '我已保存，关闭明文',
  'keys.refreshError': '密钥详情刷新失败；完整密钥会保留到你主动关闭。',
  'models.title': '平台模型',
  'models.description': '创建稳定的模型名称、连接指定的服务模型，并设置各连接的尝试顺序。',
  'models.create': '创建平台模型',
  'models.emptyTitle': '还没有平台模型',
  'models.emptyBody': '先创建服务商/模型名称，再添加一个或多个服务连接。',
  'models.provider': '服务商',
  'models.model': '模型名称',
  'models.fullName': '平台模型名称',
  'models.namingHelp':
    '服务商和模型名称可自行命名，用来组成站内 API 调用名。创建后，在服务连接中选择实际调用的上游模型。',
  'models.namePreview': 'API 调用模型名预览',
  'models.strategy': '连接策略',
  'models.ordered': '顺序',
  'models.random': '随机',
  'models.silentRetry': '静默重试',
  'models.flattenTools': '扁平化工具调用',
  'models.bindingCount': '连接数',
  'models.manage': '管理连接',
  'models.configurationTitle': '平台模型设置',
  'models.editModel': '编辑平台模型',
  'models.invalidName': 'provider 与 model 均须为 1–64 个字符，且不能含首尾空白或控制字符。',
  'models.detailTitle': '模型连接',
  'models.detailDescription': '选择要连接的模型，并按需要调整尝试顺序。',
  'models.selectorTitle': '新增连接',
  'models.levelEndpoint': '1 · 端点',
  'models.levelKey': '2 · 密钥',
  'models.levelCandidate': '3 · 自动或手工模型',
  'models.searchCandidates': '搜索上游模型',
  'models.chooseEndpoint': '请选择端点',
  'models.chooseKey': '请选择密钥',
  'models.endpointEmpty': '当前页没有可用端点。',
  'models.keyEmpty': '当前页没有可用的密钥。',
  'models.securityLocked': '安全处理中',
  'models.automatic': '自动找到的模型',
  'models.manual': '手动添加的模型',
  'models.sourceBoth': '自动 + 手工',
  'models.candidateEmpty': '此来源没有模型。',
  'models.candidateSelected': '已选择',
  'models.alreadyBound': '已连接',
  'models.selectedCount': '已跨筛选和分页选择 {{count}} 个不同模型。',
  'models.addSelected': '添加已选的 {{count}} 个连接',
  'models.selectionInvalid': '某个模型已不可用，仅移除了该选择。',
  'models.bindingsTitle': '现有连接及其顺序',
  'models.noBindings': '此平台模型还没有服务连接。',
  'models.moveUp': '上移',
  'models.moveDown': '下移',
  'models.saveOrder': '保存完整顺序',
  'models.removeBinding': '移除连接',
  'models.removeBindingTitle': '移除此连接？',
  'models.removeBindingBody': '此平台模型可能失去一个可用的服务连接。',
  'models.deleteModel': '删除平台模型',
  'models.deleteModelTitle': '删除此平台模型？',
  'models.deleteModelBody': '此平台模型的全部服务连接都会被移除。',
  'models.nextCandidates': '下一页模型',
  'models.previousCandidates': '上一页模型',
  'account.title': '账户',
  'account.description': '查看资料、保存账户语言，并管理仅保存在此浏览器的显示偏好。',
  'account.profileTitle': '账户资料',
  'account.id': '账户 ID',
  'account.username': '用户名',
  'account.nickname': '服务器昵称',
  'account.created': '账户创建时间',
  'account.languageTitle': '账户语言',
  'account.languageBody': '选择界面语言，保存后生效。',
  'account.language': '语言',
  'account.zh': '中文',
  'account.en': 'English',
  'account.languageSaved': '语言已保存。',
  'account.localTitle': '此浏览器',
  'account.localBody': '主题、密度和字号只保存在当前浏览器。',
  'account.theme': '主题',
  'account.themeLight': '浅色',
  'account.themeDark': '深色',
  'account.themeSystem': '跟随系统',
  'account.density': '密度',
  'account.densityComfortable': '舒适',
  'account.densityCompact': '紧凑',
  'account.fontSize': '字号',
  'account.fontDefault': '默认',
  'account.fontLarge': '较大',
  'account.exportTitle': '账户导出',
  'account.exportBody': '下载当前可导出的账户信息副本。',
  'account.export': '申请导出',
  'account.exportConfirm': '创建导出',
  'account.deleteTitle': '删除账户',
  'account.deleteBody':
    '删除不可逆，并会移除账户所拥有资源的访问权；共享记录只保留不含个人身份的必要信息。',
  'account.delete': '删除账户',
  'account.deleteConfirm': '永久删除账户',
  'account.deleteWord': '输入 DELETE 以继续',
  'account.deleteWordError': '请精确输入 DELETE。',
  'account.dangerTitle': '危险区',
  'account.reauthorize': '请重新验证 Discord 身份后继续。',
  'account.lifecycleUnavailable': '此账号操作暂不可用。',
  'account.elevationFailed': '无法开始 Discord 身份验证。',
  'account.exportUnknown':
    '暂时无法确认导出结果。请重新验证 Discord 身份后创建新导出；先前请求不会再次执行。',
  'account.deleteUnknown': '删除响应状态未知。请勿再次提交；先检查账号是否仍然存在。',
  'account.checkAuthority': '检查账号状态',
  'account.deleteStillActive': '账号仍处于活动状态；再次尝试删除前，请重新验证 Discord 身份。',
  'account.authorityCheckFailed': '暂时无法检查账号状态；删除请求未被重复提交。',
};

export const CORE_COPY_KEYS = Object.freeze(Object.keys(en) as CoreCopyKey[]);
export const CORE_COPY_DESCRIPTORS = Object.freeze(
  CORE_COPY_KEYS.map((key) =>
    Object.freeze({
      key,
      en: en[key],
      zh: zh[key],
    }),
  ),
);

function interpolate(template: string, values?: Readonly<Record<string, string | number>>): string {
  if (!values) return template;
  return template.replace(/\{\{([A-Za-z0-9_]+)\}\}/g, (_match, key: string) =>
    Object.hasOwn(values, key) ? String(values[key]) : '',
  );
}

export function coreText(
  key: CoreCopyKey,
  language: 'zh' | 'en',
  values?: Readonly<Record<string, string | number>>,
): string {
  return interpolate((language === 'zh' ? zh : en)[key], values);
}

export function useCoreCopy() {
  const { i18n } = useTranslation();
  const language = i18n.resolvedLanguage?.toLowerCase().startsWith('zh') ? 'zh' : 'en';
  return useMemo(
    () => ({
      language,
      t: (key: CoreCopyKey, values?: Readonly<Record<string, string | number>>) =>
        coreText(key, language, values),
    }),
    [language],
  );
}
