package claim

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/waiting-here/NonbiriAPI/internal/db"
	"github.com/waiting-here/NonbiriAPI/internal/diagnostic"
)

// RecordCharityRejectionTx records a policy rejection without accepting work,
// reserving funds, or creating a dispatch claim. The caller commits it together
// with any configured penalty. The opaque identity is generated by the server.
func (s *Service) RecordCharityRejectionTx(ctx context.Context, tx *sql.Tx, userID int64, requestID, model string, actual, minimum int, at int64) error {
	if s == nil || s.acceptance == nil || ctx == nil || tx == nil || userID <= 0 ||
		!db.ValidateOpaqueID(requestID, "req_") || actual < 0 || actual >= minimum || minimum > 1<<20 || at < 0 || at > maxUnixSecond {
		return ErrInvalidInput
	}
	if err := requireActiveUser(ctx, tx, userID, at, true); err != nil {
		return err
	}
	if err := s.acceptance.AuthorizeChatAcceptance(ctx, tx, userID, at); err != nil {
		return err
	}
	model = diagnostic.BoundTo(model, MaxModelSnapshotBytes)
	if _, err := tx.ExecContext(ctx, `INSERT INTO logical_requests
(id,user_id,route_kind,model_snapshot,state,attempt_limit,caller_result_class,caller_status,caller_error_code,
accounting_state,account_reserved_milli,settlement_destination,ledger_rows_remaining,created_at,terminal_at)
VALUES(?,?,'charity_chat_completions',?,'terminal',1,'failed',400,'content_too_short','released',0,'user',?,?,?)`,
		requestID, userID, model, u128Small(0), at, at); err != nil {
		return err
	}
	if _, err := tx.ExecContext(ctx, `INSERT INTO request_logs
(logical_request_id,user_id,model,route_kind,caller_result_class,caller_status,caller_error_code,status_code,error_code,started_at,completed_at,error_diag)
VALUES(?, ?, ?, 'charity_chat_completions','failed',400,'content_too_short',400,'content_too_short',?,?,?)`,
		requestID, userID, model, at, at, fmt.Sprintf("content has %d characters; minimum is %d", actual, minimum)); err != nil {
		return err
	}
	return addRequestUsageTx(ctx, tx, requestID, &userID, at)
}
