import { useRegisteredCopy } from '@shared/i18n/useRegisteredCopy';
import type { DuelResult } from './types';
export const duelCopyKeys = {
  'common.thisGameIsNotOpen': 'user.games.duel.common.thisGameIsNotOpen',
  'common.thisModeIsNotOpen': 'user.games.duel.common.thisModeIsNotOpen',
  'common.theGameIsTemporarilyUnavailableTryAgain':
    'user.games.duel.common.theGameIsTemporarilyUnavailableTryAgain',
  'common.close': 'user.games.duel.common.close',
  'common.victory': 'user.games.duel.common.victory',
  'common.defeat': 'user.games.duel.common.defeat',
  'common.draw': 'user.games.duel.common.draw',
  'common.systemCancelled': 'user.games.duel.common.systemCancelled',
  'bidding.biddingDuelRules': 'user.games.duel.bidding.biddingDuelRules',
  'bidding.thirteenRoundsMakeEveryCardCount':
    'user.games.duel.bidding.thirteenRoundsMakeEveryCardCount',
  'bidding.theRedSideBidsWithHeartsAnd': 'user.games.duel.bidding.theRedSideBidsWithHeartsAnd',
  'bidding.tiesAndCarry': 'user.games.duel.bidding.tiesAndCarry',
  'bidding.aTiedBidCarriesTheRewardsInto': 'user.games.duel.bidding.aTiedBidCarriesTheRewardsInto',
  'bidding.whenToUseYourJoker': 'user.games.duel.bidding.whenToUseYourJoker',
  'bidding.duringTheFirstTwelveRoundsJokerDecisions':
    'user.games.duel.bidding.duringTheFirstTwelveRoundsJokerDecisions',
  'bidding.matchingAndSettlement': 'user.games.duel.bidding.matchingAndSettlement',
  'bidding.queueForUpTo120SecondsAnd': 'user.games.duel.bidding.queueForUpTo120SecondsAnd',
  'bidding.biddingDuel': 'user.games.duel.bidding.biddingDuel',
  'bidding.holdYourNerveTakeTheWholePool': 'user.games.duel.bidding.holdYourNerveTakeTheWholePool',
  'bidding.rules': 'user.games.duel.bidding.rules',
  'bidding.gameHistory': 'user.games.duel.bidding.gameHistory',
  'bidding.round': 'user.games.duel.bidding.round',
  'bidding.message': 'user.games.duel.bidding.message',
  'bidding.jokerDecision': 'user.games.duel.bidding.jokerDecision',
  'bidding.simultaneousBidding': 'user.games.duel.bidding.simultaneousBidding',
  'bidding.secondsRemaining': 'user.games.duel.bidding.secondsRemaining',
  'bidding.pts': 'user.games.duel.bidding.pts',
  'bidding.jokerAvailable': 'user.games.duel.bidding.jokerAvailable',
  'bidding.jokerUsed': 'user.games.duel.bidding.jokerUsed',
  'bidding.locked': 'user.games.duel.bidding.locked',
  'bidding.choosing': 'user.games.duel.bidding.choosing',
  'bidding.matchFoundChooseIndependentlyRevealTogether':
    'user.games.duel.bidding.matchFoundChooseIndependentlyRevealTogether',
  'bidding.roundRewardsAndPool': 'user.games.duel.bidding.roundRewardsAndPool',
  'bidding.cURRENTPOOL': 'user.games.duel.bidding.cURRENTPOOL',
  'bidding.pointsWinnerTakesAll': 'user.games.duel.bidding.pointsWinnerTakesAll',
  'bidding.includesRewardsCarriedFromEarlierTies':
    'user.games.duel.bidding.includesRewardsCarriedFromEarlierTies',
  'bidding.surrender': 'user.games.duel.bidding.surrender',
  'bidding.yourEntry': 'user.games.duel.bidding.yourEntry',
  'bidding.fINDINGAMATCH': 'user.games.duel.bidding.fINDINGAMATCH',
  'bidding.yourSeatIsReady': 'user.games.duel.bidding.yourSeatIsReady',
  'bidding.queueTimeLeft': 'user.games.duel.bidding.queueTimeLeft',
  'bidding.cancelQueueAndRefund': 'user.games.duel.bidding.cancelQueueAndRefund',
  'bidding.theFinalRoundTiedTheRemainingPool':
    'user.games.duel.bidding.theFinalRoundTiedTheRemainingPool',
  'bidding.cHOOSEYOURTABLE': 'user.games.duel.bidding.cHOOSEYOURTABLE',
  'bidding.thirteenCardsOneDuel': 'user.games.duel.bidding.thirteenCardsOneDuel',
  'bidding.entryTier': 'user.games.duel.bidding.entryTier',
  'bidding.tier': 'user.games.duel.bidding.tier',
  'bidding.message2': 'user.games.duel.bidding.message2',
  'bidding.open': 'user.games.duel.bidding.open',
  'bidding.unavailable': 'user.games.duel.bidding.unavailable',
  'bidding.insufficientCredits': 'user.games.duel.bidding.insufficientCredits',
  'bidding.payEntryAndFindAMatch': 'user.games.duel.bidding.payEntryAndFindAMatch',
  'bidding.biddingMasters': 'user.games.duel.bidding.biddingMasters',
  'bidding.biddingProfits': 'user.games.duel.bidding.biddingProfits',
  'bidding.confirmSurrender': 'user.games.duel.bidding.confirmSurrender',
  'bidding.surrenderImmediatelyConcedesTheGameYourEntry':
    'user.games.duel.bidding.surrenderImmediatelyConcedesTheGameYourEntry',
  'bidding.surrender2': 'user.games.duel.bidding.surrender2',
  'bidding.keepPlaying': 'user.games.duel.bidding.keepPlaying',
  'bidding.finalTieThePoolIsDiscarded': 'user.games.duel.bidding.finalTieThePoolIsDiscarded',
  'bidding.tieThePoolCarriesToTheNext': 'user.games.duel.bidding.tieThePoolCarriesToTheNext',
  'bidding.roundSettled': 'user.games.duel.bidding.roundSettled',
  'bidding.you': 'user.games.duel.bidding.you',
  'bidding.opponent': 'user.games.duel.bidding.opponent',
  'bidding.collectsTheWholePool': 'user.games.duel.bidding.collectsTheWholePool',
  'bidding.chooseABidPrivatelyAndLockIt': 'user.games.duel.bidding.chooseABidPrivatelyAndLockIt',
  'bidding.discarded': 'user.games.duel.bidding.discarded',
  'bidding.carryToNextRound': 'user.games.duel.bidding.carryToNextRound',
  'bidding.poolPoints': 'user.games.duel.bidding.poolPoints',
  'bidding.roundDrawRewardsFromBothDecks': 'user.games.duel.bidding.roundDrawRewardsFromBothDecks',
  'bidding.bothBidsRevealedTogether': 'user.games.duel.bidding.bothBidsRevealedTogether',
  'bidding.rewardsAreReadyChoosePrivately':
    'user.games.duel.bidding.rewardsAreReadyChoosePrivately',
  'bidding.jokerMultiplier2IsIncluded': 'user.games.duel.bidding.jokerMultiplier2IsIncluded',
  'bidding.diamonds': 'user.games.duel.bidding.diamonds',
  'bidding.clubs': 'user.games.duel.bidding.clubs',
  'bidding.points': 'user.games.duel.bidding.points',
  'bidding.your': 'user.games.duel.bidding.your',
  'bidding.opponentS': 'user.games.duel.bidding.opponentS',
  'bidding.diamonds2': 'user.games.duel.bidding.diamonds2',
  'bidding.clubs2': 'user.games.duel.bidding.clubs2',
  'bidding.deckViewRemainingRewardRanks': 'user.games.duel.bidding.deckViewRemainingRewardRanks',
  'bidding.remainingRewardCards': 'user.games.duel.bidding.remainingRewardCards',
  'bidding.remainingRewardRanks': 'user.games.duel.bidding.remainingRewardRanks',
  'bidding.allDrawn': 'user.games.duel.bidding.allDrawn',
  'bidding.ranksOnlyThisDoesNotRevealThe': 'user.games.duel.bidding.ranksOnlyThisDoesNotRevealThe',
  'bidding.yourJokerYourMoment': 'user.games.duel.bidding.yourJokerYourMoment',
  'bidding.waitingForTheOpponentSJokerDecision':
    'user.games.duel.bidding.waitingForTheOpponentSJokerDecision',
  'bidding.doubleYourRewardCardThisRoundYour':
    'user.games.duel.bidding.doubleYourRewardCardThisRoundYour',
  'bidding.useJokerDoubleReward': 'user.games.duel.bidding.useJokerDoubleReward',
  'bidding.saveJoker': 'user.games.duel.bidding.saveJoker',
  'bidding.yourThirteenCards': 'user.games.duel.bidding.yourThirteenCards',
  'bidding.yourHand': 'user.games.duel.bidding.yourHand',
  'bidding.lockedWaitingForOpponent': 'user.games.duel.bidding.lockedWaitingForOpponent',
  'bidding.choosePrivatelyThenLockIn': 'user.games.duel.bidding.choosePrivatelyThenLockIn',
  'bidding.chooseABid': 'user.games.duel.bidding.chooseABid',
  'bidding.bid': 'user.games.duel.bidding.bid',
  'bidding.noCardSelected': 'user.games.duel.bidding.noCardSelected',
  'bidding.selected': 'user.games.duel.bidding.selected',
  'bidding.lockInBid': 'user.games.duel.bidding.lockInBid',
  'bidding.ifTimeExpiresBeforeYouLockYour':
    'user.games.duel.bidding.ifTimeExpiresBeforeYouLockYour',
  'bidding.played': 'user.games.duel.bidding.played',
  'bidding.bothPlayersHands': 'user.games.duel.bidding.bothPlayersHands',
  'bidding.opponentSHand': 'user.games.duel.bidding.opponentSHand',
  'bidding.opponentSThirteenCards': 'user.games.duel.bidding.opponentSThirteenCards',
  'bidding.greyCardsHaveAlreadyBeenPlayedSelections':
    'user.games.duel.bidding.greyCardsHaveAlreadyBeenPlayedSelections',
  'bidding.yourBidOpponentSBid': 'user.games.duel.bidding.yourBidOpponentSBid',
  'bidding.freshReward': 'user.games.duel.bidding.freshReward',
  'bidding.carriedIn': 'user.games.duel.bidding.carriedIn',
  'bidding.youUsedAJoker': 'user.games.duel.bidding.youUsedAJoker',
  'bidding.opponentUsedAJoker': 'user.games.duel.bidding.opponentUsedAJoker',
  'bidding.youWon': 'user.games.duel.bidding.youWon',
  'bidding.opponentWon': 'user.games.duel.bidding.opponentWon',
  'bidding.finalTiePoolDiscarded': 'user.games.duel.bidding.finalTiePoolDiscarded',
  'bidding.tieCarriedForward': 'user.games.duel.bidding.tieCarriedForward',
  'bidding.scoresAfterSettlement': 'user.games.duel.bidding.scoresAfterSettlement',
  'bidding.revealedBids': 'user.games.duel.bidding.revealedBids',
  'bidding.bidHistoryScrollHorizontally': 'user.games.duel.bidding.bidHistoryScrollHorizontally',
  'bidding.round2': 'user.games.duel.bidding.round2',
  'bidding.rewardStatus': 'user.games.duel.bidding.rewardStatus',
  'bidding.inCarriedPool': 'user.games.duel.bidding.inCarriedPool',
  'bidding.discarded2': 'user.games.duel.bidding.discarded2',
  'bidding.awardedToYou': 'user.games.duel.bidding.awardedToYou',
  'bidding.awardedToOpponent': 'user.games.duel.bidding.awardedToOpponent',
  'blackjack.blackjackTableRules': 'user.games.duel.blackjack.blackjackTableRules',
  'blackjack.oneRoundEvery30SecondsUpTo': 'user.games.duel.blackjack.oneRoundEvery30SecondsUpTo',
  'blackjack.every30Seconds5SecondsForSeating':
    'user.games.duel.blackjack.every30Seconds5SecondsForSeating',
  'blackjack.joiningReservesYourStakeUsingGameCredits':
    'user.games.duel.blackjack.joiningReservesYourStakeUsingGameCredits',
  'blackjack.sixDecksAndTheDealer': 'user.games.duel.blackjack.sixDecksAndTheDealer',
  'blackjack.sixCompleteDecksAreShuffledAnewEach':
    'user.games.duel.blackjack.sixCompleteDecksAreShuffledAnewEach',
  'blackjack.hitStandDoubleAndSplit': 'user.games.duel.blackjack.hitStandDoubleAndSplit',
  'blackjack.splitEqualValueCardsOnceIntoTwo':
    'user.games.duel.blackjack.splitEqualValueCardsOnceIntoTwo',
  'blackjack.returnsAndFees': 'user.games.duel.blackjack.returnsAndFees',
  'blackjack.grossReturnsAreZeroForALoss': 'user.games.duel.blackjack.grossReturnsAreZeroForALoss',
  'blackjack.disconnectionDoesNotPauseTheGameA':
    'user.games.duel.blackjack.disconnectionDoesNotPauseTheGameA',
  'blackjack.blackjackHistory': 'user.games.duel.blackjack.blackjackHistory',
  'blackjack.yourSettledTablesFromTheLast30':
    'user.games.duel.blackjack.yourSettledTablesFromTheLast30',
  'blackjack.backToList': 'user.games.duel.blackjack.backToList',
  'blackjack.systemCancellationAllOriginalPaymentsRefunded':
    'user.games.duel.blackjack.systemCancellationAllOriginalPaymentsRefunded',
  'blackjack.refunded': 'user.games.duel.blackjack.refunded',
  'blackjack.generalPaid': 'user.games.duel.blackjack.generalPaid',
  'blackjack.noGamesYet': 'user.games.duel.blackjack.noGamesYet',
  'blackjack.historyPages': 'user.games.duel.blackjack.historyPages',
  'blackjack.previous': 'user.games.duel.blackjack.previous',
  'blackjack.next': 'user.games.duel.blackjack.next',
  'blackjack.baseStake': 'user.games.duel.blackjack.baseStake',
  'blackjack.joinQueue': 'user.games.duel.blackjack.joinQueue',
  'blackjack.gameClosed': 'user.games.duel.blackjack.gameClosed',
  'blackjack.quickStakeSelection': 'user.games.duel.blackjack.quickStakeSelection',
  'blackjack.refreshingStakeConfiguration':
    'user.games.duel.blackjack.refreshingStakeConfiguration',
  'blackjack.chooseAStakeWithinTheCurrentLimits':
    'user.games.duel.blackjack.chooseAStakeWithinTheCurrentLimits',
  'blackjack.hit': 'user.games.duel.blackjack.hit',
  'blackjack.stand': 'user.games.duel.blackjack.stand',
  'blackjack.double': 'user.games.duel.blackjack.double',
  'blackjack.split': 'user.games.duel.blackjack.split',
  'blackjack.handActions': 'user.games.duel.blackjack.handActions',
  'blackjack.hand': 'user.games.duel.blackjack.hand',
  'blackjack.actionAcceptedWaitingForThisSecondS':
    'user.games.duel.blackjack.actionAcceptedWaitingForThisSecondS',
  'blackjack.yourDecisionsAreCompleteWaitingForThe':
    'user.games.duel.blackjack.yourDecisionsAreCompleteWaitingForThe',
  'blackjack.oneActionPerSecondUnfinishedHandsStand':
    'user.games.duel.blackjack.oneActionPerSecondUnfinishedHandsStand',
  'blackjack.blackjack': 'user.games.duel.blackjack.blackjack',
  'blackjack.oneTableYourOwnHandAgainstThe':
    'user.games.duel.blackjack.oneTableYourOwnHandAgainstThe',
  'blackjack.gameCenter': 'user.games.duel.blackjack.gameCenter',
  'blackjack.history': 'user.games.duel.blackjack.history',
  'blackjack.roundPhase': 'user.games.duel.blackjack.roundPhase',
  'blackjack.seating': 'user.games.duel.blackjack.seating',
  'blackjack.decisions': 'user.games.duel.blackjack.decisions',
  'blackjack.results': 'user.games.duel.blackjack.results',
  'blackjack.secondsRemaining': 'user.games.duel.blackjack.secondsRemaining',
  'blackjack.nextRound': 'user.games.duel.blackjack.nextRound',
  'blackjack.waiting': 'user.games.duel.blackjack.waiting',
  'blackjack.theTableIsWaiting': 'user.games.duel.blackjack.theTableIsWaiting',
  'blackjack.onePlayerIsEnoughNineSeatsMaximum':
    'user.games.duel.blackjack.onePlayerIsEnoughNineSeatsMaximum',
  'blackjack.tableCancelled': 'user.games.duel.blackjack.tableCancelled',
  'blackjack.everyStakeWasRefundedInItsOriginal':
    'user.games.duel.blackjack.everyStakeWasRefundedInItsOriginal',
  'blackjack.queueAndSeating': 'user.games.duel.blackjack.queueAndSeating',
  'blackjack.queuePosition': 'user.games.duel.blackjack.queuePosition',
  'blackjack.seated': 'user.games.duel.blackjack.seated',
  'blackjack.playingThisRound': 'user.games.duel.blackjack.playingThisRound',
  'blackjack.gameCreditsHeld': 'user.games.duel.blackjack.gameCreditsHeld',
  'blackjack.generalCredits': 'user.games.duel.blackjack.generalCredits',
  'blackjack.frozenFees': 'user.games.duel.blackjack.frozenFees',
  'blackjack.platform': 'user.games.duel.blackjack.platform',
  'blackjack.welfare': 'user.games.duel.blackjack.welfare',
  'blackjack.thursday': 'user.games.duel.blackjack.thursday',
  'blackjack.leaveAndRefundOriginalCredits':
    'user.games.duel.blackjack.leaveAndRefundOriginalCredits',
  'blackjack.yourPlaceRemainsValidAcrossRoundsYou':
    'user.games.duel.blackjack.yourPlaceRemainsValidAcrossRoundsYou',
  'blackjack.joinTheQueueAgainAfterThisTable':
    'user.games.duel.blackjack.joinTheQueueAgainAfterThisTable',
  'blackjack.yourNextHandIsYourChoice': 'user.games.duel.blackjack.yourNextHandIsYourChoice',
  'blackjack.step': 'user.games.duel.blackjack.step',
  'blackjack.totalFeesOnEachReturn': 'user.games.duel.blackjack.totalFeesOnEachReturn',
  'blackjack.joiningReservesYourStakeGameCreditsFirst':
    'user.games.duel.blackjack.joiningReservesYourStakeGameCreditsFirst',
  'blackjack.presetEmotes': 'user.games.duel.blackjack.presetEmotes',
  'blackjack.confirmPreviousAction': 'user.games.duel.blackjack.confirmPreviousAction',
  'blackjack.cardMasterLeaderboard': 'user.games.duel.blackjack.cardMasterLeaderboard',
  'blackjack.profitLeaderboard': 'user.games.duel.blackjack.profitLeaderboard',
  'blackjack.spades': 'user.games.duel.blackjack.spades',
  'blackjack.hearts': 'user.games.duel.blackjack.hearts',
  'blackjack.dealerHoleCard': 'user.games.duel.blackjack.dealerHoleCard',
  'blackjack.blackjack2': 'user.games.duel.blackjack.blackjack2',
  'blackjack.bust': 'user.games.duel.blackjack.bust',
  'blackjack.stood': 'user.games.duel.blackjack.stood',
  'blackjack.deciding': 'user.games.duel.blackjack.deciding',
  'blackjack.soft': 'user.games.duel.blackjack.soft',
  'blackjack.blackjackTable': 'user.games.duel.blackjack.blackjackTable',
  'blackjack.dealer': 'user.games.duel.blackjack.dealer',
  'blackjack.standsOnSoft17': 'user.games.duel.blackjack.standsOnSoft17',
  'blackjack.holeCardOpensWhenEveryoneFinishes':
    'user.games.duel.blackjack.holeCardOpensWhenEveryoneFinishes',
  'blackjack.points': 'user.games.duel.blackjack.points',
  'blackjack.waitingToDeal': 'user.games.duel.blackjack.waitingToDeal',
  'blackjack.yourHands': 'user.games.duel.blackjack.yourHands',
  'blackjack.anonymousCardPlayer': 'user.games.duel.blackjack.anonymousCardPlayer',
  'blackjack.yourHand': 'user.games.duel.blackjack.yourHand',
  'blackjack.otherSeats': 'user.games.duel.blackjack.otherSeats',
  'blackjack.seat': 'user.games.duel.blackjack.seat',
  'blackjack.open': 'user.games.duel.blackjack.open',
  'blackjack.autoStand': 'user.games.duel.blackjack.autoStand',
  'blackjack.hello': 'user.games.duel.blackjack.hello',
  'blackjack.nice': 'user.games.duel.blackjack.nice',
  'blackjack.wow': 'user.games.duel.blackjack.wow',
  'blackjack.goodLuck': 'user.games.duel.blackjack.goodLuck',
  'blackjack.thanks': 'user.games.duel.blackjack.thanks',
  'blackjack.gG': 'user.games.duel.blackjack.gG',
  'blackjack.win': 'user.games.duel.blackjack.win',
  'blackjack.loss': 'user.games.duel.blackjack.loss',
  'blackjack.push': 'user.games.duel.blackjack.push',
  'blackjack.settlementDetails': 'user.games.duel.blackjack.settlementDetails',
  'blackjack.tableResults': 'user.games.duel.blackjack.tableResults',
  'blackjack.yourResults': 'user.games.duel.blackjack.yourResults',
  'blackjack.stake': 'user.games.duel.blackjack.stake',
  'blackjack.grossReturn': 'user.games.duel.blackjack.grossReturn',
  'blackjack.platformFee': 'user.games.duel.blackjack.platformFee',
  'blackjack.welfarePool': 'user.games.duel.blackjack.welfarePool',
  'blackjack.thursdayPool': 'user.games.duel.blackjack.thursdayPool',
  'blackjack.generalCreditsPaid': 'user.games.duel.blackjack.generalCreditsPaid',
  'blackjack.allNormalReturnsAreGeneralCreditsIncluding':
    'user.games.duel.blackjack.allNormalReturnsAreGeneralCreditsIncluding',
  'common.soundOn': 'user.games.duel.common.soundOn',
  'common.soundOff': 'user.games.duel.common.soundOff',
  'common.musicOn': 'user.games.duel.common.musicOn',
  'common.musicOff': 'user.games.duel.common.musicOff',
  'common.someAudioCouldNotLoadSwitchIt': 'user.games.duel.common.someAudioCouldNotLoadSwitchIt',
  'common.theResponseIsUnconfirmedRetryTheSame':
    'user.games.duel.common.theResponseIsUnconfirmedRetryTheSame',
  'common.matchingConditionsChangedReviewThemAndTry':
    'user.games.duel.common.matchingConditionsChangedReviewThemAndTry',
  'common.theGameStateChangedContinueWithThe':
    'user.games.duel.common.theGameStateChangedContinueWithThe',
  'common.insufficientAvailableCreditsCheckYourWallets':
    'user.games.duel.common.insufficientAvailableCreditsCheckYourWallets',
  'common.newGamesAreUnavailableExistingGamesFollow':
    'user.games.duel.common.newGamesAreUnavailableExistingGamesFollow',
  'common.tooManyRequestsRightNowTryAgain':
    'user.games.duel.common.tooManyRequestsRightNowTryAgain',
  'common.thisAccountCannotPerformThisActionRefresh':
    'user.games.duel.common.thisAccountCannotPerformThisActionRefresh',
  'common.aValidResponseCouldNotBeObtained':
    'user.games.duel.common.aValidResponseCouldNotBeObtained',
  'common.confirming': 'user.games.duel.common.confirming',
  'common.retrySameRequest': 'user.games.duel.common.retrySameRequest',
  'common.refreshState': 'user.games.duel.common.refreshState',
  'common.deletedAccount': 'user.games.duel.common.deletedAccount',
  'common.anonymousPlayer': 'user.games.duel.common.anonymousPlayer',
  'common.welfare': 'user.games.duel.common.welfare',
  'common.thursday': 'user.games.duel.common.thursday',
  'common.entryTicket': 'user.games.duel.common.entryTicket',
  'common.gameCreditsAreUsedFirstThenGeneral':
    'user.games.duel.common.gameCreditsAreUsedFirstThenGeneral',
  'common.serverRestarted': 'user.games.duel.common.serverRestarted',
  'common.accountUnavailable': 'user.games.duel.common.accountUnavailable',
  'common.aPlayerSurrendered': 'user.games.duel.common.aPlayerSurrendered',
  'common.targetReached': 'user.games.duel.common.targetReached',
  'common.bothPlayersOverloaded': 'user.games.duel.common.bothPlayersOverloaded',
  'common.gameCompleted': 'user.games.duel.common.gameCompleted',
  'common.yourEntry': 'user.games.duel.common.yourEntry',
  'common.principalReturnedRefund': 'user.games.duel.common.principalReturnedRefund',
  'common.prizeGeneralCredits': 'user.games.duel.common.prizeGeneralCredits',
  'common.gameFeesPlatformWelfareThursday':
    'user.games.duel.common.gameFeesPlatformWelfareThursday',
  'common.readingTheLogDoesNotPauseThe': 'user.games.duel.common.readingTheLogDoesNotPauseThe',
  'common.round': 'user.games.duel.common.round',
  'common.automaticTimeoutAction': 'user.games.duel.common.automaticTimeoutAction',
  'common.noSettledRoundsYet': 'user.games.duel.common.noSettledRoundsYet',
  'common.refreshFirstPage': 'user.games.duel.common.refreshFirstPage',
  'common.nextPage': 'user.games.duel.common.nextPage',
  'common.yourCompleteGamesFromTheLast30': 'user.games.duel.common.yourCompleteGamesFromTheLast30',
  'common.firstPage': 'user.games.duel.common.firstPage',
  'common.verifyRandomness': 'user.games.duel.common.verifyRandomness',
  'common.seedDisclosed': 'user.games.duel.common.seedDisclosed',
  'common.openingCommitmentLocked': 'user.games.duel.common.openingCommitmentLocked',
  'common.proof': 'user.games.duel.common.proof',
  'common.loadingProof': 'user.games.duel.common.loadingProof',
  'common.theProofIsTemporarilyUnavailable':
    'user.games.duel.common.theProofIsTemporarilyUnavailable',
  'common.retry': 'user.games.duel.common.retry',
  'common.thisGamePredatesRandomProofsAndCannot':
    'user.games.duel.common.thisGamePredatesRandomProofsAndCannot',
  'common.thisGameHasEndedCheckTheSeed': 'user.games.duel.common.thisGameHasEndedCheckTheSeed',
  'common.theServerKeepsTheSeedSecretUntil':
    'user.games.duel.common.theServerKeepsTheSeedSecretUntil',
  'common.openingCommitmentSHA256': 'user.games.duel.common.openingCommitmentSHA256',
  'common.disclosedSeed': 'user.games.duel.common.disclosedSeed',
  'common.verifying': 'user.games.duel.common.verifying',
  'common.verifyLocally': 'user.games.duel.common.verifyLocally',
  'common.downloadProof': 'user.games.duel.common.downloadProof',
  'common.saveCommitment': 'user.games.duel.common.saveCommitment',
  'common.verifiedCommitmentMatchesAllRecordedDrawsReproduce':
    'user.games.duel.common.verifiedCommitmentMatchesAllRecordedDrawsReproduce',
  'common.verificationFailedTheProofIsInconsistentOr':
    'user.games.duel.common.verificationFailedTheProofIsInconsistentOr',
  'common.thisVerifiesTheConsistencyOfRandomDraws':
    'user.games.duel.common.thisVerifiesTheConsistencyOfRandomDraws',
  'likes.liveScoresAndEnergy': 'user.games.duel.likes.liveScoresAndEnergy',
  'likes.energy': 'user.games.duel.likes.energy',
  'likes.base': 'user.games.duel.likes.base',
  'likes.characterPassive': 'user.games.duel.likes.characterPassive',
  'likes.skillDecay': 'user.games.duel.likes.skillDecay',
  'likes.counter': 'user.games.duel.likes.counter',
  'likes.conditional': 'user.games.duel.likes.conditional',
  'likes.likesAdjustment': 'user.games.duel.likes.likesAdjustment',
  'likes.passive': 'user.games.duel.likes.passive',
  'likes.awarded': 'user.games.duel.likes.awarded',
  'likes.sUBSCRIPTIONUSAGE': 'user.games.duel.likes.sUBSCRIPTIONUSAGE',
  'likes.bothPlayers': 'user.games.duel.likes.bothPlayers',
  'likes.presentationProgress': 'user.games.duel.likes.presentationProgress',
  'likes.sHAREDBATTERY': 'user.games.duel.likes.sHAREDBATTERY',
  'likes.oVERLOAD': 'user.games.duel.likes.oVERLOAD',
  'likes.rECHARGING': 'user.games.duel.likes.rECHARGING',
  'likes.resolving': 'user.games.duel.likes.resolving',
  'likes.sTUNBUFF': 'user.games.duel.likes.sTUNBUFF',
  'likes.eFFECTAPPLIED': 'user.games.duel.likes.eFFECTAPPLIED',
  'likes.pARTLYRESISTED': 'user.games.duel.likes.pARTLYRESISTED',
  'likes.fULLYRESISTED': 'user.games.duel.likes.fULLYRESISTED',
  'likes.applied': 'user.games.duel.likes.applied',
  'likes.resisted': 'user.games.duel.likes.resisted',
  'likes.harnessBonusLike1': 'user.games.likes.balance.harnessLikeGain',
  'likes.cleansingApplied': 'user.games.duel.likes.cleansingApplied',
  'likes.resourcesReplenished': 'user.games.duel.likes.resourcesReplenished',
  'likes.subscriptionReplenished': 'user.games.duel.likes.subscriptionReplenished',
  'likes.followUp': 'user.games.duel.likes.followUp',
  'likes.applied2': 'user.games.duel.likes.applied2',
  'likes.derivedEffect': 'user.games.duel.likes.derivedEffect',
  'likes.followUp2': 'user.games.duel.likes.followUp2',
  'likes.notCast': 'user.games.duel.likes.notCast',
  'likes.buffsAndStates': 'user.games.duel.likes.buffsAndStates',
  'likes.nextRound': 'user.games.duel.likes.nextRound',
  'likes.rounds': 'user.games.duel.likes.rounds',
  'likes.skillSlotsAndResourceClocks': 'user.games.duel.likes.skillSlotsAndResourceClocks',
  'likes.hidden': 'user.games.duel.likes.hidden',
  'likes.empty': 'user.games.duel.likes.empty',
  'likes.burstResets': 'user.games.duel.likes.burstResets',
  'likes.clockIdle': 'user.games.duel.likes.clockIdle',
  'likes.roundsFromNow': 'user.games.duel.likes.roundsFromNow',
  'likes.totalImageResets': 'user.games.duel.likes.totalImageResets',
  'likes.distill': 'user.games.duel.likes.distill',
  'likes.progress': 'user.games.duel.likes.progress',
  'likes.seat': 'user.games.duel.likes.seat',
  'likes.buffsAndStatesBeforeAfter': 'user.games.duel.likes.buffsAndStatesBeforeAfter',
  'likes.before': 'user.games.duel.likes.before',
  'likes.after': 'user.games.duel.likes.after',
  'likes.none': 'user.games.duel.likes.none',
  'likes.roundsLeft': 'user.games.duel.likes.roundsLeft',
  'likes.activeFromRound': 'user.games.duel.likes.activeFromRound',
  'likes.sPEEDMODEFULLTHROTTLE': 'user.games.duel.likes.sPEEDMODEFULLTHROTTLE',
  'likes.cASTINTERRUPTED': 'user.games.duel.likes.cASTINTERRUPTED',
  'likes.tARGETREACHED': 'user.games.duel.likes.tARGETREACHED',
  'likes.lIKESSURGE': 'user.games.duel.likes.lIKESSURGE',
  'likes.sKILLCAST': 'user.games.duel.likes.sKILLCAST',
  'likes.fOLLOWUP': 'user.games.duel.likes.fOLLOWUP',
  'likes.cASTS': 'user.games.duel.likes.cASTS',
  'likes.lIKESAWARDED': 'user.games.duel.likes.lIKESAWARDED',
  'likes.likesChange': 'user.games.duel.likes.likesChange',
  'likes.alwaysActiveCharacterPassive': 'user.games.duel.likes.alwaysActiveCharacterPassive',
  'likes.multimodalMastery': 'user.games.duel.likes.multimodalMastery',
  'likes.subscriptionsIncludeImageQuotaThatReplenishesWith':
    'user.games.duel.likes.subscriptionsIncludeImageQuotaThatReplenishesWith',
  'likes.sOTAPressure': 'user.games.duel.likes.sOTAPressure',
  'likes.aMainSkillWithPositiveOriginalBase':
    'user.games.duel.likes.aMainSkillWithPositiveOriginalBase',
  'likes.worldKnowledge': 'user.games.duel.likes.worldKnowledge',
  'likes.basicAttacksGain1BaseLikeIncluding':
    'user.games.duel.likes.basicAttacksGain1BaseLikeIncluding',
  'likes.securityShield': 'user.games.duel.likes.securityShield',
  'likes.message25EffectResistancePlus25WhenBehind':
    'user.games.duel.likes.message25EffectResistancePlus25WhenBehind',
  'likes.bigBlueFish': 'user.games.duel.likes.bigBlueFish',
  'likes.noSubscriptionQuota25EffectHitPlus':
    'user.games.duel.likes.noSubscriptionQuota25EffectHitPlus',
  'likes.state': 'user.games.duel.likes.state',
  'likes.debuff': 'user.games.duel.likes.debuff',
  'likes.buff': 'user.games.duel.likes.buff',
  'likes.preset': 'user.games.duel.likes.preset',
  'likes.customPresets': 'user.games.duel.likes.customPresets',
  'likes.save10LoadoutsToYourAccountAcross':
    'user.games.duel.likes.save10LoadoutsToYourAccountAcross',
  'likes.loadingCustomPresets': 'user.games.duel.likes.loadingCustomPresets',
  'likes.customPresetsCouldNotBeLoadedYou':
    'user.games.duel.likes.customPresetsCouldNotBeLoadedYou',
  'likes.retryLoading': 'user.games.duel.likes.retryLoading',
  'likes.thisLoadoutDoesNotMeetTheRules': 'user.games.duel.likes.thisLoadoutDoesNotMeetTheRules',
  'likes.unavailable': 'user.games.duel.likes.unavailable',
  'likes.name': 'user.games.duel.likes.name',
  'likes.saveName': 'user.games.duel.likes.saveName',
  'likes.clearName': 'user.games.duel.likes.clearName',
  'likes.useUpTo20CharactersWithoutLine': 'user.games.duel.likes.useUpTo20CharactersWithoutLine',
  'likes.mode': 'user.games.duel.likes.mode',
  'likes.quick': 'user.games.duel.likes.quick',
  'likes.standard': 'user.games.duel.likes.standard',
  'likes.character': 'user.games.duel.likes.character',
  'likes.none2': 'user.games.duel.likes.none2',
  'likes.thisPresetNeedsRepairEditTheLoadout':
    'user.games.duel.likes.thisPresetNeedsRepairEditTheLoadout',
  'likes.emptySlot': 'user.games.duel.likes.emptySlot',
  'likes.load': 'user.games.duel.likes.load',
  'likes.overwrite': 'user.games.duel.likes.overwrite',
  'likes.saveTo': 'user.games.duel.likes.saveTo',
  'likes.checkCurrentPresets': 'user.games.duel.likes.checkCurrentPresets',
  'likes.retrySavingCustomPresets': 'user.games.duel.likes.retrySavingCustomPresets',
  'likes.saving': 'user.games.duel.likes.saving',
  'likes.presetSaved': 'user.games.duel.likes.presetSaved',
  'likes.customPresetsChangedElsewhereCheckTheRefreshed':
    'user.games.duel.likes.customPresetsChangedElsewhereCheckTheRefreshed',
  'likes.savingCouldNotBeConfirmedCheckCurrent':
    'user.games.duel.likes.savingCouldNotBeConfirmedCheckCurrent',
  'likes.thePresetWasNotSavedCheckYour': 'user.games.duel.likes.thePresetWasNotSavedCheckYour',
  'likes.presetsCouldNotBeRefreshedRetryLoading':
    'user.games.duel.likes.presetsCouldNotBeRefreshedRetryLoading',
  'likes.loadedYouHaveNotJoinedMatchmaking':
    'user.games.duel.likes.loadedYouHaveNotJoinedMatchmaking',
  'likes.overwriteCustomPresets': 'user.games.duel.likes.overwriteCustomPresets',
  'likes.thisReplacesWithYourCurrentLoadout':
    'user.games.duel.likes.thisReplacesWithYourCurrentLoadout',
  'likes.confirmOverwrite': 'user.games.duel.likes.confirmOverwrite',
  'likes.cancel': 'user.games.duel.likes.cancel',
  'likes.subAPI': 'user.games.duel.likes.subAPI',
  'likes.subscription': 'user.games.duel.likes.subscription',
  'likes.gold': 'user.games.duel.likes.gold',
  'likes.fieldGuide': 'user.games.duel.likes.fieldGuide',
  'likes.quickMode': 'user.games.duel.likes.quickMode',
  'likes.standardMode': 'user.games.duel.likes.standardMode',
  'likes.readingDoesNotPauseALiveGame': 'user.games.duel.likes.readingDoesNotPauseALiveGame',
  'likes.guideNavigation': 'user.games.duel.likes.guideNavigation',
  'likes.findAnEntry': 'user.games.duel.likes.findAnEntry',
  'likes.backToPreviousEntry': 'user.games.duel.likes.backToPreviousEntry',
  'likes.skillVersion': 'user.games.duel.likes.skillVersion',
  'likes.baseCostsAndUses': 'user.games.duel.likes.baseCostsAndUses',
  'likes.successfulUses': 'user.games.duel.likes.successfulUses',
  'likes.distillationCasts': 'user.games.duel.likes.distillationCasts',
  'likes.unlimited': 'user.games.duel.likes.unlimited',
  'likes.cannotBeDistilled': 'user.games.duel.likes.cannotBeDistilled',
  'likes.theseAreOriginalCostsCurrentPassivesBuffs':
    'user.games.duel.likes.theseAreOriginalCostsCurrentPassivesBuffs',
  'likes.distillationUsesItsOwnCostsAboveWithout':
    'user.games.duel.likes.distillationUsesItsOwnCostsAboveWithout',
  'likes.relatedExplanations': 'user.games.duel.likes.relatedExplanations',
  'likes.currentHarnessAddsBaseLikes': 'user.games.duel.likes.currentHarnessAddsBaseLikes',
  'likes.original': 'user.games.duel.likes.original',
  'likes.distilled': 'user.games.duel.likes.distilled',
  'likes.entryNotFound': 'user.games.duel.likes.entryNotFound',
  'likes.distilledII': 'user.games.duel.likes.distilledII',
  'likes.distilledI': 'user.games.duel.likes.distilledI',
  'likes.originalDistilledII': 'user.games.duel.likes.originalDistilledII',
  'likes.eachMainOrPreselectedExtraSkillWith':
    'user.games.duel.likes.eachMainOrPreselectedExtraSkillWith',
  'likes.eachMainOrPreselectedExtraSkillWith2':
    'user.games.duel.likes.eachMainOrPreselectedExtraSkillWith2',
  'likes.eachMainAndPreselectedExtraSkillCosts':
    'user.games.duel.likes.eachMainAndPreselectedExtraSkillCosts',
  'likes.eachNonBasicMainOrPreselectedExtra':
    'user.games.duel.likes.eachNonBasicMainOrPreselectedExtra',
  'likes.eachMainAndPreselectedExtraSkillSaves':
    'user.games.duel.likes.eachMainAndPreselectedExtraSkillSaves',
  'likes.aPIOnlySkillsMixedSkillsExplicitlySet':
    'user.games.duel.likes.aPIOnlySkillsMixedSkillsExplicitlySet',
  'likes.duringTheNextRoundEachMainAnd': 'user.games.duel.likes.duringTheNextRoundEachMainAnd',
  'likes.startsNextRoundAndLastsRoundsTriggered':
    'user.games.duel.likes.startsNextRoundAndLastsRoundsTriggered',
  'likes.reapplyingAddsRoundsAfterThisRoundS':
    'user.games.duel.likes.reapplyingAddsRoundsAfterThisRoundS',
  'likes.reapplyingRefreshesTheDurationToRoundsWithout':
    'user.games.duel.likes.reapplyingRefreshesTheDurationToRoundsWithout',
  'likes.distinctEntriesAndSeparatelyNamedOriginalDistilled':
    'user.games.duel.likes.distinctEntriesAndSeparatelyNamedOriginalDistilled',
  'likes.flash': 'user.games.duel.likes.flash',
  'likes.pro': 'user.games.duel.likes.pro',
  'likes.catgirlRoleplayHelloWorldPoliteReplyFormatted':
    'user.games.duel.likes.catgirlRoleplayHelloWorldPoliteReplyFormatted',
  'likes.distilled2': 'user.games.duel.likes.distilled2',
  'likes.original2': 'user.games.duel.likes.original2',
  'likes.eachLayerSavesKTokensOnUp': 'user.games.duel.likes.eachLayerSavesKTokensOnUp',
  'likes.layersEarnedByTriggeredFlashAreImmediately':
    'user.games.duel.likes.layersEarnedByTriggeredFlashAreImmediately',
  'likes.newLayersMergeWithThisCacheAcquiring':
    'user.games.duel.likes.newLayersMergeWithThisCacheAcquiring',
  'likes.andNoFollowUpProgress': 'user.games.duel.likes.andNoFollowUpProgress',
  'likes.ordinaryLayersExpireAtRoundEndIf':
    'user.games.duel.likes.ordinaryLayersExpireAtRoundEndIf',
  'likes.layersMadePersistentBySurviveExpirySkips':
    'user.games.duel.likes.layersMadePersistentBySurviveExpirySkips',
  'likes.eachLayerSavesEnergyOnMainAnd': 'user.games.duel.likes.eachLayerSavesEnergyOnMainAnd',
  'likes.newLayersStartNextRoundAndPersist':
    'user.games.duel.likes.newLayersStartNextRoundAndPersist',
  'likes.everyLayersAreSpentToAttemptOriginal':
    'user.games.duel.likes.everyLayersAreSpentToAttemptOriginal',
  'likes.successfulFollowUpsGrantProgressAndOriginal':
    'user.games.duel.likes.successfulFollowUpsGrantProgressAndOriginal',
  'likes.stunnedForRoundStartingNextRoundSkills':
    'user.games.duel.likes.stunnedForRoundStartingNextRoundSkills',
  'likes.canBeCleansedReapplyingRefreshesItsDuration':
    'user.games.duel.likes.canBeCleansedReapplyingRefreshesItsDuration',
  'likes.insufficientImageQuotaAlsoCausesOverloadThe': 'user.games.likes.balance.imageFailure',
  'likes.failedCastingFromInsufficientEnergyOrTokens':
    'user.games.duel.likes.failedCastingFromInsufficientEnergyOrTokens',
  'likes.cannotBeCleansedOrDispelledSubscriptionClocks':
    'user.games.duel.likes.cannotBeCleansedOrDispelledSubscriptionClocks',
  'likes.baseTokenAndEnergyCostsAreMultiplied': 'user.games.likes.balance.speedCosts',
  'likes.baseTokenAndEnergyCostsAreMultiplied2':
    'user.games.duel.likes.baseTokenAndEnergyCostsAreMultiplied2',
  'likes.appliesToMainSkillsDistillationExtraSkills':
    'user.games.duel.likes.appliesToMainSkillsDistillationExtraSkills',
  'likes.fromNextRoundSubscriptionBurstTotalAnd':
    'user.games.duel.likes.fromNextRoundSubscriptionBurstTotalAnd',
  'likes.upgradesResetsAndClocksContinueCleansingRestores':
    'user.games.duel.likes.upgradesResetsAndClocksContinueCleansingRestores',
  'likes.eachLayerAddsBaseEnergyToSkills': 'user.games.duel.likes.eachLayerAddsBaseEnergyToSkills',
  'likes.canBeCleansedLosesOneLayerAt': 'user.games.duel.likes.canBeCleansedLosesOneLayerAt',
  'likes.eachLayerReducesBaseLikesByFor': 'user.games.duel.likes.eachLayerReducesBaseLikesByFor',
  'likes.lastsUntilCleansedOriginalAndDistilledStacks':
    'user.games.duel.likes.lastsUntilCleansedOriginalAndDistilledStacks',
  'likes.startingNextRoundEverySuccessfulSkillLoses':
    'user.games.duel.likes.startingNextRoundEverySuccessfulSkillLoses',
  'likes.doesNotExpireNaturallyAndCanBe': 'user.games.duel.likes.doesNotExpireNaturallyAndCanBe',
  'likes.skillsWithPositiveBaseTokenCostEnergy':
    'user.games.duel.likes.skillsWithPositiveBaseTokenCostEnergy',
  'likes.thisBonusIsPartOfTheBase': 'user.games.duel.likes.thisBonusIsPartOfTheBase',
  'likes.eachDistinctDebuffSuccessfullyAppliedToThe': 'user.games.likes.balance.harnessReward',
  'likes.eachDistinctNegativeEffectASuccessfulSkill':
    'user.games.duel.likes.eachDistinctNegativeEffectASuccessfulSkill',
  'likes.applicationAtTheCapStillCountsThe':
    'user.games.duel.likes.applicationAtTheCapStillCountsThe',
  'likes.eachSuccessfulBasicAttackGrantsExtraLike':
    'user.games.duel.likes.eachSuccessfulBasicAttackGrantsExtraLike',
  'likes.theExtraLikesBypassAdditiveBuffsAnd':
    'user.games.duel.likes.theExtraLikesBypassAdditiveBuffsAnd',
  'likes.eachSuccessfulNonBasicSkillCastBy':
    'user.games.duel.likes.eachSuccessfulNonBasicSkillCastBy',
  'likes.trialQuotaPaysFinalTokenCostsBefore':
    'user.games.duel.likes.trialQuotaPaysFinalTokenCostsBefore',
  'likes.eachSuccessfulSkillLabelledAPIOnlyGrants':
    'user.games.duel.likes.eachSuccessfulSkillLabelledAPIOnlyGrants',
  'likes.mixedSkillsDoNotQualifyEvenWhen': 'user.games.duel.likes.mixedSkillsDoNotQualifyEvenWhen',
  'likes.subscriptionUpgradesCostLessGoldToA':
    'user.games.duel.likes.subscriptionUpgradesCostLessGoldToA',
  'likes.whenStrictlyBehindOnLikesAtRound':
    'user.games.duel.likes.whenStrictlyBehindOnLikesAtRound',
  'likes.theConditionIsNotReevaluatedDuringThe':
    'user.games.duel.likes.theConditionIsNotReevaluatedDuringThe',
  'likes.allSkillsSaveKBaseTokensTo': 'user.games.duel.likes.allSkillsSaveKBaseTokensTo',
  'likes.castThePreviouslyLearnedTemplateFirstThen':
    'user.games.duel.likes.castThePreviouslyLearnedTemplateFirstThen',
  'likes.aNewTemplateStartsAtDistilledI': 'user.games.duel.likes.aNewTemplateStartsAtDistilledI',
  'likes.everyTemplateUsesDistillationSOwnToken':
    'user.games.duel.likes.everyTemplateUsesDistillationSOwnToken',
  'likes.gainBaseLikes': 'user.games.duel.likes.gainBaseLikes',
  'likes.onASuccessfulCastGainOneLayer': 'user.games.duel.likes.onASuccessfulCastGainOneLayer',
  'likes.alsoGainOneLayerOf': 'user.games.duel.likes.alsoGainOneLayerOf',
  'likes.afterEachSuccessThisVersionSNext':
    'user.games.duel.likes.afterEachSuccessThisVersionSNext',
  'likes.afterCleansingAndDispellingMakeTheCache':
    'user.games.duel.likes.afterCleansingAndDispellingMakeTheCache',
  'likes.gainForRoundsStartingNextRound': 'user.games.duel.likes.gainForRoundsStartingNextRound',
  'likes.giveTheOpponentForRoundsStartingNext':
    'user.games.duel.likes.giveTheOpponentForRoundsStartingNext',
  'likes.yourDebuffs': 'user.games.duel.likes.yourDebuffs',
  'likes.theOpponentSBuffs': 'user.games.duel.likes.theOpponentSBuffs',
  'likes.yourDebuffsOrTheOpponentSBuffs': 'user.games.duel.likes.yourDebuffsOrTheOpponentSBuffs',
  'likes.randomlyRemove': 'user.games.duel.likes.randomlyRemove',
  'likes.chooseAndRemove': 'user.games.duel.likes.chooseAndRemove',
  'likes.upToOfRemovalHappensBeforeEither':
    'user.games.duel.likes.upToOfRemovalHappensBeforeEither',
  'likes.doesNotRemoveEnergyTokensOrImage':
    'user.games.duel.likes.doesNotRemoveEnergyTokensOrImage',
  'likes.gainLayersOfWhichMayTriggerFollow':
    'user.games.duel.likes.gainLayersOfWhichMayTriggerFollow',
  'likes.preselectUpToExtraSkillInThis': 'user.games.duel.likes.preselectUpToExtraSkillInThis',
  'likes.ifThisSkillSucceedsAndTheOpponent':
    'user.games.duel.likes.ifThisSkillSucceedsAndTheOpponent',
  'likes.your': 'user.games.duel.likes.your',
  'likes.theOpponentS': 'user.games.duel.likes.theOpponentS',
  'likes.gainAdditionalLikesIfSelectedMainSkill':
    'user.games.duel.likes.gainAdditionalLikesIfSelectedMainSkill',
  'likes.gainExtraLikesIfYouSuccessfullyCast':
    'user.games.duel.likes.gainExtraLikesIfYouSuccessfullyCast',
  'likes.gainExtraLikesWhenSharedEnergyAfter':
    'user.games.duel.likes.gainExtraLikesWhenSharedEnergyAfter',
  'likes.afterSkillPaymentDrainKOfThe': 'user.games.duel.likes.afterSkillPaymentDrainKOfThe',
  'likes.overloadYourselfFor1RoundStartingNext': 'user.games.likes.balance.selfOverload',
  'likes.becomeAffectedByForRoundStartingNext':
    'user.games.duel.likes.becomeAffectedByForRoundStartingNext',
  'likes.gainLayersOfFromNextRoundEach': 'user.games.duel.likes.gainLayersOfFromNextRoundEach',
  'likes.applyLayersOfToYourselfAndTo': 'user.games.duel.likes.applyLayersOfToYourselfAndTo',
  'likes.giveTheOpponentLayersOfPlusWhen': 'user.games.duel.likes.giveTheOpponentLayersOfPlusWhen',
  'likes.afterMainExtraAndFlashPaymentsGain':
    'user.games.duel.likes.afterMainExtraAndFlashPaymentsGain',
  'likes.convertAllOriginalProCacheIncludingThis':
    'user.games.duel.likes.convertAllOriginalProCacheIncludingThis',
  'likes.afterAllSkillPaymentsAndBurstDrains':
    'user.games.duel.likes.afterAllSkillPaymentsAndBurstDrains',
  'likes.toggleYourAtRoundEndForThe': 'user.games.duel.likes.toggleYourAtRoundEndForThe',
  'likes.lastingRound': 'user.games.duel.likes.lastingRound',
  'likes.lastingUntilCleansed': 'user.games.duel.likes.lastingUntilCleansed',
  'likes.giveTheOpponentStartingNextRound':
    'user.games.duel.likes.giveTheOpponentStartingNextRound',
  'likes.alsoGainLayersOf': 'user.games.duel.likes.alsoGainLayersOf',
  'likes.alwaysActiveWithoutEquipmentAlongsideHarnessPassives':
    'user.games.duel.likes.alwaysActiveWithoutEquipmentAlongsideHarnessPassives',
  'likes.classification': 'user.games.duel.likes.classification',
  'likes.eachHostileLayerChecksHitIndependentlySelf':
    'user.games.duel.likes.eachHostileLayerChecksHitIndependentlySelf',
  'likes.atLeastOneSuccessfulLayerOfA': 'user.games.duel.likes.atLeastOneSuccessfulLayerOfA',
  'likes.addsActiveSlotsForTotalFixedPassives':
    'user.games.duel.likes.addsActiveSlotsForTotalFixedPassives',
  'likes.skillsCostingEnergyAndTokensWithPositive':
    'user.games.duel.likes.skillsCostingEnergyAndTokensWithPositive',
  'likes.eachSuccessfulDistinctHostileDebuffGrants1': 'user.games.likes.balance.harnessBrief',
  'likes.eachAppliedDebuffAddsFanaticismLayers':
    'user.games.duel.likes.eachAppliedDebuffAddsFanaticismLayers',
  'likes.successfulBasicsGainLikesIncludingFlashFollow':
    'user.games.duel.likes.successfulBasicsGainLikesIncludingFlashFollow',
  'likes.eachSuccessfulOpponentNonBasicGrantsK':
    'user.games.duel.likes.eachSuccessfulOpponentNonBasicGrantsK',
  'likes.successfulAPIOnlySkillsGainLikes':
    'user.games.duel.likes.successfulAPIOnlySkillsGainLikes',
  'likes.subscriptionUpgradesSaveGold': 'user.games.duel.likes.subscriptionUpgradesSaveGold',
  'likes.whenBehindAtRoundStartSkillsWith':
    'user.games.duel.likes.whenBehindAtRoundStartSkillsWith',
  'likes.baseSkillTokensKMinimum0': 'user.games.duel.likes.baseSkillTokensKMinimum0',
  'likes.matchingBasicsSaveKTokensPerLayer':
    'user.games.duel.likes.matchingBasicsSaveKTokensPerLayer',
  'likes.automaticallySkipShoppingAndCastingWhileRecovering':
    'user.games.duel.likes.automaticallySkipShoppingAndCastingWhileRecovering',
  'likes.baseEnergyAndTokens25Rounded': 'user.games.likes.balance.speedBrief',
  'likes.baseEnergyAndTokensLikes': 'user.games.duel.likes.baseEnergyAndTokensLikes',
  'likes.qualifyingAPICastsSaveKTokens': 'user.games.duel.likes.qualifyingAPICastsSaveKTokens',
  'likes.castYourLearnedTemplateThenLearnThe':
    'user.games.duel.likes.castYourLearnedTemplateThenLearnThe',
  'likes.cacheSavesKTokensPerLayerUp': 'user.games.duel.likes.cacheSavesKTokensPerLayerUp',
  'likes.gainFlashCacheAndFollowUpProgress':
    'user.games.duel.likes.gainFlashCacheAndFollowUpProgress',
  'likes.eachSuccessReducesFutureBaseLikesBy':
    'user.games.duel.likes.eachSuccessReducesFutureBaseLikesBy',
  'likes.makeExistingCachePersistent': 'user.games.duel.likes.makeExistingCachePersistent',
  'likes.gainLikesPerEligibleCastForRounds':
    'user.games.duel.likes.gainLikesPerEligibleCastForRounds',
  'likes.opponentLosesLikesPerEligibleCastFor':
    'user.games.duel.likes.opponentLosesLikesPerEligibleCastFor',
  'likes.saveEnergyPerChosenSkillForRounds':
    'user.games.duel.likes.saveEnergyPerChosenSkillForRounds',
  'likes.opponentPaysKExtraTokensPerChosen':
    'user.games.duel.likes.opponentPaysKExtraTokensPerChosen',
  'likes.opponentSNonBasicSkillsCostK': 'user.games.duel.likes.opponentSNonBasicSkillsCostK',
  'likes.qualifyingAPISkillsSaveKTokensFrom':
    'user.games.duel.likes.qualifyingAPISkillsSaveKTokensFrom',
  'likes.cleanseUpToOfYourDebuffs': 'user.games.duel.likes.cleanseUpToOfYourDebuffs',
  'likes.dispelUpToOpponentBuffs': 'user.games.duel.likes.dispelUpToOpponentBuffs',
  'likes.cleanseYourselfOrDispelOpponentBuffsUp':
    'user.games.duel.likes.cleanseYourselfOrDispelOpponentBuffsUp',
  'likes.gainFollowUpProgress': 'user.games.duel.likes.gainFollowUpProgress',
  'likes.preselectExtraSkill': 'user.games.duel.likes.preselectExtraSkill',
  'likes.predictANonBasicMainYouGain': 'user.games.duel.likes.predictANonBasicMainYouGain',
  'likes.gainMoreIfPreviousMainWasA': 'user.games.duel.likes.gainMoreIfPreviousMainWasA',
  'likes.yourOpponentSSuccessfulNonBasicCasts':
    'user.games.duel.likes.yourOpponentSSuccessfulNonBasicCasts',
  'likes.gainMoreWhenPrePaymentEnergyIs': 'user.games.duel.likes.gainMoreWhenPrePaymentEnergyIs',
  'likes.drainKOpponentBurst': 'user.games.duel.likes.drainKOpponentBurst',
  'likes.overloadYourselfNextRoundFor1Round': 'user.games.likes.balance.selfOverloadBrief',
  'likes.stunYourselfForRoundStartingNextRound':
    'user.games.duel.likes.stunYourselfForRoundStartingNextRound',
  'likes.gainLastingEnergySavingLayersSavingEach':
    'user.games.duel.likes.gainLastingEnergySavingLayersSavingEach',
  'likes.applyBaseSuppressionLayersToYourselfOpponent':
    'user.games.duel.likes.applyBaseSuppressionLayersToYourselfOpponent',
  'likes.applyDegradationLayersPlusIfBehindAt':
    'user.games.duel.likes.applyDegradationLayersPlusIfBehindAt',
  'likes.afterPaymentGainGoldAndKAPI': 'user.games.duel.likes.afterPaymentGainGoldAndKAPI',
  'likes.convertProCacheToFlashGainingAPI':
    'user.games.duel.likes.convertProCacheToFlashGainingAPI',
  'likes.refillBothSubscriptionsAndImagesDoesNot':
    'user.games.duel.likes.refillBothSubscriptionsAndImagesDoesNot',
  'likes.toggleSpeedNextRoundBaseCostsLikes':
    'user.games.duel.likes.toggleSpeedNextRoundBaseCostsLikes',
  'likes.banOpponentSubscriptionAndImagesFromNext':
    'user.games.duel.likes.banOpponentSubscriptionAndImagesFromNext',
  'likes.baseLikes': 'user.games.duel.likes.baseLikes',
  'likes.alsoGainFollowUpProgress': 'user.games.duel.likes.alsoGainFollowUpProgress',
  'likes.persistentCache': 'user.games.duel.likes.persistentCache',
  'likes.cache': 'user.games.duel.likes.cache',
  'likes.layers': 'user.games.duel.likes.layers',
  'likes.persistentLayers': 'user.games.duel.likes.persistentLayers',
  'likes.shortLivedLayers': 'user.games.duel.likes.shortLivedLayers',
  'likes.basic': 'user.games.duel.likes.basic',
  'likes.normal': 'user.games.duel.likes.normal',
  'likes.special': 'user.games.duel.likes.special',
  'likes.ultimate': 'user.games.duel.likes.ultimate',
  'likes.likes': 'user.games.duel.likes.likes',
  'likes.subscriptionBurst': 'user.games.duel.likes.subscriptionBurst',
  'likes.subscriptionTotal': 'user.games.duel.likes.subscriptionTotal',
  'likes.aPIReserve': 'user.games.duel.likes.aPIReserve',
  'likes.trialCredits': 'user.games.duel.likes.trialCredits',
  'likes.imageQuota': 'user.games.duel.likes.imageQuota',
  'likes.sharedEnergy': 'user.games.duel.likes.sharedEnergy',
  'likes.upgradeSubscription': 'user.games.duel.likes.upgradeSubscription',
  'likes.refillAPI': 'user.games.duel.likes.refillAPI',
  'likes.chargeBattery': 'user.games.duel.likes.chargeBattery',
  'likes.cleansingItem': 'user.games.duel.likes.cleansingItem',
  'likes.regulator': 'user.games.duel.likes.regulator',
  'likes.plansRevealed': 'user.games.duel.likes.plansRevealed',
  'likes.shoppingCharge': 'user.games.duel.likes.shoppingCharge',
  'likes.paymentOverload': 'user.games.duel.likes.paymentOverload',
  'likes.cleansingBuffs': 'user.games.duel.likes.cleansingBuffs',
  'likes.likesAwarded': 'user.games.duel.likes.likesAwarded',
  'likes.followUpEffects': 'user.games.duel.likes.followUpEffects',
  'likes.roundEnd': 'user.games.duel.likes.roundEnd',
  'likes.roundReplenishment': 'user.games.duel.likes.roundReplenishment',
  'likes.beforeSettlement': 'user.games.duel.likes.beforeSettlement',
  'likes.afterSettlement': 'user.games.duel.likes.afterSettlement',
  'likes.insufficientSharedEnergy': 'user.games.duel.likes.insufficientSharedEnergy',
  'likes.insufficientPersonalResources': 'user.games.duel.likes.insufficientPersonalResources',
  'likes.cancelledAfterAnEarlierFailure': 'user.games.duel.likes.cancelledAfterAnEarlierFailure',
  'likes.noSkillSelected': 'user.games.duel.likes.noSkillSelected',
  'likes.turnBasedBattleMinigameTestRules':
    'user.games.duel.likes.turnBasedBattleMinigameTestRules',
  'likes.chooseTogetherCompeteForLikes': 'user.games.duel.likes.chooseTogetherCompeteForLikes',
  'likes.bothPlayersHave': 'user.games.duel.likes.bothPlayersHave',
  'likes.secondsToChoosePurchasesAMainSkill':
    'user.games.duel.likes.secondsToChoosePurchasesAMainSkill',
  'likes.reach': 'user.games.duel.likes.reach',
  'likes.likesToCompeteForVictoryWithAt': 'user.games.duel.likes.likesToCompeteForVictoryWithAt',
  'likes.roundsIfBothReachTheTargetTogether':
    'user.games.duel.likes.roundsIfBothReachTheTargetTogether',
  'likes.stepByStepResolution': 'user.games.duel.likes.stepByStepResolution',
  'likes.plansShoppingAndChargePaymentAndOverload':
    'user.games.duel.likes.plansShoppingAndChargePaymentAndOverload',
  'likes.sharedEnergyAndOverload': 'user.games.duel.likes.sharedEnergyAndOverload',
  'likes.afterBothPlayersShopTheirFrozenEnergy':
    'user.games.duel.likes.afterBothPlayersShopTheirFrozenEnergy',
  'likes.charactersAndLoadouts': 'user.games.duel.likes.charactersAndLoadouts',
  'likes.eachCharacterHasTheirOwnSkillsAnd':
    'user.games.duel.likes.eachCharacterHasTheirOwnSkillsAnd',
  'likes.alwaysActiveCharacterPassives': 'user.games.duel.likes.alwaysActiveCharacterPassives',
  'likes.characterBonusesEnterTheBaseStageBefore':
    'user.games.duel.likes.characterBonusesEnterTheBaseStageBefore',
  'likes.subscriptionsImagesAndAPIReserve':
    'user.games.duel.likes.subscriptionsImagesAndAPIReserve',
  'likes.subscriptionBurstAndTotalQuotaHaveSeparate':
    'user.games.duel.likes.subscriptionBurstAndTotalQuotaHaveSeparate',
  'likes.defeat': 'user.games.duel.likes.defeat',
  'likes.roundLimit': 'user.games.duel.likes.roundLimit',
  'likes.turnBasedBattleMinigameTest': 'user.games.duel.likes.turnBasedBattleMinigameTest',
  'likes.oneBatteryIndependentChoicesASimultaneousReveal':
    'user.games.duel.likes.oneBatteryIndependentChoicesASimultaneousReveal',
  'likes.rules': 'user.games.duel.likes.rules',
  'likes.tutorial': 'user.games.duel.likes.tutorial',
  'likes.newHereTryAGuidedMatch': 'user.games.duel.likes.newHereTryAGuidedMatch',
  'likes.learnTheGameFromLoadoutToA': 'user.games.duel.likes.learnTheGameFromLoadoutToA',
  'likes.startTutorial': 'user.games.duel.likes.startTutorial',
  'likes.skipForNow': 'user.games.duel.likes.skipForNow',
  'likes.theRulesHaveNotSyncedRefreshTo': 'user.games.duel.likes.theRulesHaveNotSyncedRefreshTo',
  'likes.settlement': 'user.games.duel.likes.settlement',
  'likes.chooseSkills': 'user.games.duel.likes.chooseSkills',
  'likes.roundLog': 'user.games.duel.likes.roundLog',
  'likes.mATCHFOUND': 'user.games.duel.likes.mATCHFOUND',
  'likes.timeIsAlmostUpConfirmYourPlan': 'user.games.duel.likes.timeIsAlmostUpConfirmYourPlan',
  'likes.findingYourOpponent': 'user.games.duel.likes.findingYourOpponent',
  'likes.yourLoadoutIsFrozenWhileQueuedCancel':
    'user.games.duel.likes.yourLoadoutIsFrozenWhileQueuedCancel',
  'likes.finalSettlement': 'user.games.duel.likes.finalSettlement',
  'likes.viewRoundLog': 'user.games.duel.likes.viewRoundLog',
  'likes.preparingTheTutorial': 'user.games.duel.likes.preparingTheTutorial',
  'likes.theMatchingRuleCatalogIsUnavailable':
    'user.games.duel.likes.theMatchingRuleCatalogIsUnavailable',
  'likes.theGameClockContinues': 'user.games.duel.likes.theGameClockContinues',
  'likes.completed': 'user.games.duel.likes.completed',
  'likes.returnToBattle': 'user.games.duel.likes.returnToBattle',
  'likes.surrenderImmediatelyConcedesTheGameWithoutAn':
    'user.games.duel.likes.surrenderImmediatelyConcedesTheGameWithoutAn',
  'likes.keepPlaying': 'user.games.duel.likes.keepPlaying',
  'likes.chooseACharacter': 'user.games.duel.likes.chooseACharacter',
  'likes.skillsAndResourcesBelongToThisGame':
    'user.games.duel.likes.skillsAndResourcesBelongToThisGame',
  'likes.weakness': 'user.games.duel.likes.weakness',
  'likes.activeSlots': 'user.games.duel.likes.activeSlots',
  'likes.active': 'user.games.duel.likes.active',
  'likes.passive2': 'user.games.duel.likes.passive2',
  'likes.details': 'user.games.duel.likes.details',
  'likes.loadout': 'user.games.duel.likes.loadout',
  'likes.suggestedSet': 'user.games.duel.likes.suggestedSet',
  'likes.chooseAPreset': 'user.games.duel.likes.chooseAPreset',
  'likes.includeAtLeastOneSustainableStableScoring':
    'user.games.duel.likes.includeAtLeastOneSustainableStableScoring',
  'likes.checkSkillOwnershipDuplicatesAndSlotCount':
    'user.games.duel.likes.checkSkillOwnershipDuplicatesAndSlotCount',
  'likes.selectAtLeastOneSustainableStableScoring':
    'user.games.duel.likes.selectAtLeastOneSustainableStableScoring',
  'likes.skill': 'user.games.duel.likes.skill',
  'likes.mainSkill': 'user.games.duel.likes.mainSkill',
  'likes.energyPaid': 'user.games.duel.likes.energyPaid',
  'likes.tokensPaid': 'user.games.duel.likes.tokensPaid',
  'likes.likes2': 'user.games.duel.likes.likes2',
  'likes.passiveLikes': 'user.games.duel.likes.passiveLikes',
  'likes.trialPaid': 'user.games.duel.likes.trialPaid',
  'likes.subscriptionPaid': 'user.games.duel.likes.subscriptionPaid',
  'likes.aPIPaid': 'user.games.duel.likes.aPIPaid',
  'likes.resourceCosts': 'user.games.duel.likes.resourceCosts',
  'likes.distilledTemplate': 'user.games.duel.likes.distilledTemplate',
  'likes.success': 'user.games.duel.likes.success',
  'likes.level': 'user.games.duel.likes.level',
  'likes.reason': 'user.games.duel.likes.reason',
  'likes.item': 'user.games.duel.likes.item',
  'likes.goldPrice': 'user.games.duel.likes.goldPrice',
  'likes.amount': 'user.games.duel.likes.amount',
  'likes.target': 'user.games.duel.likes.target',
  'likes.requested': 'user.games.duel.likes.requested',
  'likes.actualChange': 'user.games.duel.likes.actualChange',
  'likes.overflow': 'user.games.duel.likes.overflow',
  'likes.required': 'user.games.duel.likes.required',
  'likes.available': 'user.games.duel.likes.available',
  'likes.bothEnergyQuotes': 'user.games.duel.likes.bothEnergyQuotes',
  'likes.bothOverloadStates': 'user.games.duel.likes.bothOverloadStates',
  'likes.ownerSeat': 'user.games.duel.likes.ownerSeat',
  'likes.status': 'user.games.duel.likes.status',
  'likes.hit': 'user.games.duel.likes.hit',
  'likes.likesReduction': 'user.games.duel.likes.likesReduction',
  'likes.extraLikes': 'user.games.duel.likes.extraLikes',
  'likes.resource': 'user.games.duel.likes.resource',
  'likes.learnedTemplate': 'user.games.duel.likes.learnedTemplate',
  'likes.remaining': 'user.games.duel.likes.remaining',
  'likes.sample': 'user.games.duel.likes.sample',
  'likes.persistentLayers2': 'user.games.duel.likes.persistentLayers2',
  'likes.enabled': 'user.games.duel.likes.enabled',
  'likes.status2': 'user.games.duel.likes.status2',
  'likes.result': 'user.games.duel.likes.result',
  'likes.bothPlans': 'user.games.duel.likes.bothPlans',
  'likes.overloadCause': 'user.games.duel.likes.overloadCause',
  'likes.payment': 'user.games.duel.likes.payment',
  'likes.affectedResources': 'user.games.duel.likes.affectedResources',
  'likes.harnessPassive': 'user.games.likes.balance.harnessPassive',
  'likes.applications': 'user.games.duel.likes.applications',
  'likes.resolutionStep': 'user.games.duel.likes.resolutionStep',
  'likes.kind': 'user.games.duel.likes.kind',
  'likes.indexZeroBased': 'user.games.duel.likes.indexZeroBased',
  'likes.ruleVersion': 'user.games.duel.likes.ruleVersion',
  'likes.sourceSeat': 'user.games.duel.likes.sourceSeat',
  'likes.effect': 'user.games.duel.likes.effect',
  'likes.attemptedLayer': 'user.games.duel.likes.attemptedLayer',
  'likes.resistance': 'user.games.duel.likes.resistance',
  'likes.resistedLayers': 'user.games.duel.likes.resistedLayers',
  'likes.successfulValues': 'user.games.duel.likes.successfulValues',
  'likes.candidateCount': 'user.games.duel.likes.candidateCount',
  'likes.drawOrdinalEmptyMeansGuaranteed': 'user.games.duel.likes.drawOrdinalEmptyMeansGuaranteed',
  'likes.yes': 'user.games.duel.likes.yes',
  'likes.no': 'user.games.duel.likes.no',
  'likes.extraSkill': 'user.games.duel.likes.extraSkill',
  'likes.flashFollowUp': 'user.games.duel.likes.flashFollowUp',
  'likes.sharedEnergyShortage': 'user.games.duel.likes.sharedEnergyShortage',
  'likes.aPIReserveShortage': 'user.games.duel.likes.aPIReserveShortage',
  'likes.subscriptionShortage': 'user.games.duel.likes.subscriptionShortage',
  'likes.tokenShortage': 'user.games.duel.likes.tokenShortage',
  'likes.imageQuotaShortage': 'user.games.likes.balance.imageShortage',
  'likes.successfulCast': 'user.games.duel.likes.successfulCast',
  'likes.harnessBonusLike': 'user.games.likes.balance.harnessLike',
  'likes.castCancelled': 'user.games.duel.likes.castCancelled',
  'likes.overload': 'user.games.duel.likes.overload',
  'likes.purchase': 'user.games.duel.likes.purchase',
  'likes.sharedCharge': 'user.games.duel.likes.sharedCharge',
  'likes.cleanseDispel': 'user.games.duel.likes.cleanseDispel',
  'likes.resourceGain': 'user.games.duel.likes.resourceGain',
  'likes.trialQuota': 'user.games.duel.likes.trialQuota',
  'likes.resourceChange': 'user.games.duel.likes.resourceChange',
  'likes.quotaReset': 'user.games.duel.likes.quotaReset',
  'likes.learning': 'user.games.duel.likes.learning',
  'likes.powerGeneration': 'user.games.duel.likes.powerGeneration',
  'likes.cacheConversion': 'user.games.duel.likes.cacheConversion',
  'likes.followUpSkipped': 'user.games.duel.likes.followUpSkipped',
  'likes.buffApplied': 'user.games.duel.likes.buffApplied',
  'likes.debuffHitAndResistance': 'user.games.duel.likes.debuffHitAndResistance',
  'likes.persistentCache2': 'user.games.duel.likes.persistentCache2',
  'likes.modeChange': 'user.games.duel.likes.modeChange',
  'likes.gameEnded': 'user.games.duel.likes.gameEnded',
  'likes.global': 'user.games.duel.likes.global',
  'likes.baseLikes2': 'user.games.duel.likes.baseLikes2',
  'likes.conditionalPreMultiplierMultiplierPassiveFinal':
    'user.games.duel.likes.conditionalPreMultiplierMultiplierPassiveFinal',
  'likes.yourPlan': 'user.games.duel.likes.yourPlan',
  'likes.opponentSPlan': 'user.games.duel.likes.opponentSPlan',
  'likes.completeSettlementEvents': 'user.games.duel.likes.completeSettlementEvents',
  'likes.randomSelectionsThisRound': 'user.games.duel.likes.randomSelectionsThisRound',
  'likes.selectedPositionZeroBased': 'user.games.duel.likes.selectedPositionZeroBased',
  'likes.aPIPayment': 'user.games.duel.likes.aPIPayment',
  'likes.automaticPayment': 'user.games.duel.likes.automaticPayment',
  'likes.cleanseSelf': 'user.games.duel.likes.cleanseSelf',
  'likes.dispelOpponent': 'user.games.duel.likes.dispelOpponent',
  'likes.shop': 'user.games.duel.likes.shop',
  'likes.main': 'user.games.duel.likes.main',
  'likes.skip': 'user.games.duel.likes.skip',
  'likes.extra': 'user.games.duel.likes.extra',
  'likes.payment2': 'user.games.duel.likes.payment2',
  'likes.automatic': 'user.games.duel.likes.automatic',
  'likes.useAPIReserve': 'user.games.duel.likes.useAPIReserve',
  'likes.targetSide': 'user.games.duel.likes.targetSide',
  'likes.cleanseOwnDebuffs': 'user.games.duel.likes.cleanseOwnDebuffs',
  'likes.dispelOpponentBuffs': 'user.games.duel.likes.dispelOpponentBuffs',
  'likes.chooseTargetBuffs': 'user.games.duel.likes.chooseTargetBuffs',
  'likes.upTo': 'user.games.duel.likes.upTo',
  'likes.noEligibleTargetsRightNow': 'user.games.duel.likes.noEligibleTargetsRightNow',
  'likes.currentDistilledTemplate': 'user.games.duel.likes.currentDistilledTemplate',
  'likes.notLearned': 'user.games.duel.likes.notLearned',
  'likes.learning2': 'user.games.duel.likes.learning2',
  'likes.planLocked': 'user.games.duel.likes.planLocked',
  'likes.thisRoundSPlan': 'user.games.duel.likes.thisRoundSPlan',
  'likes.waitingForTheReveal': 'user.games.duel.likes.waitingForTheReveal',
  'likes.chooseThenConfirm': 'user.games.duel.likes.chooseThenConfirm',
  'likes.chooseASkill': 'user.games.duel.likes.chooseASkill',
  'likes.skipCasting': 'user.games.duel.likes.skipCasting',
  'likes.lockInPlan': 'user.games.duel.likes.lockInPlan',
  'likes.notEnoughGoldAdjustYourPurchases':
    'user.games.duel.likes.notEnoughGoldAdjustYourPurchases',
  'likes.chooseAMainSkillForThisRound': 'user.games.duel.likes.chooseAMainSkillForThisRound',
  'likes.overloadedShoppingAndCastingAreUnavailableThis':
    'user.games.duel.likes.overloadedShoppingAndCastingAreUnavailableThis',
  'likes.stunIsActiveYouMayCleanseIt': 'user.games.duel.likes.stunIsActiveYouMayCleanseIt',
  'likes.planSections': 'user.games.duel.likes.planSections',
  'likes.skills': 'user.games.duel.likes.skills',
  'likes.bothPlayersShopBeforeSkillCostsAre':
    'user.games.duel.likes.bothPlayersShopBeforeSkillCostsAre',
  'likes.baseGold': 'user.games.duel.likes.baseGold',
  'likes.energyReduction': 'user.games.duel.likes.energyReduction',
  'likes.removeOneDebuff': 'user.games.duel.likes.removeOneDebuff',
  'likes.remove': 'user.games.duel.likes.remove',
  'likes.addToPlan': 'user.games.duel.likes.addToPlan',
  'likes.cleansingTarget': 'user.games.duel.likes.cleansingTarget',
  'likes.unlimited2': 'user.games.duel.likes.unlimited2',
  'likes.usesLeft': 'user.games.duel.likes.usesLeft',
  'likes.preselectAnExtraSkill': 'user.games.duel.likes.preselectAnExtraSkill',
  'likes.noExtraSkill': 'user.games.duel.likes.noExtraSkill',
  'likes.atOverload': 'user.games.duel.likes.atOverload',
  'likes.need': 'user.games.duel.likes.need',
  'likes.available2': 'user.games.duel.likes.available2',
  'likes.letSPlayAPracticeMatch': 'user.games.duel.likes.letSPlayAPracticeMatch',
  'likes.raceTo60LikesBothPlayersChoose': 'user.games.duel.likes.raceTo60LikesBothPlayersChoose',
  'likes.firstChooseChatGPT': 'user.games.duel.likes.firstChooseChatGPT',
  'likes.selectTheHighlightedCharacterHerMultimodalPassive':
    'user.games.duel.likes.selectTheHighlightedCharacterHerMultimodalPassive',
  'likes.equipCodex': 'user.games.duel.likes.equipCodex',
  'likes.aHarnessDeterminesSkillSlotsAndFixed':
    'user.games.duel.likes.aHarnessDeterminesSkillSlotsAndFixed',
  'likes.usageReset': 'user.games.duel.likes.usageReset',
  'likes.refillsBothSubscriptionsAndImagesSaveIt':
    'user.games.duel.likes.refillsBothSubscriptionsAndImagesSaveIt',
  'likes.helloWorld': 'user.games.duel.likes.helloWorld',
  'likes.aStableBasicAttackRepeatedCastsBuild':
    'user.games.duel.likes.aStableBasicAttackRepeatedCastsBuild',
  'likes.regenerate': 'user.games.duel.likes.regenerate',
  'likes.spendAPIReserveToCleanseYourDebuffs':
    'user.games.duel.likes.spendAPIReserveToCleanseYourDebuffs',
  'likes.pedalFaster': 'user.games.duel.likes.pedalFaster',
  'likes.enableSpeedNextRoundTwiceTheLikes': 'user.games.likes.balance.tutorialSpeed',
  'likes.wordsAndPictures': 'user.games.duel.likes.wordsAndPictures',
  'likes.anImageConsumingUltimateThatEarnsMany':
    'user.games.duel.likes.anImageConsumingUltimateThatEarnsMany',
  'likes.equip': 'user.games.duel.likes.equip',
  'likes.loadoutReady': 'user.games.duel.likes.loadoutReady',
  'likes.allFiveSlotsAreReadyCardsShow': 'user.games.duel.likes.allFiveSlotsAreReadyCardsShow',
  'likes.matchDemoTeachingBotFound': 'user.games.duel.likes.matchDemoTeachingBotFound',
  'likes.liveMatchingReservesYourEntryCreditsAnd':
    'user.games.duel.likes.liveMatchingReservesYourEntryCreditsAnd',
  'likes.readResourcesBeforeChoosing': 'user.games.duel.likes.readResourcesBeforeChoosing',
  'likes.theBatteryAboveIsSharedSubscriptionBurst':
    'user.games.duel.likes.theBatteryAboveIsSharedSubscriptionBurst',
  'likes.cleanseToProtectYourLikes': 'user.games.duel.likes.cleanseToProtectYourLikes',
  'likes.theOpponentAppliedADebuffThatReduces':
    'user.games.duel.likes.theOpponentAppliedADebuffThatReduces',
  'likes.shopBeforeCasting': 'user.games.duel.likes.shopBeforeCasting',
  'likes.upgradingAddsBurstTotalAndImageQuota':
    'user.games.duel.likes.upgradingAddsBurstTotalAndImageQuota',
  'likes.theBatteryIsRunningLow': 'user.games.duel.likes.theBatteryIsRunningLow',
  'likes.theOpponentSUltimateBuiltALarge': 'user.games.duel.likes.theOpponentSUltimateBuiltALarge',
  'likes.counterWithAnUltimate': 'user.games.duel.likes.counterWithAnUltimate',
  'likes.youHaveEnoughImagesAndSubscriptionQuota':
    'user.games.duel.likes.youHaveEnoughImagesAndSubscriptionQuota',
  'likes.aResetHasTradeoffs': 'user.games.duel.likes.aResetHasTradeoffs',
  'likes.yourQuotasHaveFallenUsageResetCosts':
    'user.games.duel.likes.yourQuotasHaveFallenUsageResetCosts',
  'likes.fallBehindNowToAccelerate': 'user.games.duel.likes.fallBehindNowToAccelerate',
  'likes.togglingSpeedScoresNoLikesThisRound': 'user.games.likes.balance.tutorialToggle',
  'likes.yourFirstAcceleratedAttack': 'user.games.duel.likes.yourFirstAcceleratedAttack',
  'likes.useHelloWorldAndWatchSpeedCombine':
    'user.games.duel.likes.useHelloWorldAndWatchSpeedCombine',
  'likes.cacheKeepsYouGoing': 'user.games.duel.likes.cacheKeepsYouGoing',
  'likes.continueWithTheBasicAttackLastRound':
    'user.games.duel.likes.continueWithTheBasicAttackLastRound',
  'likes.oneLastPush': 'user.games.duel.likes.oneLastPush',
  'likes.youHaveANarrowLeadAndEnough': 'user.games.duel.likes.youHaveANarrowLeadAndEnough',
  'likes.openTheShop': 'user.games.duel.likes.openTheShop',
  'likes.selectTheHighlightedShopTab': 'user.games.duel.likes.selectTheHighlightedShopTab',
  'likes.chargeTheSharedBattery': 'user.games.duel.likes.chargeTheSharedBattery',
  'likes.addTheHighlightedPurchaseItResolvesWith':
    'user.games.duel.likes.addTheHighlightedPurchaseItResolvesWith',
  'likes.returnToSkills': 'user.games.duel.likes.returnToSkills',
  'likes.thePurchaseIsInYourPlanNow': 'user.games.duel.likes.thePurchaseIsInYourPlanNow',
  'likes.chooseTheHighlightedSkill': 'user.games.duel.likes.chooseTheHighlightedSkill',
  'likes.choosingASkillDoesNotLockYour': 'user.games.duel.likes.choosingASkillDoesNotLockYour',
  'likes.useAPIThisRound': 'user.games.duel.likes.useAPIThisRound',
  'likes.setPaymentToUseAPIReserve': 'user.games.duel.likes.setPaymentToUseAPIReserve',
  'likes.chooseTheDebuffToCleanse': 'user.games.duel.likes.chooseTheDebuffToCleanse',
  'likes.checkTheHighlightedDebuffToChooseWhat':
    'user.games.duel.likes.checkTheHighlightedDebuffToChooseWhat',
  'likes.reviewAndLockYourPlan': 'user.games.duel.likes.reviewAndLockYourPlan',
  'likes.youCannotChangeALockedPlanThe': 'user.games.duel.likes.youCannotChangeALockedPlanThe',
  'likes.watchTheRoundResolve': 'user.games.duel.likes.watchTheRoundResolve',
  'likes.shoppingPaymentCleansingLikesLaterChangesWatch':
    'user.games.duel.likes.shoppingPaymentCleansingLikesLaterChangesWatch',
  'likes.aHardFoughtVictory': 'user.games.duel.likes.aHardFoughtVictory',
  'likes.roundComplete': 'user.games.duel.likes.roundComplete',
  'likes.youFellBehindCleansedReplenishedResourcesAnd':
    'user.games.duel.likes.youFellBehindCleansedReplenishedResourcesAnd',
  'likes.continueWhenYouHaveReviewedTheChanges':
    'user.games.duel.likes.continueWhenYouHaveReviewedTheChanges',
  'likes.tutorialLocalPractice': 'user.games.duel.likes.tutorialLocalPractice',
  'likes.noSiteCreditsSpentOrEarned': 'user.games.duel.likes.noSiteCreditsSpentOrEarned',
  'likes.skipTutorial': 'user.games.duel.likes.skipTutorial',
  'likes.thisTutorialDoesNotMatchTheCurrent':
    'user.games.duel.likes.thisTutorialDoesNotMatchTheCurrent',
  'likes.round10': 'user.games.duel.likes.round10',
  'likes.preparation': 'user.games.duel.likes.preparation',
  'likes.continue': 'user.games.duel.likes.continue',
  'likes.useTeachingLoadout': 'user.games.duel.likes.useTeachingLoadout',
  'likes.returnToLobby': 'user.games.duel.likes.returnToLobby',
  'likes.tEACHINGMATCHFOUND': 'user.games.duel.likes.tEACHINGMATCHFOUND',
  'likes.qUICKTUTORIAL': 'user.games.duel.likes.qUICKTUTORIAL',
  'likes.waitingForYouNoCountdown': 'user.games.duel.likes.waitingForYouNoCountdown',
  'likes.roundResolved': 'user.games.duel.likes.roundResolved',
  'likes.completeTheHighlightedStepsForThisTeaching':
    'user.games.duel.likes.completeTheHighlightedStepsForThisTeaching',
  'ranking.stayAnonymousOnTheTrueCharityLeaderboard':
    'user.games.duel.ranking.stayAnonymousOnTheTrueCharityLeaderboard',
  'ranking.thisChoiceAppliesOnlyToTrueCharity':
    'user.games.duel.ranking.thisChoiceAppliesOnlyToTrueCharity',
  'ranking.trueCharity': 'user.games.duel.ranking.trueCharity',
  'ranking.anonymousTruePhilanthropist': 'user.games.duel.ranking.anonymousTruePhilanthropist',
  'ranking.gameCharity': 'user.games.duel.ranking.gameCharity',
  'ranking.anonymousPhilanthropist': 'user.games.duel.ranking.anonymousPhilanthropist',
  'ranking.anonymousBidder': 'user.games.duel.ranking.anonymousBidder',
  'ranking.gameFortuneLeaderboard': 'user.games.duel.ranking.gameFortuneLeaderboard',
  'ranking.anonymousTycoon': 'user.games.duel.ranking.anonymousTycoon',
  'ranking.luckyCatchLeaderboard': 'user.games.duel.ranking.luckyCatchLeaderboard',
  'ranking.anonymousAngler': 'user.games.duel.ranking.anonymousAngler',
  'ranking.allTimeDonationCreditsIncludingAdministratorAdjustments':
    'user.games.duel.ranking.allTimeDonationCreditsIncludingAdministratorAdjustments',
  'ranking.acrossAllSixGames': 'user.games.duel.ranking.acrossAllSixGames',
  'ranking.inPondFishing': 'user.games.duel.ranking.inPondFishing',
  'ranking.inBiddingDuel': 'user.games.duel.ranking.inBiddingDuel',
  'ranking.inBlackjack': 'user.games.duel.ranking.inBlackjack',
  'ranking.overTheLast724HoursReturns': 'user.games.duel.ranking.overTheLast724HoursReturns',
  'ranking.overTheLast724HoursSpending': 'user.games.duel.ranking.overTheLast724HoursSpending',
  'ranking.positiveProfitsBeforeFeesAcrossAllThree':
    'user.games.duel.ranking.positiveProfitsBeforeFeesAcrossAllThree',
  'ranking.positiveProfitsBeforeFeesAreAddedSeparately':
    'user.games.duel.ranking.positiveProfitsBeforeFeesAreAddedSeparately',
  'ranking.period': 'user.games.duel.ranking.period',
  'ranking.rolling7Days': 'user.games.duel.ranking.rolling7Days',
  'ranking.rolling30Days': 'user.games.duel.ranking.rolling30Days',
  'ranking.allTime': 'user.games.duel.ranking.allTime',
  'ranking.refreshLeaderboard': 'user.games.duel.ranking.refreshLeaderboard',
  'ranking.rebuildingTheBiddingMastersBoardHistoricalResults':
    'user.games.duel.ranking.rebuildingTheBiddingMastersBoardHistoricalResults',
  'ranking.verifiableHistoryStarts': 'user.games.duel.ranking.verifiableHistoryStarts',
  'ranking.unknown': 'user.games.duel.ranking.unknown',
  'ranking.knownMissingEvents': 'user.games.duel.ranking.knownMissingEvents',
  'ranking.statisticsStarted': 'user.games.duel.ranking.statisticsStarted',
  'ranking.noQualifyingRankingsYet': 'user.games.duel.ranking.noQualifyingRankingsYet',
  'ranking.rank': 'user.games.duel.ranking.rank',
  'ranking.player': 'user.games.duel.ranking.player',
  'ranking.credits': 'user.games.duel.ranking.credits',
  'ranking.me': 'user.games.duel.ranking.me',
  'ranking.charityLeaderboardPages': 'user.games.duel.ranking.charityLeaderboardPages',
  'ranking.allGameLeaderboardsShareYourGamePrivacy':
    'user.games.duel.ranking.allGameLeaderboardsShareYourGamePrivacy',
  'ranking.leaderboards': 'user.games.duel.ranking.leaderboards',
  'ranking.chooseALeaderboard': 'user.games.duel.ranking.chooseALeaderboard',
} as const;
export function useDuelText() {
  return useRegisteredCopy(duelCopyKeys).t;
}
export type DuelText = ReturnType<typeof useDuelText>;
export function outcomeText(outcome: DuelResult<unknown, unknown>['outcome'], text: DuelText) {
  return outcome === 'win'
    ? text('common.victory')
    : outcome === 'loss'
      ? text('common.defeat')
      : outcome === 'draw'
        ? text('common.draw')
        : text('common.systemCancelled');
}
