import { useCallback } from 'react';
import { useTranslation } from 'react-i18next';

const en = {
  'common.back': 'Back to game center',
  'common.retry': 'Try again',
  'common.loading': 'Loading game status…',
  'common.credits': 'credits',
  'common.open': 'Open',
  'common.partial': 'Partly open',
  'common.closed': 'Closed',
  'common.maintenance': 'Maintenance',
  'common.unavailable': 'Temporarily unavailable',
  'common.responseUnknown':
    'The result could not be confirmed. No new action can start until the latest status is checked.',
  'common.conflict': 'The game changed. The latest status is shown; review it before trying again.',
  'common.serviceStopped': 'The game service is recovering. Timers and results remain unchanged.',
  'common.leaseActive': 'This page can continue the current game.',
  'common.leaseRenewing': 'Confirming that this page can continue the game…',
  'common.leaseLost':
    'This page can no longer confirm continuation access. Timers and automatic actions still continue.',
  'common.maintenanceContinuation':
    'Maintenance is active. Keep this page open: leaving, refreshing, or losing the connection may end continuation access.',
  'common.anonymous': 'Stay anonymous on leaderboards',
  'common.anonymousHelp':
    'Applies to all game leaderboards. Turn off to show your name and avatar.',
  'common.rulesButton': 'How to play',
  'common.closeRules': 'Close rules',
  'center.eyebrow': 'Game lounge',
  'center.title': 'Choose your pace',
  'center.description': 'Three games, each with its own recovery and settlement rules.',
  'center.fishing.title': 'Pond fishing',
  'center.fishing.body': 'Cast once or open one ten-catch batch.',
  'center.linklink.title': 'LinkLink',
  'center.linklink.body': 'Clear a board before time runs out, and return later if needed.',
  'center.rps.title': 'Three-player RPS',
  'center.rps.body': 'Queue for a live three-seat match with private gestures.',
  'center.enter': 'Enter game',
  'center.details': 'View availability',
  'center.from': 'From {{amount}} credits',
  'center.specs': '{{count}} of 3 board sizes open',
  'center.modes': '{{count}} of 3 modes open',
  'fishing.eyebrow': 'Pond fishing',
  'fishing.title': 'A quiet cast, a surprise catch',
  'fishing.description': 'Choose your bait and cast a line.',
  'fishing.castCount': 'Number of casts',
  'fishing.stage.idle': 'The water is calm',
  'fishing.stage.casting': 'The float flies out',
  'fishing.stage.pending': 'The batch is settling',
  'fishing.stage.bite': 'A bite!',
  'fishing.stage.result': 'Catch revealed',
  'fishing.sound.on': 'Sound on',
  'fishing.sound.off': 'Sound off',
  'fishing.sound.hint': 'Sound starts off and is enabled only by this control.',
  'fishing.bait.worm': 'Worm',
  'fishing.bait.lure': 'Lure',
  'fishing.bait.premium': 'Premium bait',
  'fishing.batch.one': 'Single cast',
  'fishing.batch.ten': 'Ten-catch batch',
  'fishing.selected': 'Selected bait',
  'fishing.unitPrice': 'Unit price',
  'fishing.totalPrice': 'Batch total',
  'fishing.balance': 'Available balance',
  'fishing.start': 'Start this batch',
  'fishing.starting': 'Submitting one batch…',
  'fishing.insufficient': 'Your available balance is not enough for this batch.',
  'fishing.closed':
    'New fishing batches are closed. Closed is an availability state, not an empty pond.',
  'fishing.runtimeUnavailable': 'Fishing is still getting ready, so no paid batch can start.',
  'fishing.pending.title': 'This batch is already accepted',
  'fishing.pending.body': 'Do not repeat it. New starts are locked while the same batch settles.',
  'fishing.pending.next': 'Next automatic attempt: {{time}}',
  'fishing.recovery.title': 'This batch needs explicit recovery',
  'fishing.recovery.body':
    'Recovery reuses this batch and its existing outcomes. It does not refund, redraw, change bait, or create a new batch.',
  'fishing.recovery.action': 'Recover this same batch',
  'fishing.recovery.running': 'Recovering the same batch…',
  'fishing.unknown.check': 'Check this operation',
  'fishing.unknown.replay': 'Retry the same action',
  'fishing.result.title': 'This batch is complete',
  'fishing.result.total': 'Total catch',
  'fishing.result.entry': 'Entry total',
  'fishing.result.payout': 'Credits received',
  'fishing.result.balance': 'Resulting balance',
  'fishing.result.more':
    'More unviewed batches are waiting and will load after this result is marked viewed.',
  'fishing.result.ackWaiting': 'The complete result is shown. Marking it viewed…',
  'fishing.result.ackFailed':
    'This result could not be marked viewed. It remains visible and its settlement is unchanged.',
  'fishing.result.ackRetry': 'Retry marking as viewed',
  'fishing.tier.common': 'Common',
  'fishing.tier.rare': 'Rare',
  'fishing.tier.legendary': 'Legendary',
  'fishing.tier.junk': 'Pond find',
  'fishing.tier.treasure': 'Treasure',
  'fishing.size': '{{size}} cm',
  'fishing.reward': '{{amount}} credits',
  'fishing.leaderboard.single': 'Largest single catch',
  'fishing.leaderboard.total': '30-day total catch',
  'fishing.leaderboard.helpSingle': 'Largest single catches, showing the top 20 and your position.',
  'fishing.leaderboard.helpTotal': 'Rolling 30-day Top 20 plus your row.',
  'fishing.leaderboard.empty': 'No eligible rows yet.',
  'fishing.leaderboard.catch': 'Catch',
  'fishing.leaderboard.score': 'Result',
  'fishing.leaderboard.angler': 'Angler',
  'fishing.leaderboard.anonymous': 'Anonymous angler',
  'fishing.leaderboard.me': 'You',
  'fishing.rules.title': 'How pond fishing works',
  'fishing.rules.chooseTitle': 'Choose your bait',
  'fishing.rules.chooseBody':
    'Pick a worm, lure, or premium bait. The current price is shown on each button. Then choose one cast or a ten-catch batch.',
  'fishing.rules.batchTitle': 'One cast or one batch',
  'fishing.rules.batchBody':
    'A single cast uses the displayed bait price. A ten-catch batch uses the same bait and displayed price for all ten catches, charges ten times that price once, and returns ten ordered results with one total.',
  'fishing.rules.resultTitle': 'What you receive',
  'fishing.rules.resultBody':
    'Each result appears automatically when it is ready. You may find a common, rare, or legendary fish, a pond find, or a treasure. The result shows the catch, its size when applicable, and the credits received.',
  'fishing.rules.recoveryTitle': 'If you leave or refresh',
  'fishing.rules.recoveryBody':
    'A paid batch that is still being settled can be recovered after a refresh, sign-in, or lost response. Recovery shows the same batch and does not charge again, redraw, change bait, or create another batch.',
  'fishing.rules.scoresTitle': 'Catch boards',
  'fishing.rules.scoresBody':
    'Every catch from a ten-catch batch can count toward the catch boards. The ten-catch batch itself counts as one fishing entry.',
  'fishing.rules.startTitle': 'Before you start',
  'fishing.rules.startBody':
    'The total shown before starting is the amount for that batch. New batches can start only while the game is available.',
  'linklink.eyebrow': 'LinkLink',
  'linklink.title': 'Clear the board, keep your progress',
  'linklink.description':
    'Choose matching tiles while the game handles paths, removal, rearrangement, the timer, and the ending.',
  'linklink.spec': '{{spec}} board',
  'linklink.seconds': '{{seconds}} second time limit',
  'linklink.price': '{{amount}} credits',
  'linklink.specClosed': 'This size is closed',
  'linklink.startReview': 'Review paid start',
  'linklink.startConsequences':
    'Starting charges the displayed price once. An existing active board is restored with no second charge.',
  'linklink.start': 'Start {{spec}}',
  'linklink.starting': 'Starting or restoring…',
  'linklink.active': 'Active board',
  'linklink.progress': '{{removed}} / {{total}} pairs removed',
  'linklink.deadline': 'End time',
  'linklink.remaining': '{{seconds}} seconds remaining',
  'linklink.selectFirst': 'Select the first tile.',
  'linklink.selectSecond': 'Select a matching tile. The game will check whether they can connect.',
  'linklink.matching': 'Checking this pair…',
  'linklink.matchAccepted': 'Pair removed.',
  'linklink.matchRejected': 'This pair could not be removed.',
  'linklink.rearranged': 'No moves remained, so the game rearranged the tiles for free.',
  'linklink.abandon': 'Abandon this board',
  'linklink.abandonTitle': 'Abandon without refund?',
  'linklink.abandonBody':
    'This board ends with no refund and no performance score. A later board is charged again.',
  'linklink.keep': 'Keep playing',
  'linklink.confirmAbandon': 'Abandon with no refund',
  'linklink.summary.completed': 'Board completed',
  'linklink.summary.timed_out': 'Time ran out',
  'linklink.summary.abandoned': 'Board abandoned',
  'linklink.summary.score': 'Performance score',
  'linklink.summary.none': 'No performance score',
  'linklink.summary.elapsed': 'Elapsed play time',
  'linklink.summary.remaining': 'Time left when the board ended',
  'linklink.summary.seconds': '{{seconds}} seconds',
  'linklink.summary.new': 'Start another board',
  'linklink.empty': 'No active board or recent 30-day summary.',
  'linklink.rules.title': 'How LinkLink works',
  'linklink.rules.goalTitle': 'Clear every pair',
  'linklink.rules.goalBody':
    'Choose two matching tiles to remove them. Finish by clearing every pair before the board timer runs out.',
  'linklink.rules.boardTitle': 'Board sizes and time',
  'linklink.rules.boardBody':
    'Choose a 6×8 board with 24 pairs and 150 seconds, an 8×8 board with 32 pairs and 180 seconds, or a 10×10 board with 50 pairs and 240 seconds. The current price is shown before you start.',
  'linklink.rules.pathTitle': 'When a pair can connect',
  'linklink.rules.pathBody':
    'A connection may pass through empty spaces and the one-tile border around the board. It may turn at most twice and may not pass through an uncleared tile.',
  'linklink.rules.scoreTitle': 'How the score is counted',
  'linklink.rules.scoreBody':
    'Your score is the number of pairs removed multiplied by 100, plus the whole seconds left when the board ends. The score is only a game result: it does not pay credits or enter a leaderboard.',
  'linklink.rules.shuffleTitle': 'If no move remains',
  'linklink.rules.shuffleBody':
    'The game automatically rearranges the remaining tiles for free when no legal pair remains. There is no manual shuffle button or fixed shuffle-count limit.',
  'linklink.rules.clockTitle': 'The clock keeps running',
  'linklink.rules.clockBody':
    'Leaving the page, switching tabs, refreshing, or briefly losing connection does not pause or extend the timer. The board ends when it is completed, times out, or you abandon it.',
  'linklink.rules.recoveryTitle': 'Return to the same board',
  'linklink.rules.recoveryBody':
    'An active board can be restored after leaving, refreshing, signing in again, or changing device. Returning to it does not charge a second time.',
  'linklink.rules.abandonTitle': 'If you abandon a board',
  'linklink.rules.abandonBody':
    'Abandoning ends that board without a refund and without a performance score. You must confirm first; a later board uses its own displayed price.',
  'rps.eyebrow': 'Three-player RPS',
  'rps.title': 'Three seats, one clear table',
  'rps.description':
    'Choose your actions here. The game handles hidden gestures, round changes, automatic actions, and settlement.',
  'rps.tutorial.title': 'How this table works',
  'rps.tutorial.1': 'Choose one of three modes. Matching shows only an ordinary waiting state.',
  'rps.tutorial.2': 'Gestures stay hidden until the reveal. The timer does not wait for animation.',
  'rps.tutorial.3': 'View the complete result here before joining another RPS match.',
  'rps.tutorial.next': 'Next',
  'rps.tutorial.skip': 'Skip for now',
  'rps.tutorial.finish': 'Enter the lobby',
  'rps.tutorial.replay': 'Replay tutorial',
  'rps.tutorial.saveFailed':
    'Tutorial completion was not saved. You can still play; it will appear again next time.',
  'rps.mode.quick': 'Quick',
  'rps.mode.standard': 'Standard',
  'rps.mode.deathmatch': 'Deathmatch',
  'rps.mode.quickHelp': 'One reveal, then the match settles and ends.',
  'rps.mode.standardHelp': 'Five-base entry, dealer rounds, raises, and pooled ties.',
  'rps.mode.deathmatchHelp': 'Your full available balance enters the table and can be lost.',
  'rps.base': 'Current base stake',
  'rps.entry': 'Entry amount',
  'rps.insufficient': 'Your available balance cannot cover this mode’s entry amount.',
  'rps.queueTime': 'Queue for up to {{seconds}} seconds',
  'rps.queue': 'Join {{mode}} queue',
  'rps.queueing': 'Joining one queue…',
  'rps.deathmatchReview':
    'Deathmatch brings your full available balance into the match. This confirmation starts the match; the final play decides the result.',
  'rps.deathmatchConfirm': 'I understand; join deathmatch',
  'rps.pendingQueue': 'Waiting for two other players…',
  'rps.pendingQueuePrivacy':
    'Relationship and network signals are never shown. Waiting always looks the same.',
  'rps.cancelQueue': 'Leave queue and return the entry amount',
  'rps.match.title': 'Live match',
  'rps.phase.gesture': 'Choose a gesture',
  'rps.phase.dealer_raise': 'Dealer decision',
  'rps.phase.followers': 'Follower decision',
  'rps.phase.paid_pool_gesture': 'Paid pooled reveal',
  'rps.phase.free_pool_gesture': 'Free pooled reveal',
  'rps.phase.ultimate_gesture': 'Ultimate showdown',
  'rps.phase.terminal_processing': 'Finishing the match settlement',
  'rps.phaseDeadline': 'Time left for this decision',
  'rps.waiting': 'Your action is locked or another seat must act.',
  'rps.gesture.rock': 'Rock',
  'rps.gesture.scissors': 'Scissors',
  'rps.gesture.paper': 'Paper',
  'rps.gesture.hidden': 'Hidden until reveal',
  'rps.gesture.locked': 'Gesture locked',
  'rps.dealer.noRaise': 'Do not raise',
  'rps.dealer.raise': 'Raise',
  'rps.dealer.integerOnly': 'Positive whole credits only. Maximum: {{max}}.',
  'rps.dealer.noCapacity': 'Less than 1 whole credit remains; only no raise is legal.',
  'rps.follower.call': 'Call',
  'rps.follower.surrender': 'Surrender',
  'rps.actionSending': 'Submitting this decision…',
  'rps.seat.deleted': 'Deleted participant',
  'rps.seat.balance': 'Table balance',
  'rps.seat.input': 'This round',
  'rps.seat.allIn': 'All in',
  'rps.seat.managed': 'Automatic actions: {{count}}',
  'rps.fun.none': 'No completed history',
  'rps.fun.insufficient': '{{count}} completed — sample too small',
  'rps.fun.full': '{{count}} completed · {{rate}}% profitable',
  'rps.fun.gesture': '{{gesture}} {{count}} · {{rate}}%',
  'rps.fun.managed': 'Gesture counts include choices made automatically after a timeout.',
  'rps.pool': 'Player pool',
  'rps.permanentMultiplier': 'Permanent plan multiplier',
  'rps.planMultiplier': 'Current plan multiplier',
  'rps.poolMultiplier': 'Pool base multiplier',
  'rps.raiseAmount': 'Dealer raise',
  'rps.baseRounds': 'Completed base rounds',
  'rps.paidTies': 'Paid-pool ties',
  'rps.freeTies': 'Free-pool ties (limit {{limit}})',
  'rps.poolStreaks': 'Current pool streaks',
  'rps.poolStreakValues': 'paid {{paid}} · free {{free}}',
  'rps.cuts':
    'This stake is divided into platform {{platform}}, welfare {{welfare}}, and Thursday {{thursday}} credits',
  'rps.welfareCarry': 'Welfare carry: {{amount}} credits',
  'rps.reminder':
    'Fight to the last moment… The sixth consecutive free tie sends the locked pool to welfare.',
  'rps.ultimate':
    'Ultimate showdown: no dealer, no raise, no new stake. A tie allows at most six free decisions.',
  'rps.stream.connecting': 'Connecting to live match updates…',
  'rps.stream.connected': 'Live match updates connected.',
  'rps.stream.disconnected': 'Live updates disconnected. The latest match status is being loaded.',
  'rps.stream.gap': 'Some live updates were missed. The complete match status is being loaded.',
  'rps.result.title': 'Pending result',
  'rps.result.reason': 'Ending reason',
  'rps.result.reason.quick_resolved': 'Quick reveal resolved',
  'rps.result.reason.standard_round_limit': 'Standard round limit reached',
  'rps.result.reason.standard_insufficient_balance': 'Standard table balance exhausted',
  'rps.result.reason.deathmatch_balance_exhausted': 'Deathmatch balance exhausted',
  'rps.result.reason.ultimate_resolved': 'Ultimate showdown resolved',
  'rps.result.reason.free_tie_limit': 'Free-tie limit reached; pool sent to welfare',
  'rps.result.input': 'Your total input',
  'rps.result.returned': 'Your total returned',
  'rps.result.net': 'Your wallet net',
  'rps.result.ackWaiting': 'The complete private result is shown. Marking it viewed…',
  'rps.result.ackFailed':
    'The result could not be marked viewed. It remains here, and new matches stay locked.',
  'rps.result.ackRetry': 'Retry marking as viewed',
  'rps.result.deidentified': 'Identity-hidden seat',
  'rps.result.win': 'Net win',
  'rps.result.loss': 'Net loss',
  'rps.result.tie': 'No wallet change',
  'rps.leaderboard.title': 'Rolling 30-day leaderboards',
  'rps.leaderboard.profit_rate': 'Profit rate',
  'rps.leaderboard.net_profit': 'Net profit',
  'rps.leaderboard.empty': 'No eligible player has reached 10 completed sessions in this mode.',
  'rps.leaderboard.sessions': '{{count}} sessions',
  'rps.leaderboard.anonymous': 'Anonymous player',
  'rps.leaderboard.me': 'You',
  'rps.leaderboard.player': 'Player',
  'rps.rules.title': 'How three-player RPS works',
  'rps.rules.goalTitle': 'Three players, three gestures',
  'rps.rules.goalBody':
    'Each match has three randomly matched players. Everyone chooses rock, scissors, or paper: rock beats scissors, scissors beats paper, and paper beats rock.',
  'rps.rules.roundTitle': 'Choose before the reveal',
  'rps.rules.roundBody':
    'All three choices stay hidden until the reveal, and a submitted choice cannot be changed. A gesture has a 20-second limit. The dealer then has 15 seconds to raise or decline, and both followers share a 15-second limit to call or surrender. On timeout, the game chooses a random gesture, treats the dealer as declining a raise, or treats a follower as surrendering.',
  'rps.rules.scoreTitle': 'How a reveal is shared',
  'rps.rules.score.same':
    'If all three gestures are the same, or all three gestures are different, a Quick match splits the pot into thirds; Standard and Deathmatch carry the pot forward.',
  'rps.rules.score.oneWinner':
    'If one player beats two players who chose the same gesture, that player receives two-thirds of the pot and the other two receive one-sixth each.',
  'rps.rules.score.twoWinners':
    'If two players with the same gesture beat the third player, the two winners split the pot equally and the losing player receives nothing.',
  'rps.rules.modesTitle': 'Three ways to play',
  'rps.rules.mode.quick':
    'Quick: each player enters with the current base stake, there is one reveal, and the match ends.',
  'rps.rules.mode.standard':
    'Standard: each player enters with five times the current base stake. The dealer rotates for up to nine ordinary rounds. A tied pot must finish before the match can end. After a pot is settled, the match ends when nine ordinary rounds are complete or any player has less than one base stake left; every remaining in-game balance is then returned.',
  'rps.rules.mode.deathmatch':
    'Deathmatch: each player brings all currently available credits, with at least the base stake, and cannot add credits from outside during the match. The first nine ordinary stakes use the base amount; it then rises to twice the base amount and rises by one more base amount after every three ordinary stakes. During a paid tied-pot continuation, the first three stakes use its starting amount and each later tie raises the next stake by one base amount. A settled pot ends the match if any player then has no credits left. When an ordinary stake leaves all three players at zero, that hand becomes the Ultimate Showdown.',
  'rps.rules.feesTitle': 'Where each entry goes',
  'rps.rules.feesBody':
    'Every entry, base stake, raise, or continuation stake is split using the rates shown on the page: platform, welfare pool, and Thursday pool. The remainder goes into the player pot, and the same stake is never split twice.',
  'rps.rules.dealerTitle': 'Dealer rounds and raises',
  'rps.rules.dealerBody':
    'Raises are available only in Standard and Deathmatch ordinary dealer rounds. After gestures are locked, the dealer may choose no raise or enter a positive whole-credit raise up to the smallest remaining whole-credit balance. If there is a raise, each of the other two players calls with the same amount or surrenders. No raise is a separate choice from entering 0.',
  'rps.rules.surrenderBody':
    'If both followers surrender, the dealer takes the current pot. If one follower surrenders, that player gets nothing and the dealer and the other follower split the result: half each for the same gesture, or two-thirds and one-third when one beats the other.',
  'rps.rules.poolTitle': 'Tied pots',
  'rps.rules.poolBody':
    'In Standard and Deathmatch, a reveal with three equal scores and no surrender locks the pot instead of paying it out. There is no fixed limit on paid continuation rounds. Once no more credits are added, the players continue with free reveals; the third consecutive free tie starts the reminder, and the sixth consecutive free tie ends the match and sends the locked pot to the welfare pool.',
  'rps.rules.ultimateTitle': 'Ultimate Showdown',
  'rps.rules.ultimateBody':
    'The Ultimate Showdown has no dealer, raise, call, or surrender, and no new stake is added. A non-tie ends it with the normal sharing rules. A tie starts free reveals, with at most six free decisions; a sixth consecutive free tie ends the match and sends the locked pot to the welfare pool.',
  'rps.rules.queueTitle': 'Joining and leaving',
  'rps.rules.queueBody':
    'The three modes have separate queues. A queue can wait for up to 120 seconds; cancelling or timing out before a match releases the entry amount. Once a match starts, leaving the page or switching tabs does not pause the clock or cancel the match.',
  'rps.rules.statsTitle': 'Stats and leaderboards',
  'rps.rules.statsBody':
    'At the start of a match, each player sees the other two players’ combined lifetime RPS summary from before this match. Fewer than ten completed matches shows only the match count. The two public leaderboards cover the latest 30 days, are separate for each mode, and require at least ten completed matches in that mode.',
  'rps.rules.resultTitle': 'When a match ends',
  'rps.rules.resultBody':
    'The complete result appears on this page before you can join another RPS match. If you return later, your own result remains available until the page confirms that you have viewed it.',
} as const;

type CopyKey = keyof typeof en;

const zh: Record<CopyKey, string> = {
  'common.back': '返回游戏中心',
  'common.retry': '重试',
  'common.loading': '正在读取游戏状态…',
  'common.credits': '积分',
  'common.open': '开放',
  'common.partial': '部分开放',
  'common.closed': '关闭',
  'common.maintenance': '维护中',
  'common.unavailable': '暂时不可用',
  'common.responseUnknown': '暂时无法确认结果。检查最新状态前，不能开始新的操作。',
  'common.conflict': '游戏状态已经变化。页面已显示最新状态，请重新确认后再操作。',
  'common.serviceStopped': '游戏服务正在恢复；计时与结果不会改变。',
  'common.leaseActive': '当前页面可以继续本局。',
  'common.leaseRenewing': '正在确认当前页面能否继续本局…',
  'common.leaseLost': '当前页面暂时无法确认继续资格；计时和自动操作仍会继续。',
  'common.maintenanceContinuation':
    '维护已开启。请保持本页打开；离开、刷新或失去连接后可能无法继续。',
  'common.anonymous': '在排行榜中匿名',
  'common.anonymousHelp': '适用于所有游戏排行榜。关闭后将展示你的昵称和头像。',
  'common.rulesButton': '玩法说明',
  'common.closeRules': '关闭玩法说明',
  'center.eyebrow': '游戏小馆',
  'center.title': '挑一种轻松节奏',
  'center.description': '三款小游戏，各有自己的恢复和结算规则。',
  'center.fishing.title': '池塘垂钓',
  'center.fishing.body': '单次抛竿，或一次完成十连收获。',
  'center.linklink.title': '连连看',
  'center.linklink.body': '在时间结束前消除棋盘，离开后也可继续。',
  'center.rps.title': '三人猜拳',
  'center.rps.body': '进入三席实时匹配，未揭晓手势始终保密。',
  'center.enter': '进入游戏',
  'center.details': '查看开放状态',
  'center.from': '{{amount}} 积分起',
  'center.specs': '3 种棋盘开放 {{count}} 种',
  'center.modes': '3 种模式开放 {{count}} 种',
  'fishing.eyebrow': '池塘垂钓',
  'fishing.title': '悠闲抛竿，看看收获',
  'fishing.description': '选好鱼饵，抛竿试试今天的运气。',
  'fishing.castCount': '抛竿次数',
  'fishing.stage.idle': '水面正安静',
  'fishing.stage.casting': '浮漂飞出',
  'fishing.stage.pending': '本批正在结算',
  'fishing.stage.bite': '上钩了！',
  'fishing.stage.result': '收获已揭晓',
  'fishing.sound.on': '声音已开启',
  'fishing.sound.off': '声音已关闭',
  'fishing.sound.hint': '声音默认关闭，只能通过这个用户操作开启。',
  'fishing.bait.worm': '蚯蚓',
  'fishing.bait.lure': '拟饵',
  'fishing.bait.premium': '高级鱼饵',
  'fishing.batch.one': '单次抛竿',
  'fishing.batch.ten': '十连收获',
  'fishing.selected': '已选鱼饵',
  'fishing.unitPrice': '单次价格',
  'fishing.totalPrice': '本次总价',
  'fishing.balance': '可用余额',
  'fishing.start': '开始本批',
  'fishing.starting': '正在提交一个批次…',
  'fishing.insufficient': '当前可用余额不足以开始这一批。',
  'fishing.closed': '新垂钓批次已关闭；关闭是开放状态，不是池塘空数据。',
  'fishing.runtimeUnavailable': '垂钓尚未准备好，暂时不能开始付费批次。',
  'fishing.pending.title': '本批已经受理',
  'fishing.pending.body': '请勿重复操作；同一批次结算期间，所有新开始都已锁住。',
  'fishing.pending.next': '下次自动尝试：{{time}}',
  'fishing.recovery.title': '本批需要明确恢复',
  'fishing.recovery.body': '恢复会复用本批及既有结果，不退款、不重抽、不换鱼饵，也不创建新批次。',
  'fishing.recovery.action': '恢复同一批次',
  'fishing.recovery.running': '正在恢复同一批次…',
  'fishing.unknown.check': '检查本次操作',
  'fishing.unknown.replay': '重试同一操作',
  'fishing.result.title': '本批次已完成',
  'fishing.result.total': '本次总收获',
  'fishing.result.entry': '投入总额',
  'fishing.result.payout': '获得积分',
  'fishing.result.balance': '结算后余额',
  'fishing.result.more': '还有未查看批次；当前结果标记为已查看后将继续载入。',
  'fishing.result.ackWaiting': '完整结果已经显示，正在标记为已查看…',
  'fishing.result.ackFailed': '暂时无法标记为已查看；同一结果会继续保留，结算不受影响。',
  'fishing.result.ackRetry': '重试标记为已查看',
  'fishing.tier.common': '普通',
  'fishing.tier.rare': '稀有',
  'fishing.tier.legendary': '传说',
  'fishing.tier.junk': '池塘杂物',
  'fishing.tier.treasure': '宝物',
  'fishing.size': '{{size}} 厘米',
  'fishing.reward': '{{amount}} 积分',
  'fishing.leaderboard.single': '单次最大收获',
  'fishing.leaderboard.total': '近 30 天总收获',
  'fishing.leaderboard.helpSingle': '最大的单次收获，展示前 20 名和你的排名。',
  'fishing.leaderboard.helpTotal': '最近 30 天的总收获，展示前 20 名和你的排名。',
  'fishing.leaderboard.empty': '暂时没有符合条件的记录。',
  'fishing.leaderboard.catch': '收获',
  'fishing.leaderboard.score': '成绩',
  'fishing.leaderboard.angler': '垂钓者',
  'fishing.leaderboard.anonymous': '匿名垂钓者',
  'fishing.leaderboard.me': '本人',
  'fishing.rules.title': '池塘垂钓怎么玩',
  'fishing.rules.chooseTitle': '先选鱼饵',
  'fishing.rules.chooseBody':
    '可以选择蚯蚓、拟饵或高级鱼饵，每个按钮都会显示当前价格。然后选择单次抛竿，或一次十连收获。',
  'fishing.rules.batchTitle': '单次抛竿或十连收获',
  'fishing.rules.batchBody':
    '单次抛竿使用当前鱼饵的显示价格。十连会对十次收获使用同一种鱼饵和开始时显示的价格，一次扣除十倍价格，并按顺序返回十个结果和一个合计。',
  'fishing.rules.resultTitle': '你会看到什么',
  'fishing.rules.resultBody':
    '每个结果准备好后会自动出现。你可能钓到普通、稀有或传说鱼，也可能发现池塘杂物或宝物；结果会展示收获、适用时的尺寸以及获得的积分。',
  'fishing.rules.recoveryTitle': '离开或刷新后怎么办',
  'fishing.rules.recoveryBody':
    '已经开始结算的付费批次，可以在刷新、重新登录或响应丢失后恢复。恢复看到的仍是同一批次，不会再次扣费、重抽、更换鱼饵或创建另一批次。',
  'fishing.rules.scoresTitle': '收获榜',
  'fishing.rules.scoresBody': '十连中的每次收获都可以计入收获榜；十连批次本身只计作一次垂钓记录。',
  'fishing.rules.startTitle': '开始前确认',
  'fishing.rules.startBody':
    '开始前显示的合计就是这一批的金额。只有游戏当前开放时，才能开始新的批次。',
  'linklink.eyebrow': '连连看',
  'linklink.title': '消除棋盘，保留进度',
  'linklink.description': '选择配对图块；路径、消除、重排、倒计时和结束状态由游戏系统处理。',
  'linklink.spec': '{{spec}} 棋盘',
  'linklink.seconds': '{{seconds}} 秒时限',
  'linklink.price': '{{amount}} 积分',
  'linklink.specClosed': '该规格已关闭',
  'linklink.startReview': '确认付费开始',
  'linklink.startConsequences':
    '开始时只扣显示的门票一次；若已有进行中的棋盘，将直接恢复且不会再次扣费。',
  'linklink.start': '开始 {{spec}}',
  'linklink.starting': '正在开始或恢复…',
  'linklink.active': '进行中的棋盘',
  'linklink.progress': '已消除 {{removed}} / {{total}} 对',
  'linklink.deadline': '结束时间',
  'linklink.remaining': '剩余 {{seconds}} 秒',
  'linklink.selectFirst': '请选择第一枚图块。',
  'linklink.selectSecond': '请选择配对图块；游戏会检查两者能否连通。',
  'linklink.matching': '正在检查这一对…',
  'linklink.matchAccepted': '这一对已消除。',
  'linklink.matchRejected': '这一对无法消除。',
  'linklink.rearranged': '棋盘没有可消除的配对，游戏已免费重排图块。',
  'linklink.abandon': '放弃本局',
  'linklink.abandonTitle': '确认不退款放弃？',
  'linklink.abandonBody': '本局会结束，不退款且不计算表现分；之后的新局会重新扣费。',
  'linklink.keep': '继续游玩',
  'linklink.confirmAbandon': '确认不退款放弃',
  'linklink.summary.completed': '棋盘已完成',
  'linklink.summary.timed_out': '时间已用完',
  'linklink.summary.abandoned': '本局已放弃',
  'linklink.summary.score': '表现分',
  'linklink.summary.none': '本局没有表现分',
  'linklink.summary.elapsed': '本局用时',
  'linklink.summary.remaining': '结束时剩余时间',
  'linklink.summary.seconds': '{{seconds}} 秒',
  'linklink.summary.new': '开始另一局',
  'linklink.empty': '没有进行中的棋盘或近 30 天结果摘要。',
  'linklink.rules.title': '连连看怎么玩',
  'linklink.rules.goalTitle': '消除所有配对',
  'linklink.rules.goalBody': '选择两枚相同图块即可消除。请在棋盘计时结束前清除所有配对。',
  'linklink.rules.boardTitle': '棋盘大小和时间',
  'linklink.rules.boardBody':
    '可以选择 6×8 棋盘（24 对、150 秒）、8×8 棋盘（32 对、180 秒）或 10×10 棋盘（50 对、240 秒）。开始前会显示当前价格。',
  'linklink.rules.pathTitle': '什么样的连线可以成立',
  'linklink.rules.pathBody':
    '连线可以经过空格和棋盘外围的一圈空位，最多转两次弯；不能穿过尚未消除的图块。',
  'linklink.rules.scoreTitle': '表现分怎么算',
  'linklink.rules.scoreBody':
    '表现分 = 已消除配对数 × 100 + 棋盘结束时剩余的完整秒数。表现分只代表本局成绩，不兑换积分，也不进入排行榜。',
  'linklink.rules.shuffleTitle': '没有可走的配对时',
  'linklink.rules.shuffleBody':
    '如果没有合法配对，游戏会免费自动重排剩余图块。没有手动洗牌按钮，也没有固定的洗牌次数上限。',
  'linklink.rules.clockTitle': '计时不会暂停',
  'linklink.rules.clockBody':
    '离开页面、切换标签页、刷新或短暂断线都不会暂停或延长计时。棋盘会在完成、超时或主动放弃时结束。',
  'linklink.rules.recoveryTitle': '回到同一张棋盘',
  'linklink.rules.recoveryBody':
    '离开、刷新、重新登录或更换设备后，都可以恢复进行中的棋盘。恢复不会再次扣费。',
  'linklink.rules.abandonTitle': '主动放弃时',
  'linklink.rules.abandonBody':
    '放弃会结束本局，不退款，也不计算表现分；操作前需要确认，之后的新局使用新显示的价格。',
  'rps.eyebrow': '三人猜拳',
  'rps.title': '三席同桌，状态清楚',
  'rps.description': '在此选择操作；隐藏手势、回合变化、自动操作和结算由游戏系统处理。',
  'rps.tutorial.title': '这张桌子怎么玩',
  'rps.tutorial.1': '选择三种模式之一；匹配过程只显示普通等待状态。',
  'rps.tutorial.2': '揭晓前不会显示任何人的手势；动画不会暂停倒计时。',
  'rps.tutorial.3': '请先在本页查看完整结果，之后才能加入下一局猜拳。',
  'rps.tutorial.next': '下一步',
  'rps.tutorial.skip': '暂时跳过',
  'rps.tutorial.finish': '进入大厅',
  'rps.tutorial.replay': '重看玩法演示',
  'rps.tutorial.saveFailed': '演示完成状态未保存；本次仍可游玩，下次会再次显示。',
  'rps.mode.quick': '快速模式',
  'rps.mode.standard': '标准模式',
  'rps.mode.deathmatch': '生死斗',
  'rps.mode.quickHelp': '揭晓一次后完成结算并结束。',
  'rps.mode.standardHelp': '五倍基础入场、庄家轮、加注和锁池平局。',
  'rps.mode.deathmatchHelp': '全部可用余额进入场内，并可能全部损失。',
  'rps.base': '当前基础积分',
  'rps.entry': '入场金额',
  'rps.insufficient': '当前可用余额不足以支付该模式的入场金额。',
  'rps.queueTime': '最多排队 {{seconds}} 秒',
  'rps.queue': '进入{{mode}}队列',
  'rps.queueing': '正在进入唯一队列…',
  'rps.deathmatchReview': '生死斗会让全部可用余额进入场内；本次确认只负责开局，最终玩法决定结果。',
  'rps.deathmatchConfirm': '我已了解，进入生死斗',
  'rps.pendingQueue': '正在等待另外两名玩家…',
  'rps.pendingQueuePrivacy': '关系和网络信号绝不展示；所有等待看起来都完全相同。',
  'rps.cancelQueue': '取消排队并退回入场金额',
  'rps.match.title': '实时对局',
  'rps.phase.gesture': '选择手势',
  'rps.phase.dealer_raise': '庄家决策',
  'rps.phase.followers': '闲家决策',
  'rps.phase.paid_pool_gesture': '付费续池出招',
  'rps.phase.free_pool_gesture': '免费续池出招',
  'rps.phase.ultimate_gesture': '终极对决',
  'rps.phase.terminal_processing': '正在完成本局结算',
  'rps.phaseDeadline': '本次决定剩余时间',
  'rps.waiting': '你的动作已锁定，或正在等待其他席位。',
  'rps.gesture.rock': '石头',
  'rps.gesture.scissors': '剪刀',
  'rps.gesture.paper': '布',
  'rps.gesture.hidden': '揭晓前隐藏',
  'rps.gesture.locked': '手势已锁定',
  'rps.dealer.noRaise': '不加注',
  'rps.dealer.raise': '加注',
  'rps.dealer.integerOnly': '只支持正整数积分；上限 {{max}}。',
  'rps.dealer.noCapacity': '上限不足 1 个完整积分，本手只能不加注。',
  'rps.follower.call': '跟注',
  'rps.follower.surrender': '认输',
  'rps.actionSending': '正在提交本次决定…',
  'rps.seat.deleted': '已删除参与者',
  'rps.seat.balance': '场内余额',
  'rps.seat.input': '本轮投入',
  'rps.seat.allIn': '全押',
  'rps.seat.managed': '自动操作：{{count}} 次',
  'rps.fun.none': '暂无已完成数据',
  'rps.fun.insufficient': '已完成 {{count}} 局 · 样本不足',
  'rps.fun.full': '已完成 {{count}} 局 · 盈利局率 {{rate}}%',
  'rps.fun.gesture': '{{gesture}} {{count}} 次 · {{rate}}%',
  'rps.fun.managed': '手势次数包含超时后由游戏自动选择的出拳。',
  'rps.pool': '玩家奖池',
  'rps.permanentMultiplier': '永久计划倍率',
  'rps.planMultiplier': '当前计划倍率',
  'rps.poolMultiplier': '续池基线倍率',
  'rps.raiseAmount': '庄家加注',
  'rps.baseRounds': '已完成基础回合',
  'rps.paidTies': '付费续池平局',
  'rps.freeTies': '免费续池平局（上限 {{limit}}）',
  'rps.poolStreaks': '当前续池连续次数',
  'rps.poolStreakValues': '付费 {{paid}} · 免费 {{free}}',
  'rps.cuts': '本次投入分为：平台 {{platform}}、低保 {{welfare}}、疯四 {{thursday}} 积分',
  'rps.welfareCarry': '低保结转：{{amount}} 积分',
  'rps.reminder': '战至最后一刻……第六次连续免费平局会把锁定奖池注入低保池。',
  'rps.ultimate': '终极对决：无庄家、无加注、不再下注；平局后最多六次免费决胜。',
  'rps.stream.connecting': '正在连接对局实时更新…',
  'rps.stream.connected': '对局实时更新已连接。',
  'rps.stream.disconnected': '实时更新已断开，正在重新读取最新对局状态。',
  'rps.stream.gap': '部分实时更新未收到，正在重新读取完整对局状态。',
  'rps.result.title': '待查看结果',
  'rps.result.reason': '结束原因',
  'rps.result.reason.quick_resolved': '快速模式揭晓完成',
  'rps.result.reason.standard_round_limit': '标准模式轮数到达上限',
  'rps.result.reason.standard_insufficient_balance': '标准模式场内余额耗尽',
  'rps.result.reason.deathmatch_balance_exhausted': '生死斗场内余额耗尽',
  'rps.result.reason.ultimate_resolved': '终极对决已决出结果',
  'rps.result.reason.free_tie_limit': '免费平局到达上限，奖池已注入低保池',
  'rps.result.input': '本人总投入',
  'rps.result.returned': '本人总返还',
  'rps.result.net': '本人的钱包净变化',
  'rps.result.ackWaiting': '完整私有结果已经显示，正在标记为已查看…',
  'rps.result.ackFailed': '暂时无法标记为已查看；本结果会继续保留，新的对局仍不可加入。',
  'rps.result.ackRetry': '重试标记为已查看',
  'rps.result.deidentified': '已隐藏身份的席位',
  'rps.result.win': '净盈利',
  'rps.result.loss': '净亏损',
  'rps.result.tie': '钱包无变化',
  'rps.leaderboard.title': '滚动 30 天排行榜',
  'rps.leaderboard.profit_rate': '盈利局率',
  'rps.leaderboard.net_profit': '净收益',
  'rps.leaderboard.empty': '该模式尚无完成至少 10 局的合格玩家。',
  'rps.leaderboard.sessions': '{{count}} 局',
  'rps.leaderboard.anonymous': '匿名玩家',
  'rps.leaderboard.me': '本人',
  'rps.leaderboard.player': '玩家',
  'rps.rules.title': '三人猜拳怎么玩',
  'rps.rules.goalTitle': '三名玩家，三种手势',
  'rps.rules.goalBody':
    '每局由三名随机匹配的玩家参加。每人选择石头、剪刀或布：石头胜剪刀，剪刀胜布，布胜石头。',
  'rps.rules.roundTitle': '在揭晓前出招',
  'rps.rules.roundBody':
    '三人的选择会在揭晓前保持隐藏，提交后不能修改。出招限时 20 秒；之后庄家有 15 秒决定是否加注，两名闲家共用 15 秒决定跟注或认输。超时时，游戏会随机代选手势、把庄家视为不加注，或把闲家视为认输。',
  'rps.rules.scoreTitle': '揭晓后如何分配',
  'rps.rules.score.same':
    '三人手势相同，或石头、剪刀、布各出现一次时，快速模式把奖池平均分成三份；标准模式和生死斗会把奖池继续累积。',
  'rps.rules.score.oneWinner':
    '一名玩家同时战胜另外两名出相同手势的玩家时，胜者获得奖池的三分之二，另外两人各得六分之一。',
  'rps.rules.score.twoWinners':
    '两名出相同手势的玩家共同战胜第三人时，两名胜者平分奖池，败者没有收获。',
  'rps.rules.modesTitle': '三种玩法',
  'rps.rules.mode.quick': '快速模式：每人投入当前基础积分，揭晓一次后本局结束。',
  'rps.rules.mode.standard':
    '标准模式：每人投入当前基础积分的五倍。庄家轮换，最多进行九个普通回合。尚未分配的平局奖池须先完成；奖池分配后，如果九个普通回合已经完成，或任一玩家剩余不足一份基础积分，本局结束并返还三人的场内余额。',
  'rps.rules.mode.deathmatch':
    '生死斗：每人带入当前全部可用积分，至少需要基础积分，开局后不能从场外补充。前九次普通下注使用基础积分；之后升为两倍，并在每完成三次普通下注后再增加一倍基础积分。付费续池的前三次使用本次续池起始金额，之后每次继续平局都会让下一次增加一倍基础积分。奖池分配后若任一玩家没有剩余积分，本局结束；普通下注后若三人场内积分都变为零，该手会进入终极对决。',
  'rps.rules.feesTitle': '每笔投入去了哪里',
  'rps.rules.feesBody':
    '每次入场、底注、加注或续池投入，都会按页面显示的比例分到平台、低保池和疯狂星期四池，剩余部分进入奖池；同一笔投入不会重复分配。',
  'rps.rules.dealerTitle': '庄家回合和加注',
  'rps.rules.dealerBody':
    '加注只出现在标准模式和生死斗的普通庄家回合。三人出招锁定后，庄家可以不加注，也可以输入不超过三人剩余完整积分中最小值的正整数加注。有人加注时，另外两名玩家可以跟注同样金额或认输；不加注是独立选择，不是输入 0。',
  'rps.rules.surrenderBody':
    '两名闲家都认输时，庄家拿走当前奖池。一名闲家认输时，认输者没有收获，庄家和另一名闲家继续比较：手势相同则各得一半，一方胜出则按三分之二和三分之一分配。',
  'rps.rules.poolTitle': '平局奖池',
  'rps.rules.poolBody':
    '标准模式和生死斗中，三人都未认输且得分相同的揭晓不会立即分配奖池，而会锁定奖池继续进行。付费续池没有固定次数上限；不再追加积分后进入免费揭晓。连续第三次免费平局开始显示提醒，连续第六次免费平局结束本局，并将锁定奖池送入低保池。',
  'rps.rules.ultimateTitle': '终极对决',
  'rps.rules.ultimateBody':
    '终极对决没有庄家、加注、跟注或认输，也不会再增加投入。第一次出现非平局就按正常比例结束；如果平局，最多进行六次免费决胜。连续第六次免费平局会结束本局，并将锁定奖池送入低保池。',
  'rps.rules.queueTitle': '排队和离开',
  'rps.rules.queueBody':
    '三种模式分别排队，最多等待 120 秒；匹配前主动取消或等待超时会释放入场积分。对局开始后，离开页面或切换标签页不会暂停计时，也不会取消对局。',
  'rps.rules.statsTitle': '统计和排行榜',
  'rps.rules.statsBody':
    '开局时，三名玩家可以看到彼此在本局开始前、三种模式合计的账号存续期猜拳摘要；少于 10 局时只显示完成局数。两张公开排行榜分别按模式统计近 30 天成绩，且该模式至少完成 10 局才可进入。',
  'rps.rules.resultTitle': '对局结束时',
  'rps.rules.resultBody':
    '完整结果会先显示在本页，之后才能加入下一局猜拳。如果稍后回来，属于你的结果会一直保留到页面确认你已经看过为止。',
};

function interpolate(
  template: string,
  variables?: Readonly<Record<string, string | number>>,
): string {
  if (!variables) return template;
  return template.replace(/\{\{([A-Za-z0-9_]+)\}\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(variables, key) ? String(variables[key]) : match,
  );
}

export function useGameCopy() {
  const { i18n } = useTranslation();
  const language = i18n.resolvedLanguage?.toLowerCase().startsWith('zh') ? 'zh' : 'en';
  const dictionary = language === 'zh' ? zh : en;
  const text = useCallback(
    (key: CopyKey, variables?: Readonly<Record<string, string | number>>) =>
      interpolate(dictionary[key], variables),
    [dictionary],
  );
  return { language, text };
}

export type GameCopyKey = CopyKey;
