import { useCallback } from 'react';
import { useTranslation } from 'react-i18next';

type GameCopyEntry = readonly [en: string, zh: string];

const copy = {
  'common.generalBalance': ['General credits', '通用积分'],
  'common.entryPayment': ['Entry payment', '入场付款'],

  'common.gameBalance': ['Game credits', '游戏积分'],
  'common.back': ['Back to game center', '返回游戏中心'],
  'common.retry': ['Try again', '重试'],
  'common.loading': ['Loading game status…', '正在读取游戏状态…'],
  'common.credits': ['credits', '积分'],
  'common.open': ['Open', '开放'],
  'common.partial': ['Partly open', '部分开放'],
  'common.closed': ['Closed', '关闭'],
  'common.maintenance': ['Maintenance', '维护中'],
  'common.responseUnknown': [
    'The result could not be confirmed. No new action can start until the latest status is checked.',
    '暂时无法确认结果。检查最新状态前，不能开始新的操作。',
  ],
  'common.serviceStopped': [
    'The game service is recovering. Timers and results remain unchanged.',
    '游戏服务正在恢复；计时与结果不会改变。',
  ],
  'common.leaseRenewing': [
    'Confirming that this page can continue the game…',
    '正在确认当前页面能否继续本局…',
  ],
  'common.leaseLost': [
    'This page can no longer confirm continuation access. Timers and automatic actions still continue.',
    '当前页面暂时无法确认继续资格；计时和自动操作仍会继续。',
  ],
  'common.maintenanceContinuation': [
    'Maintenance is active. Keep this page open: leaving, refreshing, or losing the connection may end continuation access.',
    '维护已开启。请保持本页打开；离开、刷新或失去连接后可能无法继续。',
  ],
  'common.anonymous': ['Stay anonymous on leaderboards', '在排行榜中匿名'],
  'common.anonymousHelp': [
    'Applies to all game leaderboards. Turn off to show your name and avatar. In three-player RPS matches and other public-identity play, your name and avatar remain visible to the other players.',
    '适用于所有游戏排行榜。关闭后将展示你的昵称和头像。三人猜拳对局等强制公开身份的场景中，其他玩家仍会看到你的昵称和头像。',
  ],
  'common.rulesButton': ['How to play', '玩法说明'],
  'common.closeRules': ['Close rules', '关闭玩法说明'],
  'center.eyebrow': ['Game lounge', '游戏小馆'],
  'center.title': ['Choose your pace', '挑一种轻松节奏'],
  'center.description': [
    'Unwind with fishing, tile matching, or a round of rock-paper-scissors.',
    '垂钓、连连看、三人猜拳，换种方式放松一下。',
  ],
  'center.fishing.title': ['Pond fishing', '池塘垂钓'],
  'center.fishing.body': [
    'Cast once or open one ten-catch batch.',
    '单次抛竿，或一次完成十连收获。',
  ],
  'center.linklink.title': ['LinkLink', '连连看'],
  'center.linklink.body': [
    'Clear a board before time runs out, and return later if needed.',
    '在时间结束前消除棋盘，离开后也可继续。',
  ],
  'center.rps.title': ['Three-player RPS', '三人猜拳'],
  'center.rps.body': [
    'Take a seat, read your opponents, and reveal your next move.',
    '三人同桌，揣摩对手，亮出你的下一手。',
  ],
  'center.enter': ['Enter game', '进入游戏'],
  'center.details': ['View availability', '查看开放状态'],
  'center.from': ['From {{amount}} credits', '{{amount}} 积分起'],
  'center.specs': ['{{count}} of 3 board sizes open', '3 种棋盘开放 {{count}} 种'],
  'center.modes': ['{{count}} of 3 modes open', '3 种模式开放 {{count}} 种'],
  'fishing.eyebrow': ['Pond fishing', '池塘垂钓'],
  'fishing.title': ['A quiet cast, a surprise catch', '悠闲抛竿，看看收获'],
  'fishing.description': ['Choose your bait and cast a line.', '选好鱼饵，抛竿试试今天的运气。'],
  'fishing.castCount': ['Number of casts', '抛竿次数'],
  'fishing.stage.idle': ['The water is calm', '水面正安静'],
  'fishing.stage.casting': ['The float flies out', '浮漂飞出'],
  'fishing.stage.pending': ['Preparing your catch', '正在整理收获'],
  'fishing.stage.bite': ['A bite!', '上钩了！'],
  'fishing.stage.result': ['Catch revealed', '收获已揭晓'],
  'fishing.sound.on': ['Sound on', '声音已开启'],
  'fishing.sound.off': ['Sound off', '声音已关闭'],
  'fishing.bait.worm': ['Worm', '蚯蚓'],
  'fishing.bait.lure': ['Lure', '拟饵'],
  'fishing.bait.premium': ['Premium bait', '高级鱼饵'],
  'fishing.batch.one': ['Single cast', '单次抛竿'],
  'fishing.batch.ten': ['Ten-catch batch', '十连收获'],
  'fishing.selected': ['Selected bait', '已选鱼饵'],
  'fishing.unitPrice': ['Unit price', '单次价格'],
  'fishing.totalPrice': ['Batch total', '本次总价'],
  'fishing.balance': ['Available balance', '可用余额'],
  'fishing.start': ['Start fishing', '开始垂钓'],
  'fishing.starting': ['Casting…', '正在抛竿…'],
  'fishing.insufficient': [
    'You need more credits to use this bait and number of casts.',
    '当前积分不足，请调整鱼饵或抛竿次数。',
  ],
  'fishing.closed': [
    'Fishing is closed for now. Please come back later.',
    '垂钓暂未开放，请稍后再来。',
  ],
  'fishing.runtimeUnavailable': [
    'The pond is getting ready. Please try again later.',
    '池塘正在准备中，请稍后再来。',
  ],
  'fishing.pending.title': ['Your catch is on its way', '正在等待收获'],
  'fishing.pending.body': [
    'Please wait for your results before casting again.',
    '请稍候，收获揭晓后即可再次垂钓。',
  ],
  'fishing.pending.next': ['Next automatic attempt: {{time}}', '下次自动尝试：{{time}}'],
  'fishing.recovery.title': ['Continue your unfinished fishing trip', '继续上次未完成的垂钓'],
  'fishing.recovery.body': [
    'Continue to see the original catch. Your bait and results stay the same, with no additional charge.',
    '继续后会显示原有收获。鱼饵和结果保持不变，无需再次付费。',
  ],
  'fishing.recovery.action': ['Continue fishing', '继续垂钓'],
  'fishing.recovery.running': ['Loading your catch…', '正在找回收获…'],
  'fishing.unknown.check': ['Check this operation', '检查本次操作'],
  'fishing.unknown.replay': ['Retry the same action', '重试同一操作'],
  'fishing.result.title': ['Your catch is ready', '收获已揭晓'],
  'fishing.result.total': ['Total catch', '本次总收获'],
  'fishing.result.entry': ['Entry total', '投入总额'],
  'fishing.result.payout': ['Credits received', '获得积分'],
  'fishing.result.balance': ['Resulting balance', '结算后余额'],
  'fishing.result.more': [
    'More catches are waiting to be shown next.',
    '还有其他收获未查看，接下来会继续展示。',
  ],
  'fishing.result.ackWaiting': [
    'The complete result is shown. Marking it viewed…',
    '完整结果已经显示，正在标记为已查看…',
  ],
  'fishing.result.ackFailed': [
    'This result could not be marked viewed. It remains visible and its settlement is unchanged.',
    '暂时无法标记为已查看；同一结果会继续保留，结算不受影响。',
  ],
  'fishing.result.ackRetry': ['Retry marking as viewed', '重试标记为已查看'],
  'fishing.tier.small': ['Small', '小型'],
  'fishing.tier.regular': ['Common', '普通'],
  'fishing.tier.big': ['Big catch', '大鱼'],
  'fishing.tier.giant': ['Giant', '巨物'],
  'fishing.tier.legend': ['Legendary', '传说'],
  'fishing.tier.junk': ['Pond find', '池塘杂物'],
  'fishing.tier.treasure': ['Treasure', '宝物'],
  'fishing.size': ['{{size}} cm', '{{size}} 厘米'],
  'fishing.reward': ['{{amount}} credits', '{{amount}} 积分'],
  'fishing.blueFatFish': ['Blue fat fish', '蓝色大肥鱼'],
  'fishing.blueFatFish.original': [
    'Original legendary species: {{species}}',
    '原传奇鱼种：{{species}}',
  ],
  'fishing.leaderboard.single': ['Largest single catch', '单次最大收获'],
  'fishing.leaderboard.recentSingle': [
    'Largest single catch · last 30 days',
    '近 30 天单次最大收获',
  ],
  'fishing.leaderboard.total': ['30-day total catch', '近 30 天总收获'],
  'fishing.leaderboard.windowHistorical': ['Historical board', '历史榜'],
  'fishing.leaderboard.windowRecent': ['Rolling 30-day window', '近 30 天窗口'],
  'fishing.leaderboard.helpSingle': [
    'Historical largest single catches, showing the top 20 and your position.',
    '历史单次最大收获，展示前 20 名和你的排名。',
  ],
  'fishing.leaderboard.helpRecentSingle': [
    'Largest single catches from the last 30 days, showing the top 20 and your position.',
    '近 30 天内的单次最大收获，展示前 20 名和你的排名。',
  ],
  'fishing.leaderboard.helpTotal': [
    'Rolling 30-day Top 20 plus your row.',
    '最近 30 天的总收获，展示前 20 名和你的排名。',
  ],
  'fishing.leaderboard.empty': ['No eligible rows yet.', '暂时没有符合条件的记录。'],
  'fishing.leaderboard.catch': ['Catch', '收获'],
  'fishing.leaderboard.score': ['Result', '成绩'],
  'fishing.leaderboard.angler': ['Angler', '垂钓者'],
  'fishing.leaderboard.anonymous': ['Anonymous angler', '匿名垂钓者'],
  'fishing.leaderboard.me': ['You', '本人'],
  'fishing.leaderboard.refresh': ['Refresh board', '刷新榜单'],
  'fishing.leaderboard.refreshing': ['Refreshing…', '正在刷新…'],
  'fishing.rules.title': ['How pond fishing works', '池塘垂钓怎么玩'],
  'fishing.rules.chooseTitle': ['Choose your bait', '先选鱼饵'],
  'fishing.rules.chooseBody': [
    'Pick a worm, lure, or premium bait. The current price is shown on each button. Then choose one cast or a ten-catch batch.',
    '可以选择蚯蚓、拟饵或高级鱼饵，每个按钮都会显示当前价格。然后选择单次抛竿，或一次十连收获。',
  ],
  'fishing.rules.batchTitle': ['One cast or one batch', '单次抛竿或十连收获'],
  'fishing.rules.batchBody': [
    'A single cast uses the displayed bait price. A ten-catch batch uses the same bait and displayed price for all ten catches, charges ten times that price once, and returns ten ordered results with one total.',
    '单次抛竿使用当前鱼饵的显示价格。十连会对十次收获使用同一种鱼饵和开始时显示的价格，一次扣除十倍价格，并按顺序返回十个结果和一个合计。',
  ],
  'fishing.rules.resultTitle': ['What you receive', '你会看到什么'],
  'fishing.rules.resultBody': [
    'Results show the catch, length and credits. Legendary fish have a 10% chance of the blue fat fish egg: 201 cm or longer, with exponentially decreasing odds and no gameplay limit. Only artwork and length rankings change; original species and rewards stay unchanged.',
    '结果展示收获、长度和积分。传奇鱼有 10% 概率成为蓝色大肥鱼：201 厘米起，长度概率指数衰减，不设玩法上限。彩蛋只改变图案和长度榜，结果及榜单保留原鱼种，奖励不变。',
  ],
  'fishing.rules.recoveryTitle': ['If you leave or refresh', '离开或刷新后怎么办'],
  'fishing.rules.recoveryBody': [
    'Continue a paid fishing trip after a refresh, sign-in, or lost connection. Your bait and catches stay the same, with no additional charge.',
    '已付费的垂钓可以在刷新、重新登录或断线后继续。鱼饵和收获保持不变，无需再次付费。',
  ],
  'fishing.rules.scoresTitle': ['Catch boards', '收获榜'],
  'fishing.rules.scoresBody': [
    'Each of the ten catches can enter the single-catch board, and all catches count toward your total.',
    '十连中的每次收获都可以计入收获榜，全部渔获都会计入总收获。',
  ],
  'fishing.rules.startTitle': ['Before you start', '开始前确认'],
  'fishing.rules.startBody': [
    'Check your bait, number of casts, and total price. You can start while fishing is open.',
    '请先确认鱼饵、抛竿次数和总价，开放期间即可开始垂钓。',
  ],
  'linklink.eyebrow': ['LinkLink', '连连看'],
  'linklink.title': ['Find a pair, draw a path', '找相同，连成对'],
  'linklink.description': [
    'Match identical pictures and clear the board before time runs out.',
    '配对相同图案，在时间用完前消除整个棋盘。',
  ],
  'linklink.playing': ['Playing', '游玩中'],
  'linklink.spec': ['{{spec}} board', '{{spec}} 棋盘'],
  'linklink.seconds': ['{{seconds}} second time limit', '{{seconds}} 秒时限'],
  'linklink.specClosed': ['This size is closed', '该规格已关闭'],
  'linklink.startReview': ['Review paid start', '确认付费开始'],
  'linklink.startConsequences': [
    'Confirm to pay the displayed ticket price and start the timer. Leaving the page does not pause the game or refund the ticket.',
    '确认后扣除下方门票并开始计时。离开页面后计时继续，门票不退还。',
  ],
  'linklink.start': ['Start {{spec}}', '开始 {{spec}}'],
  'linklink.active': ['Active board', '进行中的棋盘'],
  'linklink.progress': [
    '{{removed}} / {{total}} pairs removed',
    '已消除 {{removed}} / {{total}} 对',
  ],
  'linklink.remaining': ['{{seconds}} seconds remaining', '剩余 {{seconds}} 秒'],
  'linklink.selectFirst': [
    'Connect identical pictures with no more than two turns.',
    '点击两个相同图案，连线最多转弯两次。',
  ],
  'linklink.matchRejected': ['This pair could not be removed.', '这一对无法消除。'],
  'linklink.rearranged': [
    'No moves remained, so the game rearranged the tiles for free.',
    '棋盘没有可消除的配对，游戏已免费重排图块。',
  ],
  'linklink.abandon': ['Abandon this board', '放弃本局'],
  'linklink.abandonTitle': ['Abandon without refund?', '确认不退款放弃？'],
  'linklink.abandonBody': [
    'This board ends with no refund and no performance score. A later board is charged again.',
    '本局会结束，不退款且不计算表现分；之后的新局会重新扣费。',
  ],
  'linklink.keep': ['Keep playing', '继续游玩'],
  'linklink.confirmAbandon': ['Abandon with no refund', '确认不退款放弃'],
  'linklink.summary.completed': ['Board completed', '棋盘已完成'],
  'linklink.summary.timed_out': ['Time ran out', '时间已用完'],
  'linklink.summary.abandoned': ['Board abandoned', '本局已放弃'],
  'linklink.summary.score': ['Performance score', '表现分'],
  'linklink.summary.none': ['No performance score', '本局没有表现分'],
  'linklink.summary.elapsed': ['Elapsed play time', '本局用时'],
  'linklink.summary.remaining': ['Time left when the board ended', '结束时剩余时间'],
  'linklink.summary.seconds': ['{{seconds}} seconds', '{{seconds}} 秒'],
  'linklink.summary.new': ['Start another board', '开始另一局'],
  'linklink.empty': [
    'No active board or recent 30-day summary.',
    '没有进行中的棋盘或近 30 天结果摘要。',
  ],
  'linklink.rules.title': ['How LinkLink works', '连连看怎么玩'],
  'linklink.rules.goalTitle': ['Clear every pair', '消除所有配对'],
  'linklink.rules.goalBody': [
    'Choose two matching tiles to remove them. Finish by clearing every pair before the board timer runs out.',
    '选择两枚相同图块即可消除。请在棋盘计时结束前清除所有配对。',
  ],
  'linklink.rules.boardTitle': ['Board sizes and time', '棋盘大小和时间'],
  'linklink.rules.boardBody': [
    'Choose a 6×8 board with 24 pairs and 150 seconds, an 8×8 board with 32 pairs and 180 seconds, or a 10×10 board with 50 pairs and 240 seconds. The current price is shown before you start.',
    '可以选择 6×8 棋盘（24 对、150 秒）、8×8 棋盘（32 对、180 秒）或 10×10 棋盘（50 对、240 秒）。开始前会显示当前价格。',
  ],
  'linklink.rules.pathTitle': ['When a pair can connect', '什么样的连线可以成立'],
  'linklink.rules.pathBody': [
    'A connection may pass through empty spaces and the one-tile border around the board. It may turn at most twice and may not pass through an uncleared tile.',
    '连线可以经过空格和棋盘外围的一圈空位，最多转两次弯；不能穿过尚未消除的图块。',
  ],
  'linklink.rules.scoreTitle': ['How the score is counted', '表现分怎么算'],
  'linklink.rules.scoreBody': [
    'Your score is the number of pairs removed multiplied by 100, plus the whole seconds left when the board ends. The score is only a game result: it does not pay credits or enter a leaderboard.',
    '表现分 = 已消除配对数 × 100 + 棋盘结束时剩余的完整秒数。表现分只代表本局成绩，不兑换积分，也不进入排行榜。',
  ],
  'linklink.rules.shuffleTitle': ['If no move remains', '没有可走的配对时'],
  'linklink.rules.shuffleBody': [
    'The game automatically rearranges the remaining tiles for free when no legal pair remains. There is no manual shuffle button or fixed shuffle-count limit.',
    '如果没有合法配对，游戏会免费自动重排剩余图块。没有手动洗牌按钮，也没有固定的洗牌次数上限。',
  ],
  'linklink.rules.clockTitle': ['The clock keeps running', '计时不会暂停'],
  'linklink.rules.clockBody': [
    'Leaving the page, switching tabs, refreshing, or briefly losing connection does not pause or extend the timer. The board ends when it is completed, times out, or you abandon it.',
    '离开页面、切换标签页、刷新或短暂断线都不会暂停或延长计时。棋盘会在完成、超时或主动放弃时结束。',
  ],
  'linklink.rules.recoveryTitle': ['Return to the same board', '回到同一张棋盘'],
  'linklink.rules.recoveryBody': [
    'An active board can be restored after leaving, refreshing, signing in again, or changing device. Returning to it does not charge a second time.',
    '离开、刷新、重新登录或更换设备后，都可以恢复进行中的棋盘。恢复不会再次扣费。',
  ],
  'linklink.rules.abandonTitle': ['If you abandon a board', '主动放弃时'],
  'linklink.rules.abandonBody': [
    'Abandoning ends that board without a refund and without a performance score. You must confirm first; a later board uses its own displayed price.',
    '放弃会结束本局，不退款，也不计算表现分；操作前需要确认，之后的新局使用新显示的价格。',
  ],
  'rps.eyebrow': ['Three-player RPS', '三人猜拳'],
  'rps.title': ['Three players, one showdown', '三人同桌，一决胜负'],
  'rps.description': [
    'Three players, three gestures. Read the table and make your move.',
    '三人同桌，石头剪刀布。看准局势，亮出你的下一手。',
  ],
  'rps.tutorial.title': ['How this table works', '这张桌子怎么玩'],
  'rps.tutorial.1': [
    'Choose quick, standard, or deathmatch. The game begins when three players join.',
    '选择快速、标准或生死斗，凑齐三人即可开局。',
  ],
  'rps.tutorial.2': [
    'Pick a gesture before the timer runs out. Everyone reveals their choice together.',
    '倒计时结束前选好手势，大家同时揭晓。',
  ],
  'rps.tutorial.3': [
    'View the complete result here before joining another RPS match.',
    '请先在本页查看完整结果，之后才能加入下一局猜拳。',
  ],
  'rps.tutorial.next': ['Next', '下一步'],
  'rps.tutorial.skip': ['Skip for now', '暂时跳过'],
  'rps.tutorial.finish': ['Enter the lobby', '进入大厅'],
  'rps.tutorial.replay': ['Replay tutorial', '重看玩法演示'],
  'rps.tutorial.saveFailed': [
    'Tutorial completion was not saved. You can still play; it will appear again next time.',
    '演示完成状态未保存；本次仍可游玩，下次会再次显示。',
  ],
  'rps.mode.quick': ['Quick', '快速模式'],
  'rps.mode.standard': ['Standard', '标准模式'],
  'rps.mode.deathmatch': ['Deathmatch', '生死斗'],
  'rps.mode.quickHelp': [
    'One reveal, then the match settles and ends.',
    '揭晓一次后完成结算并结束。',
  ],
  'rps.mode.standardHelp': [
    'Five-base entry, dealer rounds, raises, and pooled ties.',
    '五倍基础入场、庄家轮、加注和锁池平局。',
  ],
  'rps.mode.deathmatchHelp': [
    'Your full available balance enters the table and can be lost.',
    '全部可用余额进入场内，并可能全部损失。',
  ],
  'rps.base': ['Current base stake', '当前基础积分'],
  'rps.entry': ['Entry amount', '入场金额'],
  'rps.insufficient': [
    'Your available balance cannot cover this mode’s entry amount.',
    '当前可用余额不足以支付该模式的入场金额。',
  ],
  'rps.queueTime': ['Queue for up to {{seconds}} seconds', '最多排队 {{seconds}} 秒'],
  'rps.queue': ['Join {{mode}} queue', '进入{{mode}}队列'],
  'rps.queueing': ['Joining the queue…', '正在加入匹配…'],
  'rps.deathmatchReview': [
    'Deathmatch uses all your available credits. You can lose the full amount. Confirm when you are ready to join.',
    '本局会投入全部可用积分，可能全部损失。请确认后入场。',
  ],
  'rps.deathmatchConfirm': ['I understand; join deathmatch', '我已了解，进入生死斗'],
  'rps.pendingQueue': ['Waiting for two other players…', '正在等待另外两名玩家…'],
  'rps.pendingQueuePrivacy': [
    'The game will begin automatically once three players are matched.',
    '匹配成功后会自动进入对局，请保持此页面打开。',
  ],
  'rps.cancelQueue': ['Leave queue and return the entry amount', '取消排队并退回入场金额'],
  'rps.match.title': ['Live match', '实时对局'],
  'rps.phase.gesture': ['Choose a gesture', '选择手势'],
  'rps.phase.dealer_raise': ['Dealer decision', '庄家决策'],
  'rps.phase.followers': ['Follower decision', '闲家决策'],
  'rps.phase.paid_pool_gesture': ['Paid pooled reveal', '付费续池出招'],
  'rps.phase.free_pool_gesture': ['Free pooled reveal', '免费续池出招'],
  'rps.phase.ultimate_gesture': ['Ultimate showdown', '终极对决'],
  'rps.phase.terminal_processing': ['Finishing the match settlement', '正在完成本局结算'],
  'rps.phaseDeadline': ['Time left for this decision', '本次决定剩余时间'],
  'rps.waiting': [
    'Your action is locked or another seat must act.',
    '你的动作已锁定，或正在等待其他席位。',
  ],
  'rps.gesture.rock': ['Rock', '石头'],
  'rps.gesture.scissors': ['Scissors', '剪刀'],
  'rps.gesture.paper': ['Paper', '布'],
  'rps.gesture.hidden': ['Hidden until reveal', '揭晓前隐藏'],
  'rps.gesture.locked': ['Gesture locked', '手势已锁定'],
  'rps.dealer.noRaise': ['Do not raise', '不加注'],
  'rps.dealer.raise': ['Raise', '加注'],
  'rps.dealer.adjust': ['Adjust the raise', '快捷调整加注'],
  'rps.dealer.subtract': ['−{{amount}} credits', '−{{amount}} 积分'],
  'rps.dealer.add': ['+{{amount}} credits', '+{{amount}} 积分'],
  'rps.dealer.maximum': ['Max {{amount}} credits', '最大 {{amount}} 积分'],
  'rps.dealer.allIn': ['All in {{amount}} credits', '全押 {{amount}} 积分'],
  'rps.dealer.integerOnly': [
    'Positive whole credits only. Maximum: {{max}}.',
    '只支持正整数积分；上限 {{max}}。',
  ],
  'rps.dealer.noCapacity': [
    'Less than 1 whole credit remains; only no raise is legal.',
    '上限不足 1 个完整积分，本手只能不加注。',
  ],
  'rps.follower.call': ['Call', '跟注'],
  'rps.follower.required': ['Required to call: {{amount}} credits', '需跟注 {{amount}} 积分'],
  'rps.waitingSync': ['Waiting for the current decision to sync…', '正在等待当前决策同步…'],
  'rps.instruction.gesture': [
    'Choose your gesture before the deadline.',
    '请在倒计时结束前选择手势。',
  ],
  'rps.instruction.dealer': [
    'You are the dealer: raise or keep the current stake.',
    '你是庄家：可以加注，也可以保持当前下注。',
  ],
  'rps.instruction.follow': [
    'Choose whether to call the dealer’s raise or surrender.',
    '请选择跟注庄家的加注，或认输。',
  ],
  'rps.poolTies': ['Ties in this pool: {{count}}', '同一奖池连续平局：{{count}}'],
  'rps.poolTiesUnknown': [
    'This ongoing pool has no recorded tie count.',
    '这份进行中的奖池未记录完整平局数。',
  ],
  'rps.follower.surrender': ['Surrender', '认输'],
  'rps.actionSending': ['Submitting this decision…', '正在提交本次决定…'],
  'rps.seat.deleted': ['Deleted participant', '已删除参与者'],
  'rps.seat.balance': ['Table balance', '场内余额'],
  'rps.seat.currentFunding': ['Your remaining table funds', '本人的场内资金分项'],
  'rps.queuePayment': ['Entry payment · refunded in the original assets if cancelled', '入场付款 · 取消匹配时按原币种退回'],
  'rps.seat.input': ['This round', '本轮投入'],
  'rps.seat.allIn': ['All in', '全押'],
  'rps.seat.managed': ['Automatic actions: {{count}}', '自动操作：{{count}} 次'],
  'rps.fun.none': ['No completed history', '暂无已完成数据'],
  'rps.fun.insufficient': [
    '{{count}} completed — sample too small',
    '已完成 {{count}} 局 · 样本不足',
  ],
  'rps.fun.full': [
    '{{count}} completed · {{rate}}% profitable',
    '已完成 {{count}} 局 · 盈利局率 {{rate}}%',
  ],
  'rps.fun.gesture': ['{{gesture}} {{count}} · {{rate}}%', '{{gesture}} {{count}} 次 · {{rate}}%'],
  'rps.fun.managed': [
    'Gesture counts include choices made automatically after a timeout.',
    '手势次数包含超时后由游戏自动选择的出拳。',
  ],
  'rps.pool': ['Player pool', '玩家奖池'],
  'rps.permanentMultiplier': ['Permanent plan multiplier', '永久计划倍率'],
  'rps.planMultiplier': ['Current plan multiplier', '当前计划倍率'],
  'rps.poolMultiplier': ['Pool base multiplier', '续池基线倍率'],
  'rps.raiseAmount': ['Dealer raise', '庄家加注'],
  'rps.baseRounds': ['Completed base rounds', '已完成基础回合'],
  'rps.paidTies': ['Paid-pool ties', '付费续池平局'],
  'rps.freeTies': ['Free-pool ties (limit {{limit}})', '免费续池平局（上限 {{limit}}）'],
  'rps.poolStreaks': ['Current pool streaks', '当前续池连续次数'],
  'rps.poolStreakValues': ['paid {{paid}} · free {{free}}', '付费 {{paid}} · 免费 {{free}}'],
  'rps.cuts': [
    'This stake is divided into platform {{platform}}, welfare {{welfare}}, and Thursday {{thursday}} credits',
    '本次投入分为：平台 {{platform}}、低保 {{welfare}}、疯四 {{thursday}} 积分',
  ],
  'rps.welfareCarry': ['Welfare carry: {{amount}} credits', '低保结转：{{amount}} 积分'],
  'rps.fun.title': ['Player stats', '对局统计'],
  'rps.economyDetails': ['Stakes and round details', '投入与轮次明细'],
  'rps.tieStreak': [
    'Consecutive free ties {{count}} / {{limit}}',
    '连续免费平局 {{count}} / {{limit}}',
  ],
  'rps.lastReveal': ['Previous round', '上一轮揭晓'],
  'rps.reveal.three_equal': ['Three alike — the standoff continues.', '三人同招，胜负未分'],
  'rps.reveal.all_distinct': ['One of each — the standoff continues.', '三招齐出，胜负未分'],
  'rps.reveal.one_beats_two': ['One player wins this round.', '一人制胜'],
  'rps.reveal.two_beat_one': ['Two players share this round.', '两人共同获胜'],
  'rps.reveal.one_surrender_tie': ['The two remaining players tie.', '一人认输，其余两人平局'],
  'rps.reveal.one_surrender_decided': [
    'The remaining players have a winner.',
    '一人认输，其余两人分出胜负',
  ],
  'rps.reveal.two_surrenders': ['One player remains standing.', '两人认输，一人胜出'],
  'rps.result.ascension': ['A final bow to the heavens', '战至最后一刻，自刎归天！'],
  'rps.result.ascensionBody': [
    'Six free ties in a row. The locked prize pool has gone to welfare, and the remaining table balances have been returned.',
    '连续六次免费平局，锁定奖池已注入低保池。三人的剩余场内余额均已返还。',
  ],
  'rps.result.close': ['Back to the lobby', '返回大厅'],
  'rps.reminder': [
    'Fight to the last moment… The sixth consecutive free tie sends the locked pool to welfare.',
    '战至最后一刻……第六次连续免费平局会把锁定奖池注入低保池。',
  ],
  'rps.ultimate': [
    'Ultimate showdown: no dealer, no raise, no new stake. A tie allows at most six free decisions.',
    '终极对决：无庄家、无加注、不再下注；平局后最多六次免费决胜。',
  ],
  'rps.stream.connecting': ['Connecting to live match updates…', '正在连接对局实时更新…'],
  'rps.stream.connected': ['Connected', '已连接'],
  'rps.stream.disconnected': [
    'Live updates disconnected. The latest match status is being loaded.',
    '实时更新已断开，正在重新读取最新对局状态。',
  ],
  'rps.stream.gap': [
    'Some live updates were missed. The complete match status is being loaded.',
    '部分实时更新未收到，正在重新读取完整对局状态。',
  ],
  'rps.result.title': ['Match result', '本局战报'],
  'rps.result.reason': ['Ending reason', '结束原因'],
  'rps.result.reason.quick_resolved': ['Quick reveal resolved', '快速模式揭晓完成'],
  'rps.result.reason.standard_round_limit': [
    'Standard round limit reached',
    '标准模式轮数到达上限',
  ],
  'rps.result.reason.standard_insufficient_balance': [
    'Standard table balance exhausted',
    '标准模式场内余额耗尽',
  ],
  'rps.result.reason.deathmatch_balance_exhausted': [
    'Deathmatch balance exhausted',
    '生死斗场内余额耗尽',
  ],
  'rps.result.reason.ultimate_resolved': ['Ultimate showdown resolved', '终极对决已决出结果'],
  'rps.result.reason.free_tie_limit': [
    'Free-tie limit reached; pool sent to welfare',
    '免费平局到达上限，奖池已注入低保池',
  ],
  'rps.result.input': ['Your total input', '本人总投入'],
  'rps.result.returned': ['Your total returned', '本人总返还'],
  'rps.result.net': ['Your wallet net', '本人的钱包净变化'],
  'rps.result.buyIn': ['Starting buy-in (actual input)', '开局带入（实际投入）'],
  'rps.result.cashOut': ['Ending cash-out in general credits', '结束带出（通用积分到账）'],
  'rps.result.unrecorded': ['Not recorded for this historical result', '该历史结果未记录'],
  'rps.result.ackWaiting': [
    'The complete private result is shown. Marking it viewed…',
    '正在保存查看状态…',
  ],
  'rps.result.ackFailed': [
    'The result could not be marked viewed. It remains here, and new matches stay locked.',
    '暂时无法标记为已查看；本结果会继续保留，新的对局仍不可加入。',
  ],
  'rps.result.ackRetry': ['Retry marking as viewed', '重试标记为已查看'],
  'rps.result.deidentified': ['Identity-hidden seat', '已隐藏身份的席位'],
  'rps.result.win': ['Net win', '净盈利'],
  'rps.result.loss': ['Net loss', '净亏损'],
  'rps.result.tie': ['No wallet change', '钱包无变化'],
  'rps.leaderboard.title': ['Rolling 30-day leaderboards', '滚动 30 天排行榜'],
  'rps.leaderboard.profit_rate': ['Profit rate', '盈利局率'],
  'rps.leaderboard.net_profit': ['Net profit', '净收益'],
  'rps.leaderboard.empty': [
    'No eligible player has reached 10 completed sessions in this mode.',
    '该模式尚无完成至少 10 局的合格玩家。',
  ],
  'rps.leaderboard.sessions': ['{{count}} sessions', '{{count}} 局'],
  'rps.leaderboard.anonymous': ['Anonymous player', '匿名玩家'],
  'rps.leaderboard.me': ['You', '本人'],
  'rps.leaderboard.player': ['Player', '玩家'],
  'rps.rules.title': ['How three-player RPS works', '三人猜拳怎么玩'],
  'rps.rules.goalTitle': ['Three players, three gestures', '三名玩家，三种手势'],
  'rps.rules.goalBody': [
    'Each match has three randomly matched players. Everyone chooses rock, scissors, or paper: rock beats scissors, scissors beats paper, and paper beats rock.',
    '每局由三名随机匹配的玩家参加。每人选择石头、剪刀或布：石头胜剪刀，剪刀胜布，布胜石头。',
  ],
  'rps.rules.roundTitle': ['Choose before the reveal', '在揭晓前出招'],
  'rps.rules.roundBody': [
    'All three choices stay hidden until the reveal, and a submitted choice cannot be changed. A gesture has a 20-second limit. The dealer then has 15 seconds to raise or decline, and both followers share a 15-second limit to call or surrender. On timeout, the game chooses a random gesture, treats the dealer as declining a raise, or treats a follower as surrendering.',
    '三人的选择会在揭晓前保持隐藏，提交后不能修改。出招限时 20 秒；之后庄家有 15 秒决定是否加注，两名闲家共用 15 秒决定跟注或认输。超时时，游戏会随机代选手势、把庄家视为不加注，或把闲家视为认输。',
  ],
  'rps.rules.scoreTitle': ['How a reveal is shared', '揭晓后如何分配'],
  'rps.rules.score.same': [
    'If all three gestures are the same, or all three gestures are different, a Quick match splits the pot into thirds; Standard and Deathmatch carry the pot forward.',
    '三人手势相同，或石头、剪刀、布各出现一次时，快速模式把奖池平均分成三份；标准模式和生死斗会把奖池继续累积。',
  ],
  'rps.rules.score.oneWinner': [
    'If one player beats two players who chose the same gesture, that player receives two-thirds of the pot and the other two receive one-sixth each.',
    '一名玩家同时战胜另外两名出相同手势的玩家时，胜者获得奖池的三分之二，另外两人各得六分之一。',
  ],
  'rps.rules.score.twoWinners': [
    'If two players with the same gesture beat the third player, the two winners split the pot equally and the losing player receives nothing.',
    '两名出相同手势的玩家共同战胜第三人时，两名胜者平分奖池，败者没有收获。',
  ],
  'rps.rules.modesTitle': ['Three ways to play', '三种玩法'],
  'rps.rules.mode.quick': [
    'Quick: each player enters with the current base stake, there is one reveal, and the match ends.',
    '快速模式：每人投入当前基础积分，揭晓一次后本局结束。',
  ],
  'rps.rules.mode.standard': [
    'Standard: each player enters with five times the current base stake. The dealer rotates for up to nine ordinary rounds. A tied pot must finish before the match can end. After a pot is settled, the match ends when nine ordinary rounds are complete or any player has less than one base stake left; every remaining in-game balance is then returned.',
    '标准模式：每人投入当前基础积分的五倍。庄家轮换，最多进行九个普通回合。尚未分配的平局奖池须先完成；奖池分配后，如果九个普通回合已经完成，或任一玩家剩余不足一份基础积分，本局结束并返还三人的场内余额。',
  ],
  'rps.rules.mode.deathmatch': [
    'Deathmatch: each player brings all currently available credits, with at least the base stake, and cannot add credits from outside during the match. The first nine ordinary stakes use the base amount; it then rises to twice the base amount and rises by one more base amount after every three ordinary stakes. During a paid tied-pot continuation, the first three stakes use its starting amount and each later tie raises the next stake by one base amount. A settled pot ends the match if any player then has no credits left. When an ordinary stake leaves all three players at zero, that hand becomes the Ultimate Showdown.',
    '生死斗：每人带入当前全部可用积分，至少需要基础积分，开局后不能从场外补充。前九次普通下注使用基础积分；之后升为两倍，并在每完成三次普通下注后再增加一倍基础积分。付费续池的前三次使用本次续池起始金额，之后每次继续平局都会让下一次增加一倍基础积分。奖池分配后若任一玩家没有剩余积分，本局结束；普通下注后若三人场内积分都变为零，该手会进入终极对决。',
  ],
  'rps.rules.feesTitle': ['Where each entry goes', '每笔投入去了哪里'],
  'rps.rules.feesBody': [
    'Every entry, base stake, raise, or continuation stake is split using the rates shown on the page: platform, welfare pool, and Thursday pool. The remainder goes into the player pot, and the same stake is never split twice.',
    '每次入场、底注、加注或续池投入，都会按页面显示的比例分到平台、低保池和疯狂星期四池，剩余部分进入奖池；同一笔投入不会重复分配。',
  ],
  'rps.rules.dealerTitle': ['Dealer rounds and raises', '庄家回合和加注'],
  'rps.rules.dealerBody': [
    'Raises are available only in Standard and Deathmatch ordinary dealer rounds. After gestures are locked, the dealer may choose no raise or enter a positive whole-credit raise up to the smallest remaining whole-credit balance. If there is a raise, each of the other two players calls with the same amount or surrenders. No raise is a separate choice from entering 0.',
    '加注只出现在标准模式和生死斗的普通庄家回合。三人出招锁定后，庄家可以不加注，也可以输入不超过三人剩余完整积分中最小值的正整数加注。有人加注时，另外两名玩家可以跟注同样金额或认输；不加注是独立选择，不是输入 0。',
  ],
  'rps.rules.surrenderBody': [
    'If both followers surrender, the dealer takes the current pot. If one follower surrenders, that player gets nothing and the dealer and the other follower split the result: half each for the same gesture, or two-thirds and one-third when one beats the other.',
    '两名闲家都认输时，庄家拿走当前奖池。一名闲家认输时，认输者没有收获，庄家和另一名闲家继续比较：手势相同则各得一半，一方胜出则按三分之二和三分之一分配。',
  ],
  'rps.rules.poolTitle': ['Tied pots', '平局奖池'],
  'rps.rules.poolBody': [
    'In Standard and Deathmatch, a reveal with three equal scores and no surrender locks the pot instead of paying it out. There is no fixed limit on paid continuation rounds. Once no more credits are added, the players continue with free reveals; the third consecutive free tie starts the reminder, and the sixth consecutive free tie ends the match and sends the locked pot to the welfare pool.',
    '标准模式和生死斗中，三人都未认输且得分相同的揭晓不会立即分配奖池，而会锁定奖池继续进行。付费续池没有固定次数上限；不再追加积分后进入免费揭晓。连续第三次免费平局开始显示提醒，连续第六次免费平局结束本局，并将锁定奖池送入低保池。',
  ],
  'rps.rules.ultimateTitle': ['Ultimate Showdown', '终极对决'],
  'rps.rules.ultimateBody': [
    'The Ultimate Showdown has no dealer, raise, call, or surrender, and no new stake is added. A non-tie ends it with the normal sharing rules. A tie starts free reveals, with at most six free decisions; a sixth consecutive free tie ends the match and sends the locked pot to the welfare pool.',
    '终极对决没有庄家、加注、跟注或认输，也不会再增加投入。第一次出现非平局就按正常比例结束；如果平局，最多进行六次免费决胜。连续第六次免费平局会结束本局，并将锁定奖池送入低保池。',
  ],
  'rps.rules.queueTitle': ['Joining and leaving', '排队和离开'],
  'rps.rules.queueBody': [
    'The three modes have separate queues. A queue can wait for up to 120 seconds; cancelling or timing out before a match releases the entry amount. Once a match starts, leaving the page or switching tabs does not pause the clock or cancel the match.',
    '三种模式分别排队，最多等待 120 秒；匹配前主动取消或等待超时会释放入场积分。对局开始后，离开页面或切换标签页不会暂停计时，也不会取消对局。',
  ],
  'rps.rules.statsTitle': ['Stats and leaderboards', '统计和排行榜'],
  'rps.rules.statsBody': [
    'At the start of a match, each player sees the other two players’ combined lifetime RPS summary from before this match. Fewer than ten completed matches shows only the match count. The two public leaderboards cover the latest 30 days, are separate for each mode, and require at least ten completed matches in that mode.',
    '开局时，三名玩家可以看到彼此在本局开始前、三种模式合计的账号存续期猜拳摘要；少于 10 局时只显示完成局数。两张公开排行榜分别按模式统计近 30 天成绩，且该模式至少完成 10 局才可进入。',
  ],
  'rps.rules.resultTitle': ['When a match ends', '对局结束时'],
  'rps.rules.resultBody': [
    'The complete result appears on this page before you can join another RPS match. If you return later, your own result remains available until the page confirms that you have viewed it.',
    '完整结果会先显示在本页，之后才能加入下一局猜拳。如果稍后回来，属于你的结果会一直保留到页面确认你已经看过为止。',
  ],
} as const satisfies Record<string, GameCopyEntry>;

type CopyKey = keyof typeof copy;

function interpolate(
  template: string,
  variables?: Readonly<Record<string, string | number>>,
): string {
  if (!variables) return template;
  return template.replace(/\{\{([A-Za-z0-9_]+)\}\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(variables, key) ? String(variables[key]) : match,
  );
}

export function useGameCopy() {
  const { i18n } = useTranslation();
  const language = i18n.resolvedLanguage?.toLowerCase().startsWith('zh') ? 'zh' : 'en';
  const localeIndex = language === 'zh' ? 1 : 0;
  const text = useCallback(
    (key: CopyKey, variables?: Readonly<Record<string, string | number>>) =>
      interpolate(copy[key][localeIndex], variables),
    [localeIndex],
  );
  return { language, text };
}

export type GameCopyKey = CopyKey;
