import { useCallback } from 'react';
import { useTranslation } from 'react-i18next';

const en = {
  'common.back': 'Back to game center',
  'common.retry': 'Try again',
  'common.loading': 'Loading authoritative game state…',
  'common.credits': 'credits',
  'common.open': 'Open',
  'common.partial': 'Partly open',
  'common.closed': 'Closed',
  'common.maintenance': 'Maintenance',
  'common.unavailable': 'Temporarily unavailable',
  'common.responseUnknown':
    'The response is unknown. No new intent will be created until this operation is reconciled.',
  'common.conflict':
    'The state changed. The latest authoritative state has been loaded; review it before trying again.',
  'common.serviceStopped':
    'The game service is recovering. Deadlines and outcomes remain server-authoritative.',
  'common.leaseActive': 'This page holds the current game lease.',
  'common.leaseRenewing': 'Confirming this page’s game lease…',
  'common.leaseLost':
    'The game lease is no longer confirmed. The server remains responsible for deadlines and default actions.',
  'common.maintenanceContinuation':
    'Maintenance is active. Keep this page open: leaving, refreshing, or losing the lease can end continuation access.',
  'common.noHistory': 'This page does not create a normal game history.',
  'center.eyebrow': 'Game lounge',
  'center.title': 'Choose your pace',
  'center.description':
    'Three server-authoritative games, each with its own recovery and settlement boundary.',
  'center.fishing.title': 'Pond fishing',
  'center.fishing.body': 'Cast once or open one atomic ten-catch batch.',
  'center.linklink.title': 'LinkLink',
  'center.linklink.body': 'Clear a recoverable board before its absolute deadline.',
  'center.rps.title': 'Three-player RPS',
  'center.rps.body': 'Queue for a live three-seat match with private gestures.',
  'center.enter': 'Enter game',
  'center.details': 'View availability',
  'center.from': 'From {{amount}} credits',
  'center.specs': '{{count}} of 3 board sizes open',
  'center.modes': '{{count}} of 3 modes open',
  'fishing.eyebrow': 'Pond fishing',
  'fishing.title': 'A quiet cast, an authoritative catch',
  'fishing.description':
    'Choose a bait and one atomic batch. Settlement and every outcome come from the server.',
  'fishing.stage.idle': 'The water is calm',
  'fishing.stage.casting': 'The float flies out',
  'fishing.stage.pending': 'The batch is settling',
  'fishing.stage.bite': 'A bite!',
  'fishing.stage.result': 'Catch revealed',
  'fishing.sound.on': 'Sound on',
  'fishing.sound.off': 'Sound off',
  'fishing.sound.hint': 'Sound starts off and is enabled only by this control.',
  'fishing.bait.worm': 'Worm',
  'fishing.bait.lure': 'Lure',
  'fishing.bait.premium': 'Premium bait',
  'fishing.batch.one': 'Single cast',
  'fishing.batch.ten': 'Atomic ten-catch',
  'fishing.selected': 'Selected bait',
  'fishing.unitPrice': 'Unit price',
  'fishing.totalPrice': 'Frozen batch total',
  'fishing.balance': 'Available balance',
  'fishing.start': 'Start this batch',
  'fishing.starting': 'Submitting one batch…',
  'fishing.insufficient': 'The authoritative balance is not enough for this batch.',
  'fishing.closed':
    'New fishing batches are closed. Closed is an availability state, not an empty pond.',
  'fishing.runtimeUnavailable': 'The fishing runtime is not ready, so no paid batch can start.',
  'fishing.pending.title': 'This batch is already accepted',
  'fishing.pending.body': 'Do not repeat it. New starts are locked while the same batch settles.',
  'fishing.pending.next': 'Next automatic attempt: {{time}}',
  'fishing.recovery.title': 'This batch needs explicit recovery',
  'fishing.recovery.body':
    'Recovery reuses this batch and its existing outcomes. It does not refund, redraw, change bait, or create a new batch.',
  'fishing.recovery.action': 'Recover this same batch',
  'fishing.recovery.running': 'Recovering the same batch…',
  'fishing.unknown.check': 'Check this operation',
  'fishing.unknown.replay': 'Retry the same operation identity',
  'fishing.result.title': 'This batch is committed',
  'fishing.result.total': 'Total catch',
  'fishing.result.entry': 'Entry total',
  'fishing.result.payout': 'Credits received',
  'fishing.result.balance': 'Resulting balance',
  'fishing.result.more': 'More unviewed batches are waiting and will load after this ACK.',
  'fishing.result.ackWaiting': 'The complete result is rendered. Marking it viewed…',
  'fishing.result.ackFailed':
    'The ACK did not complete. This exact result remains visible and settlement is unchanged.',
  'fishing.result.ackRetry': 'Retry result ACK',
  'fishing.tier.common': 'Common',
  'fishing.tier.rare': 'Rare',
  'fishing.tier.legendary': 'Legendary',
  'fishing.tier.junk': 'Pond find',
  'fishing.tier.treasure': 'Treasure',
  'fishing.size': '{{size}} cm',
  'fishing.reward': '{{amount}} credits',
  'fishing.leaderboard.single': 'Largest single catch',
  'fishing.leaderboard.total': '30-day total catch',
  'fishing.leaderboard.helpSingle':
    'All-time Top 20 plus your row, with deterministic hidden ties.',
  'fishing.leaderboard.helpTotal': 'Rolling 30-day Top 20 plus your row.',
  'fishing.leaderboard.empty': 'No eligible rows yet.',
  'fishing.leaderboard.catch': 'Catch',
  'fishing.leaderboard.score': 'Result',
  'fishing.leaderboard.angler': 'Angler',
  'fishing.leaderboard.anonymous': 'Anonymous angler',
  'fishing.leaderboard.me': 'You',
  'linklink.eyebrow': 'LinkLink',
  'linklink.title': 'Clear the board, keep the authority',
  'linklink.description':
    'Selection is local; paths, removal, rearrangement, revision, deadline, and terminal state belong to the server.',
  'linklink.spec': '{{spec}} board',
  'linklink.seconds': '{{seconds}} second absolute limit',
  'linklink.price': '{{amount}} credits',
  'linklink.specClosed': 'This size is closed',
  'linklink.startReview': 'Review paid start',
  'linklink.startConsequences':
    'Starting charges the displayed price once. An existing active board is restored with no second charge.',
  'linklink.start': 'Start {{spec}}',
  'linklink.starting': 'Starting or restoring…',
  'linklink.active': 'Active authoritative board',
  'linklink.progress': '{{removed}} / {{total}} pairs removed',
  'linklink.deadline': 'Absolute deadline',
  'linklink.remaining': '{{seconds}} seconds shown locally; the server decides timeout',
  'linklink.selectFirst': 'Select the first tile.',
  'linklink.selectSecond':
    'Select a matching tile. The server alone decides whether a path exists.',
  'linklink.matching': 'Submitting coordinates and revision…',
  'linklink.matchAccepted': 'The server accepted and removed that pair.',
  'linklink.matchRejected': 'The server did not accept that pair. No tile was removed.',
  'linklink.rearranged':
    'No moves remained, so the server applied a free authoritative rearrangement.',
  'linklink.abandon': 'Abandon this board',
  'linklink.abandonTitle': 'Abandon without refund?',
  'linklink.abandonBody':
    'This board becomes terminal with no refund and no performance score. A later board is charged again.',
  'linklink.keep': 'Keep playing',
  'linklink.confirmAbandon': 'Abandon with no refund',
  'linklink.summary.completed': 'Board completed',
  'linklink.summary.timed_out': 'Absolute deadline reached',
  'linklink.summary.abandoned': 'Board abandoned',
  'linklink.summary.score': 'Performance score',
  'linklink.summary.none': 'No performance score',
  'linklink.summary.elapsed': 'Elapsed play time',
  'linklink.summary.remaining': 'Time left at terminal state',
  'linklink.summary.seconds': '{{seconds}} seconds',
  'linklink.summary.new': 'Start another board',
  'linklink.empty': 'No active board or recent 30-day summary.',
  'rps.eyebrow': 'Three-player RPS',
  'rps.title': 'Three seats, one authoritative table',
  'rps.description':
    'The page sends only legal intent. Hidden gestures, phases, defaults, and settlement remain server-owned.',
  'rps.tutorial.title': 'How this table works',
  'rps.tutorial.1': 'Choose one of three modes. Matching shows only an ordinary waiting state.',
  'rps.tutorial.2':
    'Gestures stay absent from the wire until the server reveals them. Deadlines never wait for animation.',
  'rps.tutorial.3':
    'A terminal result must render here before its account-level ACK unlocks a new RPS queue.',
  'rps.tutorial.next': 'Next',
  'rps.tutorial.skip': 'Skip for now',
  'rps.tutorial.finish': 'Enter the lobby',
  'rps.tutorial.replay': 'Replay tutorial',
  'rps.tutorial.saveFailed':
    'Tutorial completion was not saved. You can still play; it will appear again next time.',
  'rps.mode.quick': 'Quick',
  'rps.mode.standard': 'Standard',
  'rps.mode.deathmatch': 'Deathmatch',
  'rps.mode.quickHelp': 'One resolved reveal, then terminal settlement.',
  'rps.mode.standardHelp': 'Five-base entry, dealer rounds, raises, and pooled ties.',
  'rps.mode.deathmatchHelp': 'Your full available balance enters the table and can be lost.',
  'rps.base': 'Frozen base',
  'rps.entry': 'Entry commitment',
  'rps.insufficient': 'The authoritative balance cannot cover this mode’s entry commitment.',
  'rps.queueTime': '{{seconds}} second queue deadline',
  'rps.queue': 'Join {{mode}} queue',
  'rps.queueing': 'Joining one queue…',
  'rps.deathmatchReview':
    'Deathmatch uses the full authoritative available balance. Settlement, not this confirmation, decides the result.',
  'rps.deathmatchConfirm': 'I understand; join deathmatch',
  'rps.pendingQueue': 'Waiting for two other players…',
  'rps.pendingQueuePrivacy':
    'Relationship and network signals are never shown. Waiting always looks the same.',
  'rps.cancelQueue': 'Cancel queue and release the reservation',
  'rps.match.title': 'Live match',
  'rps.phase.gesture': 'Choose a gesture',
  'rps.phase.dealer_raise': 'Dealer decision',
  'rps.phase.followers': 'Follower decision',
  'rps.phase.paid_pool_gesture': 'Paid pooled reveal',
  'rps.phase.free_pool_gesture': 'Free pooled reveal',
  'rps.phase.ultimate_gesture': 'Ultimate showdown',
  'rps.phase.terminal_processing': 'Terminal settlement is processing',
  'rps.phaseDeadline': 'Authoritative phase deadline',
  'rps.waiting': 'Your action is locked or another seat must act.',
  'rps.gesture.rock': 'Rock',
  'rps.gesture.scissors': 'Scissors',
  'rps.gesture.paper': 'Paper',
  'rps.gesture.hidden': 'Hidden until reveal',
  'rps.gesture.locked': 'Gesture locked',
  'rps.dealer.noRaise': 'Do not raise',
  'rps.dealer.raise': 'Raise',
  'rps.dealer.integerOnly': 'Positive whole credits only. Maximum: {{max}}.',
  'rps.dealer.noCapacity': 'Less than 1 whole credit remains; only no raise is legal.',
  'rps.follower.call': 'Call',
  'rps.follower.surrender': 'Surrender',
  'rps.actionSending': 'Submitting this phase identity…',
  'rps.seat.deleted': 'Deleted participant',
  'rps.seat.balance': 'Table balance',
  'rps.seat.input': 'This round',
  'rps.seat.allIn': 'All in',
  'rps.seat.managed': 'Server-managed defaults: {{count}}',
  'rps.fun.none': 'No completed history',
  'rps.fun.insufficient': '{{count}} completed — sample too small',
  'rps.fun.full': '{{count}} completed · {{rate}}% profitable',
  'rps.fun.gesture': '{{gesture}} {{count}} · {{rate}}%',
  'rps.fun.managed': 'Gesture counts include server-managed timeout gestures.',
  'rps.pool': 'Player pool',
  'rps.permanentMultiplier': 'Permanent plan multiplier',
  'rps.planMultiplier': 'Current plan multiplier',
  'rps.poolMultiplier': 'Pool base multiplier',
  'rps.raiseAmount': 'Dealer raise',
  'rps.baseRounds': 'Completed base rounds',
  'rps.paidTies': 'Paid-pool ties',
  'rps.freeTies': 'Free-pool ties (limit {{limit}})',
  'rps.poolStreaks': 'Current pool streaks',
  'rps.poolStreakValues': 'paid {{paid}} · free {{free}}',
  'rps.cuts':
    'Committed cuts: platform {{platform}}, welfare {{welfare}}, Thursday {{thursday}} credits',
  'rps.welfareCarry': 'Welfare carry: {{amount}} credits',
  'rps.reminder':
    'Fight to the last moment… The sixth consecutive free tie sends the locked pool to welfare.',
  'rps.ultimate':
    'Ultimate showdown: no dealer, no raise, no new stake. A tie allows at most six free decisions.',
  'rps.stream.connecting': 'Connecting to the shared account stream…',
  'rps.stream.connected': 'Shared account stream connected.',
  'rps.stream.disconnected':
    'Shared stream disconnected. This is not proof of a lost game lease; authority is being re-read.',
  'rps.stream.gap': 'A replay gap occurred. The full authoritative state is being re-read.',
  'rps.result.title': 'Pending result',
  'rps.result.reason': 'Terminal reason',
  'rps.result.reason.quick_resolved': 'Quick reveal resolved',
  'rps.result.reason.standard_round_limit': 'Standard round limit reached',
  'rps.result.reason.standard_insufficient_balance': 'Standard table balance exhausted',
  'rps.result.reason.deathmatch_balance_exhausted': 'Deathmatch balance exhausted',
  'rps.result.reason.ultimate_resolved': 'Ultimate showdown resolved',
  'rps.result.reason.free_tie_limit': 'Free-tie limit reached; pool sent to welfare',
  'rps.result.input': 'Your total input',
  'rps.result.returned': 'Your total returned',
  'rps.result.net': 'Your wallet net',
  'rps.result.ackWaiting': 'The complete private result is rendered. Sending the account ACK…',
  'rps.result.ackFailed': 'ACK failed. This result remains and every RPS mode stays queue-locked.',
  'rps.result.ackRetry': 'Retry result ACK',
  'rps.result.deidentified': 'Deidentified seat',
  'rps.result.win': 'Net win',
  'rps.result.loss': 'Net loss',
  'rps.result.tie': 'No wallet change',
  'rps.leaderboard.title': 'Rolling 30-day leaderboards',
  'rps.leaderboard.profit_rate': 'Profit rate',
  'rps.leaderboard.net_profit': 'Net profit',
  'rps.leaderboard.empty': 'No eligible player has reached 10 completed sessions in this mode.',
  'rps.leaderboard.sessions': '{{count}} sessions',
  'rps.leaderboard.anonymous': 'Anonymous player',
  'rps.leaderboard.me': 'You',
  'rps.leaderboard.player': 'Player',
} as const;

type CopyKey = keyof typeof en;

const zh: Record<CopyKey, string> = {
  'common.back': '返回游戏中心',
  'common.retry': '重试',
  'common.loading': '正在读取权威游戏状态…',
  'common.credits': '积分',
  'common.open': '开放',
  'common.partial': '部分开放',
  'common.closed': '关闭',
  'common.maintenance': '维护中',
  'common.unavailable': '暂时不可用',
  'common.responseUnknown': '响应结果未知。在本次操作完成权威对账前，不会创建新意图。',
  'common.conflict': '状态已经变化。已读取最新权威状态，请重新确认后再操作。',
  'common.serviceStopped': '游戏服务正在恢复；deadline 与结果仍以服务端为准。',
  'common.leaseActive': '当前页面持有本局在线租约。',
  'common.leaseRenewing': '正在确认当前页面的游戏租约…',
  'common.leaseLost': '本局租约已无法确认；deadline 与托管动作仍由服务端负责。',
  'common.maintenanceContinuation':
    '维护已开启。请保持本页打开；离开、刷新或租约失效后可能无法继续。',
  'common.noHistory': '本页不会建立普通游戏历史。',
  'center.eyebrow': '游戏小馆',
  'center.title': '挑一种轻松节奏',
  'center.description': '三款服务端权威小游戏，各自拥有独立的恢复与结算边界。',
  'center.fishing.title': '池塘垂钓',
  'center.fishing.body': '单次抛竿，或开启一个原子十连批次。',
  'center.linklink.title': '连连看',
  'center.linklink.body': '在绝对截止时间前消除可恢复的权威棋盘。',
  'center.rps.title': '三人猜拳',
  'center.rps.body': '进入三席实时匹配，未揭晓手势始终保密。',
  'center.enter': '进入游戏',
  'center.details': '查看开放状态',
  'center.from': '{{amount}} 积分起',
  'center.specs': '3 种棋盘开放 {{count}} 种',
  'center.modes': '3 种模式开放 {{count}} 种',
  'fishing.eyebrow': '池塘垂钓',
  'fishing.title': '悠闲抛竿，权威收获',
  'fishing.description': '选择鱼饵和一个原子批次；结算与每个 outcome 都只来自服务端。',
  'fishing.stage.idle': '水面正安静',
  'fishing.stage.casting': '浮漂飞出',
  'fishing.stage.pending': '本批正在结算',
  'fishing.stage.bite': '上钩了！',
  'fishing.stage.result': '收获已揭晓',
  'fishing.sound.on': '声音已开启',
  'fishing.sound.off': '声音已关闭',
  'fishing.sound.hint': '声音默认关闭，只能通过这个用户操作开启。',
  'fishing.bait.worm': '蚯蚓',
  'fishing.bait.lure': '拟饵',
  'fishing.bait.premium': '高级鱼饵',
  'fishing.batch.one': '单次抛竿',
  'fishing.batch.ten': '原子十连',
  'fishing.selected': '已选鱼饵',
  'fishing.unitPrice': '权威单价',
  'fishing.totalPrice': '冻结批次总价',
  'fishing.balance': '可用余额',
  'fishing.start': '开始本批',
  'fishing.starting': '正在提交一个批次…',
  'fishing.insufficient': '权威余额不足以开始这个批次。',
  'fishing.closed': '新垂钓批次已关闭；关闭是开放状态，不是池塘空数据。',
  'fishing.runtimeUnavailable': '垂钓运行时尚未就绪，不能开始付费批次。',
  'fishing.pending.title': '本批已经受理',
  'fishing.pending.body': '请勿重复操作；同一批次结算期间，所有新开始都已锁住。',
  'fishing.pending.next': '下次自动尝试：{{time}}',
  'fishing.recovery.title': '本批需要明确恢复',
  'fishing.recovery.body': '恢复会复用本批及既有结果，不退款、不重抽、不换鱼饵，也不创建新批次。',
  'fishing.recovery.action': '恢复同一批次',
  'fishing.recovery.running': '正在恢复同一批次…',
  'fishing.unknown.check': '检查本次操作',
  'fishing.unknown.replay': '复用同一操作身份重试',
  'fishing.result.title': '本批已经提交结算',
  'fishing.result.total': '本次总收获',
  'fishing.result.entry': '投入总额',
  'fishing.result.payout': '获得积分',
  'fishing.result.balance': '结算后余额',
  'fishing.result.more': '还有未查看批次；当前 ACK 后将继续读取。',
  'fishing.result.ackWaiting': '完整结果已经真实渲染，正在标记为已查看…',
  'fishing.result.ackFailed': 'ACK 未完成；同一结果继续保留，经济结算不受影响。',
  'fishing.result.ackRetry': '重试结果 ACK',
  'fishing.tier.common': '普通',
  'fishing.tier.rare': '稀有',
  'fishing.tier.legendary': '传说',
  'fishing.tier.junk': '池塘杂物',
  'fishing.tier.treasure': '宝物',
  'fishing.size': '{{size}} 厘米',
  'fishing.reward': '{{amount}} 积分',
  'fishing.leaderboard.single': '单次最大收获',
  'fishing.leaderboard.total': '近 30 天总收获',
  'fishing.leaderboard.helpSingle': '全期 Top 20 与本人行；并列由隐藏稳定键确定。',
  'fishing.leaderboard.helpTotal': '滚动 30 天 Top 20 与本人行。',
  'fishing.leaderboard.empty': '暂时没有符合条件的记录。',
  'fishing.leaderboard.catch': '收获',
  'fishing.leaderboard.score': '成绩',
  'fishing.leaderboard.angler': '垂钓者',
  'fishing.leaderboard.anonymous': '匿名垂钓者',
  'fishing.leaderboard.me': '本人',
  'linklink.eyebrow': '连连看',
  'linklink.title': '消除棋盘，权威始终在线',
  'linklink.description':
    '选择只存在本地；路径、消除、重排、revision、deadline 与终态都由服务端决定。',
  'linklink.spec': '{{spec}} 棋盘',
  'linklink.seconds': '{{seconds}} 秒绝对时限',
  'linklink.price': '{{amount}} 积分',
  'linklink.specClosed': '该规格已关闭',
  'linklink.startReview': '确认付费开始',
  'linklink.startConsequences': '开始时只扣显示门票一次；若已有在途棋盘，将零重复扣费地恢复。',
  'linklink.start': '开始 {{spec}}',
  'linklink.starting': '正在开始或恢复…',
  'linklink.active': '权威在途棋盘',
  'linklink.progress': '已消除 {{removed}} / {{total}} 对',
  'linklink.deadline': '绝对截止时间',
  'linklink.remaining': '本地显示 {{seconds}} 秒；是否超时只由服务端决定',
  'linklink.selectFirst': '请选择第一枚图块。',
  'linklink.selectSecond': '请选择配对图块；路径是否存在只由服务端判断。',
  'linklink.matching': '正在提交坐标和 revision…',
  'linklink.matchAccepted': '服务端已接受并消除这一对。',
  'linklink.matchRejected': '服务端未接受这组配对，没有图块被消除。',
  'linklink.rearranged': '棋盘无可消除对，服务端已免费完成权威重排。',
  'linklink.abandon': '放弃本局',
  'linklink.abandonTitle': '确认不退款放弃？',
  'linklink.abandonBody': '本局将无退款终结且不计算表现分；之后的新局会重新扣费。',
  'linklink.keep': '继续游玩',
  'linklink.confirmAbandon': '确认不退款放弃',
  'linklink.summary.completed': '棋盘已完成',
  'linklink.summary.timed_out': '绝对时限已到',
  'linklink.summary.abandoned': '本局已放弃',
  'linklink.summary.score': '表现分',
  'linklink.summary.none': '本局没有表现分',
  'linklink.summary.elapsed': '本局用时',
  'linklink.summary.remaining': '终局时剩余时间',
  'linklink.summary.seconds': '{{seconds}} 秒',
  'linklink.summary.new': '开始另一局',
  'linklink.empty': '没有在途棋盘或近 30 天最小摘要。',
  'rps.eyebrow': '三人猜拳',
  'rps.title': '三席同桌，一份权威状态',
  'rps.description': '页面只提交合法意图；隐藏手势、阶段、托管和结算始终属于服务端。',
  'rps.tutorial.title': '这张桌子怎么玩',
  'rps.tutorial.1': '选择三种模式之一；匹配过程只显示普通等待状态。',
  'rps.tutorial.2': '服务端揭晓前，手势字段不会出现在 wire 中；动画不会延后 deadline。',
  'rps.tutorial.3': '终局结果必须先在本页完整渲染，账号级 ACK 成功后才能再次排队。',
  'rps.tutorial.next': '下一步',
  'rps.tutorial.skip': '暂时跳过',
  'rps.tutorial.finish': '进入大厅',
  'rps.tutorial.replay': '重看玩法演示',
  'rps.tutorial.saveFailed': '演示完成状态未保存；本次仍可游玩，下次会再次显示。',
  'rps.mode.quick': '快速模式',
  'rps.mode.standard': '标准模式',
  'rps.mode.deathmatch': '生死斗',
  'rps.mode.quickHelp': '一次可结算揭晓后进入终局。',
  'rps.mode.standardHelp': '五倍基础入场、庄家轮、加注和锁池平局。',
  'rps.mode.deathmatchHelp': '全部可用余额进入场内，并可能全部损失。',
  'rps.base': '冻结基础积分',
  'rps.entry': '入场预留',
  'rps.insufficient': '权威余额不足以覆盖该模式的入场预留。',
  'rps.queueTime': '{{seconds}} 秒排队截止',
  'rps.queue': '进入{{mode}}队列',
  'rps.queueing': '正在进入唯一队列…',
  'rps.deathmatchReview': '生死斗会让全部权威可用余额进入场内；结果由结算决定，不由本确认决定。',
  'rps.deathmatchConfirm': '我已了解，进入生死斗',
  'rps.pendingQueue': '正在等待另外两名玩家…',
  'rps.pendingQueuePrivacy': '关系和网络信号绝不展示；所有等待看起来都完全相同。',
  'rps.cancelQueue': '取消排队并释放预留',
  'rps.match.title': '实时对局',
  'rps.phase.gesture': '选择手势',
  'rps.phase.dealer_raise': '庄家决策',
  'rps.phase.followers': '闲家决策',
  'rps.phase.paid_pool_gesture': '付费续池出招',
  'rps.phase.free_pool_gesture': '免费续池出招',
  'rps.phase.ultimate_gesture': '终极对决',
  'rps.phase.terminal_processing': '正在完成终局结算',
  'rps.phaseDeadline': '权威阶段截止',
  'rps.waiting': '你的动作已锁定，或正在等待其他席位。',
  'rps.gesture.rock': '石头',
  'rps.gesture.scissors': '剪刀',
  'rps.gesture.paper': '布',
  'rps.gesture.hidden': '揭晓前隐藏',
  'rps.gesture.locked': '手势已锁定',
  'rps.dealer.noRaise': '不加注',
  'rps.dealer.raise': '加注',
  'rps.dealer.integerOnly': '只支持正整数积分；上限 {{max}}。',
  'rps.dealer.noCapacity': '上限不足 1 个完整积分，本手只能不加注。',
  'rps.follower.call': '跟注',
  'rps.follower.surrender': '认输',
  'rps.actionSending': '正在提交当前 phase identity…',
  'rps.seat.deleted': '已删除参与者',
  'rps.seat.balance': '场内余额',
  'rps.seat.input': '本轮投入',
  'rps.seat.allIn': '全押',
  'rps.seat.managed': '服务端托管动作：{{count}} 次',
  'rps.fun.none': '暂无已完成数据',
  'rps.fun.insufficient': '已完成 {{count}} 局 · 样本不足',
  'rps.fun.full': '已完成 {{count}} 局 · 盈利局率 {{rate}}%',
  'rps.fun.gesture': '{{gesture}} {{count}} 次 · {{rate}}%',
  'rps.fun.managed': '手势次数包含服务端托管出拳。',
  'rps.pool': '玩家奖池',
  'rps.permanentMultiplier': '永久计划倍率',
  'rps.planMultiplier': '当前计划倍率',
  'rps.poolMultiplier': '续池基线倍率',
  'rps.raiseAmount': '庄家加注',
  'rps.baseRounds': '已完成基础回合',
  'rps.paidTies': '付费续池平局',
  'rps.freeTies': '免费续池平局（上限 {{limit}}）',
  'rps.poolStreaks': '当前续池连续次数',
  'rps.poolStreakValues': '付费 {{paid}} · 免费 {{free}}',
  'rps.cuts': '已提交抽水：平台 {{platform}}、低保 {{welfare}}、疯四 {{thursday}} 积分',
  'rps.welfareCarry': '低保结转：{{amount}} 积分',
  'rps.reminder': '战至最后一刻……第六次连续免费平局会把锁定奖池注入低保池。',
  'rps.ultimate': '终极对决：无庄家、无加注、不再下注；平局后最多六次免费决胜。',
  'rps.stream.connecting': '正在连接共享账号事件流…',
  'rps.stream.connected': '共享账号事件流已连接。',
  'rps.stream.disconnected': '共享事件流已断开；这不等于游戏租约失效，正在重读权威状态。',
  'rps.stream.gap': '事件 replay 出现 gap，正在重读完整权威状态。',
  'rps.result.title': '待查看结果',
  'rps.result.reason': '终局原因',
  'rps.result.reason.quick_resolved': '快速模式揭晓完成',
  'rps.result.reason.standard_round_limit': '标准模式轮数到达上限',
  'rps.result.reason.standard_insufficient_balance': '标准模式场内余额耗尽',
  'rps.result.reason.deathmatch_balance_exhausted': '生死斗场内余额耗尽',
  'rps.result.reason.ultimate_resolved': '终极对决已决出结果',
  'rps.result.reason.free_tie_limit': '免费平局到达上限，奖池已注入低保池',
  'rps.result.input': '本人总投入',
  'rps.result.returned': '本人总返还',
  'rps.result.net': '本人的钱包净变化',
  'rps.result.ackWaiting': '完整私有结果已经渲染，正在发送账号级 ACK…',
  'rps.result.ackFailed': 'ACK 失败；本结果继续保留，三种猜拳模式仍禁止排队。',
  'rps.result.ackRetry': '重试结果 ACK',
  'rps.result.deidentified': '去标识席位',
  'rps.result.win': '净盈利',
  'rps.result.loss': '净亏损',
  'rps.result.tie': '钱包无变化',
  'rps.leaderboard.title': '滚动 30 天排行榜',
  'rps.leaderboard.profit_rate': '盈利局率',
  'rps.leaderboard.net_profit': '净收益',
  'rps.leaderboard.empty': '该模式尚无完成至少 10 局的合格玩家。',
  'rps.leaderboard.sessions': '{{count}} 局',
  'rps.leaderboard.anonymous': '匿名玩家',
  'rps.leaderboard.me': '本人',
  'rps.leaderboard.player': '玩家',
};

function interpolate(
  template: string,
  variables?: Readonly<Record<string, string | number>>,
): string {
  if (!variables) return template;
  return template.replace(/\{\{([A-Za-z0-9_]+)\}\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(variables, key) ? String(variables[key]) : match,
  );
}

export function useGameCopy() {
  const { i18n } = useTranslation();
  const language = i18n.resolvedLanguage?.toLowerCase().startsWith('zh') ? 'zh' : 'en';
  const dictionary = language === 'zh' ? zh : en;
  const text = useCallback(
    (key: CopyKey, variables?: Readonly<Record<string, string | number>>) =>
      interpolate(dictionary[key], variables),
    [dictionary],
  );
  return { language, text };
}

export type GameCopyKey = CopyKey;
