export function charityControlCopy(language: string) {
  return language.startsWith('zh')
    ? {
        thanks: '是否接受 Discord 公屏感谢',
        yes: '是',
        no: '否',
        unknown: '未确认',
        choose: '请选择',
        thanksHint: '由管理员或 6 级协管手动发送；提交后不可更改。',
        donorNote: '捐赠者备注',
        approvalNote: '审批备注',
        keyNote: '密钥备注',
        mainstream: '主流渠道公益模型',
        excluded: '排除的请求参数',
        excludedHint: '填写顶层参数名，以空格或逗号分隔；路由、输入和响应方式等关键参数不可排除。',
        excludedInvalid: '参数名无效、超过 32 项，或包含不可排除的关键参数。',
        halfPrice: '回馈填入定价的一半',
        keyUsage: '状态与用量',
        cumulativeLimits: '累计限额',
        tokenReservations: 'Token 预留',
        keyManagement: '有效期与管理设置',
        basicSettings: '基本信息',
        accessRouting: '访问与路由',
        pricingRewards: '计价与回馈',
        discountSettings: '折扣',
        halfInvalid: '请先填写有效的用户定价。',
        trainee: '见习协管',
        selectModel: '选择主流公益模型',
        manageKey: '维护密钥',
        shared: '此密钥的公益配置由所有绑定共用，修改会同时影响这些绑定。',
        totalBindings: '全部绑定数量',
        visibleModels: '可查看的关联模型',
        truncated: '仅显示前 20 个模型。',
        recent: '近期请求成功率',
        window: '最近 24 小时',
        insufficient: '样本不足',
        samples: '已完成样本',
        cancelled: '已排除取消请求',
        totalTokens: '总 token 限额',
        inputTokens: '输入 token 限额',
        outputTokens: '输出 token 限额',
        inputReserve: '输入 token 预留量',
        outputReserve: '输出 token 预留量',
        splitHint:
          '限额留空表示不限，三项共同生效。启用输入或输出限额前，请同时填写两项预留量；预留量之和必须大于 0。',
        breakdown: '分项统计起点',
        unattributed: '未拆分的总 token 用量',
      }
    : {
        thanks: 'Accept a public Discord thank-you',
        yes: 'Yes',
        no: 'No',
        unknown: 'Unconfirmed',
        choose: 'Select an option',
        thanksHint:
          'An administrator or level 6 steward sends it manually. This choice cannot change after submission.',
        donorNote: 'Donor note',
        approvalNote: 'Approval note',
        keyNote: 'Key note',
        mainstream: 'Mainstream charity model',
        excluded: 'Excluded request parameters',
        excludedHint:
          'Enter top-level field names separated by spaces or commas. Routing, input and response-control fields cannot be removed.',
        excludedInvalid: 'Invalid parameter name, more than 32 fields, or a protected field.',
        halfPrice: 'Fill rewards with half the price',
        keyUsage: 'Status and usage',
        cumulativeLimits: 'Cumulative limits',
        tokenReservations: 'Token reservations',
        keyManagement: 'Expiry and management',
        basicSettings: 'Basic information',
        accessRouting: 'Access and routing',
        pricingRewards: 'Pricing and rewards',
        discountSettings: 'Discount',
        halfInvalid: 'Enter valid user prices first.',
        trainee: 'Trainee steward',
        selectModel: 'Select a mainstream charity model',
        manageKey: 'Manage key',
        shared:
          'All bindings share this key’s charity configuration. Changes affect every binding.',
        totalBindings: 'Total bindings',
        visibleModels: 'Visible related models',
        truncated: 'Only the first 20 models are shown.',
        recent: 'Recent request success rate',
        window: 'Last 24 hours',
        insufficient: 'Insufficient sample',
        samples: 'Completed samples',
        cancelled: 'Cancelled requests excluded',
        totalTokens: 'Total token limit',
        inputTokens: 'Input token limit',
        outputTokens: 'Output token limit',
        inputReserve: 'Input token reservation',
        outputReserve: 'Output token reservation',
        splitHint:
          'Blank limits are unlimited; all configured limits apply. Input or output limits require both reservations, with a positive combined value.',
        breakdown: 'Breakdown tracking started',
        unattributed: 'Unattributed total token usage',
      };
}
