export const alertDetailCopy = {
  en: {
    details: 'Alert details',
    open: 'Details',
    close: 'Close details',
    back: 'Return to previous page',
    facts: 'When it happened',
    current: 'Current state',
    targets: 'Related objects',
    logs: 'Related request logs',
    diagnostic: 'Exact object diagnostic',
    projectionDiagnostic: 'Issue projection',
    closeDiagnostic: 'Close diagnostic',
    relatedIssues: 'Retained related issue IDs',
    noRelatedIssues: 'No related issues are currently retained.',
    projectionPhases: {
      not_recorded: 'No projection state recorded',
      complete: 'Complete',
      incomplete: 'Incomplete',
      checkpointed: 'Saved rebuild checkpoint',
    },
    unknown: 'Unknown for this earlier alert',
    missing: 'The object is no longer available.',
    noTarget: 'This reference cannot be linked reliably.',
    noFacts: 'No structured event facts were retained.',
    noLogs: 'No request logs remain in the event window.',
    eventWindow: 'From 15 minutes before to 5 minutes after this alert',
    technicalReference: 'Technical reference',
    copied: 'Copied',
    copy: 'Copy reference',
    resolution: 'Resolution',
    unresolved: 'Not resolved',
    occurred: 'Occurred',
    state: 'Status',
    targetNames: {
      deleted_account: 'Deleted account',
      donation: 'Donation',
      donation_key: 'Donation key',
      endpoint_key: 'Endpoint key',
      endpoint: 'Endpoint',
      user: 'User',
      report_case: 'Report',
      issue: 'Issue',
      fishing_batch: 'Fishing batch',
      rps_session: 'RPS match',
      request_log: 'Request log',
      maintenance_event: 'Maintenance event',
      worker_checkpoint: 'Lifecycle worker',
    },
    factNames: {
      actor_role: 'Actor role',
      reason: 'Reason',
      operation: 'Operation',
      error_class: 'Error class',
      attempts: 'Attempts at event',
      generation: 'Generation',
      fold: 'Fold sequence',
      policy_revision: 'Policy revision',
      donation_id: 'Donation ID',
      donation_key_id: 'Donation key ID',
      endpoint_key_id: 'Endpoint key ID',
      failure_streak: 'Failure count at event',
      failure_threshold: 'Disable threshold at event',
      worker_domain: 'Worker domain',
      worker_stage: 'Worker stage',
      last_error_class: 'Last error class',
      attempt_count: 'Retry attempts',
      next_attempt_at: 'Next attempt',
      checkpoint_updated_at: 'Checkpoint updated',
      last_success_at: 'Last successful pass',
      maintenance_enabled: 'Maintenance enabled',
      endpoint_key: 'Endpoint key',
      user_id: 'User ID',
      source: 'Source',
      resource_kind: 'Resource kind',
      root_cause: 'Root cause',
      state: 'State',
      first_seen_at: 'First seen',
      last_seen_at: 'Last seen',
      count: 'Occurrence count',
      closed_at: 'Closed',
      retry_exhausted: 'Retry limit reached',
      created_at: 'Created',
      settled_at: 'Settled',
      mode: 'Mode',
      phase: 'Phase',
      retry_attempts: 'Terminal retry attempts',
      started_at: 'Started',
      terminal_reason: 'Terminal reason',
      terminal_at: 'Finished',
      projection_phase: 'Projection stage',
      rebuild_generation: 'Rebuild generation',
      projection_updated_at: 'Projection updated',
      retained_issue_count: 'Retained issues',
      current_issue_count: 'Current issues',
    },
  },
  zh: {
    details: '告警详情',
    open: '详情',
    close: '关闭详情',
    back: '返回原页面',
    facts: '发生时事实',
    current: '当前状态',
    targets: '关联对象',
    logs: '相关请求日志',
    diagnostic: '精确对象诊断',
    projectionDiagnostic: '问题投影',
    closeDiagnostic: '关闭诊断',
    relatedIssues: '仍保留的相关问题 ID',
    noRelatedIssues: '当前未保留相关问题。',
    projectionPhases: {
      not_recorded: '未记录投影状态',
      complete: '已完成',
      incomplete: '未完成',
      checkpointed: '已保存重建检查点',
    },
    unknown: '历史告警未记录',
    missing: '对象已不可用。',
    noTarget: '无法可靠定位此引用。',
    noFacts: '未保留结构化事件事实。',
    noLogs: '事件时间范围内已无保留的请求日志。',
    eventWindow: '告警前15分钟至后5分钟',
    technicalReference: '技术引用',
    copied: '已复制',
    copy: '复制引用',
    resolution: '处置',
    unresolved: '未解决',
    occurred: '发生时间',
    state: '状态',
    targetNames: {
      deleted_account: '历史账号',
      donation: '捐赠',
      donation_key: '捐赠凭据',
      endpoint_key: '端点凭据',
      endpoint: '端点',
      user: '用户',
      report_case: '举报',
      issue: '问题',
      fishing_batch: '垂钓批次',
      rps_session: '猜拳对局',
      request_log: '请求日志',
      maintenance_event: '维护事件',
      worker_checkpoint: '生命周期任务',
    },
    factNames: {
      actor_role: '操作角色',
      reason: '原因',
      operation: '操作',
      error_class: '错误类别',
      attempts: '发生时重试次数',
      generation: '代次',
      fold: '折叠序号',
      policy_revision: '策略修订号',
      donation_id: '捐赠 ID',
      donation_key_id: '捐赠凭据 ID',
      endpoint_key_id: '端点凭据 ID',
      failure_streak: '发生时失败次数',
      failure_threshold: '发生时停用阈值',
      worker_domain: '任务域',
      worker_stage: '任务阶段',
      last_error_class: '最近错误类别',
      attempt_count: '当前重试次数',
      next_attempt_at: '下次尝试',
      checkpoint_updated_at: '检查点更新时间',
      last_success_at: '上次成功执行',
      maintenance_enabled: '维护已启用',
      endpoint_key: '端点凭据',
      user_id: '用户 ID',
      source: '来源',
      resource_kind: '资源类型',
      root_cause: '根因',
      state: '状态',
      first_seen_at: '首次发现',
      last_seen_at: '最近发现',
      count: '发生次数',
      closed_at: '关闭时间',
      retry_exhausted: '已达重试上限',
      created_at: '创建时间',
      settled_at: '结算时间',
      mode: '模式',
      phase: '阶段',
      retry_attempts: '终结重试次数',
      started_at: '开始时间',
      terminal_reason: '终结原因',
      terminal_at: '结束时间',
      projection_phase: '投影阶段',
      rebuild_generation: '重建代次',
      projection_updated_at: '投影更新时间',
      retained_issue_count: '仍保留问题数',
      current_issue_count: '当前问题数',
    },
  },
} as const;
