package db

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"reflect"
	"sort"
	"strings"
	"unicode/utf8"
)

// PinnedGenerationTwoSchemaHash makes an intentional DDL change explicit.
// It is derived from the canonical Generation 2 DDL and is checked before a
// database is opened for writing.
const PinnedGenerationTwoSchemaHash = "bc8b2e27206a59758182fffff272cc7d65975b1e4f077dfceff05a89622d7a02"

// PinnedGenerationTwoManifestHash is an independently checked-in fixture for
// the complete sqlite_schema/table_xinfo/foreign-key/index manifest.  It is
// deliberately not generated by executing the DDL constant at runtime:
// changing one DDL object without updating this fixture must fail closed.
const PinnedGenerationTwoManifestHash = "00bd568b4b8c95484134b737946add8171963a9102d0dbfa2bbe1088b664001a"

const generationTwoManifestFixture = `{"sha256":"00bd568b4b8c95484134b737946add8171963a9102d0dbfa2bbe1088b664001a"}`

// PinnedGenerationTwoFreshConfigSeedHash is an independently checked-in
// golden for the complete fresh site_config row set.  Unlike the current
// seed validator, this golden is intentionally not derived from the runtime
// configuration catalog or its INSERT helper.  The announcement epoch is
// generated per database and is canonicalized to a fixed marker before this
// digest is calculated; every other key, value, and updated_at is covered
// byte-for-byte by the ordered row digest.
const PinnedGenerationTwoFreshConfigSeedHash = "d07ead0c73eb8173f5e88cc463601bac7b72b576f22361db87e0da7a1cc0c1fc"

const generationTwoFreshConfigSeedFixture = `{"sha256":"d07ead0c73eb8173f5e88cc463601bac7b72b576f22361db87e0da7a1cc0c1fc"}`

const generationTwoFreshConfigEpochMarker = "<generated:b1e_>"

type queryer interface {
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

type schemaObject struct {
	Type, Name, Table, SQL string
}

type columnManifest struct {
	CID, NotNull, PrimaryKey, Hidden int
	Name, Type                       string
	Default                          sql.NullString
}

type foreignKeyManifest struct {
	ID, Sequence                               int
	Table, From, To, OnUpdate, OnDelete, Match string
}

type indexManifest struct {
	Name            string
	Unique, Partial int
	Origin          string
	Columns         []indexColumnManifest
}

type indexColumnManifest struct {
	Sequence, CID, Descending, Key int
	Name                           sql.NullString
	Collation                      string
}

type tableManifest struct {
	Name        string
	Columns     []columnManifest
	ForeignKeys []foreignKeyManifest
	Indexes     []indexManifest
}

type generationManifest struct {
	Objects []schemaObject
	Tables  []tableManifest
}

// generationTwoSeedManifest is intentionally independent from the structural
// schema manifest.  SQLite's sqlite_schema cannot prove that the required
// bootstrap rows (or their exact key set) exist, and a structural match must
// never make a partially seeded database writable.
type generationTwoSeedAccount struct {
	Code  string
	Kind  string
	Asset string
}

type generationTwoSeedPool struct {
	IDPrefix      string
	PoolType      string
	State         string
	Revision      int64
	AccountKind   string
	AccountPrefix string
	PeriodIsNull  bool
}

type generationTwoSeedManifest struct {
	ConfigKeys            []string
	ConfigRevisionDomains []string
	FixedAccounts         []generationTwoSeedAccount
	InitialPools          []generationTwoSeedPool
	SingletonRows         []string
}

type generationTwoFreshConfigSeedRow struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt int64  `json:"updated_at"`
}

func expectedGenerationTwoSeedManifest() generationTwoSeedManifest {
	return generationTwoSeedManifest{
		ConfigKeys:            generationTwoConfigKeys(),
		ConfigRevisionDomains: []string{"activities", "games", "site"},
		FixedAccounts: []generationTwoSeedAccount{
			{Code: "charity_reserve", Kind: "platform", Asset: "general"},
			{Code: "external", Kind: "external", Asset: "game"},
			{Code: "external", Kind: "external", Asset: "general"},
			{Code: "external", Kind: "external", Asset: "sketch_brush"},
			{Code: "external", Kind: "external", Asset: "sketch_paper"},
			{Code: "forward_reserve", Kind: "platform", Asset: "general"},
			{Code: "game_fishing_reserve", Kind: "platform", Asset: "game"},
			{Code: "game_fishing_reserve", Kind: "platform", Asset: "general"},
			{Code: "image_activity_reserve", Kind: "platform", Asset: "sketch_brush"},
			{Code: "image_activity_reserve", Kind: "platform", Asset: "sketch_paper"},
			{Code: "platform", Kind: "platform", Asset: "game"},
			{Code: "platform", Kind: "platform", Asset: "general"},
		},
		InitialPools: []generationTwoSeedPool{
			{IDPrefix: "pol_", PoolType: "welfare", AccountKind: "pool", AccountPrefix: "pool:", PeriodIsNull: true},
		},
		SingletonRows: []string{"credit_capacity", "maintenance_state", "site_usage_totals"},
	}
}

func validateGenerationTwoSeedManifest(ctx context.Context, q queryer) error {
	return validateAssetSeedManifest(ctx, q, false)
}

func validateAssetSeedManifest(ctx context.Context, q queryer, prior bool) error {
	return validateVersionSeedManifest(ctx, q, prior, prior)
}

func validateVersionSeedManifest(ctx context.Context, q queryer, priorAssets, priorDuels bool) error {
	governancePresent, err := GovernanceStoragePresent(ctx, q)
	if err != nil {
		return err
	}
	progressionPresent, err := ProgressionStoragePresent(ctx, q)
	if err != nil {
		return err
	}
	duelsPresent, err := DuelStoragePresent(ctx, q)
	if err != nil {
		return err
	}
	priorDuels = !duelsPresent
	blackjackPresent, err := BlackjackStoragePresent(ctx, q)
	if err != nil {
		return err
	}
	var gatewayColumns int
	if err := q.QueryRowContext(ctx, `SELECT count(*) FROM pragma_table_info('donation_keys') WHERE name='failure_disable_threshold'`).Scan(&gatewayColumns); err != nil {
		return err
	}
	actual, err := readAssetSeedManifest(ctx, q, priorAssets)
	if err != nil {
		return err
	}
	if err := validateGenerationTwoDynamicSeedRows(ctx, q); err != nil {
		return err
	}
	expected := expectedGenerationTwoSeedManifest()
	if !governancePresent {
		accounts := expected.FixedAccounts[:0]
		for _, account := range expected.FixedAccounts {
			if account.Asset != "sketch_paper" && account.Asset != "sketch_brush" {
				accounts = append(accounts, account)
			}
		}
		expected.FixedAccounts = accounts
	}
	if priorAssets {
		accounts := expected.FixedAccounts[:0]
		for _, account := range expected.FixedAccounts {
			if account.Asset == "general" {
				accounts = append(accounts, account)
			}
		}
		expected.FixedAccounts = accounts
	}
	// The required fresh rows are part of the seed contract, while known
	// optional rows (for example the raw-null inherited settings and dynamic
	// alert preferences) may be added or removed after bootstrap.  Comparing
	// the complete key slice here would turn an allowed optional edit into a
	// schema mismatch; unknown/deleted keys are still rejected by the config
	// validator and by this closed known-key check.
	known := make(map[string]struct{}, len(generationTwoKnownConfigKeys())+1)
	for _, key := range generationTwoKnownConfigKeys() {
		known[key] = struct{}{}
	}
	// The timezone lock is internal lifecycle metadata, not an administrator-
	// editable catalog entry. Temporal-data writers add it after fresh seed,
	// so current-database validation must recognize it without exposing it as
	// a public configuration key.
	known[timezoneLockKey] = struct{}{}
	for _, key := range actual.ConfigKeys {
		if _, added := governanceConfigDefaults()[key]; added && !governancePresent {
			return errors.New("prior schema contains governance configuration")
		}
		if _, added := progressionConfigDefaults()[key]; added && !progressionPresent {
			return errors.New("prior schema contains progression configuration")
		}
		if _, added := blackjackConfigDefaults()[key]; added && !blackjackPresent {
			return errors.New("prior schema contains blackjack configuration")
		}
		if _, added := duelConfigDefaults()[key]; added && priorDuels {
			return errors.New("prior schema contains duel configuration")
		}
		if _, ok := known[key]; !ok {
			return fmt.Errorf("generation-two seed contains unknown site configuration %q", key)
		}
	}
	required := make(map[string]struct{}, len(expected.ConfigKeys))
	for _, key := range expected.ConfigKeys {
		if _, added := governanceConfigDefaults()[key]; added && !governancePresent {
			continue
		}
		if _, added := progressionConfigDefaults()[key]; added && !progressionPresent {
			continue
		}
		if key == "gateway_user_attribution_enabled" && gatewayColumns == 0 {
			continue
		}
		if _, added := blackjackConfigDefaults()[key]; added && !blackjackPresent {
			continue
		}
		if priorAssets && priorAssetOptionalConfig(key) {
			continue
		}
		if _, added := duelConfigDefaults()[key]; added && priorDuels {
			continue
		}
		required[key] = struct{}{}
	}
	for key := range required {
		if !containsSortedString(actual.ConfigKeys, key) {
			return fmt.Errorf("generation-two seed is missing required site configuration %q", key)
		}
	}
	actual.ConfigKeys = nil
	expected.ConfigKeys = nil
	if !reflect.DeepEqual(expected, actual) {
		return errors.New("generation-two seed manifest mismatch")
	}
	if progressionPresent {
		var epoch, counters int
		if err := q.QueryRowContext(ctx, `SELECT count(*) FROM game_statistics_epoch WHERE id=1 AND rules_version=1`).Scan(&epoch); err != nil {
			return err
		}
		if err := q.QueryRowContext(ctx, `SELECT count(*) FROM game_rank_counters WHERE id=1`).Scan(&counters); err != nil {
			return err
		}
		if epoch != 1 || counters != 1 {
			return errors.New("generation-two progression seed mismatch")
		}
	}
	return nil
}

func readGenerationTwoFreshConfigSeedRows(ctx context.Context, q queryer) ([]generationTwoFreshConfigSeedRow, error) {
	rows, err := q.QueryContext(ctx, `
SELECT key,value,updated_at,typeof(key),typeof(value),typeof(updated_at)
FROM site_config
ORDER BY key`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []generationTwoFreshConfigSeedRow
	for rows.Next() {
		var row generationTwoFreshConfigSeedRow
		var keyType, valueType, updatedAtType string
		if err := rows.Scan(&row.Key, &row.Value, &row.UpdatedAt, &keyType, &valueType, &updatedAtType); err != nil {
			return nil, err
		}
		if keyType != "text" || valueType != "text" || updatedAtType != "integer" ||
			!utf8.ValidString(row.Key) || !utf8.ValidString(row.Value) {
			return nil, errors.New("generation-two fresh site configuration has invalid storage type")
		}
		if row.Key == generationTwoAnnouncementEpochKey {
			if !ValidateOpaqueID(row.Value, "b1e_") {
				return nil, errors.New("generation-two fresh announcement epoch is invalid")
			}
			row.Value = generationTwoFreshConfigEpochMarker
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

func generationTwoFreshConfigSeedDigest(rows []generationTwoFreshConfigSeedRow) (string, error) {
	encoded, err := json.Marshal(rows)
	if err != nil {
		return "", err
	}
	digest := sha256.Sum256(encoded)
	return hex.EncodeToString(digest[:]), nil
}

func expectedGenerationTwoFreshConfigSeedHash() (string, error) {
	var fixture struct {
		SHA256 string `json:"sha256"`
	}
	if err := json.Unmarshal([]byte(generationTwoFreshConfigSeedFixture), &fixture); err != nil {
		return "", err
	}
	if len(fixture.SHA256) != sha256.Size*2 || fixture.SHA256 != PinnedGenerationTwoFreshConfigSeedHash {
		return "", errors.New("generation-two fresh config seed fixture is inconsistent")
	}
	if _, err := hex.DecodeString(fixture.SHA256); err != nil {
		return "", errors.New("generation-two fresh config seed fixture is not hexadecimal")
	}
	return fixture.SHA256, nil
}

func validateGenerationTwoFreshConfigSeed(ctx context.Context, q queryer) error {
	rows, err := readGenerationTwoFreshConfigSeedRows(ctx, q)
	if err != nil {
		return err
	}
	actual, err := generationTwoFreshConfigSeedDigest(rows)
	if err != nil {
		return err
	}
	expected, err := expectedGenerationTwoFreshConfigSeedHash()
	if err != nil {
		return err
	}
	if actual != expected {
		return fmt.Errorf("generation-two fresh site configuration seed mismatch: got %s", actual)
	}
	return nil
}

// validateGenerationTwoFreshSeedManifest is intentionally stricter than the
// current-state seed validator.  Fresh bootstrap must prove that both
// canonical pool rows were created by the single seed transaction; a later
// current database may bind/close Thursday pools as periods advance.
func validateGenerationTwoFreshSeedManifest(ctx context.Context, q queryer) error {
	if err := validateGenerationTwoFreshConfigSeed(ctx, q); err != nil {
		return err
	}
	rows, err := q.QueryContext(ctx, `
 SELECT p.id,p.pool_type,p.state,p.revision,p.period_id,a.kind,a.code,a.balance_sign,hex(a.balance_mag)
FROM shared_pools p
JOIN credit_accounts a ON a.id=p.account_id
ORDER BY p.pool_type,p.id`)
	if err != nil {
		return err
	}
	seen := make(map[string]bool, 2)
	count := 0
	for rows.Next() {
		var id, poolType, state, accountKind, accountCode, balanceHex string
		var revision int64
		var balanceSign int
		var periodID sql.NullString
		if err := rows.Scan(&id, &poolType, &state, &revision, &periodID, &accountKind, &accountCode, &balanceSign, &balanceHex); err != nil {
			rows.Close()
			return err
		}
		count++
		if count > 2 || seen[poolType] || (poolType != "welfare" && poolType != "thursday") ||
			!ValidateOpaqueID(id, "pol_") || state != "open" || revision != 1 || periodID.Valid ||
			accountKind != "pool" || accountCode != "pool:"+id || balanceSign != 0 || balanceHex != "00000000000000000000000000000000" {
			rows.Close()
			return errors.New("generation-two fresh pool seed mismatch")
		}
		seen[poolType] = true
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return err
	}
	if err := rows.Close(); err != nil {
		return err
	}
	if count != 2 || !seen["welfare"] || !seen["thursday"] {
		return errors.New("generation-two fresh pool seed is incomplete")
	}
	rows, err = q.QueryContext(ctx, `SELECT code,kind,balance_sign,hex(balance_mag)
FROM credit_accounts WHERE code IN ('charity_reserve','external','forward_reserve','game_fishing_reserve','image_activity_reserve','platform') ORDER BY code`)
	if err != nil {
		return err
	}
	accounts := 0
	for rows.Next() {
		var code, kind, balanceHex string
		var balanceSign int
		if err := rows.Scan(&code, &kind, &balanceSign, &balanceHex); err != nil {
			rows.Close()
			return err
		}
		wantKind := "platform"
		if code == "external" {
			wantKind = "external"
		}
		if kind != wantKind || balanceSign != 0 || balanceHex != "00000000000000000000000000000000" {
			rows.Close()
			return errors.New("generation-two fresh fixed account seed mismatch")
		}
		accounts++
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return err
	}
	if err := rows.Close(); err != nil {
		return err
	}
	if accounts != 12 {
		return errors.New("generation-two fresh fixed account seed is incomplete")
	}
	var dynamicSystemAccounts int
	if err := q.QueryRowContext(ctx, `SELECT COUNT(*) FROM credit_accounts
WHERE kind IN ('platform','external') AND code NOT IN ('charity_reserve','external','forward_reserve','game_fishing_reserve','image_activity_reserve','platform')`).Scan(&dynamicSystemAccounts); err != nil {
		return err
	}
	if dynamicSystemAccounts != 0 {
		return errors.New("generation-two fresh seed contains dynamic system accounts")
	}
	var totalAccounts int
	if err := q.QueryRowContext(ctx, `SELECT COUNT(*) FROM credit_accounts`).Scan(&totalAccounts); err != nil {
		return err
	}
	if totalAccounts != 14 {
		return fmt.Errorf("generation-two fresh account seed has %d rows", totalAccounts)
	}
	var revision, updatedAt int64
	if err := q.QueryRowContext(ctx, `SELECT revision,updated_at FROM config_revisions WHERE domain='site'`).Scan(&revision, &updatedAt); err != nil {
		return err
	}
	if revision != 1 || updatedAt != 0 {
		return errors.New("generation-two fresh site revision seed mismatch")
	}
	if err := q.QueryRowContext(ctx, `SELECT revision,updated_at FROM config_revisions WHERE domain='activities'`).Scan(&revision, &updatedAt); err != nil {
		return err
	}
	if revision != 1 || updatedAt != 0 {
		return errors.New("generation-two fresh activities revision seed mismatch")
	}
	if err := q.QueryRowContext(ctx, `SELECT revision,updated_at FROM config_revisions WHERE domain='games'`).Scan(&revision, &updatedAt); err != nil {
		return err
	}
	if revision != 1 || updatedAt != 0 {
		return errors.New("generation-two fresh games revision seed mismatch")
	}
	var enabled int
	var currentEvent sql.NullString
	if err := q.QueryRowContext(ctx, `SELECT enabled,revision,changed_at,current_event_id FROM maintenance_state WHERE id=1`).Scan(&enabled, &revision, &updatedAt, &currentEvent); err != nil {
		return err
	}
	if enabled != 1 || revision != 1 || updatedAt != 0 || currentEvent.Valid {
		return errors.New("generation-two fresh maintenance seed mismatch")
	}
	var capacityReservedHex, capacityRevisionHex string
	if err := q.QueryRowContext(ctx, `SELECT hex(reserved_future_rows),hex(revision) FROM credit_capacity WHERE id=1`).Scan(&capacityReservedHex, &capacityRevisionHex); err != nil {
		return err
	}
	if capacityReservedHex != "00000000000000000000000000000000" || capacityRevisionHex != "00000000000000000000000000000000" {
		return errors.New("generation-two fresh capacity seed mismatch")
	}
	var usageHex [7]string
	if err := q.QueryRowContext(ctx, `SELECT hex(total_requests),hex(total_uncached_input_tokens),hex(total_cache_write_input_tokens),hex(total_cache_read_input_tokens),hex(total_output_tokens),hex(total_unknown_usage_requests),hex(revision) FROM site_usage_totals WHERE id=1`).Scan(&usageHex[0], &usageHex[1], &usageHex[2], &usageHex[3], &usageHex[4], &usageHex[5], &usageHex[6]); err != nil {
		return err
	}
	for _, value := range usageHex {
		if value != "00000000000000000000000000000000" {
			return errors.New("generation-two fresh usage seed mismatch")
		}
	}
	return nil
}

func containsSortedString(values []string, want string) bool {
	i := sort.SearchStrings(values, want)
	return i < len(values) && values[i] == want
}

func readGenerationTwoSeedManifest(ctx context.Context, q queryer) (generationTwoSeedManifest, error) {
	return readAssetSeedManifest(ctx, q, false)
}

func readAssetSeedManifest(ctx context.Context, q queryer, prior bool) (generationTwoSeedManifest, error) {
	manifest := generationTwoSeedManifest{}
	rows, err := q.QueryContext(ctx, `SELECT key FROM site_config WHERE key NOT LIKE 'alert_prefs_%' ORDER BY key`)
	if err != nil {
		return manifest, err
	}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			rows.Close()
			return manifest, err
		}
		manifest.ConfigKeys = append(manifest.ConfigKeys, key)
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return manifest, err
	}
	rows.Close()

	rows, err = q.QueryContext(ctx, `SELECT domain FROM config_revisions ORDER BY domain`)
	if err != nil {
		return manifest, err
	}
	for rows.Next() {
		var domain string
		if err := rows.Scan(&domain); err != nil {
			rows.Close()
			return manifest, err
		}
		manifest.ConfigRevisionDomains = append(manifest.ConfigRevisionDomains, domain)
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return manifest, err
	}
	rows.Close()

	assetColumn := "asset_type"
	if prior {
		assetColumn = "'general'"
	}
	rows, err = q.QueryContext(ctx, `SELECT code,kind,`+assetColumn+` FROM credit_accounts WHERE code IN ('charity_reserve','external','forward_reserve','game_fishing_reserve','image_activity_reserve','platform') ORDER BY code,`+assetColumn)
	if err != nil {
		return manifest, err
	}
	for rows.Next() {
		var account generationTwoSeedAccount
		if err := rows.Scan(&account.Code, &account.Kind, &account.Asset); err != nil {
			rows.Close()
			return manifest, err
		}
		manifest.FixedAccounts = append(manifest.FixedAccounts, account)
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return manifest, err
	}
	rows.Close()

	rows, err = q.QueryContext(ctx, `SELECT kind,code FROM credit_accounts
WHERE kind IN ('platform','external')
ORDER BY kind,code`)
	if err != nil {
		return manifest, err
	}
	for rows.Next() {
		var kind string
		var code sql.NullString
		if err := rows.Scan(&kind, &code); err != nil {
			rows.Close()
			return manifest, err
		}
		if code.Valid && ((kind == "external" && code.String == "external") ||
			(kind == "platform" &&
				(code.String == "charity_reserve" || code.String == "forward_reserve" ||
					code.String == "game_fishing_reserve" || code.String == "image_activity_reserve" || code.String == "platform"))) {
			continue
		}
		if kind == "platform" && code.Valid && (validateGenerationTwoDynamicRPSAccountCode(code.String) || validateDuelAccountCode(code.String) || validateBlackjackAccountCode(code.String)) {
			continue
		}
		rows.Close()
		return manifest, errors.New("generation-two seed contains invalid dynamic system account")
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return manifest, err
	}
	if err := rows.Close(); err != nil {
		return manifest, err
	}

	rows, err = q.QueryContext(ctx, `
SELECT p.id,p.pool_type,a.kind,a.code,p.period_id
FROM shared_pools p
JOIN credit_accounts a ON a.id=p.account_id
WHERE p.pool_type='welfare' AND p.period_id IS NULL
ORDER BY p.id`)
	if err != nil {
		return manifest, err
	}
	for rows.Next() {
		var pool generationTwoSeedPool
		var id, accountCode string
		var periodID sql.NullString
		if err := rows.Scan(&id, &pool.PoolType, &pool.AccountKind, &accountCode, &periodID); err != nil {
			rows.Close()
			return manifest, err
		}
		pool.IDPrefix = id
		if len(id) >= 4 {
			pool.IDPrefix = id[:4]
		}
		if strings.HasPrefix(accountCode, "pool:") {
			pool.AccountPrefix = "pool:"
		} else {
			pool.AccountPrefix = accountCode
		}
		pool.PeriodIsNull = !periodID.Valid
		manifest.InitialPools = append(manifest.InitialPools, pool)
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return manifest, err
	}
	rows.Close()

	for _, table := range []string{"credit_capacity", "maintenance_state", "site_usage_totals"} {
		var count int
		if err := q.QueryRowContext(ctx, `SELECT COUNT(*) FROM `+quoteSQLiteIdentifier(table)).Scan(&count); err != nil {
			return manifest, err
		}
		if count != 1 {
			return manifest, fmt.Errorf("seed singleton %s has %d rows", table, count)
		}
		manifest.SingletonRows = append(manifest.SingletonRows, table)
	}
	return manifest, nil
}

func validateGenerationTwoDynamicSeedRows(ctx context.Context, q queryer) error {
	rows, err := q.QueryContext(ctx, `
SELECT p.id,p.pool_type,p.period_id,p.state,p.revision,a.kind,a.code
FROM shared_pools p
LEFT JOIN credit_accounts a ON a.id=p.account_id
ORDER BY p.id`)
	if err != nil {
		return err
	}
	welfareCount := 0
	thursdayCount := 0
	for rows.Next() {
		var id, poolType, state string
		var periodID, accountKind, accountCode sql.NullString
		var revision int64
		if err := rows.Scan(&id, &poolType, &periodID, &state, &revision, &accountKind, &accountCode); err != nil {
			rows.Close()
			return err
		}
		if !ValidateOpaqueID(id, "pol_") || (poolType != "welfare" && poolType != "thursday") || !accountKind.Valid || accountKind.String != "pool" ||
			!accountCode.Valid || accountCode.String != "pool:"+id || revision < 1 || (state != "open" && state != "closed") {
			rows.Close()
			return errors.New("generation-two pool account identity mismatch")
		}
		if poolType == "welfare" {
			if periodID.Valid {
				rows.Close()
				return errors.New("welfare pool unexpectedly has a period")
			}
			welfareCount++
		} else {
			// A current Generation 2 database must retain at least one Thursday
			// pool.  Its period binding and lifecycle are intentionally dynamic;
			// the DDL/state validators enforce those per-period matrices.
			thursdayCount++
		}
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return err
	}
	if err := rows.Close(); err != nil {
		return err
	}
	if welfareCount != 1 {
		return fmt.Errorf("generation-two welfare pool count is %d", welfareCount)
	}
	if thursdayCount < 1 {
		return errors.New("generation-two Thursday pool seed is missing")
	}
	var invalidPoolAccounts int
	if err := q.QueryRowContext(ctx, `SELECT COUNT(*) FROM credit_accounts a
WHERE a.kind='pool' AND NOT EXISTS(
  SELECT 1 FROM shared_pools p WHERE p.account_id=a.id AND a.code='pool:'||p.id
)`).Scan(&invalidPoolAccounts); err != nil {
		return err
	}
	if invalidPoolAccounts != 0 {
		return errors.New("generation-two pool account has no matching pool row")
	}
	return nil
}

func validateGenerationTwoDynamicRPSAccountCode(code string) bool {
	if strings.HasPrefix(code, "rps-queue:") {
		return len(code) == len("rps-queue:")+27 && ValidateOpaqueID(strings.TrimPrefix(code, "rps-queue:"), "rpsq_")
	}
	if strings.HasPrefix(code, "rps-session:") {
		return len(code) == len("rps-session:")+26 && ValidateOpaqueID(strings.TrimPrefix(code, "rps-session:"), "rps_")
	}
	return false
}

func validateDuelAccountCode(code string) bool {
	if id, ok := strings.CutPrefix(code, "duel-queue:"); ok {
		return ValidateOpaqueID(id, "bidq_") || ValidateOpaqueID(id, "likq_")
	}
	if id, ok := strings.CutPrefix(code, "duel-session:"); ok {
		return ValidateOpaqueID(id, "bid_") || ValidateOpaqueID(id, "lik_")
	}
	return false
}

func validateBlackjackAccountCode(code string) bool {
	id, ok := strings.CutPrefix(code, "blackjack-payment:")
	return ok && ValidateOpaqueID(id, "bjp_")
}

func expectedGenerationTwoManifestHash() (string, error) {
	var fixture struct {
		SHA256 string `json:"sha256"`
	}
	if err := json.Unmarshal([]byte(generationTwoManifestFixture), &fixture); err != nil {
		return "", fmt.Errorf("generation-two manifest fixture is invalid: %w", err)
	}
	if fixture.SHA256 == "" || fixture.SHA256 != PinnedGenerationTwoManifestHash {
		return "", errors.New("generation-two manifest fixture is not pinned")
	}
	return fixture.SHA256, nil
}

func generationManifestDigest(manifest generationManifest) string {
	encoded, err := json.Marshal(manifest)
	if err != nil {
		// generationManifest contains only JSON-marshalable concrete fields. Keep
		// this impossible branch deterministic if that ever changes.
		return ""
	}
	digest := sha256.Sum256(encoded)
	return hex.EncodeToString(digest[:])
}

func validateGenerationTwoManifest(ctx context.Context, q queryer) error {
	if GenerationTwoSchemaHash() != PinnedGenerationTwoSchemaHash {
		return errors.New("generation-two schema hash drift")
	}
	expected, err := expectedGenerationTwoManifestHash()
	if err != nil {
		return err
	}
	actual, err := readGenerationManifest(ctx, q)
	if err != nil {
		return err
	}
	if generationManifestDigest(actual) != expected {
		return errors.New("generation-two schema manifest mismatch")
	}
	return nil
}

func readGenerationManifest(ctx context.Context, q queryer) (generationManifest, error) {
	manifest := generationManifest{}
	rows, err := q.QueryContext(ctx, `
SELECT type, name, tbl_name, COALESCE(sql,'')
FROM sqlite_schema
WHERE name NOT LIKE 'sqlite_%'
  AND type IN ('table','index','trigger','view')
ORDER BY type, name`)
	if err != nil {
		return manifest, err
	}
	var tableNames []string
	for rows.Next() {
		var object schemaObject
		if err := rows.Scan(&object.Type, &object.Name, &object.Table, &object.SQL); err != nil {
			rows.Close()
			return manifest, err
		}
		manifest.Objects = append(manifest.Objects, object)
		if object.Type == "table" {
			tableNames = append(tableNames, object.Name)
		}
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return manifest, err
	}
	rows.Close()
	sort.Strings(tableNames)
	for _, tableName := range tableNames {
		table, err := readTableManifest(ctx, q, tableName)
		if err != nil {
			return manifest, err
		}
		manifest.Tables = append(manifest.Tables, table)
	}
	return manifest, nil
}

func quoteSQLiteIdentifier(value string) string {
	return `"` + strings.ReplaceAll(value, `"`, `""`) + `"`
}

func readTableManifest(ctx context.Context, q queryer, tableName string) (tableManifest, error) {
	table := tableManifest{Name: tableName}
	rows, err := q.QueryContext(ctx, `PRAGMA table_xinfo(`+quoteSQLiteIdentifier(tableName)+`)`)
	if err != nil {
		return table, err
	}
	for rows.Next() {
		var column columnManifest
		if err := rows.Scan(&column.CID, &column.Name, &column.Type, &column.NotNull, &column.Default, &column.PrimaryKey, &column.Hidden); err != nil {
			rows.Close()
			return table, err
		}
		table.Columns = append(table.Columns, column)
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return table, err
	}
	rows.Close()

	rows, err = q.QueryContext(ctx, `PRAGMA foreign_key_list(`+quoteSQLiteIdentifier(tableName)+`)`)
	if err != nil {
		return table, err
	}
	for rows.Next() {
		var fk foreignKeyManifest
		if err := rows.Scan(&fk.ID, &fk.Sequence, &fk.Table, &fk.From, &fk.To, &fk.OnUpdate, &fk.OnDelete, &fk.Match); err != nil {
			rows.Close()
			return table, err
		}
		table.ForeignKeys = append(table.ForeignKeys, fk)
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return table, err
	}
	rows.Close()
	sort.Slice(table.ForeignKeys, func(i, j int) bool {
		if table.ForeignKeys[i].ID == table.ForeignKeys[j].ID {
			return table.ForeignKeys[i].Sequence < table.ForeignKeys[j].Sequence
		}
		return table.ForeignKeys[i].ID < table.ForeignKeys[j].ID
	})

	rows, err = q.QueryContext(ctx, `PRAGMA index_list(`+quoteSQLiteIdentifier(tableName)+`)`)
	if err != nil {
		return table, err
	}
	for rows.Next() {
		var sequence int
		var index indexManifest
		if err := rows.Scan(&sequence, &index.Name, &index.Unique, &index.Origin, &index.Partial); err != nil {
			rows.Close()
			return table, err
		}
		table.Indexes = append(table.Indexes, index)
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		return table, err
	}
	rows.Close()
	sort.Slice(table.Indexes, func(i, j int) bool { return table.Indexes[i].Name < table.Indexes[j].Name })
	for i := range table.Indexes {
		rows, err := q.QueryContext(ctx, `PRAGMA index_xinfo(`+quoteSQLiteIdentifier(table.Indexes[i].Name)+`)`)
		if err != nil {
			return table, err
		}
		for rows.Next() {
			var column indexColumnManifest
			if err := rows.Scan(&column.Sequence, &column.CID, &column.Name, &column.Descending, &column.Collation, &column.Key); err != nil {
				rows.Close()
				return table, err
			}
			table.Indexes[i].Columns = append(table.Indexes[i].Columns, column)
		}
		if err := rows.Err(); err != nil {
			rows.Close()
			return table, err
		}
		rows.Close()
	}
	return table, nil
}
